### ISSUE TITLE
[ bug ] 1.8版本在执行一条慢的查询时，整个系统都会卡主。

### ISSUE THREAD

**Issue by 2002wmj** [hhyo/Archery#1002]
### 重现步骤
 升级1.8版本以后，只要一个用户在sql查询页面执行了一个慢查询，整个系统都会卡主，其他所有人页面都会卡主。等这个查询结果出来后，其他操作才恢复正常。
 之前版本是没有这个问题的，是不是http的异步出了问题？

### 版本信息
应用版本/分支：1.8.0

部署方式：Docker

**Comment by dongqianzheng** [comment]
偶尔是有卡住的问题，不知道是不是查了慢sql导致的。我的版本是1.7.7 。这种卡住了，不知道怎么看是卡在了哪里，只能是重启。是不是开了debug日志就能看到？

**Comment by 2002wmj** [comment]
应该是和切换到uvicorn启动有关系，以前的gevent没有这种问题。

**Comment by alwaystest18** [comment]
同遇到，等待官方解决

**Comment by 2002wmj** [comment]
我的临时解决办法是换回gevent模式启动

**Comment by alwaystest18** [comment]
> 我的临时解决办法是换回gevent模式启动

这个是在哪改的？

**Comment by alwaystest18** [comment]
> 我的临时解决办法是换回gevent模式启动

咋改的，我把startup.sh里面改成gunicorn -w 4 -k gevent -b 127.0.0.1:8888 --timeout 600 archery.wsgi:application后访问不了了，cpu打满了

**Comment by alwaystest18** [comment]
经过2002wmj大佬指点，修改docker中/opt/archery/src/docker/startup.sh启动部分内容为
gunicorn -w 4 -b 127.0.0.1:8888 --timeout 600 archery.wsgi:application
问题已解决，目前执行慢sql时系统可正常工作

**Comment by hhyo** [comment]
感谢反馈，经测试确实存在这个问题，具体原因待确认

**Comment by 5sdba** [comment]
我的版本是1.7.13,我看docker中/opt/archery/src/docker/startup.sh里面的timeoute 已经是600了，执行sql查询，超过60s左右系统就报错了

**Comment by gdsea** [comment]
这个bug解决了没，有没有解决方案
