### ISSUE TITLE
[ 问题咨询 ] mongodb 需要正则匹配该怎么查询？

### ISSUE THREAD

**Issue by dmanbu** [hhyo/Archery#1005]
mongo 原语句如下
`db.getCollection("my_log").find({"body" : /.*o984056423.*/i})`

在 Archery 中，我首先使用如下语句查询
`my_log.find({"body": /.*o984056423.*/i})`
然后 Archery 程序日志就开始报 json.decoder.JSONDecodeError: Expecting value: line 1 column 10 (char 9) 错误

我尝试使用如下语句
``my_log.find({"body": ”/.*o984056423.*/i“})``
虽然没报错，但没有查询到任何数据

然后又使用如下语句
``my_log.find({"body": {"$gt": "/.*o984056423.*/i"})``
虽然有数据，但和预期的数据不一样，我也使用 $eq 尝试，但并没有数据

请问改用什么查询方式？谢谢

**Comment by fancy-lee** [comment]
目前只支持这样查询：db.audioinfos.find({"fileName":{ $regex: "^C002"}})
