### ISSUE TITLE
SyntaxError: Unexpected end of JSON input[ bug ]

### ISSUE THREAD

**Issue by longyunhe** [hhyo/Archery#1006]
查询语句超过100条则报错，在60条时正常显示，

![image](https://user-images.githubusercontent.com/39185008/103397877-2a6d6000-4b75-11eb-94b9-5eb574a8823e.png)

出现这个报错时日志中没有提示

手动部署   Archery (v1.7.10)

**Comment by longyunhe** [comment]
nginx权限问题

**Comment by xwbops** [comment]
这个问题1.9版本也有啊，请问怎么解决有
