### ISSUE TITLE
[ 问题咨询 ]权限管理模块的工单缺少操作信息

### ISSUE THREAD

**Issue by xiang-coco** [hhyo/Archery#1013]
### 问题描述
1. 权限管理模块的工单缺少操作信息
2. 权限管理模块的工单，配置的审核工作流是 开发经理->DBA，但是当开发经理填写了审核意见，提交审核后，看不到开发经理写的审核意见及审批信息，但是流程会走到下一步。
2. DBA的审核意见也看不到
![image](https://user-images.githubusercontent.com/39326801/104799245-7cb2b000-5808-11eb-9350-9bb88d258597.png)
3.sql上线工单可以看到操作信息。

### 版本信息
Archery (v1.7.13)

**Comment by LeoQuote** [comment]
这些问题在 demo 上可以复现吗? https://demo.archerydms.com/login/

**Comment by hhyo** [comment]
这个原本就没有实现，应该是只在SQL上线工单增加了
