### ISSUE TITLE
[ bug ]飞书无法发送通知

### ISSUE THREAD

**Issue by caicai19900921** [hhyo/Archery#1016]
1.7.13版本，配置好飞书和钉钉的webhook，实际钉钉能收到推送消息而飞书无法收到。

部署方式：Docker

**Comment by LeoQuote** [comment]
升级可以解决吗

**Comment by caicai19900921** [comment]
升级到最新的1.8.0版本吗？

**Comment by caicai19900921** [comment]
> 升级可以解决吗



> 升级可以解决吗

**Comment by caicai19900921** [comment]
> 升级可以解决吗

升级到最新的1.8.0版本吗？

**Comment by caicai19900921** [comment]
> 升级可以解决吗

升级到最新的1.8.0版本吗？

**Comment by caicai19900921** [comment]
> > 升级可以解决吗
> 
> 升级到最新的1.8.0版本吗？

我测试过最新的1.8.0版本也有此问题。

下面是发送飞书错误信息：
![image](https://user-images.githubusercontent.com/32893009/105673358-e88bcb80-5f20-11eb-99e4-7cf5c18dfd9e.png)

**Comment by hhyo** [comment]
https://gitee.com/rtttte/Archery/issues/I28FXG

应该是有不兼容的修改

**Comment by caicai19900921** [comment]
> https://gitee.com/rtttte/Archery/issues/I28FXG
> 
> 应该是有不兼容的修改

最后得以解决了吗？

**Comment by caicai19900921** [comment]
> https://gitee.com/rtttte/Archery/issues/I28FXG
> 
> 应该是有不兼容的修改

我尝试修改过/opt/archery/common/utils/sendmsg.py这个文件，问题依旧
![image](https://user-images.githubusercontent.com/32893009/105808115-200e7c80-5fe2-11eb-8fdf-c175f1fd325f.png)

**Comment by czxin788** [comment]
这个问题有进展了吗，遗憾的是我也不会改

**Comment by calfzhou** [comment]
1.8.0 也是不行：
  File "/opt/archery/common/utils/sendmsg.py", line 212, in send_feishu_webhook
    if r_json['ok']:
KeyError: 'ok'

是不是因为现在飞书返回的消息体是这样的：
![image](https://user-images.githubusercontent.com/3761553/108096104-8d7e6c00-70bb-11eb-9881-077dd87be614.png)

**Comment by calfzhou** [comment]
![image](https://user-images.githubusercontent.com/3761553/108097620-527d3800-70bd-11eb-9c7c-de3ab5dfa817.png)

这个是旧版的推送格式了，新版应该是：

``` python
data = {
            "msg_type": "text",
            "content": {
                "text": f'{title}\n{content}'
            }
        }
```

飞书文档：
https://www.feishu.cn/hc/zh-cn/articles/360024984973

**Comment by calfzhou** [comment]
如果是现在刚创建的飞书机器人，默认拿到的 webhook 地址是新版本的，只需要在 archery 里给资源组配置飞书 webhook 地址的时候，手动改成老版本即可，修改方式是把链接中的 v2 去掉。

archery 1.8 docker，手动修改 webhook 地址后可以收到推送了。

附：新旧版 webhook 地址对比

```
new:
https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxxxxxxx

old:
https://open.feishu.cn/open-apis/bot/hook/xxxxxxxxxxxxxxxxxx
```

**Comment by calfzhou** [comment]
> > https://gitee.com/rtttte/Archery/issues/I28FXG
> > 应该是有不兼容的修改
> 
> 我尝试修改过/opt/archery/common/utils/sendmsg.py这个文件，问题依旧
> ![image](https://user-images.githubusercontent.com/32893009/105808115-200e7c80-5fe2-11eb-8fdf-c175f1fd325f.png)

@caicai19900921 您这里参数名写错了，应该是 `msg_type`，而不是 `msgtype`。

可以考虑根据 url 中是否有 `v2` 来自适应飞书的接口版本吧。

**Comment by caicai19900921** [comment]
> > > https://gitee.com/rtttte/Archery/issues/I28FXG
> > > 应该是有不兼容的修改
> > 
> > 
> > 我尝试修改过/opt/archery/common/utils/sendmsg.py这个文件，问题依旧
> > ![image](https://user-images.githubusercontent.com/32893009/105808115-200e7c80-5fe2-11eb-8fdf-c175f1fd325f.png)
> 
> @caicai19900921 您这里参数名写错了，应该是 `msg_type`，而不是 `msgtype`。
> 
> 可以考虑根据 url 中是否有 `v2` 来自适应飞书的接口版本吧。

确实可以了，感谢！

**Comment by yidoa** [comment]
![image](https://user-images.githubusercontent.com/87849176/128449357-7430800c-4a26-43eb-9d66-98cf1dd2f938.png)

/archery/common/utils/sendmsg.py这个文件 这样修改时可以兼容最新版 飞书得

**Comment by LeoQuote** [comment]
楼上的好人们, 顺手提个pr呗?
