### ISSUE TITLE
[ 问题咨询 ]请问用archery查询，支持redis的zrange命令吗

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1017]
### 问题描述
请问用archery查询，支持redis的zrange命令吗，为啥我在命令行可以查询，在archery报：禁止执行该命令
执行的命令为：zrange  a:customer:logo:sort:1516259094506 0 -1

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

 
![image](https://user-images.githubusercontent.com/13861904/105818733-39b7c000-5ff2-11eb-8d16-17971ab9b572.png)

**Comment by dongqianzheng** [comment]
7.11不行，7.13之后支持。
