### ISSUE TITLE
[ bug ] SQL语句中含有 *

### ISSUE THREAD

**Issue by dongqianzheng** [hhyo/Archery#1018]
这段代码需要改下，换下位置
-------------------------------------------------
         if re.match(r"^select|^show|^explain", sql, re.I) is None:
            result['bad_query'] = True
            result['msg'] = '不支持的查询语法类型!'
       if '*' in sql:
            result['has_star'] = True
            result['msg'] = 'SQL语句中含有 * '
--------------------------------------------------
        if '*' in sql:
            result['has_star'] = True
            result['msg'] = 'SQL语句中含有 * '
        if re.match(r"^select|^show|^explain", sql, re.I) is None:
            result['bad_query'] = True
            result['msg'] = '不支持的查询语法类型!'

如果查询的时候sql没有以select开头或者select写错了，就会报 ‘SQL语句中含有 *’（如果sql中有*的话），这个报错就比较奇怪了。

**Comment by LeoQuote** [comment]
代码相关的直接提 pr 吧
