### ISSUE TITLE
[ bug ]执行SQL上线工单（仅自己提交的）权限控制

### ISSUE THREAD

**Issue by canyueduyi** [hhyo/Archery#1019]
版本1.8.0

 
简单描述问题出现场景和重现步骤：
工单由提交人提交后，经过一系列审批，最后定时执行，这时具有【执行SQL上线工单（仅自己提交的）】权限提交人可以直接点击立即处理

期待结果：
如果是符合自动审批条件的工单，可以由提交人直接处理。
其他进入审批流程的工单，提交人即使具有此权限，也不应发生直接处理的行为

**Comment by hhyo** [comment]
目前该权限仅控制提交人是否可以自己执行工单(包括定时立即执行)，不做其他场景判断

**Comment by charnet1019** [comment]
这个功能对控制开发环境和生产环境很有用，不知是否后续可以加上  @hhyo
