### ISSUE TITLE
SQL上线无法选择数据库

### ISSUE THREAD

**Issue by Marco1221** [hhyo/Archery#102]
您好，
SQL审核> SQL上线 功能可以选择数据库实例，选择后不显示数据库，请问会是什么原因导致。admin 账号可以正常显示，权限都为最大权限。

**Comment by hhyo** [comment]
FAQ有说明，还有问题模板为什么不用呢，不用版本和部署方式，解决问题的方式都会有很大差异

**Comment by Marco1221** [comment]
抱歉 我在FQA中没找到相关信息，只看到了会过滤系统库，资源组 权限都已经关联和设置了。安装方式是docker 安装

**Comment by hhyo** [comment]
docker安装，那版本呢？

**Comment by hhyo** [comment]
还有，浏览器是不是chrome，非chrome会存在兼容性问题

**Comment by LeoQuote** [comment]
这个问题听起来很奇怪，如果能获取到实例的话，按理说数据库列表是可以拿到的，因为并没有在这里做权限限制。

你可以看看你的网络请求吗，应该会有一个get db list之类的请求。

另外请你告诉我们版本号，还有日志信息。

日志在 download文件夹下的logs

另外版本很重要，本项目更新比较快，现在最新版本已经是1.4.5了。请提供一下版本信息。

**Comment by Marco1221** [comment]
您好，我在隐身模式下功能正常了，可能是缓存的问题。谢谢了
