### ISSUE TITLE
[ 问题咨询 ] 飞书的webhook消息通知和个人推送都不起作用

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1020]
### 问题描述
之前一直使用archery的钉钉的webhook和个人推送，都可以正常使用。
由于公司现在改成飞书了，发现archery的飞书消息，无论是webhook，还是个人推送，都不发消息，通过docker logs -f archery看不到任何报错日志。

请问，有关于archery的飞书通知的配置文档吗
### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
在这里讨论吧 https://github.com/hhyo/Archery/issues/1016 这个issue 先关了
