### ISSUE TITLE
[ 问题咨询 ] 从用户登录后到跳转sqlworkflow整个过程中页面加载很慢有的时候能长达10秒以上

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#1021]
### 问题描述
从用户登录后到跳转sqlworkflow整个过程中页面加载很慢有的时候能长达10秒以上

### 版本信息
 - 应用版本/分支：Release v1.7.12
 - 部署方式：Docker

**Comment by hhyo** [comment]
可通过浏览器调试模式查看具体响应慢的请求

**Comment by benevolence-doctor** [comment]
![image](https://user-images.githubusercontent.com/13461419/110568625-3b96a680-818e-11eb-8f8a-39e097d50f0d.png)
就是点击页面请求的时候一直是pending，不只是这个页面大部分页面首次加载都是这样

**Comment by benevolence-doctor** [comment]
![image](https://user-images.githubusercontent.com/13461419/111096669-08cc2400-857b-11eb-8f20-851f193c9a76.png)
@hhyo  帮忙看看

**Comment by hhyo** [comment]
看下worker配置的是否足够，现在SQL检测，查询等都是同步操作，容易出现阻塞
