### ISSUE TITLE
[ 问题咨询 ] 关于SQL上线是否可以关闭相关语句检测

### ISSUE THREAD

**Issue by kun376361** [hhyo/Archery#1022]
### 问题描述
关于创建SQL上线，是否可以关闭SQL检测，比如必须设置主键、注释、列不允许为null等。

### 版本信息
 - 应用版本/分支：Release v1.8.0  
 - 部署方式：Docker、手工部署

**Comment by kun376361** [comment]
> ### 问题描述
> 关于创建SQL上线，是否可以关闭SQL检测，比如必须设置主键、注释、列不允许为null等。
> 
> ### 版本信息
> * 应用版本/分支：Release v1.8.0
> * 部署方式：Docker、手工部署

主要是建表的时候。

**Comment by LeoQuote** [comment]
可以, 具体要看 goinception 和inception 的配置

**Comment by kun376361** [comment]
找到配置文件了，多谢。
