### ISSUE TITLE
[ 问题咨询 ] SQL上线选择备份数据库提示host太长

### ISSUE THREAD

**Issue by kun376361** [hhyo/Archery#1023]
### 问题描述

我这里SQL上线使用的RDS，备份库使用本地的Mysql。

在执行SQL上线选择备份数据库执行后报错如下，但是发现SQL依然可以成功执行。
Data too long for column 'host' at row 1.

可能是RDS名称太长了？我看备份数据库已经创建了对应的备份库。

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
这个 faq 和其他issue 里都有了, 设 cname 或者用 ip
