### ISSUE TITLE
[ 功能建议 ]归档任务希望可以加上定时执行，类似crontab

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/Archery#1024]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by czxin788** [comment]
在管理后台django_q/schedule增加schedule配置，用于定时归档，可配置多个schedule在不同的时间调度归档任务，配置的func设置为sql.archiver.add_archive_task，Args填写归档配置ID列表（不填写则默认调度所有配置），如[1,2]，schedule仅会获取审核通过+启用状态的配置
暂时还没有归档状态的通知，可以自行写脚本查询相关表的数据

参见
https://archerydms.com/modules/tools/#_3

**Comment by sona-yuan** [comment]
建议在归档申请的时候，直接增加归档周期（每时/每天/每周/每月） 并且选择归档执行的时间，毕竟这些信息对于业务才是最准确知道的，dba后台配置不是很友好，归档日志也可以在归档list上输出。
