### ISSUE TITLE
[ bug ]规则添加功能报“有违法字符”的错误

### ISSUE THREAD

**Issue by xx287442776** [hhyo/Archery#103]
版本1.5.0，部署方式docker
进入规则添加页面，添加一个你们demo网页中已有的一个规则：TABLE_WITHOUT_TIMESTAMP,会报“有违法字符错误框”，如图：
![image](https://user-images.githubusercontent.com/18021151/55544019-cba75800-56fc-11e9-94e5-17351679bd47.png)

不知道这个问题怎么解决，以及你们demo中的规则是如何加上去的？

**Comment by LeoQuote** [comment]
图片中看不清你填写的具体信息， 请按纯文本形式粘贴出来。

**Comment by hhyo** [comment]
demo规则由初始文件导入，可见 [rule.json](https://github.com/hhyo/archery/blob/master/src/script/rule.json)

**Comment by hhyo** [comment]
查看代码发现是themis限制了部分关键字，代码暂时不做修改，需要添加包含关键字的规则还是直接操作mongo吧
https://github.com/hhyo/Archery/blob/master/themis/utils/wtform_models.py#L93

**Comment by xx287442776** [comment]
好的，试验通过可以直接用mongoimport命令导入rule.json规则文件
