### ISSUE TITLE
[ 功能建议 ]在sql查询中，建议对查询oracle数据库实例的sql，添加表字段的提示和自动补全功能。

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1030]
### 目前遇到的问题/使用障碍
1、目前发现写查询oracle的sql语句时，表的字段不会提示，不方便，建议添加对表字段的提示和自动补全功能，如下图所示：
![image](https://user-images.githubusercontent.com/13861904/108589114-bd699000-7397-11eb-9ab0-3fbfb89f2f80.png)

### 希望如何解决/实现它
1、建议oracle实例支持查询sql对表字段的提示和自动补全功能。

**Comment by 13240339983** [comment]
确实生产当中用到 提醒功能，现在oracle的字段没有办法进行提示，非常不方便
