### ISSUE TITLE
[ 问题咨询 ]请问sql上线中，定时执行功能中如果是使用gh-ost执行alter，指定的时间是cutover时间吗

### ISSUE THREAD

**Issue by 17888821070** [hhyo/Archery#1031]
### 问题描述
请问sql上线中，定时执行功能中如果是使用gh-ost执行alter，指定的时间是cutover时间吗？
例如针对大表进行alter修改表结构，使用gh-ost复制表时间会比较长，那么cutover的时间会不会就赶上了高峰期？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
目前对于cutover时间并没有控制，默认copy完就会切割

**Comment by 17888821070** [comment]
如果默认copy完就cutover会不会将cutover时间赶上访问高峰期？
