### ISSUE TITLE
[ 问题咨询 ]工单大表调用OSC执行进度显示：没有找到匹配的记录

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#1033]
### 问题描述
您好：麻烦分析一下以下情况：
SQL上线执行时候，大表调用OSC，点击查看进度，执行进度显示：没有找到匹配的记录，工单最后是执行成功；
备注：之前使用时候是有进度；

### 版本信息
 - 应用版本/分支：Archery (v1.7.13)
 - 部署方式：Docker

### 截图信息
查看到该工单的OSC没有进度信息，进度显示：没有找到匹配的记录，点击刷新也是一样（以前使用是有执行进度）：
![image](https://user-images.githubusercontent.com/71009460/109091274-6aa12700-774f-11eb-8eb3-3bf864232cbd.png)

日志信息：
![image](https://user-images.githubusercontent.com/71009460/109091119-29a91280-774f-11eb-9f98-52731161c755.png)

goinception日志：
![image](https://user-images.githubusercontent.com/71009460/109121197-ecaa4380-7781-11eb-8870-a9d39b3fb3db.png)

**Comment by hhyo** [comment]
看起来是goInception异常，可以给对应项目提交一个issue，或者尝试更新版本看下

**Comment by zhituanchen** [comment]
好的 已经提交goInception的issue
