### ISSUE TITLE
迁移不一致

### ISSUE THREAD

**Issue by hydgladiator** [hhyo/Archery#1034]
我线上的Archery所有容器打包后迁移到线下做成镜像，然后通过docker-compose.yml启动，只能正确启动redis 和 archery两个容器，其他几个都不能通过compose启动。
查了线上的是低版本内核，线下是高版本内核，都是CentOS Linux release 7.8.2003 (Core)。
<img width="934" alt="image" src="https://user-images.githubusercontent.com/13326206/109244546-da7be400-7819-11eb-96ea-a08b17a084cf.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/13326206/109244578-e5cf0f80-7819-11eb-90ad-e8fb0154a25e.png">

能确定下是怎么一个问题么

**Comment by hydgladiator** [comment]
@hhyo

**Comment by LeoQuote** [comment]
不能启动具体是怎么个不能启动? docker hello world 能启动吗? 是不是 docker 问题?

**Comment by hydgladiator** [comment]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/13326206/109268666-5db32f00-7846-11eb-8676-89275e3733de.png">
只有redis在compose下能正常调用entrypoint生成容器访问，其他的不是命令错误，要么就是启动失败。
失败图如下
![image](https://user-images.githubusercontent.com/13326206/109268860-a1a63400-7846-11eb-84ca-dfae013984d0.png)

**Comment by LeoQuote** [comment]
我看你这个是环境问题, 不是程序的问题, 你自己对照 app 的 log 还有 docker 的log 看看吧

**Comment by hydgladiator** [comment]
仔细查了，从产线同步到测试环境的镜像没问题，只是启动配置文件有点问题。
现在是一个mysql的镜像启动成容器的时候，始终处于Created状态，是否和原先产线上导出的容器过大有关，有7个G之多。

**Comment by LeoQuote** [comment]
为什么你要从线上导出镜像啊, 考虑一下导出 sql 文件然后导入试试? docker 导出会非常大的

**Comment by hydgladiator** [comment]
线上容器中有很多配置好的Archery信息，手动下载mysql容器的话，很多东西又要重新导入。
