### ISSUE TITLE
[ 问题咨询 ] 查询导出excel后，原来是空的数据，在excel里面显示null，原来是有时间数据，在excel里面只显示年月日

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1035]
### 问题描述
查询导出excel后，原来是空的数据，在excel里面显示null，原来是有时间数据，在excel里面只显示年月日
![image](https://user-images.githubusercontent.com/13861904/109448411-e3baba00-7a80-11eb-8ae7-ef1e721c0487.png)

通过archery导入为excel后，为如下图：
![image](https://user-images.githubusercontent.com/13861904/109448517-16fd4900-7a81-11eb-803c-9c5aa15a4104.png)

如果用navicat导出后，其实真实的数据是这样的：

![image](https://user-images.githubusercontent.com/13861904/109448569-398f6200-7a81-11eb-843b-a81bc10a6197.png)

### 版本信息
 - 应用版本/分支：Release v1.8.0 
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
用 csv 导出看看, excel 的魔法太多了
