### ISSUE TITLE
[ 问题咨询 ]二次开发的开发环境大家都是在什么操作系统下进行的

### ISSUE THREAD

**Issue by jimmy-bj** [hhyo/Archery#1038]
二次开发的开发环境大家都是在什么操作系统下进行的### 问题描述
开发环境不是在windows上吧，windows环境部署起来很麻烦，pip没装成功，说是要装distribute，装distribute又失败了……，后面可能还会有其他环境的问题，所有就放弃了在windows上部署这个项目。
想做二次开发，在linux操作系统下按照部署文档部署成功了，但在linux下调试太困难了。希望有二开经验的同学分享一下
开发环境如何顺利部署。
是不是要搞个苹果系统

### 版本信息
 - 应用版本/分支：Archery-1.8.0
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
开发环境还是要自己多探索探索, pip 没装成功就是有些包没有现成的预编译包, 我猜是 ldap, 自己可以再看看

**Comment by LeoQuote** [comment]
windows 也可以开发的, 我就是windows 开发的, 二次开发的一些功能也可以考虑提 pr 回馈下社区

**Comment by jimmy-bj** [comment]
> windows 也可以开发的, 我就是windows 开发的, 二次开发的一些功能也可以考虑提 pr 回馈下社区
感谢

**Comment by jimmy-bj** [comment]
可以加一下你的私人QQ吗
我现在在做钉钉微应用的免登录
和钉钉对接部分都调试通过了，
现在到Archery这边想重写一下Archery用户session信息
方便交流一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hhyo/Archery] [ 问题咨询 ]二次开发的开发环境大家都是在什么操作系统下进行的 (#1038)





 
windows 也可以开发的, 我就是windows 开发的, 二次开发的一些功能也可以考虑提 pr 回馈下社区

**Comment by hhyo** [comment]
方便的话可以添加下我的个人微信，主页简介中有
