### ISSUE TITLE
[ bug ]SQL审核上线功能，没有按实际配置的规则进行校验和命中

### ISSUE THREAD

**Issue by xx287442776** [hhyo/Archery#104]
线上http://139.199.0.191的demo网站，
提交了一个如下的建表sql：
CREATE TABLE `city2` (
  `area` varchar(255) NOT NULL COMMENT '区域',
  `province` blob NOT NULL COMMENT '省份',
  `city` varchar(255) NOT NULL COMMENT '城市'
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = '城市区域划分字典表';

点击SQL检测/提交按钮，没有命中规则中的“EXIST_LOB_COLUMN | 存在大对象字段”规则，其规则定义为：
SELECT TABLE_NAME,column_name , DATA_TYPE FROM information_schema.COLUMNS where TABLE_SCHEMA='@username@' and DATA_TYPE in ('blob','mediumblob','longblob','text','mediumblob','longtext') order by table_name
亦如图：
![image](https://user-images.githubusercontent.com/18021151/55610595-d540c680-57b5-11e9-87ee-bb8e889441fc.png)

按理我提交的建表的字段中含有类型为blob的，应该被拦截或提示才对，但检测结果却无任何信息，
提交通过的截图如下：
![image](https://user-images.githubusercontent.com/18021151/55610464-8c890d80-57b5-11e9-9e29-4b9182fc80a1.png)

请帮看一下为什么规则没有命中或生效？

**Comment by hhyo** [comment]
SQL审核和数据库审核是两个独立的模块，没有关联，也就是数据库审核中添加的规则不适用于SQL审核

SQL审核中的语句审核是依赖inception实现，具体有哪些规则可以查看inception文档

数据库审核是移植的Themis，仅分析收集到平台的慢日志以及数据库对象
