### ISSUE TITLE
[ 问题咨询 ] mysql update语句报错，说列不存在，实际存在

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1042]
### 问题描述
mysql update语句报错，说列不存在，实际存在
![image](https://user-images.githubusercontent.com/13861904/110915055-28cccf00-8352-11eb-9390-5f912cf26438.png)

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker、

**Comment by hhyo** [comment]
更新goInception，此问题应该已经解决
