### ISSUE TITLE
查询脱敏数据报错

### ISSUE THREAD

**Issue by kun376361** [hhyo/Archery#1043]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker、手工部署

开启QUERY_CHECK后查询页面报错list index out of range，后台日志如下
[ThreadPoolExecutor-0_0:140158502303488][task_id:default][data_masking.py:37][WARNING]- 数据脱敏异常，错误信息：Traceback (most recent call last):
  File "/opt/archery/sql/utils/data_masking.py", line 32, in data_masking
    query_tree = inception_engine.query_print(instance=instance, db_name=db_name, sql=sql)
  File "/opt/archery/sql/engines/inception.py", line 171, in query_print
    print_info = self.query(db_name=db_name, sql=sql).to_dict()[0]
IndexError: list index out of range

关闭QUERY_CHECK后查询返回结果未脱敏，关闭QUERY_CHECK查询其他实例脱敏表返回结果正常脱敏。

查询语句是select * from tablename;

**Comment by hhyo** [comment]
应该是未配置inception导致

**Comment by kun376361** [comment]
inception已经配置过了，其他实例脱敏是正常的。

**Comment by kun376361** [comment]
字段的数量有限制吗？这个表的字段数量很多。

**Comment by xiaoshanshans** [comment]
同复现了这个问题，inception脱敏结果异常，但是goinception没问题，脱敏这块可以选用goinception么？ @hhyo
