### ISSUE TITLE
[ 问题咨询 ] LDAP配置完后没有同步到用户

### ISSUE THREAD

**Issue by lushenao** [hhyo/Archery#1044]
### 问题描述
LDAP配置完后没有同步到用户

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/59196347/111114304-04653280-859e-11eb-9f7f-0f503bcc41ba.png)

重新登录系统后没有同步到用户 系统日志也没有打印任何信息

**Comment by LeoQuote** [comment]
ldap 信息只有在用户登录时才会去同步
