### ISSUE TITLE
[ 问题咨询 ] docker安装部署，怎么选择docker外部数据库？

### ISSUE THREAD

**Issue by lanheader** [hhyo/Archery#1045]
### 问题描述
docker安装部署，怎么选择docker外部数据库？

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
在配置文件里更改 mysql 的连接信息, docker-compose 里去掉 mysql 容器就可以

**Comment by renkaige5** [comment]
在docker-compose中注释了mysql的配置,修改了redis的端口 在settings.py中修改了redis和mysql的配置
![image](https://user-images.githubusercontent.com/15625600/117395686-fd69f900-af2a-11eb-92b8-2a640615cebc.png)
![image](https://user-images.githubusercontent.com/15625600/117395718-0ce94200-af2b-11eb-92af-0c639bed1d4a.png)

  但是启动报错 请问有人知道怎么解决吗?
![image](https://user-images.githubusercontent.com/15625600/117395639-e4614800-af2a-11eb-88bb-416770d25e6a.png)

**Comment by LeoQuote** [comment]
这个报错说明改配置不成功, 检查下挂的配置吧

**Comment by hhyo** [comment]
yaml文件archery启动的地方需要修改下

**Comment by wokwong** [comment]
请问这个问题解决了吗？我遇到同样的问题。求帮助。

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/484a80e1b28c7d234cf35febc24a308ceee60a5c/src/docker-compose/docker-compose.yml#L56

这里的连接信息需要调整

**Comment by RayWoodson** [comment]
docker-compose.yml里archery服务的entrypoint: "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 60s /opt/archery/src/docker/startup.sh" 修改为：entrypoint: "dockerize -wait tcp://{{MySQLhostIP}}:{{mysqlport}} -wait tcp://{{redishostip}}:{{redisport}} -timeout 60s /opt/archery/src/docker/startup.sh"
settings.py文件里搜索MySQL和redis对应的端口全都是改成ip和端口
inception目录下的config.toml 和inc.cnf中backup_host backup_port 以及用户名和密码都改掉，然后重启archery
