### ISSUE TITLE
[ 问题咨询 ]数据脱敏查询始终报错：DataMaskingRules matching query does not exist.

### ISSUE THREAD

**Issue by waitspring** [hhyo/Archery#1046]
#### 背景说明
+ Inception 运行正常且已经接入 Archery，SQL 查询语句可以在 Inception 的日志中查到
+ Archery 已经配置有数据脱敏字段，相应的脱敏字段的元数据，可以在 Archery 数据库中查到

#### 发生问题
SQL 查询语句中，一旦查询被脱敏字段，Archery 平台始终报错 **DataMaskingRules matching query does not exist.**
**_请问如何才能有效配置脱敏字段？_**

#### 问题举例
Archery 的脱敏字段配置如下：
![image](https://user-images.githubusercontent.com/43627142/111406758-b3ca0400-8687-11eb-9d3e-68875488a8ce.png)

Archery 提交的 SQL 查询语句如下：
`select * from t_account_info limit 100;`

Inception 日志信息如下：
![image](https://user-images.githubusercontent.com/43627142/111406922-f12e9180-8687-11eb-9419-e10b4f466960.png)

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：手工部署

**Comment by waitspring** [comment]
问题已经解决：

1. 优先通过”系统管理“ ---> ”其他配置项管理“ ---> ”全部后台数据“ ---> ”脱敏规则配置” 配置脱敏规则
2. 针对已有的脱敏规则，通过 “系统管理” ---> “其他配置项管理” ---> “全部后台数据” ---> “脱敏字段配置” 配置有待脱敏的字段
3. 通过 “系统管理” ---> “配置项管理” ---> “SQL 查询” 开启动态脱敏

实话讲，现有的 Archery 文档写得一般，很多地方都描述得不清不楚的

**Comment by LeoQuote** [comment]
欢迎把上面这些说明加入到文档中
