### ISSUE TITLE
[ 功能建议 ] 修复子查询脱敏失败的问题

### ISSUE THREAD

**Issue by waitspring** [hhyo/Archery#1047]
### 目前遇到的问题/使用障碍
MySQL 子查询脱敏失败，例如：

_SELECT * FROM (
    SELECT * FROM t_account_info
) AS tmp;_
### 希望如何解决/实现它
遇到子查询直接抛错，不允许提交子查询
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
Duplicate of #123
