### ISSUE TITLE
[ 功能建议 ] 希望添加with语法的支持

### ISSUE THREAD

**Issue by belingud** [hhyo/Archery#1048]
### 目前遇到的问题/使用障碍

使用with语法进行查询会返回`不支持的查询语法类型`异常

### 希望如何解决/实现它

希望可以实现with语法的支持

**Comment by belingud** [comment]
我测试了项目的依赖sqlparse和mysqlclient，都是支持with语法的SQL语句的

**Comment by LeoQuote** [comment]
如果你启用了脱敏, 语句是会经过 inception 去查询的, 如果 inception 不支持, archery 也没有办法支持
