### ISSUE TITLE
[ 功能建议 ]好像不能连接docker主机外的数据库实例，连接失败。还是需要自己配置路由呢？

### ISSUE THREAD

**Issue by blandtblandt** [hhyo/Archery#105]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
可以进入容器测试网络连通性是否正常，对docker不熟悉可以尝试手动部署

**Comment by blandtblandt** [comment]
谢谢告知，按照文档重启下docker就可以了
https://www.cnblogs.com/hailun1987/p/7518306.html
