### ISSUE TITLE
连接阿里云mongdb执行update出现错误

### ISSUE THREAD

**Issue by hala21** [hhyo/Archery#1052]
mongo-shell已经升级到4版本，可以连接上，select也没有问题，update就出现下面的错误，replset 不正确，变成了mgset-300325:3717/admin。
实例连接:：
mongodb://dds-432434-pub.mongodb.hangzhou.rds.aliyuncs.com:3717,dds-342ff3-pub.mongodb.hangzhou.rds.aliyuncs.com:3717/?replicaSet=mgset-300325
端口:3717

错误信息：
replset name mismatch: expected **mgset-300325:3717/admin**, but remote node dds-432434-pub.mongodb.hangzhou.rds.aliyuncs.com:3717 has **replset name "mgset-300325"**, ismaster: { hosts: [ "11.17.14.39:3717", "11.17.14.109:3717" ], setName: "mgset-300325", setVersion: 1, ismaster: true, secondary: false, primary: "11.17.14.39:3717", me: "11.17.14.39:3717", electionId: ObjectId('7fffffff0000000000000001'), lastWrite: { opTime: { ts: Timestamp(1616147351, 1), t: 1 }, lastWriteDate: new Date(1616147351000), majorityOpTime: { ts: Timestamp(1616147351, 1), t: 1 }, majorityWriteDate: new Date(1616147351000) }, maxBsonObjectSize: 16777216, maxMessageSizeBytes: 48000000, maxWriteBatchSize: 100000, localTime: new Date(1616147354251), logicalSessionTimeoutMinutes: 30, connectionId: 29662894, minWireVersion: 0, maxWireVersion: 8, readOnly: false, ok: 1.0

**Comment by fancy-lee** [comment]
请问你配置实例是怎么配置的?

**Comment by hala21** [comment]
实例名称: moss
实例类型:  主库
数据库类型: Mongo
实例连接: mongodb://dds-432434-pub.mongodb.hangzhou.rds.aliyuncs.com:3717,dds-342ff3-pub.mongodb.hangzhou.rds.aliyuncs.com:3717/?replicaSet=mgset-300325
端口:3717
用户名：archery
密码：
数据库:moss

现象：update有错误。replset name 副本集的名字解析不正确。

**Comment by fancy-lee** [comment]
1.配置实例的时候，你只要配置任何一个节点就可以，不用配置所有的节点，读、写会自动查找其它节点然后进行读写操作
2.mongodb还是建议开启认证并为账号创建密码，开发的时候我这边没有对不开启认证并没有创建账号密码的情况做测试
3.数据库名默认是admin,我在后台写死了，所以你配置的账号最好也要有admin的权限
![image](https://user-images.githubusercontent.com/23489502/113963268-de107b00-985b-11eb-953a-16409f205fa8.png)

**Comment by hala21** [comment]
按照你的方法，已经能正常update
非常的谢谢！
