### ISSUE TITLE
[ 问题咨询 ] mongodb导出的json格式的数据有问题

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1053]
### 问题描述
从mongodb查询出来的数据，导成json格式后，数据有问题，具体见下图：

![image](https://user-images.githubusercontent.com/13861904/112260234-80e5c880-8ca4-11eb-95e2-e90d8bf44c1f.png)

![image](https://user-images.githubusercontent.com/13861904/112260327-ad014980-8ca4-11eb-91a7-f6179f221314.png)

 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by fancy-lee** [comment]
带数组的列导出暂时没有想到更好的办法，所以还不能很好支持，你标记 （array)7 Elements 是为了表格的正常显示，在后台对数据做的替换。要看或导出数组内的内容，你可以选择把最前的隐藏列选中再导出，注意要对$date和$oid做一下替换
![image](https://user-images.githubusercontent.com/23489502/113266431-dacf3980-9307-11eb-8f33-ebdc5ec34b73.png)

**Comment by czxin788** [comment]
感谢
