### ISSUE TITLE
[ 问题咨询 ] ldap配置完成后，使用ldap登录时，依旧提示“用户名或密码错误，请重新输入！”

### ISSUE THREAD

**Issue by shinideyuweiwen** [hhyo/Archery#1055]
### 问题描述
ldap配置完成后，使用ldap登录时，依旧提示“用户名或密码错误，请重新输入！”

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
你不能就这样报一个现象就没了, 不管是报bug 还是咨询, 配置, 日志, 截图, 你起码得有一个吧.

**Comment by shinideyuweiwen** [comment]
![image](https://user-images.githubusercontent.com/38178390/112830599-5a20fb00-90c5-11eb-9d42-05502e20a674.png)


![image](https://user-images.githubusercontent.com/38178390/112830657-6c029e00-90c5-11eb-91e9-e53d1d8493e8.png)

![image](https://user-images.githubusercontent.com/38178390/112831017-e9c6a980-90c5-11eb-8b5e-5acf2a349aa0.png)

**Comment by LeoQuote** [comment]
logging 里有一个选项是针对 django auth ldap 的debug , 可以开起来然后看看debug 日志

**Comment by shinideyuweiwen** [comment]
已解决，谢谢

**Comment by LeoQuote** [comment]
是怎么解决的呢? 麻烦分享一下解决的过程可以吗?

**Comment by shinideyuweiwen** [comment]
一开始setting里ldap配置错了，
```python
AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": "givenName",
        "last_name": "sn",
        "username": "sn"
    }
```

**Comment by tangtangli** [comment]
> 已解决，谢谢
遇到了同样的问题，请问下是怎么解决的呢？能否看下你的配置文件呢？
