### ISSUE TITLE
[ 功能建议 ] 建议添加对select语句的审核，使运维前置

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1056]
### 目前遇到的问题/使用障碍
目前，生产库故障频出，都是由select类型的慢sql引起。这些慢sql有的是没加合适索引，有的是sql语句写法有性能问题。
现在我们都是坐在那等着生产库出现故障了，才逼迫DBA和开发去优化慢sql，非常被动，天天被领导和客户骂。

### 希望如何解决/实现它
前置运维，即在开发和测试阶段，就能提前发现这些sql，优化整改后再上线，大大提高数据库的稳定性。
希望archery能加入对select的sql审核，因为引起生产库故障的sql，几乎都是select语句。
我调研过关于对select审核的工具：
1、商业版的：云和恩墨的SQM：https://enmotech.com/products/SQM
2、开源的：https://www.sohu.com/a/218893146_470018
![image](https://user-images.githubusercontent.com/13861904/112598773-09ea3480-8e4a-11eb-9880-16735dd4f9cb.png)

3、我个人的想法：买商业版的没必要，开源的功能没archery强大，希望archery能实现该功能：
```
    a）archery可以利用soar做select语句审核；
    b）用户提交sql，通过soar进行检测，如果分数低于90分的，自动驳回；分数高于90分的，可以形成工单，进入审批流程；
    c）对于特殊情况的sql，比如分数低于90分的，但是还想发线上，那就在archery中走特殊审批流程，只要有人同意，将来sql出性能问题，审批人就要担责
```

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/discussions/863

**Comment by czxin788** [comment]
感谢，现在想看看是不是可以把soar和jenkins结合

https://www.toutiao.com/i6802592447714034179/
