### ISSUE TITLE
[ bug ] 1.8.0 setting.py文件修改异常

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/Archery#1058]
### 重现步骤
setting.py文件修改debug=False或者DATA_UPLOAD_MAX_MEMORY_SIZE两个参数后，重启archery会导致网页加载不了js和css静态文件
步骤：
       用手动安装步骤，所有前置步骤完成后，根据wiki部署文档https://139.199.0.191/installation/manual/
的建议，
![image](https://user-images.githubusercontent.com/40595864/112712253-26997180-8f09-11eb-9d25-d1664c27865d.png)
修改DEBUG和DATA_UPLOAD_MAX_MEMORY_SIZE两个参数的值，发现启动时网页加载不了js和css文件，F12报错提示500异常代码，后续经过多次安装发现，只要不修改这2个参数，archery就能正常加载静态文件。

**Comment by hhyo** [comment]
https://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail

**Comment by michael-liumh** [comment]
哦，insecure模式就等同于Debug=FALSE了，了解了。
