### ISSUE TITLE
运行 docker-compose -f docker-compose.yml up -d 没一点反映，是什么情况呢

### ISSUE THREAD

**Issue by mawenbin666** [hhyo/Archery#106]
### 问题描述
我用的是docker安装，但是再安装的的时候，
运行命令，docker-compose -f docker-compose.yml up -d
屏幕上也没一点反映，请问这是什么情况。

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
聚聚，-d 就是后台运行。 屏幕上不会有显示的。

**Comment by mawenbin666** [comment]
> 聚聚，-d 就是后台运行。 屏幕上不会有显示的。

不加-d也是一样的呢
![image](https://user-images.githubusercontent.com/22042460/55698460-7fa82c00-59f8-11e9-837f-aa3955906950.png)

**Comment by LeoQuote** [comment]
哦我知道了，你的app已经运行起来了，所以up没反应。

你可以试一下 docker-compose down

然后再 docker-compose up

**Comment by LeoQuote** [comment]
从描述判断应该是docker或docker-compose的问题，和archery无关。

**Comment by hhyo** [comment]
检查docker环境，简单的pull和run试一下

**Comment by mawenbin666** [comment]
问题解决了，是docker-compose没安装好，谢谢大家
