### ISSUE TITLE
[ 问题咨询 ]sql上线执行以后报出Error：Backup: ERROR 1105 (HY000): Failed to register slave; too long 'report-password'.

### ISSUE THREAD

**Issue by Dreamyyxt** [hhyo/Archery#1063]
### 问题描述
工单执行时系统报出Backup: ERROR 1105 (HY000): Failed to register slave; too long 'report-password'. Execute Successfully Backup failed
但是语句执行已经成功

![image](https://user-images.githubusercontent.com/7802431/113403588-7aa8c800-93d9-11eb-9bea-443d3e6e948c.png)

我查看了一下 src/init_sql/v1.0_init.sql:605->`slave_password` varchar(300) NOT NULL, 
我的sql密码是16位的，不知道是什么密码导致的 "too long report-password"
想寻求大佬的帮助！
谢谢！

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by hhyo** [comment]
#373

**Comment by Huangliyang-pub** [comment]
已修复，感谢
