### ISSUE TITLE
[ 问题咨询 ] 急！

### ISSUE THREAD

**Issue by Huangliyang-pub** [hhyo/Archery#1064]
### 问题描述
在archery服务器一次内存崩溃，导致服务器强制重启，之后重新启动服务器，浏览器界面的Markdown  SQL编辑界面无法操作，其余功能正常，想问一下怎么解决呢。。急
（之前版本是1.8.0，后来升级了1.8.1也没有解决）
### 版本信息
 - 应用版本/分支： v1.8.1  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
SQL上线的输入框无法编辑内容？

可以浏览器开发者模式看一下是否有静态资源加载失败或者错误

**Comment by Huangliyang-pub** [comment]
浏览器静态页面报错：
Failed to load resource: the server responded with a status of 404 (Not Found)
(index):974 Uncaught ReferenceError: editor is not defined
    at (index):974

Uncaught ReferenceError: editor is not defined
    at HTMLDocument.<anonymous> ((index):1501)
    at l (jquery.min.a09e13ee94d5.js:2)
    at c (jquery.min.a09e13ee94d5.js:2)

**Comment by Huangliyang-pub** [comment]
已修复，感谢。
