### ISSUE TITLE
[ 问题咨询 ] Oracle提交SQL检测报Internal Server Error

### ISSUE THREAD

**Issue by linxianhao** [hhyo/Archery#1066]
### 问题描述
Oracle提交SQL “update xxx set x=y where id in (1000条id)‘  SQL检测会报“Internal Server Error”。
### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
发一下日志吧, 500 只是表象, 不清楚到底怎么了
