### ISSUE TITLE
[ 问题咨询 ]oracle问题

### ISSUE THREAD

**Issue by zph1995818** [hhyo/Archery#1068]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

 

oracle的update语句可以在plsql里面执行，可以在“在线查询”看到有一条数据，但是在"sql上线"功能报错，看报错的意思是没有这条数据，以下具体报错，麻烦帮忙看看下，谢谢！！！
Oracle执行语句报错,语句 explain plan for update s_cs_setting set value = 'xxx' where code='xxx',错误信息Traceback(most recent call last):
File "/data/Archery-1.8.0/sql/engines/oracle.py",line279,in explain_check
if row[0] is None:
TypeError: 'NoneType' object is not subscriotable

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/pull/701
确认下权限是否都满足
