### ISSUE TITLE
[ 问题咨询 ]工单审核后一直排队中

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/Archery#1069]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
<img width="922" alt="企业微信截图_20210407093949" src="https://user-images.githubusercontent.com/78458951/113798208-56f0d380-9785-11eb-80e1-4682a3918d30.png">
python manage.py qmonitor截图如上

ps -ef|grep manage
也只发现一个qcluster进程
supervisorctl 重启qcluster   问题解决

### 版本信息
 - 应用版本/分支：Release v1.8.0 
 - 部署方式：k8s

**Comment by LeoQuote** [comment]
这不是问题解决了吗? 还需要干啥

**Comment by sona-yuan** [comment]
k8s部署就是为了部署即可用呀，总不能每次部署完还手动到容器重启一下吧

**Comment by hhyo** [comment]
是不是没有等待redis启动就启动了服务，导致worker启动失败

**Comment by sona-yuan** [comment]
redis是单独部署的，先启动了的。而且启动日志没有任何报错

**Comment by karhow** [comment]
您好，请问用k8s部署，你的GO_INCEPTION_HOST的host填的是什么
![image](https://user-images.githubusercontent.com/32405381/117433250-de388f00-af5d-11eb-8d30-dee3ec466b28.png)，我没找到答案
