### ISSUE TITLE
[ 问题咨询 ]实例中的test库默认被过滤掉了吗？

### ISSUE THREAD

**Issue by blandtblandt** [hhyo/Archery#107]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
还是贴一下吧：https://github.com/hhyo/archery/wiki/FAQ#%E9%80%89%E6%8B%A9%E5%AE%9E%E4%BE%8B%E5%90%8E%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%95%B0%E6%8D%AE%E5%BA%93

提问前先看文档
