### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by wangyi-5102** [hhyo/Archery#1071]
### 问题描述
SQL审核->SQL上线->输入SQL->SQL检测
SQL上线模块文本框添加建表语句每个表字段50个，添加1个表语句SQL检测通过，添加2个表时SQL检测报错Forbidden
请问报错原因是因为SQL模块SQL文本条数有限制吗？怎么调整？

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：手工部署

![image](https://user-images.githubusercontent.com/66997612/114337047-f1d11f80-9b82-11eb-88ef-03ee13fbdfeb.png)

**Comment by hhyo** [comment]
并没有限制，可查看下后端返回，怀疑是账号登出了
