### ISSUE TITLE
[ 问题咨询 ]--权限问题

### ISSUE THREAD

**Issue by Huangliyang-pub** [hhyo/Archery#1072]
### 问题描述
在添加“提交SQL查询”权限，用户就会有 资源组中所有库的查询权限，我想 定义 用户某个库或表 单独的查询权限，而不是所有库的查询权限

### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：手工部署

**Comment by Hank-Yoon** [comment]
请问您这个问题是怎么解决的？
我现在就是在用户管理，给资源组后，就可以直接查询，而不需要单独申请查询权限。  想实现您说的这种，请问是怎么解决的？  谢谢。
