### ISSUE TITLE
[ 问题咨询 ]审批流程

### ISSUE THREAD

**Issue by sona-yuan** [hhyo/Archery#1077]
### 问题描述
sql查询和上线审批流程为：申请人-->TL-->dba
用户A 是申请人，但同时也是用户B的TL，这时候按照用户组进行审批流程设定时，用户A可以提交申请  同时又有审批申请的权限了，这一块怎么控制呢？

### 版本信息
 - 应用版本/分支：Release v1.8.0 
 - 部署方式：Docker

**Comment by hhyo** [comment]
诉求是？

**Comment by sona-yuan** [comment]
有审批权限的人不能审批自己提交的申请，否则审批就无意义了

**Comment by wayde-P** [comment]
这个问题是个问题..有没有啥解决方法呀?
