### ISSUE TITLE
[ 功能建议 ] 分库情况下，建议上线 增加 1份sql工单，同时上线多个实例的功能

### ISSUE THREAD

**Issue by earl86** [hhyo/Archery#108]
### 目前遇到的问题/使用障碍
分库情况下 1份sql，同时编辑多个工单，分多次上线db实例
### 希望如何解决/实现它
分库情况下，建议上线 增加 1份sql工单，同时上线多个实例的功能
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
重复#95
