### ISSUE TITLE
[ bug ] mongodb不支持aggregate

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#1080]
### 重现步骤
mongodb查询语句是aggregate时，报错，如下图：
![image](https://user-images.githubusercontent.com/13861904/115810623-d090ee80-a420-11eb-961a-2478f0c02132.png)

但是该语句在命令行里面是可以执行的：
![image](https://user-images.githubusercontent.com/13861904/115810739-059d4100-a421-11eb-8902-6590162780a6.png)

可见，mongodb是不支持aggregate原生sql的

### 期待结果和实际结果
期待结果：希望支持aggregate

实际结果:

 
### 版本信息
应用版本/分支：Release v1.8.0

部署方式：Docker

**Comment by linux-li** [comment]
支持模糊查询吗？
