### ISSUE TITLE
[ 问题咨询 ]SQL开启脱敏在线查询，报数据脱敏异常：'errlevel'

### ISSUE THREAD

**Issue by calvin2020** [hhyo/Archery#1085]
![image](https://user-images.githubusercontent.com/27796010/117412151-0668c380-af47-11eb-9de0-323f6b8487ad.png)
有朋友遇到过这是啥问题吗？

**Comment by LeoQuote** [comment]
里面没有 inception ?

**Comment by calvin2020** [comment]
![image](https://user-images.githubusercontent.com/27796010/117415111-82183f80-af4a-11eb-9690-83172b308b2d.png)
有inception.py

> 里面没有 inception ?

**Comment by calvin2020** [comment]
需要单独安装inception吗？archery不是集成了inception吗

**Comment by calvin2020** [comment]
已经处理了，要单独安装inception，谢谢解答

**Comment by calvin2020** [comment]
已解决
