### ISSUE TITLE
[ bug ] Sqlserver 子查询数据异常

### ISSUE THREAD

**Issue by sunnylua** [hhyo/Archery#1087]
#### 正常工具查询结果：
![企业微信截图_16203875675813](https://user-images.githubusercontent.com/43692993/117446999-81de6b00-af6f-11eb-824a-8f2e6027504b.png)

#### Archery查询结果：
![微信截图_20210507194810](https://user-images.githubusercontent.com/43692993/117447090-9f133980-af6f-11eb-957e-5fc6fe00124f.png)

### 版本信息
Sqlserver 2017
应用版本/分支：Release v1.8.1
部署方式：Docker

**Comment by sunnylua** [comment]
@LeoQuote 

不是的，上图实际查询结果只有1条，但是Archery的子查询没有生效！
例如：
Archery查询： ` select count(1) from t1 where id in (select top 10  id from t2) `
Archery查询结果等于： ` select count(1) from t1 where id in ('') `

实际结果：其他工具10条，Archery查询0条

**Comment by LeoQuote** [comment]
查询历史里的实际查询语句是什么?
