### ISSUE TITLE
[ 问题咨询 ]上线工单执行一直排队中

### ISSUE THREAD

**Issue by karhow** [hhyo/Archery#1088]
### 问题描述
上线工单执行一直排队中，setting.py的Django-Q设置sync已经是默认的 False  
![image](https://user-images.githubusercontent.com/32405381/117525213-be53aa80-aff3-11eb-86e5-2a419d8a1331.png)
![image](https://user-images.githubusercontent.com/32405381/117525219-c90e3f80-aff3-11eb-91ad-d0a7aaddbf1d.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：k8s部署

**Comment by LeoQuote** [comment]
请参阅一下文档按照文档排查看看

**Comment by WuhuGoldPilot** [comment]
文档没有关于这个排队中的描述啊，这个Django-Q设置sync还是我在其他issue看见的，但是就是默认的false，也是排队中

**Comment by WuhuGoldPilot** [comment]
请问容器里面只有这个日志
![image](https://user-images.githubusercontent.com/32405381/117529788-40e86400-b00c-11eb-8a52-0e74987461fb.png)
没有qcluster.log日志是什么鬼？

**Comment by karhow** [comment]
![image](https://user-images.githubusercontent.com/32405381/117529846-a3d9fb00-b00c-11eb-879e-a7a68d62e0c8.png)
这个接口里面队列有9个任务，没有成功的，也没有失败的

**Comment by karhow** [comment]
![image](https://user-images.githubusercontent.com/32405381/117536110-d5ae8a00-b02b-11eb-8f98-3ddd2d3d50f7.png)
请问这个是启动正常吗？
![image](https://user-images.githubusercontent.com/32405381/117536161-15757180-b02c-11eb-88e1-16d5d47d7395.png)
还有为什么官方的docker环境想要确认qcluster的运行状态时为什么都会报包错误的？

**Comment by karhow** [comment]
![image](https://user-images.githubusercontent.com/32405381/117536270-ae0bf180-b02c-11eb-8152-d531551799fd.png)
这是debug接口的数据，请问这是异常吗？还有我发现我的logs/qcluster.log日志是空的

**Comment by karhow** [comment]
![image](https://user-images.githubusercontent.com/32405381/117536352-2a063980-b02d-11eb-997b-bcb0cc9be89b.png)
查看qcluster状态，这样我的qcluster应该是成功启动的吧？

**Comment by hhyo** [comment]
很明显是启动失败了，supervisord配置文件没找到，启动脚本是很旧的版本了

**Comment by karhow** [comment]
https://github.com/hhyo/Archery/blob/master/src/charts/values.yaml 
我是用这个yaml启动的，请问需要修改什么

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/e10b061bee6c1abc12bcf5d77212e44ca7306f93/src/charts/values.yaml#L517

这个参考docker启动修改。yaml文件应该比较久没有维护了，如果部署成功可以帮助项目做下修改

**Comment by tata9001** [comment]
更新一下有问题的workflow状态，然后重新执行一下，应该就好了。

`update sql_workflow set status='workflow_review_pass' where status = 'workflow_queuing';
`

**Comment by maxianwei** [comment]
赞，用这个方法正常了。

**Comment by maxianwei** [comment]
> 更新一下有问题的workflow状态，然后重新执行一下，应该就好了。
> 
> `update sql_workflow set status='workflow_review_pass' where status = 'workflow_queuing'; `
@wangyun1517 赞，用这个方法正常了。

**Comment by jeromeji** [comment]
请问我现在状态都正常，但是状态就是不翻转，一直是排队中。。
