### ISSUE TITLE
[ 问题咨询 ] 添加数据库实例接口

### ISSUE THREAD

**Issue by boldmanQ** [hhyo/Archery#1089]
### 问题描述
有接口可以添加数据库实例嘛？
需求：内部OA系统审批，通过调用Archery接口，来自动添加实例

**Comment by LeoQuote** [comment]
没有接口文档, 接口也不一定有, 你可以看看页面上的请求, 自己构造一下

**Comment by boldmanQ** [comment]
我尝试过使用SQL直接入往sql_instance表中插入数据，发现插入后，无法在Djangon Admin后台进行维护
