### ISSUE TITLE
[ 问题咨询 ]docker安装binlog2sql在downloads下没有生成sql文件

### ISSUE THREAD

**Issue by blandtblandt** [hhyo/Archery#109]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
请详细描述你的操作步骤和结果

**Comment by blandtblandt** [comment]
这是目前日志的报错情况，异步获取完整的SQL文件不太确定是否需要另行配置。前端显示sql是没有问题的。
![image](https://user-images.githubusercontent.com/42641454/55734825-d6425400-5a52-11e9-8fb4-c73da888e41b.png)
![image](https://user-images.githubusercontent.com/42641454/55735558-2241c880-5a54-11e9-8020-df60c0aea068.png)

**Comment by LeoQuote** [comment]
@hh

**Comment by hhyo** [comment]
可到系统设置-其他配置-全部后台数据，django_q的task表查看相关任务执行情况

**Comment by blandtblandt** [comment]
Django Q下的Scheduled task、Failed tasks、Successful tasks都没有任何条目
![image](https://user-images.githubusercontent.com/42641454/55769697-3a493480-5ab4-11e9-840c-f9b0b08800e9.png)

**Comment by LeoQuote** [comment]
手工部署的？异步任务的django Q是不是没起？

**Comment by blandtblandt** [comment]
我是docker部署的，djiango Q服务是需要另启吗？

**Comment by blandtblandt** [comment]
查看了应该是启动命令的问题，我之前直接用docker-compose up -d启动的，用docker-compose -f docker-compose.yml up -d就可以了

**Comment by hhyo** [comment]
docker-compose up -d启动过程中可能出现redis比archery后启动，这会导致Django Q启动失败，
问题排查中，这两个个日志文件很重要，注意查看
```
downloads/log/archery.log
downloads/log/qcluster.log
```
