### ISSUE TITLE
[ 问题咨询 ] ldap用户退出重新登录报错

### ISSUE THREAD

**Issue by wokwong** [hhyo/Archery#1091]
### 问题描述
使用 ldap 认证，用户退出登录后重新登录，页面报“Internal Server Error”错误，日志报： django.db.utils.IntegrityError: (1062, "Duplicate entry 'wangj7@xxx.cn' for key 'username'")  错误。需要用管理员账号删除ldap账号之后，ldap账号才能再次登录。

怀疑  AUTH_LDAP_ALWAYS_UPDATE_USER = True 所致，改为False 依然报相同错误。

ldap配置为：
#LDAP
ENABLE_LDAP = True
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch

    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
        'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
    )

    AUTH_LDAP_SERVER_URI = "ldap://172.31.xxx.xxxx:389"
    AUTH_LDAP_BIND_DN = 'cn=admin,dc=xxx,dc=int'
    AUTH_LDAP_BIND_PASSWORD = 'xxxx'
    AUTH_LDAP_USER_DN_TEMPLATE = "cn=%(user)s,ou=Users,dc=xxx,dc=int"
    AUTH_LDAP_ALWAYS_UPDATE_USER = False  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息  #ldap属性映射
        #"username": "cn",
        "username": "mail",
        #"display": "displayname",
        "display": "cn",
        "email": "mail"
    }

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker、手工部署

**Comment by zhongy002** [comment]
没有遇到您说的这种情况，我用以下方式接的域认证。
    AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
    AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
    AUTH_LDAP_BIND_PASSWORD = "xxx"
    AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
    AUTH_LDAP_ALWAYS_UPDATE_USER = True 
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "samaccountname",
        "display": "displayname",
        "email": "mail"

**Comment by wokwong** [comment]
> 没有遇到您说的这种情况，我用以下方式接的域认证。
> AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
> AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
> AUTH_LDAP_BIND_PASSWORD = "xxx"
> AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
> AUTH_LDAP_ALWAYS_UPDATE_USER = True
> AUTH_LDAP_USER_ATTR_MAP = { # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
> "username": "samaccountname",
> "display": "displayname",
> "email": "mail"

我是在接AD域没成功的情况下，使用的ldap。我先参考你的配置，试试AD 能不能行。谢谢

**Comment by wokwong** [comment]
> 没有遇到您说的这种情况，我用以下方式接的域认证。
> AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
> AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
> AUTH_LDAP_BIND_PASSWORD = "xxx"
> AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
> AUTH_LDAP_ALWAYS_UPDATE_USER = True
> AUTH_LDAP_USER_ATTR_MAP = { # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
> "username": "samaccountname",
> "display": "displayname",
> "email": "mail"



> > 没有遇到您说的这种情况，我用以下方式接的域认证。
> > AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
> > AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
> > AUTH_LDAP_BIND_PASSWORD = "xxx"
> > AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
> > AUTH_LDAP_ALWAYS_UPDATE_USER = True
> > AUTH_LDAP_USER_ATTR_MAP = { # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
> > "username": "samaccountname",
> > "display": "displayname",
> > "email": "mail"
> 
> 我是在接AD域没成功的情况下，使用的ldap。我先参考你的配置，试试AD 能不能行。谢谢

**Comment by wokwong** [comment]
> > 没有遇到您说的这种情况，我用以下方式接的域认证。
> > AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
> > AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
> > AUTH_LDAP_BIND_PASSWORD = "xxx"
> > AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
> > AUTH_LDAP_ALWAYS_UPDATE_USER = True
> > AUTH_LDAP_USER_ATTR_MAP = { # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
> > "username": "samaccountname",
> > "display": "displayname",
> > "email": "mail"
> 
> 我是在接AD域没成功的情况下，使用的ldap。我先参考你的配置，试试AD 能不能行。谢谢

按照您的方法没能成功，报错信息;
[2021-05-19 20:02:54,219][MainThread:140289208461120][task_id:django_auth_ldap][backend.py:368][WARNING]- Caught LDAPError while authenticating wangj7: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090453, comment: AcceptSecurityContext error, data 52e, v3839'})

**Comment by 007akuan** [comment]
> > > 没有遇到您说的这种情况，我用以下方式接的域认证。
> > > AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
> > > AUTH_LDAP_BIND_DN = "cn=xx,ou=xx,dc=xx,dc=xx"
> > > AUTH_LDAP_BIND_PASSWORD = "xxx"
> > > AUTH_LDAP_USER_SEARCH = LDAPSearch('ou=xx,ou=xx,ou=xx,dc=xx,dc=xx',ldap.SCOPE_SUBTREE, '(samaccountname=%(user)s)',)
> > > AUTH_LDAP_ALWAYS_UPDATE_USER = True
> > > AUTH_LDAP_USER_ATTR_MAP = { # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
> > > "username": "samaccountname",
> > > "display": "displayname",
> > > "email": "mail"
> > 
> > 
> > 我是在接AD域没成功的情况下，使用的ldap。我先参考你的配置，试试AD 能不能行。谢谢
> 
> 按照您的方法没能成功，报错信息; [2021-05-19 20:02:54,219][MainThread:140289208461120][task_id:django_auth_ldap][backend.py:368][WARNING]- Caught LDAPError while authenticating wangj7: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090453, comment: AcceptSecurityContext error, data 52e, v3839'})

请问最后解决了吗，我遇到同样的问题

**Comment by JCchenxiang** [comment]
+1
