### ISSUE TITLE
[ bug ] Archery  tools PTArchiver not support mysql 8.0

### ISSUE THREAD

**Issue by liven0923** [hhyo/Archery#1093]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
![image](https://user-images.githubusercontent.com/19588537/118582465-f57d4500-b7c5-11eb-9744-9a15352514be.png)
用pt-archiver工具直接归档mysql 8.0的可以
![image](https://user-images.githubusercontent.com/19588537/118582547-180f5e00-b7c6-11eb-9a45-6c54c91ccf91.png)
使用Archery  tools PTArchiver 报错
这是mysql5.7的可以使用工具归档
![image](https://user-images.githubusercontent.com/19588537/118582750-763c4100-b7c6-11eb-9625-776625cc2c2b.png)
这个截图证明配置是没有问题的

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
最新版本验证没有出现异常，看起来是mysql 库的字符集不兼容导致，可以重新尝试看下

https://demo.archerydms.com/archive/7/
