### ISSUE TITLE
[ 问题咨询 ] 查询审核通过仍然无法查询

### ISSUE THREAD

**Issue by he941649438** [hhyo/Archery#1094]
### 问题描述
您好，我设置了查询审核，但是在我审核通过了，还是没有在线查询。

![image](https://user-images.githubusercontent.com/53210983/118587526-5fe6b300-b7cf-11eb-9192-1cdcf6dda171.png)

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docke

**Comment by LeoQuote** [comment]
这是两个权限, 一个是能不能看到菜单和 网页, 另一个是能不能查询, 你得有对应的查看权限才能看到

**Comment by he941649438** [comment]
您好，我给的权限如下图，您看一下是是缺少什么权限？
![image](https://user-images.githubusercontent.com/53210983/118606894-88c87180-b7ea-11eb-8e4c-018ea81ed0de.png)

**Comment by he941649438** [comment]
> 这是两个权限, 一个是能不能看到菜单和 网页, 另一个是能不能查询, 你得有对应的查看权限才能看到

您好，我给的权限如下图，您看一下是是缺少什么权限？

![image](https://user-images.githubusercontent.com/53210983/118607083-c2997800-b7ea-11eb-92c8-9c6eff9ad618.png)

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/auth#%E6%9D%83%E9%99%90%E6%B8%85%E5%8D%95 参考下这个吧

**Comment by he941649438** [comment]
> https://github.com/hhyo/archery/wiki/auth#%E6%9D%83%E9%99%90%E6%B8%85%E5%8D%95 参考下这个吧

为啥我现在查看提示我：  错误信息：connect() argument 1 must be str, not None

![image](https://user-images.githubusercontent.com/53210983/118610342-3db05d80-b7ee-11eb-86f7-460cb5225c85.png)

**Comment by LeoQuote** [comment]
实例配置有问题, 看看后台日志, 检查下配置

**Comment by he941649438** [comment]
现在是这样的，我已经实现了不需要审核就可以查询数据库，但是我现在想实现用户提交查询权限，然后dba同意了，用户才可以进行查看，然后我分配的权限如下：
![image](https://user-images.githubusercontent.com/53210983/118611062-055d4f00-b7ef-11eb-995f-c74478622f3a.png)
