### ISSUE TITLE
[ 问题咨询 ]如何修改SQL提交工单时候的，文件大小10M限制

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#1096]
### 问题描述
如何修改SQL提交工单时候的，文件大小10M限制。

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：手工部署

**Comment by gaoqiang-0327** [comment]
archery-1.8.1/sql/templates/sqlsubmit.html

**Comment by wujuwu** [comment]
补充提问个问题：我的版本是1.9.1，我修改了sql/templates/sqlsubmit.html内限制上传文件的大小为50M，但是SQL检测也不能通过，请问最大SQL文件是多少？
