### ISSUE TITLE
[ 功能建议 ]能否增加ssl的配置

### ISSUE THREAD

**Issue by bbnnqlyb** [hhyo/Archery#1097]
### 目前遇到的问题/使用障碍

mysql和postgresql都开启了ssl功能，在配置实例界面没有ssl相关配置，配置完实例会连接报错

### 希望如何解决/实现它

能否增加ssl相关的配置，比如是否开启ssl，可以上传证书

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

当前是通过修改mysql.py写死的证书
    def get_connection(self, db_name=None):
        # https://stackoverflow.com/questions/19256155/python-mysqldb-returning-x01-for-bit-values
        conversions = MySQLdb.converters.conversions
        conversions[FIELD_TYPE.BIT] = lambda data: data == b'\x01'
        if self.conn:
            self.thread_id = self.conn.thread_id()
            return self.conn
        if db_name:
            self.conn = MySQLdb.connect(host=self.host, port=self.port, user=self.user, passwd=self.password,
                                        db=db_name, charset=self.instance.charset or 'utf8mb4',
                                        conv=conversions,
                                        connect_timeout=10
                                        ssl={‘ca’:’/opt/archery/XXX.crt.pem’})
但是跨项目就很不愉快了，没法用多个证书

**Comment by LeoQuote** [comment]
这个 issue 早就提了, 欢迎 pr #918
