### ISSUE TITLE
[ 问题咨询 ] 一万多条update语句执行后，查看不了回滚SQL

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/Archery#1098]
### 问题描述
开发一次性提交上万条update语句，执行完成后，点击“查看回滚SQL”，提示：数据加载失败！请检查接口返回信息和错误日志！，查看后端archery日志，没有任何输出

初始怀疑是机器性能问题，用top命令监控资源消耗，发现也没有太大消耗，不知道问题出在哪？

### 版本信息
 - 应用版本/分支：Release v1.8.1  
 - 部署方式：Docker部署
 -->

**Comment by michael-liumh** [comment]
docker日志如下
![image](https://user-images.githubusercontent.com/40595864/118968963-18af1c80-b99f-11eb-8e62-7ac5392a5f18.png)

**Comment by michael-liumh** [comment]
看了后端数据库，只存储了34条回滚SQL？
![image](https://user-images.githubusercontent.com/40595864/118969873-2ca74e00-b9a0-11eb-9624-0ce56c8da60f.png)

**Comment by michael-liumh** [comment]
更正一下查询结果，1621505285对应的是提单时间，但准确的数量应该是14536才对，难道因为少了一条，所以不返回了？
![image](https://user-images.githubusercontent.com/40595864/118971013-7cd2e000-b9a1-11eb-93e2-22dfd656f2c7.png)

那问题来了，为什么会少一条呢？

**Comment by michael-liumh** [comment]
看到错误日志了，不好意思：
[2021-05-22 18:26:14,180][MainThread:140235347568448][task_id:django-q][signals.py:28][ERROR]- return hook sql.utils.execute_sql.execute_callback failed on [sqlreview-execute-115] because 'NoneType' object has no attribute 'values'

**Comment by michael-liumh** [comment]
回滚SQL少了一条的原因搞明白了，那条SQL的影响行数为0，所以不需要备份，这样回滚SQL的数量就没问题了，但是为什么看不了回滚SQL呢？试过一次执行5000条，也还是看不了

**Comment by LeoQuote** [comment]
有可能是5000还是量太大了....

**Comment by hhyo** [comment]
可以试下能否正常下载

**Comment by michael-liumh** [comment]
> 可以试下能否正常下载
下载不了，等待一段时间后提示504错误
![image](https://user-images.githubusercontent.com/40595864/119443939-021d1280-bd5d-11eb-9323-354da7508b8c.png)
后端日志也没有任何输出

**Comment by michael-liumh** [comment]
数据库的审计日志一直在输出
![image](https://user-images.githubusercontent.com/40595864/119444096-46a8ae00-bd5d-11eb-84c5-c4a89f52755e.png)

**Comment by michael-liumh** [comment]
查看回滚SQL的时候，貌似也是这样，估计是数据量太多，archery等待超时了
![image](https://user-images.githubusercontent.com/40595864/119444518-f41bc180-bd5d-11eb-9200-a0f4136bdfbb.png)
![image](https://user-images.githubusercontent.com/40595864/119444530-f9790c00-bd5d-11eb-8181-b22562d44e9c.png)

**Comment by dba3306** [comment]
我也遇到类似的问题，希望官方能解决这个问题

**Comment by hhyo** [comment]
goInception为了备份效率没有给这个字段加索引，如果语句多查询会很慢，可以考虑自行添加索引

**Comment by michael-liumh** [comment]
加索引后5000条的能正常显示了，1万条的还是不能，一直显示在加载中
![image](https://user-images.githubusercontent.com/40595864/119525116-d1ff5f00-bdb0-11eb-896d-38c032573689.png)
后端数据库的数据是已经读取完成的了，这里的瓶颈应该是应用端了

**Comment by hhyo** [comment]
所以才提供了下载功能

**Comment by michael-liumh** [comment]
ok
