### ISSUE TITLE
[ bug ] 修改字符集和排序规则的DDL没有回滚语句

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/Archery#1107]
如图：提交修改表字符集的DDL
![image](https://user-images.githubusercontent.com/40595864/120181343-811fb880-c23f-11eb-97e8-6fd663cacefb.png)
执行完，提示备份成功，但提交回滚请求的时候，发现回滚语句是不完整的
![image](https://user-images.githubusercontent.com/40595864/120181439-a6acc200-c23f-11eb-8b98-24b2ff5efbe6.png)

部署方式：docker
版本：1.8.1

**Comment by hhyo** [comment]
已知问题，建议给goInception提交issue
