### ISSUE TITLE
[ 功能建议 ] 建议在上线工单的部分数据库可以多选，然后批量执行

### ISSUE THREAD

**Issue by AndyFan2017** [hhyo/Archery#1109]
### 目前遇到的问题/使用障碍

目前因为有多租户数据库，所以部分初始化工单需要多库执行，但是目前每个工单只能选择一个数据库

### 希望如何解决/实现它

建议在上线工单的部分数据库可以多选，然后批量执行

**Comment by hhyo** [comment]
同一实例🉑尝试使用 use 语句来切换数据库

**Comment by xiaozhi1236** [comment]
建议增加选择多实例批量执行

**Comment by cslingjun** [comment]
![image](https://user-images.githubusercontent.com/24772668/148726117-16f99f75-5ca4-4f1b-bb7b-50bedd1785e4.png)
![image](https://user-images.githubusercontent.com/24772668/148726206-382f0816-4f6b-46a4-b86e-cf84f0401ade.png)
改改大概就这样吧

**Comment by dongyinuo** [comment]
这个问题现在解决了吗？ 我看最新的版本，仍然没有这个功能
