### ISSUE TITLE
设置授权后无效

### ISSUE THREAD

**Issue by xiang-coco** [hhyo/Archery#1117]
### 问题描述
1. 新建用户后，给用户赋予Default 权限组。
2. 但是使用新用户登录后，无需申请权限，就能在 sql查询--在线查询 页面，选择到所在组的实例，实例下的所有数据库名，数据库名下的所有表信息。
3. 请问是需要在哪里配置还是bug呢
具体如下图：
![image](https://user-images.githubusercontent.com/39326801/122339932-3bb7f680-cf74-11eb-9bc3-4280cb076135.png)

![image](https://user-images.githubusercontent.com/39326801/122339962-44a8c800-cf74-11eb-8002-26adb3d9ba75.png)

![image](https://user-images.githubusercontent.com/39326801/122198062-64d07c80-cecb-11eb-95c1-705978744377.png)

![image](https://user-images.githubusercontent.com/39326801/122197933-44a0bd80-cecb-11eb-8b26-9112918f83b0.png)

### 版本信息
 - 应用版本/分支： Archery (v1.8.1)
 - 部署方式：手工部署

**Comment by xiang-coco** [comment]
请问有大神解答一下嘛

**Comment by hhyo** [comment]
库表信息没有做权限控制

**Comment by xiang-coco** [comment]
感谢大佬回复。
如果可以的话，建议按照用户申请的权限进行显示。

**Comment by lsp201811** [comment]
这个是不是申请的权限无效，只有两种权限有效，就是查询资源组内所有实例，或者查询所有实例，必须赋予这两个权限才能查，这个是什么问题，v.1.7.10版本

**Comment by lsp201811** [comment]
这个是不是申请的权限无效，只有两种权限有效，就是查询资源组内所有实例，或者查询所有实例，必须赋予这两个权限才能查，这个是什么问题，v.1.7.10版本
