### ISSUE TITLE
[ 功能建议 ]SET FOREIGN_KEY_CHECKS = 0语句

### ISSUE THREAD

**Issue by ht2324** [hhyo/Archery#1118]
### 目前遇到的问题/使用障碍
不支持语法 SET FOREIGN_KEY_CHECKS = 0语句
### 希望如何解决/实现它
后续可以支持吗 谢谢 或者我们可以修改源码吗
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
欢迎pr

**Comment by czxin788** [comment]
我也需要这个功能

![Image](https://github.com/user-attachments/assets/c27365dc-5c2c-4597-a027-a58d1af8085b)

**Comment by czxin788** [comment]
请问这个需要从哪下手呀，没有思路呀
是goinception不支持set foreign_key_chedks = 0 吧
