### ISSUE TITLE
[ bug ] archey调用binlog工具的bug

### ISSUE THREAD

**Issue by michael-liumh** [hhyo/Archery#1120]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1. 打开binlog工具页面，选择必要参数后，点击“获取SQL”，如下图
![image](https://user-images.githubusercontent.com/40595864/122863340-29afcc80-d355-11eb-9284-42fd4dedca57.png)
2. 到后台用ps命令`ps -ef | grep binlog2sql`获取命令行参数，如下图
![image](https://user-images.githubusercontent.com/40595864/122863533-80b5a180-d355-11eb-82d0-8858e402d686.png)
3. 可以看到archery调用binlog2sql时，--sql-type参数的值是加了引号的`--sql-type 'INSERT UPDATE DELETE'`
4. 参照`ps -ef | grep binlog2sql`获取到的执行命令，手动执行一次，如下图：
![image](https://user-images.githubusercontent.com/40595864/122863720-e6a22900-d355-11eb-9f03-97a441673133.png)
5. 可以发现，执行完，确实没有结果输出，但如果去掉--sql-type参数值的引号后再执行，会发现，是能获取到结果的，如下图
![image](https://user-images.githubusercontent.com/40595864/122863934-4b5d8380-d356-11eb-9c23-bf3789fadc12.png)

### 期待结果和实际结果
期待结果：能获取binlog解析后的结果

实际结果：不能获取binlog解析后的结果

 
### 错误日志
无，截图见上述重现步骤

### 版本信息
应用版本/分支：Release v1.8.1

部署方式：手工部署

**Comment by michael-liumh** [comment]
解决方案：
1、编辑 /opt/archery/src/plugins/binlog2sql/binlog2sql.py，修改第 43 行，将 self.sql_type = [t.upper() for t in sql_type] if sql_type else [] 修改为 self.sql_type = [t.upper() for t in sql_type.split()] if sql_type else []；
2、编辑 /opt/archery/src/plugins/binlog2sql/binlog2sql_util.py，修改第 43 行，将 nargs='*',  这个参数删掉

**Comment by LeoQuote** [comment]
请直接提pr 吧

**Comment by michael-liumh** [comment]
> 请直接提pr 吧

这个是 docker 里内置的 binlog2sql 工具的兼容问题，我这是直接改工具的代码，直接拉线上代码找不到 binlog2sql.py 这个文件

**Comment by LeoQuote** [comment]
https://github.com/danfengcao/binlog2sql/blob/master/binlog2sql/binlog2sql.py 是这个项目吧, 去这里提, 然后在 archery 这里更新版本号

**Comment by hhyo** [comment]
那边项目不更新了，这个应该是增加shlex.quote转义引入的bug，可以做个识别处理

**Comment by hhyo** [comment]
已处理
