### ISSUE TITLE
[ bug ]提交sql上线请求时，不美化sql，报错：read_only = self.query(sql='SELECT @@global.read_only;').rows[0][0] IndexError: list index out of range

### ISSUE THREAD

**Issue by Skatexg** [hhyo/Archery#1121]
简单描述问题出现场景和重现步骤，如
1. 在提交sql上线请求时，偶尔汇报如下错误
![image](https://user-images.githubusercontent.com/9860126/123571349-9c5cf400-d7fc-11eb-99e8-8d6c011312dd.png)

2. 但是重新提交下，把提交的sql语句内容“美化”下，重新提交就可以

### 期待结果和实际结果
期待结果：可以正常提交sql上线请求

实际结果: 提交sql上线请求，偶尔会报错（目前遇到的是，提交的sql内容稍微长一点）

### 错误日志
list index out of range : Traceback (most recent call last):
File "/root/venv4archery/lib/python3.6/site-packages/django_q/cluster.py", line 436, in worker
res = f(*task["args"], **task["kwargs"])
File "/data/dbsoft/Archery-1.8.1/sql/utils/execute_sql.py", line 35, in execute
return execute_engine.execute_workflow(workflow=workflow_detail)
File "/data/dbsoft/Archery-1.8.1/sql/engines/mysql.py", line 292, in execute_workflow
read_only = self.query(sql='SELECT @@global.read_only;').rows[0][0]
IndexError: list index out of range

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：手工部署

**Comment by hbzhu** [comment]
我也是遇到这个类似的报错

**Comment by chaigang0** [comment]
我们用了 1.8.1 版本，也偶尔遇到这个问题，
重新提一次相同工单又没有任何问题，
这个问题目前不可复现。

**Comment by chaigang0** [comment]
为何要关闭这个ISSUE呢，是因为大家都无法复现吗？
我们这边偶尔还是有这个报错，但是都发生在，我们要执行工单的时候，一点击执行工单，马上就会返回报错。
根据多次错误经验，我们认识是代码没有连接到数据库，SQL命令【SELECT @@global.read_only】结果返回是空，所以才会报错【IndexError: list index out of range】，
我们调整了JDBC connect_timeout=30 
但于事无补，还是会出现，一点击执行工单，马上就会返回报错的场景。

@hhyo

**Comment by hhyo** [comment]
执行工单会做库的只读检测，避免在只读库上执行，出现这个异常就是获取只读状态异常了，可以看看error，执行异常都会有错误记录

**Comment by weideguo** [comment]
有没可能是执行[query](https://github.com/hhyo/Archery/blob/4131417635e2eb69e486ab46164312096b6d6016/sql/engines/mysql.py#L140)函数出现异常，导致[result_set.rows](https://github.com/hhyo/Archery/blob/4131417635e2eb69e486ab46164312096b6d6016/sql/engines/mysql.py#L161)的值为`[]`，因而在[判断](https://github.com/hhyo/Archery/blob/4131417635e2eb69e486ab46164312096b6d6016/sql/engines/mysql.py#L306)时发生报错。@hhyo

**Comment by xiaozhuang-a** [comment]
我这里稳定复现，奇怪的是同样的语句执行到阿里云的rds高可用版且有代理的就不行（archery里面填写不是代理地址，是主库地址），普通的就可以。
报错信息完全相同

**Comment by FLGBetter** [comment]
我们的也是，怎么解决的啊
