### ISSUE TITLE
【mongo查询报错 -禁止执行该命令！】

### ISSUE THREAD

**Issue by caicaicaiyuting** [hhyo/Archery#1123]
### 问题描述
-  添加mongodb实例，启用用户密码认证通过，能够连接数据库实例，但是查询时报错：
- 语法是正确的，但命令被禁止了，这个怎么配置呢？
-  `禁止执行该命令！正确格式为：{collection_name}.find() or {collection_name}.find(expression),如 : 'test.find({"id":{"$gt":1.0}})'`
![image](https://user-images.githubusercontent.com/39758945/124087500-a2fd9c80-da84-11eb-99ca-7d6fc0c02df2.png)
- 

### 版本信息
 - 应用版本：Archery (v1.6.7)
 - 部署方式：Docker

**Comment by fancy-lee** [comment]
建议升级一下最近的版本，1.8开始支持原生的语法查询和审核了

**Comment by caicaicaiyuting** [comment]
> 建议升级一下最近的版本，1.8开始支持原生的语法查询和审核了

- OK 
- Thank you very much.
