### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by opsonly** [hhyo/Archery#1125]
### 问题描述
v1.7.11升级v1.7.12的时候 ，src/init_sql/v1.7.11_v1.7.12.sql 里的字段是不是有问题，我部署的发现跟model的里的冲突了，model里的是pkey_path，sql里的是pkey_address，麻烦确认下
### 版本信息
 - 应用版本/分支：Release v1.7.12
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/src/init_sql/v1.7.11_v1.7.12.sql 已经修复了. 以最新版本为准
