### ISSUE TITLE
[ 问题咨询 ]如何添加实例呢

### ISSUE THREAD

**Issue by mawenbin666** [hhyo/Archery#113]
### 问题描述
我再实例列表里填好了数据库的用户配置信息，但是点击测试的时候，报错：无法连接实例
![image](https://user-images.githubusercontent.com/22042460/55793848-6a192c00-5af6-11e9-8084-fa8ecc85536e.png)

![image](https://user-images.githubusercontent.com/22042460/55793824-5b327980-5af6-11e9-9b73-94ca56d14bff.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by mawenbin666** [comment]
> ### 问题描述
> 我再实例列表里填好了数据库的用户配置信息，但是点击测试的时候，报错：无法连接实例
> ![图片](https://user-images.githubusercontent.com/22042460/55793848-6a192c00-5af6-11e9-8084-fa8ecc85536e.png)
> 
> ![图片](https://user-images.githubusercontent.com/22042460/55793824-5b327980-5af6-11e9-9b73-94ca56d14bff.png)
> 
> ### 版本信息
> * 应用版本/分支：发布v1.4.5
> * 部署方式：码头工人

补充下，权限是够的
![image](https://user-images.githubusercontent.com/22042460/55793969-b19fb800-5af6-11e9-9677-64494910cc17.png)

**Comment by LeoQuote** [comment]
把密码重新填一下然后保存

**Comment by mawenbin666** [comment]
> 把密码重新填一下然后保存

重新保存了密码也是不行的。是不是缓存的问题呢，
还有，我的服务器ip是172.16.168.30，但是报错提示说是172.18.0.1的ip不能访问，
是不是安装了docker引起的呢？
![image](https://user-images.githubusercontent.com/22042460/55794886-13f9b800-5af9-11e9-97d8-1cd8bdc962ab.png)

**Comment by hhyo** [comment]
直接进docker，进行各种测试吧，docker网络相关文档也可以了解下
```
docker exec -ti archery /bin/bash
mysql -h
```
