### ISSUE TITLE
[ bug ]MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'P.time' in 'where clause'")

### ISSUE THREAD

**Issue by huangpeng0817** [hhyo/Archery#1130]
手动部署
使用会话管理，事物信息时，报错：
<img width="928" alt="图片" src="https://user-images.githubusercontent.com/46477158/125577801-7572b8c3-6555-45a8-bf3a-3d37700434cc.png">
手动去db_diagnostic.py把AND p.time > 3删除重写了下，好了。。

**Comment by GloomyNAN** [comment]
已修复，[pr1175](https://github.com/hhyo/Archery/pull/1175)
