### ISSUE TITLE
SQL上线执行出错

### ISSUE THREAD

**Issue by jaker16888** [hhyo/Archery#1135]
![image](https://user-images.githubusercontent.com/59276927/126153052-829e2633-7a6a-4fec-a50c-cf6372ea40bc.png)
上线执行sql失败，劳烦看下。

**Comment by cdzhangyong** [comment]
因为你的数据库实例配置有问题

**Comment by Ants5** [comment]
我也碰到同样错误，docker-compose安装的，但mysql是外部的数据库，该怎么解决

**Comment by Ants5** [comment]
> ![image](https://user-images.githubusercontent.com/59276927/126153052-829e2633-7a6a-4fec-a50c-cf6372ea40bc.png) 上线执行sql失败，劳烦看下。

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/issues/1362
是否有用隧道连接？

**Comment by cdzhangyong** [comment]
ip地址写错了




就爱古琦
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hhyo/Archery] SQL上线执行出错 (#1135)





  
 上线执行sql失败，劳烦看下。
