### ISSUE TITLE
[ 问题咨询 ] 升级时如果涉及表结构变更，回退的时候需要把表结构也回退吗

### ISSUE THREAD

**Issue by opsonly** [hhyo/Archery#1139]
### 问题描述
升级时如果涉及表结构变更，回退的时候需要把表结构也回退吗

### 版本信息
 - 应用版本/分支：v1.8.1
 - 部署方式：手工部署

**Comment by hhyo** [comment]
早期的版本有一些不兼容的表结构变更，可能需要回滚，具体可以自己分析下变更语句
