### ISSUE TITLE
[ 新功能 ] 数据库服务器密码在已经加密的情况下，不做二次加密

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#114]
### 目前遇到的问题/使用障碍
在修改现有数据库实例时，会遇到密码二次加密，导致密码失效的问题

特别有些手贱的情况保存了两次，就会导致服务器密码被二次加密，导致配置失效。
### 希望如何解决/实现它
在加密完成后给密文最后加上一串字符串（最好是密文中不会出现的字符），用来标记这个字段已经被加密过，不需要重复加密。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
今天思考了一下，如果在里面加上一些字符串标示密码已加密，到时候还要在文档里写禁止使用$1$ 开头的密码，不然不知道什么时候有用户就踩坑了。
我们还是自己实现一套修改实例配置的页面，进入修改页面的时候，默认不显示密码（毕竟是密文，显示没用），只有点击“修改实例密码”时才能修改密码。这样就可以区分开来部分save了。

**Comment by hhyo** [comment]
django admin可以增加自定义字段，也可以编辑时就展示明文字段
