### ISSUE TITLE
[ 问题咨询 ]  SQL分析，分析报告报错；

### ISSUE THREAD

**Issue by Are-xi** [hhyo/Archery#1140]
SQL分析，分析报告报错；所有的分析报告全是如下错误：
<img width="524" alt="8317e542a50ba763801add3d3154273" src="https://user-images.githubusercontent.com/49400334/126752766-8e315d84-6aae-454c-bce0-9c18751b9ece.png">

**Comment by hhyo** [comment]
没有配置soar信息
