### ISSUE TITLE
部署v.1.7.10版本，查询权限无法控制

### ISSUE THREAD

**Issue by lsp201811** [hhyo/Archery#1143]
### 问题描述
版本v1.7.10版本，其他功能都正常，但是查询这块有小问题，就是权限必须选这两者之中的一个才能查询，申请的权限查询报错
![image](https://user-images.githubusercontent.com/45093372/126959663-6b6ccfa4-5917-43e3-9dc6-0c47b6759df6.png)

![image](https://user-images.githubusercontent.com/45093372/126959889-480ce189-b30c-44b0-89da-167d414bfb21.png)
大佬有时间的话，可以帮忙提看下

**Comment by lsp201811** [comment]
必须拥有这两者权限之一，才能进行查询，没有这两个权限，然后进行权限申请，通过后，应该就可以查对应的申请通过的表，但是现在不行

**Comment by lsp201811** [comment]
感觉应该是没装goinception导致
![image](https://user-images.githubusercontent.com/45093372/126969620-e17a87b2-3be6-496d-a33e-880ce782b32c.png)
![image](https://user-images.githubusercontent.com/45093372/126969621-fe94b30b-ba82-46e3-a111-036568024718.png)
我还是用的之情的inception

**Comment by xiang-coco** [comment]
现在都用goinception , 是时候换掉inception 了

**Comment by lsp201811** [comment]
是的，已经解决了，是的




| |
13647430070
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年07月29日 16:36，xiang-coco 写道：

现在都用goinception , 是时候换掉inception 了
