### ISSUE TITLE
[ bug ]提交MySQL回滚语句报错

### ISSUE THREAD

**Issue by cdzhangyong** [hhyo/Archery#1162]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1、执行了mysql的update语句点选回滚
2、提示报错：(2006, 'MySQL server has gone away')
### 期待结果和实际结果
期待结果：
正常回滚
实际结果:

### 截图
![image](https://user-images.githubusercontent.com/13670030/129701804-9bc9babd-f1fa-4dba-bce8-2df5b56aed93.png)

 
### 版本信息
应用版本/分支：1.8.0

部署方式：Docker

**Comment by hhyo** [comment]
应该是语句过大，可以先下载
