### ISSUE TITLE
[ 功能建议 ] SQL上线工单加入假执行功能

### ISSUE THREAD

**Issue by jonn-yan** [hhyo/Archery#117]
### 目前遇到的问题/使用障碍
使用障碍：创建上线SQL工单，审核通过后，最后管理员立即执行这一步会连接数据库进行执行，为了规范管理而不仅仅为了方便所以不希望archery连接master库，会存在执行权限报错问题

### 希望如何解决/实现它
希望能够在立即执行这一步可以由人工去数据库执行，然后确认结束工单

### 其他信息
无

**Comment by LeoQuote** [comment]
没有这样的计划，我们的目标是尽量少让人直接接触数据库。
你的想法似乎是只想拿archery走流程，如果你只想有个走工单的流程，你可以尝试钉钉的审批流，那个设计起来更方便。

**Comment by jonn-yan** [comment]
挺喜欢 archery 里边的sql审核和优化的模块，流程也是挺好用的一块，只是为了安全考虑，不想过多于依赖系统的自动化，是否可以增加一个人工执行的按钮呢

**Comment by LeoQuote** [comment]
这块我感觉还是没想好， 暂时没有计划做， 但是我可以告诉你应该改哪里。

1. 在工单详情模版， https://github.com/hhyo/Archery/blob/master/sql/templates/detail.html#L138 执行工单的区域内加入一个 checkbox (可以叫dry_run 之类的)， 代表这个工单执行的时候是假执行
2. 在execute view https://github.com/hhyo/Archery/blob/master/sql/sql_workflow.py#L280 内读到这个前端传过来的参数， 如果为 dry_run 模拟一个返回，而不是真正的执行， 这样整个流程就可以走通了。

由于这个目前确实不是开发的重点， 近期应该不会考虑做这个， 但是你也可以考虑自己做。

同时也欢迎你提交pull request ， 只要单元测试全过， 代码风格上没有大问题我们就会合并。

**Comment by jonn-yan** [comment]
好的，非常感谢

**Comment by yzypals** [comment]
我在 detail.html中发现手工执行的一段modal，   这个原来是要做手工执行的功能的吗 ，~！~

**Comment by yzypals** [comment]
这个假执行的 我改好了 ，  oracle的查询和上线（手工执行）也做好了 ，可以上传吗

**Comment by LeoQuote** [comment]
非常感谢，请提交pr @yzypals

**Comment by hhyo** [comment]
已合并，支持开关配置
