### ISSUE TITLE
[ 问题咨询 ]用户管理-编辑功能无“资源组关联用户”

### ISSUE THREAD

**Issue by GloomyNAN** [hhyo/Archery#1174]
### 问题描述

https://archerydms.com/FAQ/#_2
根据文档：管理后台-用户管理-编辑用户 无法找到资源组绑定用户功能

### 文档位置

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/9264987/131462287-864512a6-d3b0-49f0-a0a6-1c6fa2d9e429.png">

### 系统编辑用户界面

![image](https://user-images.githubusercontent.com/9264987/131462431-31bdfb40-b8da-4a68-9723-2dc771107f70.png)

补充一下另外一个问题，文档实例管理中v1.8.1中只有测试按钮，没有“用户管理”
https://archerydms.com/home/#_8
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/9264987/131467945-0a226c71-caa6-4818-91df-74724734ea68.png">

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by hhyo** [comment]
文档比较旧了，加入日期上面的资源组就是关联资源组，用户管理独立为单独的菜单了

**Comment by GloomyNAN** [comment]
好的谢谢
