### ISSUE TITLE
[ 问题咨询 ]脱敏脚本问题

### ISSUE THREAD

**Issue by GloomyNAN** [hhyo/Archery#1176]
### 问题描述

https://archerydms.com/FAQ/#_7
<img width="761" alt="image" src="https://user-images.githubusercontent.com/9264987/131630628-b4df346e-b38f-4fa1-8da6-3faa669cc1e2.png">

此脚本为方便设置脱敏字段，但由于用户名和密码必须加密存储，所以代码获取脱敏字段mysql命令基本无效。

目前能想到的方式就是设置变量指定数据库，但又失去了脚本的扩展性~问一下可以把此功能集成到系统内部吗？

### 版本信息
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker

**Comment by hhyo** [comment]
敏感字段 命名各方没有标准，建议自行进行维护
