### ISSUE TITLE
工单明细没有过滤无效用户显示

### ISSUE THREAD

**Issue by hcb1987** [hhyo/Archery#1177]
在将用户设置为无效用户，且非工作人员状态后，工单明细里面显示的“”当前审批人“没有过滤
需要修改resource_group.py文件中auth_group_users函数的过滤条件
users = users.filter(groups__name__in=auth_group_names,is_active=1)

一般建议使用release版本，其他都是非稳定版本
 - 应用版本/分支：Release v1.8.1
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
欢迎提交pr
