### ISSUE TITLE
[ 功能建议 ] 支持ldap统一用户密码认证

### ISSUE THREAD

**Issue by jonn-yan** [hhyo/Archery#118]
### 目前遇到的问题/使用障碍
需要配置登陆用户密码，未支持ldap统一认证

### 希望如何解决/实现它
希望支持ldap统一用户密码认证

### 其他信息
无

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E9%9B%86%E6%88%90ldap archery支持ldap ， 请仔细查看文档。

**Comment by jonn-yan** [comment]
sorry，没有注意到这个细节配置，thanks！

**Comment by yzypals** [comment]
这里  如果能根据 组名，关联django 同名资源组和权限组 就好了  ， 不过感觉这个需求比较小众

**Comment by LeoQuote** [comment]
@yzypals 新需求请另开issue
