### ISSUE TITLE
[ 问题咨询 ]提交SQL上线工单需要什么权限呢

### ISSUE THREAD

**Issue by mawenbin666** [hhyo/Archery#119]
### 问题描述
普通用户提交SQL上线工单需要什么权限呢，每次都说权限不足。

![image](https://user-images.githubusercontent.com/22042460/55946851-fefb6100-5c7f-11e9-86e1-346abcce5fc3.png)
![image](https://user-images.githubusercontent.com/22042460/55946889-0e7aaa00-5c80-11e9-8927-0fd569a66cc3.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、

**Comment by hhyo** [comment]
文档

**Comment by LeoQuote** [comment]
建议查看文档 https://github.com/hhyo/archery/wiki

首页有对权限组的说明。
