### ISSUE TITLE
请问下相关的地址有变动吗

### ISSUE THREAD

**Issue by yidoa** [hhyo/Archery#1191]
### 问题描述
https://archerydms.com/installation/manual/
https://archerydms.com/home/
现在这些地址怎么打不开了呢
![image](https://user-images.githubusercontent.com/87849176/136937979-03b331ee-19ed-4490-bcf5-35df01769b42.png)

**Comment by hhyo** [comment]
#1189

**Comment by hhyo** [comment]
已开启ipv4的访问
