### ISSUE TITLE
脱敏问题

### ISSUE THREAD

**Issue by eason0420** [hhyo/Archery#12]
我用手册中的脱敏规则设置后，发现和实际不一样
(.{3})(.*)(.{4})  隐藏手机号前3位

(.*)(.{4})$  保留证件号后4位了

**Comment by hhyo** [comment]
麻烦把具体配置贴出来

**Comment by eason0420** [comment]
脱敏规则
手机号  |   (.{3})(.*)(.{4})   |   1   |   保留前三后四   |   2018-11-14 18:23:56
脱敏字段配置
1   |   手机号   |  激活  |  PROD_XXX_READ01  | table_name |  test01  |  mobile  |  2018-11-14 17:12:30


查询结果
id | name | mobile
1 | abcde | ****01945436
2 | bbbb | ****98362715
3 | ccccc | ****34827142


这是手机号的

**Comment by hhyo** [comment]
上面的脱敏规则就是隐藏第一组，正则把匹配的手机号分成了前三、中间、后四三组，隐藏第一组也就出现了对应的查询结果，如果需要保留前三后四，把隐藏的组改成2就好了

**Comment by eason0420** [comment]
噢，这里的组是这个意思，理解成了这个脱敏规则对哪个资源组生效啦
