### ISSUE TITLE
[ 问题咨询 ]升级1.4.5工单状态为未知状态

### ISSUE THREAD

**Issue by shizy123** [hhyo/Archery#120]
### 问题描述
docker部署升级1.4.5工单状态为全部未知状态
### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
升级时请阅读 release 页面的升级说明，有一些数据库脚本需要运行。

https://github.com/hhyo/archery/releases/

**Comment by shizy123** [comment]
v1.4.3_v1.4.5.sql脚本已经全部执行。别的页面都正常，就是工单状态有问题，全部都是未知状态

**Comment by LeoQuote** [comment]
你是从哪个版本升上来的？

https://github.com/hhyo/Archery/releases/tag/v1.4.3 这是1.4.3 的release 说明，是不是漏了这个脚本？

**Comment by shizy123** [comment]
我是从1.4.2升级上来的，我把1.4.3的sql还原就正常了，但是新提交的工单显示未知状态了，是和1.4.3的sql脚本有关系。

**Comment by hhyo** [comment]
可强制刷新浏览缓存，目前js没有版本控制，会出现缓存问题

**Comment by shizy123** [comment]
强制刷新浏览缓存,解决问题，谢谢

**Comment by LeoQuote** [comment]
> 
> 
> 可强制刷新浏览缓存，目前js没有版本控制，会出现缓存问题

666, 没想到js缓存的问题.....
