### ISSUE TITLE
会话管理--事务管理[ bug ]

### ISSUE THREAD

**Issue by jimsoft1000** [hhyo/Archery#1204]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
如果监控的MySQL数据库实例参数lower_case_table_names=0
调用会话管理--事务管理功能时，会报错，原因是执行下面的SQL，p.time中的p是大写
select trx.trx_started,
       trx.trx_state,
       trx.trx_operation_state,
       trx.trx_mysql_thread_id,
       trx.trx_tables_locked,
       trx.trx_rows_locked,
       trx.trx_rows_modified,
       trx.trx_is_read_only,
       trx.trx_isolation_level,
      p.user,
      p.host,
      p.db,
      TO_SECONDS(NOW()) - TO_SECONDS(trx.trx_started) trx_idle_time,
      p.time thread_time,
      IFNULL((SELECT
       GROUP_CONCAT(t1.sql_text SEPARATOR ';
      ')
    FROM performance_schema.events_statements_history t1
      INNER JOIN performance_schema.threads t2
        ON t1.thread_id = t2.thread_id
    WHERE t2.PROCESSLIST_ID = p.id), '') info
FROM information_schema.INNODB_TRX trx
  INNER JOIN information_schema.PROCESSLIST p
    ON trx.trx_mysql_thread_id = p.id
    WHERE trx.trx_state = 'RUNNING'
    AND p.COMMAND = 'Sleep'
    AND P.time > 3
    ORDER BY trx.trx_started ASC;

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
#1175
