### ISSUE TITLE
[ 问题咨询 ]关于子查询检测报错的问题，求解答

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#123]
### 问题描述
如下SQL无法通过检测：
INSERT INTO table_1 (
    pk_id,
    content,
    type
) SELECT
    UUID_SHORT(),
    0,
    a.print_type
FROM
    (
        SELECT
            tb2.type as type
        FROM
            table_2 tb2
            tb2.is_del = 0
    ) as a WHERE 1=1;

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
报什么错？ 请提供详细日志

**Comment by thickhang** [comment]
66 Query  /*--user=***;--password=***;--host=***;--enable-check=1;--port=***;*/            inception_magic_start;            use test;            INSERT INTO test.tm_print_config (
    pk_id,
    content,
    print_type,
    creationtime,
    modifiedtime,
    id_own_org
) SELECT
    UUID_SHORT(),
    0,
    "hisMemberCarEntranceDisplay",
    NOW(),
    NOW(),
    a.pk_id
FROM
    (
        SELECT
            tbo.pk_id
        FROM
            test.tb_org tbo
        INNER JOIN test.tg_org_group tgo ON tbo.pk_id = tgo.group_sponsor
        WHERE
            tbo.is_del = 0
    ) a;            inception_magic_commit

只有inception有日志输出，archery在这时间段没有日志打印出。这个问题没有别人反馈过吗？我感觉是个bug,开发者，你可以在自己的数据库简单模拟下这种子查询中用到别名 的这种插入操作。

**Comment by hhyo** [comment]
inception不支持，后续也不会支持

**Comment by liyingxiao94** [comment]
您好，我也最近在1.5.3版本docker方式部署遇到过类似的这个问题，update涉及到的派生表存在别名也遇到过，我尝试了inception和goinception两种审核方式，inception报两个别名错误，goinception报了一种别名错误

**Comment by hhyo** [comment]
goinception最近有相关更新，可使用新版验证，如果仍有问题可以给goinception项目提交issue

**Comment by liyingxiao94** [comment]
好的，谢谢 @hhyo
