### ISSUE TITLE
[ 问题咨询 ] TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by jonn-yan** [hhyo/Archery#124]
### 问题描述
SQL上线，执行SQL检测提示报错：
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/FAQ#%E6%A3%80%E6%B5%8Bsql%E6%8A%A5%E9%94%99 请按文档使用。
