### ISSUE TITLE
[ 功能建议 ] 提供1.50 版本添加 表结构备注的SQL文件

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#126]
### 目前遇到的问题/使用障碍

查询日志表 1.32版本中SQL中有备注说明，1.50版本就删除了备注说明。
很多表字段仍没有备注，对于升级、修改表数据时，非常不方便，望采纳，谢谢🙏。

--1.32 版本改动
-- 修改查询日志表
ALTER TABLE query_log
  ADD priv_check TINYINT NOT NULL DEFAULT 0
COMMENT '查询权限是否正常校验，1, 正常, 2, 跳过'
  AFTER user_display,
  ADD hit_rule TINYINT NOT NULL DEFAULT 0
COMMENT '查询是否命中脱敏规则，0,未知, 1, 命中, 2,未命中'
  AFTER priv_check,
  ADD masking TINYINT NOT NULL DEFAULT 0
COMMENT '查询结果是否正常脱敏，1, 是, 2, 否'
  AFTER hit_rule;

--1.50 版本改动
ALTER TABLE query_log
  MODIFY priv_check TINYINT NOT NULL DEFAULT 0 COMMENT '查询权限是否正常校验',
  MODIFY hit_rule TINYINT NOT NULL DEFAULT 0 COMMENT '查询是否命中脱敏规则',
  MODIFY masking TINYINT NOT NULL DEFAULT 0 COMMENT '查询结果是否正常脱敏';

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/src/init_sql/

这是初始化脚本的位置，刚刚看了下升级脚本并不存在字段没有comment的问题。

你想怎么改可以直接发pull request

**Comment by hhyo** [comment]
因为都改为布尔值，也就没必要注释，如果需要全表的注释，可以看代码里面的model定义，你可以按照model整理一份有注释的语句，给我们提pr

**Comment by think-coding** [comment]
按照1.0 版本的SQL，一路更新SQL，很多表没有comment，因为1.0的表，字段和表都没有comment。

**Comment by LeoQuote** [comment]
🤦🏽‍♂️头疼，这么说的话太多表没有备注了...我看一下django有没有这种功能，django里代码里的字段都是有备注的。

**Comment by hhyo** [comment]
> 🤦🏽‍♂️头疼，这么说的话太多表没有备注了...我看一下django有没有这种功能，django里代码里的字段都是有备注的。

我是没找到，看这里吧，别折腾了
https://github.com/hhyo/Archery/blob/master/sql/models.py

**Comment by think-coding** [comment]
好像对应不上表名，里面的列也不是表的所有列。
每个类没有类似 __tablename__ 的声明。

**Comment by LeoQuote** [comment]
>  每个类没有类似 **tablename** 的声明。

tablename 就是class名的驼峰式转下划线式

**Comment by hhyo** [comment]
db_table对应数据库内的tablename，如果没有db_table，就是appname_class名的驼峰式转下划线式

上面的model文件仅包含Archery的表信息，系统模块和三方模块比如auth、seesion、djang_q对应的对应的表信息要到对应app的model文件中确认

**Comment by hhyo** [comment]
已合并   #155
