### ISSUE TITLE
[ 问题咨询 ]初始化表结构报错

### ISSUE THREAD

**Issue by mawenbin666** [hhyo/Archery#128]
### 问题描述
我运行 python3 manage.py makemigrations sql的时候报错，我就改了端口，其他的都没改，
![image](https://user-images.githubusercontent.com/22042460/56140324-43af3100-5fcd-11e9-8775-18132a8b1d35.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by hhyo** [comment]
你还改了配置吧

假如你要解决问题，要尽可能的提供完整信息，至少详细到别人按照你的步骤能重现吧

**Comment by LeoQuote** [comment]
你怎么改的端口？ssh到容器里改的settings吗？具体改了哪些文件？具体做了哪些操作？仅仅说一个改了端口不是特别清楚。

另外从你的日志来看，mysql的配置怎么会是127.0.0.1？ 默认的docker镜像应该不是这个配置。

**Comment by LeoQuote** [comment]
@hhyo docker-compose 文件要不放在源码里不要放zip里，手机上不方便看，放zip里是出于什么考虑？因为docker-compose用的dockerfile和src里的dockerfile不一样吗？

**Comment by hhyo** [comment]
@LeoQuote 主要是有许多配置文件，当然都放在docker目录也没问题，其实可以新建一个archery-docker的项目

**Comment by LeoQuote** [comment]
🤦🏽‍♂️可能手机不适合用GitHub

**Comment by hhyo** [comment]
> @hhyo docker-compose 文件要不放在源码里不要放zip里，手机上不方便看，放zip里是出于什么考虑？因为docker-compose用的dockerfile和src里的dockerfile不一样吗？

已删除压缩包，改成文件夹形式
