### ISSUE TITLE
[ 问题咨询 ]当用户只申请table级别权限，查询报无权限？

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#134]
### 问题描述
用户申请表级别权限，但是查询时，不加条件可以进行查询，加了某个过滤条件，则报错无此库查询权限。

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
请给出具体语句。

**Comment by thickhang** [comment]
例如申请了数据库DB1的表table1权限；执行如下SQL：select * from table1;(可以查询)
执行如下：select * from table1 where name='test1';(弹框提示您无DB1库查询权限)

**Comment by hhyo** [comment]
很抱歉无法复现

**Comment by LeoQuote** [comment]
目前首页中的demo版本是1.5.1 如果在demo中没有这样的问题可以考虑升级版本解决问题。

**Comment by hhyo** [comment]
有复现步骤可以重开

**Comment by jerryhu1234** [comment]
版本1.53 docker部署
desc source_stat_v2;
开了表级的查询权限，提示没有权限
