### ISSUE TITLE
[ bug ] SQL上线--邮件通知标题中英文混合

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#137]
### 重现步骤
执行工单后，观察邮件通知标题。

### 期待结果和实际结果
期待结果：
上线和审核都是中文标题。

实际结果:
上线和审核都是中文标题，执行成功是英文标题。

### 截图
![image](https://user-images.githubusercontent.com/35367394/56481060-a897e900-64ef-11e9-886c-fcdac2cb702a.png)

部署方式：
手工部署  1.50

**Comment by think-coding** [comment]
已提交pr

**Comment by hhyo** [comment]
尝试编译文件后重启服务试试，v1.5.2测试未复现该问题

```
python3 manage.py compilemessages
```
