### ISSUE TITLE
[ 问题咨询 ] SQL查询结果导出EXCEL是异步方式吗？为什么导出8万行会卡死呢？

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#142]
### 问题描述
从SQL查询模块中，导出8万行数据，导出格式为excel，导出过程中卡死。

### 版本信息
 - 应用版本/分支：Release v1.5.0
 - 部署方式：手工部署

**Comment by hhyo** [comment]
导出是纯前端实现的，可以看下readme的依赖清单，大数据应该会导致浏览器不响应

**Comment by think-coding** [comment]
最好是能实现类似Navicat导出的效果。

**Comment by hhyo** [comment]
测试通过非谷歌浏览器比如IE\safari可以正常导出
