### ISSUE TITLE
[ 功能建议 ] 增加Oracle数据库的支持

### ISSUE THREAD

**Issue by hhyo** [hhyo/Archery#144]
由于没有接触过Oracle，不方便测试，所以一直没有加入Oracle模块，希望有相关需求的用户可以认领该功能，实现对Oracle的支持，使用Engine接入非常简单，可以在该Issue下讨论

### 希望如何解决/实现它
使用Engine接入Oracle的上线、查询功能，可以参考#91 #101

### 其他信息
https://github.com/hhyo/Archery/tree/master/sql/engines

**Comment by LeoQuote** [comment]
立个文档的flag🤔，这周做完

**Comment by hhyo** [comment]
🏃

**Comment by yzypals** [comment]
拭目以待啊 ， 找了一大圈  没找到支持oracle的开源项目

**Comment by LeoQuote** [comment]
@yzypals  由于缺乏oracle的资源， 目前的计划是出engine的文档， 然后其他人可以根据文档开发oracle相关功能。

**Comment by yzypals** [comment]
@LeoQuote  文档有吗  完全看源代码 有点累。    目前  想上线这个 项目  测试用 ， 需要 上oracle的 功能， 前期 就上线 审核 记录3个功能就行，   自己慢慢改代码。   现在在读源代码 整理你们 思路，  如果有开发文档 就更好了。

**Comment by LeoQuote** [comment]
@yzypals 文档有了, https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97

**Comment by yzypals** [comment]
@LeoQuote  

oracle 连接 需要多一个字段，有2种方法解决 a.修改model（Instance），在这里添加一个非必填字段sid（最好能和db_type扯上关系，只有选oracle的时候需要填写）。b. 添加1个model（Oracle），只有2列，关联Instance和sid。 目前想到 a比较好实现。但是要改到你们原来的model，特来请教。

**Comment by LeoQuote** [comment]
@yzypals 我们已经有一个oracle的初稿了， 在上面提到的pr中有代码

**Comment by hhyo** [comment]
@yzypals 查询已经合并进主干分支，前面的执行功能可以在该基础上提交PR，感谢

**Comment by yzypals** [comment]
@hhyo 我来同步下信息，  oracle 查询功能你们测试了吗

**Comment by yzypals** [comment]
oracle ajax 传的是db_name ,后端接收的是schema_name

**Comment by hhyo** [comment]
> @hhyo 我来同步下信息， oracle 查询功能你们测试了吗

目前还没有进行过测试👣

**Comment by hhyo** [comment]
#196

**Comment by rhkjyn** [comment]
什么时候能把这个功能发上来，我们这有环境，可以安排时间测试。

**Comment by LeoQuote** [comment]
@rhkjyn 感谢关心，目前oracle的相关代码已合并进master，只是没有release。

目前完成工单执行和检测功能，可以进行集成测试。

**Comment by LeoQuote** [comment]
@rhkjyn 欢迎帮我们测试master分支并提交bug报告👏

**Comment by rhkjyn** [comment]
sql查询时提示ORA-00942: table or view does not exist，无法获取到表信息

**Comment by rhkjyn** [comment]
ORA-00942: table or view does not exist


![WX20190522-160634](https://user-images.githubusercontent.com/16643979/58157824-c2be1600-7cab-11e9-93dc-de4706bb0ae6.png)
日志报错    select username from sys.dba_users;
理论上来说，应该不需要取sys下面的表的权限的。

**Comment by yzypals** [comment]
这个是权限的问题，  但是写这个的时候 默认拿了  oracle的系统级别的  只读权限的账号 ， 这个后期 有优化的 空间

**Comment by yzypals** [comment]
找DBA 要权限 select
        TABLE_NAME
        from dba_tab_privs
        where grantee in ('{db_name}')
        union
        select
        OBJECT_NAME
        from dba_objects
        WHERE OWNER IN ('{db_name}') and object_type in ('TABLE')

**Comment by rhkjyn** [comment]
嗯，感谢您的回复，我只是觉得不应该需要去查询sys下的表

**Comment by LeoQuote** [comment]
@rhkjyn 非常感谢你提供的测试反馈, 如果后期还有类似问题建议新开issue比较好, 这样比较清晰.

**Comment by hhyo** [comment]
后续讨论新开issue，1.6.0已发布，此issue关闭
