### ISSUE TITLE
[ 问题咨询 ] redis 缓存是给SQL上线用还是查询用？

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#146]
### 问题描述
现在的archery 没有配置redis，运行过程中，有很多次oom，archery 和 inception 都挂过。

### 版本信息
 - 应用版本/分支：Release v1.3.8
 - 部署方式：手工部署

 
问他一下 redis 缓存加入后，archery 还会不会挂？查询比较多，挂的原因是因为查询功能导致的OOM吗？

**Comment by LeoQuote** [comment]
一般你查多少行的时候会oom？后台有没有对返回的结果集行数做限制？

**Comment by LeoQuote** [comment]
如果消息体巨大的话，oom应该还是无法避免。

**Comment by think-coding** [comment]
有限制，每个用户默认100、500、1000，个别人单独调到了10000。
因为不是一个人用，可能有并发查询，有时候inception挂，有时候archery挂。
我写了个简单的守护脚本，一分钟检测一次，这是重启的日志。

![image](https://user-images.githubusercontent.com/35367394/56572560-e1b88200-65f1-11e9-8fae-45b0c8ae0138.png)

**Comment by think-coding** [comment]
04-18  15:14 时间点附近没有大查询、也没有上线。
![image](https://user-images.githubusercontent.com/35367394/56573658-2c3afe00-65f4-11e9-8d6e-f907b16587ee.png)
![image](https://user-images.githubusercontent.com/35367394/56573768-63111400-65f4-11e9-8af3-2b5898a53bc9.png)

**Comment by hhyo** [comment]
runserver起的？runserver崩溃很正常，不一定是oom，每次崩溃时的操作日志还是需要提供下

查询结果返回不是流式的，结果集会全部在内存中，1.5.0以后会缓存在redis中60s

inception就没办法了，也没人维护，可以替换成goinception

不过我自己docker部署，2核4g的机器稳定运行几个月没有出现过问题，也有几万的查询

**Comment by think-coding** [comment]
inception 最近一次挂之前有大查询
![image](https://user-images.githubusercontent.com/35367394/56574066-efbbd200-65f4-11e9-927c-40ff714a855b.png)

**Comment by think-coding** [comment]
> runserver起的？runserver崩溃很正常，不一定是oom，每次崩溃时的操作日志还是需要提供下
> 
> 查询结果返回不是流式的，结果集会全部在内存中，但不至于占用那么大
> 
> inception就没办法了，也没人维护，可以替换成goinception
> 
> 不过我自己docker部署，2c4u的机器稳定运行几个月没有出现过问题，也有几万的查询

是的，run server 启动的，好像之前配置的时候有问题，就用的runserver

**Comment by LeoQuote** [comment]
建议先从runserver改成 gunicorn 或者uwsgi 这些都有多进程，而且也有自动重启

inception好像真是没辙...

另外就是建议升级，升级后的查询和网页可以分开部署，qcluster可以自带的多进程和自动重启，能分担一些压力。

**Comment by think-coding** [comment]
> 建议先从runserver改成 gunicorn 或者uwsgi 这些都有多进程，而且也有自动重启
> 
> inception好像真是没辙...
> 
> 另外就是建议升级，升级后的查询和网页可以分开部署，qcluster可以自带的多进程和自动重启，能分担一些压力。

你说的查询和网页分开部署，是指的 archery 和 inception 吗？inception 一直可以部署在其他机器啊。

**Comment by LeoQuote** [comment]
发现一直都离题了，redis主要是两个角色：缓存和消息队列

缓存包括模版缓存和配置的缓存。

消息队列包括查询/执行的SQL语句和结果集。

加了之后网页的渲染速度应该会稍快一些，别的好处可能有限，消息体过大的问题可能依然存在。

**Comment by LeoQuote** [comment]
升级后的查询和执行是传到qcluster执行的，网页和qcluster可以分开部署

**Comment by think-coding** [comment]
> 升级后的查询和执行是传到qcluster执行的，网页和qcluster可以分开部署

了解，那是不是 qcluster 的机器只需要安装 qcluster，然后启动它。
在archery 再配置 qcluster 就可以了。

**Comment by LeoQuote** [comment]
qcluster和网页程序都需要archery完整的程序，具体可以看文档手动部署的部分。

这两个程序和配置都完全一样部署起来是最方便的，这样的情况下是完全免配置的。
