### ISSUE TITLE
[ 问题咨询 ]升级都1.5.2后点击sql检测没反应

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#148]
### 问题描述
我从1.4.5升级到1.5.2后，点击sql检测没反应是怎么回事，console报如下错误：
![image](https://user-images.githubusercontent.com/13861904/56637350-0407d980-669e-11e9-8cf1-d8277d8d3793.png)

### 版本信息
 - 应用版本/分支：Release v1.5.2
 - 部署方式：Docker、

**Comment by LeoQuote** [comment]
先尝试清理一下浏览器缓存，看看问题是否复现。
