### ISSUE TITLE
[ bug ]archery 大查询django页面渲染异常。run server 重启后正常。

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#149]
### 重现步骤
使用 gunicron 启动，archery 大查询后，django 后台页面渲染异常。
我把python3 所有进程 kill 后，重启nginx ，重启 startup.sh 仍然异常。

### 截图
![image](https://user-images.githubusercontent.com/35367394/56651026-c2395c00-66ba-11e9-8a7e-d42db6ed15eb.png)
![image](https://user-images.githubusercontent.com/35367394/56651501-bc904600-66bb-11e9-904a-cb8c6a4a4799.png)

### 错误日志
/downloads/log/archery.log
![image](https://user-images.githubusercontent.com/35367394/56651588-f6614c80-66bb-11e9-85c1-4a69c3fe55cc.png)

### 版本信息
应用版本/分支：

部署方式：手工部署 1.5.0

**Comment by think-coding** [comment]
把 nginx 停掉，启动 debug.sh 后正常。
![image](https://user-images.githubusercontent.com/35367394/56651951-c23a5b80-66bc-11e9-9244-0363b27a344b.png)

**Comment by hhyo** [comment]
看下faq里面关于前端样式异常的部分

**Comment by think-coding** [comment]
/etc/nginx/conf.d/nginx.conf
![image](https://user-images.githubusercontent.com/35367394/56652427-f3675b80-66bd-11e9-956e-ed56e6a67866.png)
settings.py
![image](https://user-images.githubusercontent.com/35367394/56652500-172aa180-66be-11e9-9253-be4c896173a5.png)
startup.sh
![image](https://user-images.githubusercontent.com/35367394/56652512-227dcd00-66be-11e9-928f-33a8a5e4bef4.png)

**Comment by LeoQuote** [comment]
gunicorn是处理动态网页的，nginx是用来做静态文件托管的，你得运行的 collectstatics 把文件收集过来。

再次推荐使用docker部署，手动部署目前文档不太完善，比较推荐对django有些接触的。

**Comment by think-coding** [comment]
> gunicorn是处理动态网页的，nginx是用来做静态文件托管的，你得运行的 collectstatics 把文件收集过来。
> 
> 再次推荐使用docker部署，手动部署目前文档不太完善，比较推荐对django有些接触的。

默认脚本里有collectstatics 啊

**Comment by LeoQuote** [comment]
默认的start.sh 把静态文件收集到了 项目文件夹下的 common/static 文件夹下，nginx也需要改成对应的目录才可以，这里要设置绝对路径。

**Comment by think-coding** [comment]
> 默认的start.sh 把静态文件收集到了 项目文件夹下的 common/static 文件夹下，nginx也需要改成对应的目录才可以，这里要设置绝对路径。

STATICFILES_DIRS  里面要用绝对路径吗

**Comment by hhyo** [comment]
alias去除common就好了

**Comment by think-coding** [comment]
哦，我试一试

**Comment by think-coding** [comment]
可以了。
common/static 和 static 有什么区别呢？

**Comment by LeoQuote** [comment]
https://docs.djangoproject.com/en/2.2/howto/static-files/ 建议看这个文档， 这个是django相关的知识

STATICFILES_DIRS 是待收集的静态资源文件夹列表

STATIC_ROOT 是收集后，静态资源的存放位置，把nginx配置到这个位置就对了。

由于和archery不相关本issue将关闭。
