### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by kaoanaa** [hhyo/Archery#150]
### 问题描述
archery支持高可用部署吗

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
archery的各组件包括 网页，django-q，redis，后端数据库mysql和inception，其中inception应该是不支持高可用部署，其他组件都可以做高可用部署
