### ISSUE TITLE
[ bug ] 1.5.0 DBA 查询不能获取完整结果集

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#151]
### 重现步骤
DBA 权限为什么查不出来29万行，手动加limit  一直提示”参数为空“？？？！！！

### 期待结果和实际结果
期待结果：
![image](https://user-images.githubusercontent.com/35367394/56721899-76e58300-6778-11e9-9033-8264005fa930.png)

实际结果:

### 截图
![image](https://user-images.githubusercontent.com/35367394/56721878-69c89400-6778-11e9-92fa-9b51aa2b9ae0.png)

![image](https://user-images.githubusercontent.com/35367394/56721566-bbbcea00-6777-11e9-8dec-0dfab0b9b92b.png)

### 版本信息

部署方式：手工部署 1.5.0

**Comment by think-coding** [comment]
SQL中去掉LIMIT，用 max 显示 参数为空！！！
想要申请权限修改结果集大小，但是显示有权限，不让添加，修改不了结果集！！！
急急急！！！！！

**Comment by LeoQuote** [comment]
http://139.199.0.191/sqlquery/ 已在demo页面复现 

复现步骤
查询时结果集大小选择max ， 输入任意查询, 点击查询

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/sql/query.py#L46 这一行改为 
```python
    if None in [sql_content, db_name, instance_name, limit_num]:
```
