### ISSUE TITLE
[ bug ]查询结果创建临时表的语句没办法通过语法检查。

### ISSUE THREAD

**Issue by 2002wmj** [hhyo/Archery#153]
类似这种创建临时表语句，点检测会报错。
重现步骤：
create table test555 (
select * from archer_test
);
截图：

![image](https://user-images.githubusercontent.com/16568733/56857753-e1c6d200-69a3-11e9-9efb-875a1e1f9e1c.png)

**Comment by LeoQuote** [comment]
没见过这种神仙语法，只见过create table 也没搜到create tables相关的语法介绍。 

这个语句在mysql客户端里能正常执行吗？

你是不是想写 CREATE TABLE new_tbl AS SELECT * FROM orig_tbl; ?

这是create table 文档 供参考 https://dev.mysql.com/doc/refman/8.0/en/create-table.html

**Comment by 2002wmj** [comment]
这条语句和你说的是一样的意思，加不加as都是一样的。
还有就是加上AS,语法检测也通过不了。
![image](https://user-images.githubusercontent.com/16568733/56857094-bf30bb00-699b-11e9-8d60-a4b9335fcc24.png)

![image](https://user-images.githubusercontent.com/16568733/56857779-22bee680-69a4-11e9-9d26-6ea34faaf43f.png)

**Comment by hhyo** [comment]
这种语句就拆分成两个吧，实例开启gtid也需要禁止执行此类语句

create like 和insert select

如果确实想支持，可以给goinception项目提交issues

**Comment by 2002wmj** [comment]
哦，那没问题了，我关闭issue了。

**Comment by think-coding** [comment]
SQL有别名， inception 审核是通不过的
