### ISSUE TITLE
[ 功能建议 ]增加一个权限让某个用户可以查询所有数据库。

### ISSUE THREAD

**Issue by 2002wmj** [hhyo/Archery#154]
### 目前遇到的问题/使用障碍
公司领导账号，不想给他超级用户权限，但希望他可以有所有库的查询权限，而不是让他自己一个个实例去提申请（如果新加了库还在去提）。

### 希望如何解决/实现它
增加一个用户权限，赋予后能查询所有库。

**Comment by LeoQuote** [comment]
可以考虑在检查权限代码里加上一个权限判断，如果用户有这个权限就和超级用户一样处理。

管理员要做的就是把权限授给用户或者把用户放进有这个权限的组里

**Comment by hhyo** [comment]
小需求，要是能直接提交pr就好了

**Comment by LeoQuote** [comment]
功能已完成, 给用户或用户所属组添加``可查询所有实例``权限, 用户即可查询所有实例, limit限制和后台配置的admin_limit一致
