### ISSUE TITLE
[ 问题咨询 ]如何结束异常状态的SQL？

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#156]
### 问题描述
由于某种意外原因，比如数据库服务意外宕机，导致某些工单状态一直在确认中...不停产生日志报错，请问如何结束此类工单？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
现阶段只能在admin界面或数据库中将工单状态直接置为中止或完成。

可以考虑后续加一个按钮可以强行结束工单。

**Comment by hhyo** [comment]
只能修改为人工终止的状态，否则详情打开会报错

**Comment by hhyo** [comment]
新版应该不会有这个问题了吧，只要qcluster起来，任务结束后一定会修改工单状态，并且有异常的会显示异常信息

**Comment by LeoQuote** [comment]
@hhyo 当时回复的时候没注意，不过新版依然没有配置超时吧，要不要加一个全局默认超时时间？

**Comment by hhyo** [comment]
超时这个不好说，DDL大表执行一天的可能都有
