### ISSUE TITLE
[ 功能建议 ] 如何在docker部署实现SlowQuery配置？？？

### ISSUE THREAD

**Issue by FANTASYSSL** [hhyo/Archery#159]
产看慢查询日志需要手动部署，能否利用docker部署涵盖，不要手动，必要时作少量修改即可。
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
慢日志主要的配置在各个实例，Archery这边要做的仅仅是创建相关表即可

**Comment by FANTASYSSL** [comment]
如果各个实例是部署在docker中，那怎么配置？

**Comment by LeoQuote** [comment]
这个问题和docker的相关性更高， 请自行搜索 docker 定时任务相关答案。 基本上是在docker 容器中安装pt 组件， 然后在宿主机中使用``docker exec`` 命令在docker 容器内执行shell脚本。

**Comment by hhyo** [comment]
即使实例在docker内，数据和日志应该也是通过volume或者其他途径持久化到宿主机

脚本部署环境满足以下条件即可，具体怎么实现，可自由发挥
- 能运行pt工具
- 能访问慢日志文件
- 能连接archery实例数据库写入数据

**Comment by cai823294620** [comment]
![image](https://user-images.githubusercontent.com/44595276/57267141-9ef6af80-70b1-11e9-8aaa-bafae34648d4.png)

` "Table 'archery.mysql_slow_query_review' doesn't exist")`
这个表是在哪个服务上创建呢，archery这个服务嘛？但是archery服务里默认是没有安装Mysql的。
