### ISSUE TITLE
[ bug ]数据库名中有减号的库不能查询

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#164]
### 重现步骤
创建数据库，如：db-test-1.
在其中创建表，创建账号，分配select 权限后，在“sql 查询” 菜单中，选择数据库看不到表，1.38可以看到。

##### 期待结果：
可以正常查询
##### 实际结果：
看不到库中的表

### 截图
![image](https://user-images.githubusercontent.com/35367394/57189816-c466aa80-6f45-11e9-810c-beb95b8a26f3.png)

### 错误日志
![image](https://user-images.githubusercontent.com/35367394/57189828-eb24e100-6f45-11e9-8399-cdc93863aac1.png)

### 版本信息
手工部署 1.50

**Comment by think-coding** [comment]
error提示代码如下
![image](https://user-images.githubusercontent.com/35367394/57190345-b451c980-6f4b-11e9-9c9b-d8bb88327d4d.png)

**Comment by LeoQuote** [comment]
改成 ``'use `{}`'.format(db_name)`` 应该就可以解决.

**Comment by hhyo** [comment]
可以把get_connection的db_name利用起来

**Comment by think-coding** [comment]
> 改成 `` 'use `{}`'.format(db_name) `` 应该就可以解决.

改过了，还是报错

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/57190831-8079a280-6f51-11e9-93f7-f0ad1550e30e.png)

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/57191194-3d213300-6f55-11e9-9e72-f8e06dc65fe6.png)
![image](https://user-images.githubusercontent.com/35367394/57191197-46120480-6f55-11e9-8cd5-a154dfa67df6.png)
![image](https://user-images.githubusercontent.com/35367394/57191203-5d50f200-6f55-11e9-9af8-9581ad019a3c.png)

=============
改成这样了，仍然报错～～～

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/57191421-0bf63200-6f58-11e9-904f-dbb91d6d1426.png)
![image](https://user-images.githubusercontent.com/35367394/57191437-3b0ca380-6f58-11e9-82b0-af4ee361f19b.png)
====================
是不是没得救了？除非改库包？

**Comment by LeoQuote** [comment]
改完之后， qcluster也需要重启。
简单改成这样就可以``'use `{}`'.format(db_name)``

**Comment by think-coding** [comment]
> 改完之后， qcluster也需要重启。
> 简单改成这样就可以`` 'use `{}`'.format(db_name) ``

重启后OK了

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/57192212-8460f100-6f60-11e9-89e2-65bcaf633196.png)
=================
SQL上线功能也有这个问题，怎么改一下呢？

**Comment by LeoQuote** [comment]
感谢🙏， 稍后我会在pr中新增修改方案， 你对照修改即可

**Comment by LeoQuote** [comment]
pr中已修改， 请对照修改， 修改完成后重启站点和qcluster即可。
