### ISSUE TITLE
[ bug ]权限申请数据库字段显示不全

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#165]
### 重现步骤
申请多个数据库，字符长度大于30个字符以上时复现。
数据库字段长度足够，存储正常。

### 期待结果和实际结果
期待结果：

实际结果:
![image](https://user-images.githubusercontent.com/35367394/57189927-10661f00-6f47-11e9-8e6d-aa77ac777dff.png)
![image](https://user-images.githubusercontent.com/35367394/57189948-633fd680-6f47-11e9-8902-4897ed173e86.png)

### 截图
![image](https://user-images.githubusercontent.com/35367394/57189917-f9bfc800-6f46-11e9-81be-51c97c70826f.png)

### 版本信息
部署方式：Docker、手工部署1.5.0

**Comment by hhyo** [comment]
权限级别为DATABASE时，详情会列出完整的数据库清单，不会存在显示不全的问题
权限级别为TABLE时，详情会列出完整的表清单，这时候如果单数据库名长度超过30，才会有影响

这里会修改成124，与主流数据库标识符长度限制保持一致

![image](https://user-images.githubusercontent.com/8842982/57190632-ddc02480-6f4e-11e9-9add-54f870632d0b.png)

**Comment by think-coding** [comment]
可是页面确实是30个字符，数据库实际是31个字符

**Comment by hhyo** [comment]
目前限制就是30，上面说了，清单列表可以显示
