### ISSUE TITLE
[ 问题咨询 ] archery 启动时有错误 LC_MESSAGES

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#168]
### 问题描述
CommandError: Execution of msgfmt failed: /opt/archery_1.5.0/venv4archery150/lib/python3.6/site-packages/wtforms/locale/ar/LC_MESSAGES/wtforms.po:57: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
msgfmt: found 1 fatal error

如图：
![image](https://user-images.githubusercontent.com/35367394/57194581-18d84d00-6f7b-11e9-9635-22214bc43bed.png)

startup.sh
![image](https://user-images.githubusercontent.com/35367394/57194595-33aac180-6f7b-11e9-9caa-f7200997d19b.png)

### 版本信息
 - 应用版本/分支：手工部署 1.5.0

**Comment by LeoQuote** [comment]
这个错误可以忽略，是wtform的小错误。

我已经提了wtform的pr，也已经merge，但没有发布新版，目前无法去掉这个错误。
https://github.com/wtforms/wtforms/pull/471

如果这个问题实在是想修复，可以把 python 环境移到项目外部，只要移到外部就不会有这样的问题。

另外说一下，如果可以的话，非ui方面的问题，建议你复制粘贴文本会比图友好一些，手机上看方便一些。

使用markdown中的代码区块会让这些文本好看很多。 http://www.runoob.com/markdown/md-code.html
