### ISSUE TITLE
上线SQL 为什么需要有对mysql库的权限？需要哪些权限？

### ISSUE THREAD

**Issue by FANTASYSSL** [hhyo/Archery#169]
### 问题描述
添加的主库账号对``mysql`` 库没有权限时， 检测SQL语句会失败。
```
Error 1044: Access denied for user '.......'  to database 'mysql'
```

上线SQL 为什么需要有对mysql库的权限？需要哪些权限？

### 版本信息
 - 应用版本/分支：Release v1.5.3  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
请按照模版提issue，并在提issue前查阅文档。

**Comment by FANTASYSSL** [comment]
执行一个SQL检测，返回这个错误 . 文档没提到上线检测sql 需要对 MySQL数据库 中的`mysql`库进行访问的权限，不考虑inception备份。

**Comment by LeoQuote** [comment]
请提供具体检测的语句，以及模版中需要的所有信息，archery版本，部署方式，等。

**Comment by FANTASYSSL** [comment]
docker 部署v1.5.3 ；

![image](https://user-images.githubusercontent.com/28664364/57210359-fbed5980-700e-11e9-9d62-f3e46f815184.png)

test用户仅拥有对l_mall库的所有权限.

实测: 当赋予test用户mysql库的所有权限时，检测通过。

为什么需要用户有对mysql库的访问权限？

**Comment by LeoQuote** [comment]
这个是inception需要的正常权限， 具体为什么inception需要我也不清楚， inception这块文档确实是不够全。 我一般是授 
```
GRANT REPLICATION CLIENT ON *.* TO 'sql_audit'@'host' identified by 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, INDEX, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW View,create,alter  ON *.* TO  'sql_audit'@'host' identified by 'password';
```

**Comment by think-coding** [comment]
inception 要检测用户是否有执行权限。
另外 REPLICATION CLIENT 是 pt-osc 需要用到的，所以也需要授权。

**Comment by hhyo** [comment]
用的goinception吧，可以给对应项目提交issue

**Comment by FANTASYSSL** [comment]
高手


| |
platofantasy
|
|
邮箱：platofantasy@163.com
|

Signature is customized by Netease Mail Master

在2019年05月06日 19:23，小圈圈 写道：

用的goinception吧，可以给对应项目提交issue

**Comment by FANTASYSSL** [comment]
> 用的goinception吧，可以给对应项目提交issue

高手
