### ISSUE TITLE
[ 问题咨询 ] mssql 报连接超时，sqlcmd可以正常连接，telnet 也可以正常连接

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#173]
### 问题描述
sql server 连接超时，使用 sqlcmd 可以访问。

![image](https://user-images.githubusercontent.com/35367394/57222055-dcb4f300-7033-11e9-9f36-937e969e5fde.png)

![image](https://user-images.githubusercontent.com/35367394/57222188-48975b80-7034-11e9-8fe1-4b78806fa881.png)

![image](https://user-images.githubusercontent.com/35367394/57222233-66fd5700-7034-11e9-981f-e4b58befb691.png)

![image](https://user-images.githubusercontent.com/35367394/57222267-84322580-7034-11e9-8692-3b6d65ca9fd7.png)

### 版本信息
 - 应用版本/分支：手工部署 1.5.0

**Comment by LeoQuote** [comment]
检查一下端口号写对了没有。

**Comment by LeoQuote** [comment]
另外就是这些driver和你的服务器sql server版本是不是对应的，在网上搜索一下有很多方案，我也不能准确帮你判断出来你是哪种问题

**Comment by think-coding** [comment]
端口、ip都没问题

**Comment by think-coding** [comment]
版本如果不正确的化，sqlcmd 不会连上去的

**Comment by LeoQuote** [comment]
我也没法帮你提供很多帮助，你可以在odbc的项目下发issue。
我的sql server是公司DBA帮我做的，具体怎么做的我也不清楚。
