### ISSUE TITLE
[ 问题咨询 ]sql 上线不能操作redis吗？

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#176]
### 问题描述
sql 上线不能操作redis吗？
![image](https://user-images.githubusercontent.com/35367394/57289358-c9fef480-70ed-11e9-92c2-bdfae72f5e34.png)

### 版本信息
 - 应用版本/分支：手工部署 1.5.3

**Comment by LeoQuote** [comment]
不能，redis上线功能未实现。

**Comment by hhyo** [comment]
> 不能，redis上线功能未实现。

可以的，提示不是让选择数据库么，不然怎么知道set到哪个db

**Comment by LeoQuote** [comment]
hhhhh， 原来已经实现了
