### ISSUE TITLE
如果启用一个布尔型的配置项, 再禁用, 会导致配置项实际上未关闭

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#18]
https://github.com/hhyo/archery/blob/master/sql/utils/execute_sql.py#L173

比如这里的判断, 因为写入数据库的时候,是文本型变量, 关闭配置项后, 配置值是 'false', 是字符串, 这里的if 判断条件会为真.

建议修改:

1. sysconfig 对象中加入 get 方法, 如果获取到的key 的内容是 'false' ,转换为 返回 ``False`` ,如果内容是 'true', 返回 `True`
2. 把所有的 ``sys_config.get()`` 改成 ``.get()``, 使用新定义的get方法

**Comment by LeoQuote** [comment]
经验证,由于使用了simplejson ,会在解析时将值自己改为``True`` 和 ``False``

**Comment by hhyo** [comment]
是自己在类方法里面转了一遍，哈哈
