### ISSUE TITLE
[ 问题咨询 ]修改了redis端口，sql查询时连接拒绝

### ISSUE THREAD

**Issue by DemonTang** [hhyo/Archery#184]
### 问题描述
将docker-compose.yml中的redis对外端口改为16379，我已经调整了settings.py中的使用sql查询的时候提示连接拒绝

### 版本信息
 - 应用版本/分支：Release v1.5.3
 - 部署方式：Docker
 
查询异常报错，错误信息：Error 111 connecting to redis:16379. Connection refused.

**Comment by hhyo** [comment]
docker 网络内使用原端口即可
