### ISSUE TITLE
[ 问题咨询 ]当数据库表名或数据库名含有-号不能查询，提示语法错误

### ISSUE THREAD

**Issue by DemonTang** [hhyo/Archery#185]
### 问题描述
docker-compose安装的，当数据库名或表名有-号时，查询提示语法错误

### 版本信息
 - 应用版本/分支：Release v1.5.4
 - 部署方式：Docker

Error
--
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-sky' at line 1")

**Comment by LeoQuote** [comment]
该问题已修复， 参见 #164 #166 #167 ，请等待我们的下次release，届时更新版本即可
