### ISSUE TITLE
[ bug ] 1.5.0 binlog2sql 不能返回结果，文件内容为空

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#191]
### 重现步骤
![image](https://user-images.githubusercontent.com/35367394/57567553-8a961800-740d-11e9-8ab5-c36853a0314a.png)

### 期待结果和实际结果
![image](https://user-images.githubusercontent.com/35367394/57567549-61758780-740d-11e9-8b1e-11eab75ed781.png)

### 错误日志
![image](https://user-images.githubusercontent.com/35367394/57567536-39862400-740d-11e9-971c-15d7a74f6659.png)

部署方式：手工部署1.5.0

**Comment by LeoQuote** [comment]
应该是重复issue #5

**Comment by think-coding** [comment]
他的有结果，我的没有结果，不一样！

**Comment by think-coding** [comment]
![image](https://user-images.githubusercontent.com/35367394/57567718-1d37b680-7410-11e9-973d-612f5e05aab3.png)
![image](https://user-images.githubusercontent.com/35367394/57567722-29237880-7410-11e9-9c93-53b9a48253ec.png)

**Comment by think-coding** [comment]
要测试回滚功能，不能正常使用，急

**Comment by LeoQuote** [comment]
在admin界面看一下django-Q的执行有没有错误

**Comment by hhyo** [comment]
单独一个binlog2sql文件跑不起来的，按照手动文档部署binlog2sql

**Comment by think-coding** [comment]
ok了，老版本是别人弄的，只复制一个py文件就可以直接跑。
这次git完就可以用了。
