### ISSUE TITLE
[ 潜在bug ] engine中重复写工单状态问题

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#195]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

在工单执行view中，使用django-Q异步调用了 engine.excute_workflow 方法，并且指定了回调函数 https://github.com/hhyo/Archery/blob/master/sql/utils/execute_sql.py

所以理论上来说在engine中应该不涉及工单状态和日志等事务，在mysqlengine中也是这样做的

但在之后的redis引擎中，engine中有修改工单状态的相关代码，可能会造成工单状态重复保存的问题，是一个潜在的坑，建议修改
### 期待结果和实际结果
期待结果：
不适用
实际结果:
不适用
### 错误日志
目前无错误日志

### 版本信息
应用版本/分支：
master分支
部署方式：Docker、手工部署

**Comment by yzypals** [comment]
嗯  目前我的oracle.py 就放了上面说的错误，  回头好好改改

**Comment by hhyo** [comment]
engine中目前是赋值到status了，但是貌似没有用到，可以删除该赋值以及workflow的save
