### ISSUE TITLE
[ 功能建议 ] 上线工单强制要求备份

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#198]
### 目前遇到的问题/使用障碍
目前工单可以选择备份或者不备份, 但大部分公司要求sql操作必须备份, 造成审核人员需要额外查看工单是否开启备份, 这是没有必要的.

### 希望如何解决/实现它
1. 备份项的前端设置默认值, 设置为备份
2. 在系统配置中加入配置项, 禁止不备份的上线操作. 如果禁用, 在前端禁用不启用备份的选项, 在后端不允许相应工单的创建.

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
这个配置项可以加，目前只有在极少数情况会要求关闭备份

**Comment by LeoQuote** [comment]
功能已完成
