### ISSUE TITLE
[ 功能建议 ]PG 审核、执行、备份

### ISSUE THREAD

**Issue by cnwelee** [hhyo/Archery#204]
### 目前遇到的问题/使用障碍
PostgreSQL目前只支持查询，希望能增加PG的审核、执行、备份功能
### 希望如何解决/实现它
这可能是个大工程吧……
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
难度适中, 有兴趣可以参考我们的开发者指南增加相关代码 https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97

**Comment by yzypals** [comment]
这个功能我来吧   公司 要上线pg了   不写不行了

**Comment by yzypals** [comment]
这里记录1个bug ，  如果 表不是在  系统默认有的schemea中，  则无法查看 表结构信息
后台报错 
ERROR:default:PgSQL命令执行报错，语句：select
        col.column_name,
        col.data_type,
        col.character_maximum_length,
        col.numeric_precision,
        col.numeric_scale,
        col.is_nullable,
        col.column_default,
        des.description
        from
        information_schema.columns col left join pg_description des on
        col.table_name::regclass = des.objoid
        and col.ordinal_position = des.objsubid
        where table_catalog='postgresql'
        and table_schema = 'myschema'
        and table_name = 'user_tbl'
        order by ordinal_position;， 错误信息：Traceback (most recent call last):
  File "/home/yingzy/Desktop/djangodev/Archery/sql/engines/pgsql.py", line 153, in query
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "user_tbl" does not exist
报表不存在 。

**Comment by bucardo111** [comment]
持续关注中，期待支持pg上线功能

**Comment by LeoQuote** [comment]
@bucardo111 感谢关注, 可以点击上面关联的pr , 然后在新打开的页面中点击右侧的 subscribe 接收pr 的最新进展.
也欢迎在pr中直接参与我们关于实现的讨论或提交你的pr

**Comment by boldmanQ** [comment]
@yzypals 请教PG数据库sql上线是什么流程？需要用goinception嘛

**Comment by yzypals** [comment]
不需要。 直接走的engine里的各种方法

**Comment by LeoQuote** [comment]
已完成, close

**Comment by maxianwei** [comment]
@LeoQuote  你好，pgsql上线功能是不是不支持DDL，我创建数据库报错CREATE DATABASE cannot run inside a transaction block
