### ISSUE TITLE
binlog2sql 选择解析时间 或解析位置 后无法查询[ bug ]

### ISSUE THREAD

**Issue by eqieyiran** [hhyo/Archery#209]
![image](https://user-images.githubusercontent.com/30651724/57821782-61d2a180-77c4-11e9-9b37-b101a3da2eca.png)

取消时间条件后，查询正常

**Comment by eqieyiran** [comment]
通过如下命令查询日志并无报错：
docker logs archery -f --tail=50

**Comment by hhyo** [comment]
经测试，position过滤是正常的，时间过滤不可用，binlog2sql的时间过滤存在比较严重的性能问题，不建议使用，还是自行确认position再过滤比较快

**Comment by hhyo** [comment]
没记错的话，这是第二次提issues没有按规范了，下次会直接关闭
