### ISSUE TITLE
[ 用户权限 ] 

### ISSUE THREAD

**Issue by cai823294620** [hhyo/Archery#210]
我创建了一个普通用户,用户依赖与组。

组权限如下：
![image](https://user-images.githubusercontent.com/44595276/57844775-4cc93300-7803-11e9-8e3a-c4a0c0fdfc8e.png)

我使用管理员查询就没有问题。但是为什么我在使用普通用户查询时提示`你无apolloconfigdbdev数据库的查询权限！请先到查询权限管理进行申请`。但问题是我已经授予所有权限了呀。

**Comment by LeoQuote** [comment]
请按模板提交, 提供模板中需要的信息. 请修改issue内容或重新按规范提交.

**Comment by cai823294620** [comment]
已解决，谢谢
