### ISSUE TITLE
[ 功能建议 ] 新增一个info/debug 页面, 显示目前archery的系统版本等信息

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#216]
### 目前遇到的问题/使用障碍
当平台出现问题的时候, 有一些情况下是一些组件失去连接, 而管理员还需要去服务器上执行相关命令才能知道情况, 可能会有一些延迟

如果新增一个info页面, 管理员可以很快知道哪里出了问题, 如果要在issue上讨论也很方便的可以复制粘贴.

### 希望如何解决/实现它
1. 提供一个info或者debug接口, 输出info或debug信息, 包括以下内容:
    *  目前代码版本
    *  inception 和备份库连接状态
    *  qcluster 状态
    *  近期job 的数量, 成功/失败 数量
    *  redis 连接状态
2. (可以后期做) 如果是管理员用户, 在 todo 方法里加上检查的函数, 在todo处警告管理员
3. (可以后期做) 提供一个和监控工具比如 prometheus 兼容的监控接口
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by AceAttorney** [comment]
django跑定时任务？
然后弄个页面展示出来。

**Comment by LeoQuote** [comment]
不用，我们用的qcluster有相关的接口，写成动态页面就行，就是近期没时间做。

**Comment by hhyo** [comment]
其实不做界面直接出个接口也行，然后在设置或者什么地方保留一个获取接口信息的按钮
