### ISSUE TITLE
[ 问题咨询 ]oracle功能查询提示ERROR: 查询时间超过 60 秒，已被主动终止

### ISSUE THREAD

**Issue by rhkjyn** [hhyo/Archery#218]
### 问题描述
oracle11g RAC环境，己授于sys.dba_users dba_tab_privs    dba_objects权限，并能成功列出secame和表结构，但select表数据的时候，提示"ERROR:  查询时间超过 60 秒，已被主动终止，请优化语句或者联系管理员。"

### 版本信息
 - 应用版本/分支：Release v1.6
 - 部署方式：Docker

**Comment by rhkjyn** [comment]
执行计划功能不可用，提示『仅支持^select语法!』

**Comment by hhyo** [comment]
贴一下qcluster.log，一般是qcluster启动失败了，可以重启一下archery

执行计划暂时不支持，按钮没有禁用

**Comment by rhkjyn** [comment]
重启解决
