### ISSUE TITLE
[ 问题咨询 ] 升级时遇到 django_content_type 内容变化，这个表数据如何处理？

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#219]
### 问题描述
老版本
![image](https://user-images.githubusercontent.com/35367394/58302263-c3c28500-7e1c-11e9-8a50-5f260998aa88.png)

新版本
![image](https://user-images.githubusercontent.com/35367394/58302272-cb822980-7e1c-11e9-9b3c-bf5d054dd0ce.png)

### 版本信息
 - 应用版本/分支：Release v1.5.3 手工部署(从1.2.0-->1.3.8--1.5.3升级)

**Comment by hhyo** [comment]
升级就按照升级脚本依次执行，不会有任何问题

拿两个独立部署的不同版本对比model没有任何意义

**Comment by hhyo** [comment]
升级说明中还有个附加说明，就是处理新增app的场景

**Comment by think-coding** [comment]
我要把之前的数据迁移到新数据库的表里面，这个 django_content_type 有没有跟别的表数据有关联，如果有，需要更新哪些表。
我是问这个，请明确回答一下。

**Comment by hhyo** [comment]
这个需要去看django的内置模块，没法给你更多帮助。

**Comment by think-coding** [comment]
额。。这个表是做什么功能的？

**Comment by think-coding** [comment]
好像不动这个表也没啥问题～～

**Comment by hhyo** [comment]
目前已知会和权限相关，应该只要权限和这边关联的上就可以
