### ISSUE TITLE
[ 问题咨询 ]慢日志不显示，报错

### ISSUE THREAD

**Issue by kcxg** [hhyo/Archery#232]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
1.慢日志信息发送到数据库，在平台查不到
![image](https://user-images.githubusercontent.com/31840413/58477994-89901500-8187-11e9-9ad6-57b41dda0094.png)
2.
![image](https://user-images.githubusercontent.com/31840413/58478065-b47a6900-8187-11e9-83cd-255ae0d90cf7.png)
3.日志报错
![image](https://user-images.githubusercontent.com/31840413/58478127-d70c8200-8187-11e9-8afa-f3af9e1fe047.png)

### 版本信息
 - 应用版本/分支：Release v1.5.3  
 - 部署方式：Docker

**Comment by hhyo** [comment]
什么浏览器览器访问的，确认下请求入参
![image](https://user-images.githubusercontent.com/8842982/58479205-5a2ed780-818a-11e9-823e-42dbfb7c9796.png)

**Comment by kcxg** [comment]
![image](https://user-images.githubusercontent.com/31840413/58479526-083a8180-818b-11e9-927e-42930d58a44b.png)
chrome 浏览器

**Comment by hhyo** [comment]
没毛病啊，接口返回看起来也是200
检查下这个吧：https://github.com/hhyo/archery/wiki/FAQ#慢日志不显示

**Comment by kcxg** [comment]
ok啦，O(∩_∩)O谢谢。
