### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by kcxg** [hhyo/Archery#233]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
1、实例添加成功
![image](https://user-images.githubusercontent.com/31840413/58481726-9153b780-818f-11e9-9585-4ac9bce04815.png)
2、sql查询时，没有实例可以选择
![image](https://user-images.githubusercontent.com/31840413/58481844-cb24be00-818f-11e9-8305-8c387ac09308.png)

### 版本信息
 - 应用版本/分支：Release v1.5.3  
 - 部署方式：Docker

**Comment by hhyo** [comment]
文档有的内容不再回复
