### ISSUE TITLE
[ 问题咨询 ] SQL查询不显示实例

### ISSUE THREAD

**Issue by kcxg** [hhyo/Archery#234]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
没有加tag的地方啊
![image](https://user-images.githubusercontent.com/31840413/58482803-ad585880-8191-11e9-812d-dcc6b3c71d5d.png)
![image](https://user-images.githubusercontent.com/31840413/58483117-47b89c00-8192-11e9-9094-f6bb55260230.png)

### 版本信息
 - 应用版本/分支：Release v1.5.3 
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
实例标签这个功能在1.5.3 上还没有，可以尝试升级archery版本再体验标签功能

**Comment by hhyo** [comment]
抱歉没有注意版本的区别，补文档...
1.6.0以前只有从库可以查询，主库可以上线

**Comment by kcxg** [comment]
ok.thanks
