### ISSUE TITLE
提交的Sql，审核通过之后工单状态一直是执行中

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#242]
### 问题描述
提交工单，审核通过之后，点击执行按钮之后，工单的状态一直是执行中，等了一天还是这个状态，如下图所示：
![image](https://user-images.githubusercontent.com/40845632/58679207-1825b180-8395-11e9-9953-1aa8c50fa9dd.png)
![image](https://user-images.githubusercontent.com/40845632/58679229-2c69ae80-8395-11e9-984e-3059f3b506a8.png)
![image](https://user-images.githubusercontent.com/40845632/58679245-368bad00-8395-11e9-8ae3-f8e3f1801010.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by cnlong** [comment]
部署模式是Docker 部署的

**Comment by LeoQuote** [comment]
不好意思，这是我们程序的一个小bug，预计我们周末会发一个修复版，请届时更新，如果等不及可以自己修复，在settings.py 中的 177行下加入两行代码即可

    import ldap
    from django_auth_ldap.config import LDAPSearch

**Comment by cnlong** [comment]
![image](https://user-images.githubusercontent.com/40845632/58680713-92593480-839b-11e9-90ec-ea1429dbd3b4.png)
我自己手动启动了这个服务，发现邮件也推送了，sql也执行了，是docker 部署的时候，这个服务不能自启动吗？

**Comment by LeoQuote** [comment]
这个qcluster不启动的问题预计在下个版本会解决，发布时间大概是本周末

**Comment by cnlong** [comment]
好的，感谢哦，辛苦了大佬
