### ISSUE TITLE
[ bug ] 新建账户时密码不符合复杂度，提示报错依然能创建成功

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#243]
新建账户时密码不符合复杂度，提示报错依然能创建成功
![image](https://user-images.githubusercontent.com/26135288/58684206-f97de580-83a9-11e9-9670-c104a07cee64.png)
![image](https://user-images.githubusercontent.com/26135288/58684213-039fe400-83aa-11e9-8ac7-6c4e483c0fb1.png)

 - 应用版本/分支：Release v1.6.0
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
已确认bug https://github.com/hhyo/Archery/blob/318a040acaffd39ed3aca0b85f2271d20dac2570/common/auth.py#L144

**Comment by LeoQuote** [comment]
非常欢迎直接提pr，只要把上面代码中的下面初始化用户相关代码放进try即可。

如果有能力建议将这个bug作为测试用例放进测试脚本。

**Comment by a5546868001** [comment]
还在学习阶段

**Comment by liyingxiao94** [comment]
这个功能我也遇到过，参照原有作者的代码修改下就能解决
