### ISSUE TITLE
【慢查日志】慢日志统计慢sql不显示，[ 问题咨询 ]

### ISSUE THREAD

**Issue by fancy-lee** [hhyo/Archery#244]
### 问题描述
慢日志：（阿里云rds)慢日志统计tab中没有数据，点慢日志明细tab却有数据

### 版本信息
 - 应用版本/分支：Release v1.5.2
 - 部署方式：Docker

**Comment by hhyo** [comment]
可以对比RDS管理后台中的数据，配置了RDS实例信息的慢日志数据完全来源于RDS的SDK
