### ISSUE TITLE
Deabin9 docker-compose安装报如下错误[ 问题咨询 ]

### ISSUE THREAD

**Issue by singer929** [hhyo/Archery#245]
Creating mongo ... 
Creating redis ... 
Creating archery ... 
Creating inception   ... error
Creating inception ... 
Creating redis       ... done

ERROR: for inception  Cannot start service inception: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/inception/inc.cnf\\\" to rootfs 
Creating mysql       ... error: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Creating archery     ... error
ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/mysql/my.cnf\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/cf3d89497ab14e82d4011b33aa072f6d1041c5afbb371677ede8e5de1d71bb9f/merged\\\" at \\\"/usr/local/dockerfile/overlay2/cf3d89497ab14e82d4011b33aa072f6d1041c5afbb371677ede8e5de1d71bb9f/merged/etc/mysql/mysql.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for archery  Cannot start service archery: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/archery/settings.py\\\" to rootfs \\
Creating mongo       ... done
Creating goinception ... error

ERROR: for goinception  Cannot start service goinception: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/inception/config.toml\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/c37d489620d719bf859881061bb6fc3d4a9b287243353040fed9141e3a7f0ee4/merged\\\" at \\\"/usr/local/dockerfile/overlay2/c37d489620d719bf859881061bb6fc3d4a9b287243353040fed9141e3a7f0ee4/merged/etc/config.toml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for inception  Cannot start service inception: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/inception/inc.cnf\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/b4f76ced3b0475a62c687a0f6fae1ff7fb2dbbd5ffeb0512d4f05aa6d6c2e2b2/merged\\\" at \\\"/usr/local/dockerfile/overlay2/b4f76ced3b0475a62c687a0f6fae1ff7fb2dbbd5ffeb0512d4f05aa6d6c2e2b2/merged/etc/inc.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/mysql/my.cnf\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/cf3d89497ab14e82d4011b33aa072f6d1041c5afbb371677ede8e5de1d71bb9f/merged\\\" at \\\"/usr/local/dockerfile/overlay2/cf3d89497ab14e82d4011b33aa072f6d1041c5afbb371677ede8e5de1d71bb9f/merged/etc/mysql/mysql.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for archery  Cannot start service archery: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/archery/settings.py\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/103dd19adec0c95f828d82000f35eb0b532b4776a09224945e62e29849629aca/merged\\\" at \\\"/usr/local/dockerfile/overlay2/103dd19adec0c95f828d82000f35eb0b532b4776a09224945e62e29849629aca/merged/opt/archery/archery/settings.py\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for goinception  Cannot start service goinception: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/local/archery/inception/config.toml\\\" to rootfs \\\"/usr/local/dockerfile/overlay2/c37d489620d719bf859881061bb6fc3d4a9b287243353040fed9141e3a7f0ee4/merged\\\" at \\\"/usr/local/dockerfile/overlay2/c37d489620d719bf859881061bb6fc3d4a9b287243353040fed9141e3a7f0ee4/merged/etc/config.toml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by LeoQuote** [comment]
我这里无法复现，请检查你的docker安装，并且自行搜索一下相关错误。

**Comment by hhyo** [comment]
文档有说明
需要下载整个docker-compose文件夹，进入文件夹内执行启动
日志的报错都是找不到相应的配置文件，导致将文件映射成了目录
