### ISSUE TITLE
执行SQL，主键冲突，archer无报错

### ISSUE THREAD

**Issue by xcg** [hhyo/Archery#247]
### 重现步骤
1.建表
CREATE TABLE `pay_rule` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `rule_no` varchar(50) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '111',
  `add_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `mark` tinyint(1) NOT NULL DEFAULT '0' COMMENT '标识(是否有效 0有效；-1无效)',
  PRIMARY KEY (`id`),
  KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='1111'

2.初始化数据
INSERT INTO pay_rule` (`id`, `rule_no`, `add_time`, `update_time`, `mark`) VALUES 
(1, '20190601', '2019-06-03 15:20:28', '2019-06-03 15:20:28', 0);

3.开始测试，利用archery提交如下sql
update pss_pay_rule set mark =-1 ; 
INSERT INTO `pay_rule` (`id`, `rule_no`, `add_time`, `update_time`, `mark`) VALUES 
(1, '20190601', '2019-06-03 15:20:28', '2019-06-03 15:20:28', 0);

4.点击执行后，改单无法访问，报错：
    if isinstance(loaded_rows[-1], list):
IndexError: list index out of range

数据库，执行结果json格式值为: [] ；将该值设置为空值后，可访问，但数据未执行成功

问题排查：
主键冲突，未捕获异常

### 版本信息
应用版本/分支：
Archery-1.6.1

部署方式：Docker、手工部署
手工部署

**Comment by hhyo** [comment]
无法复现，具体见http://139.199.0.191/detail/398/
