### ISSUE TITLE
[ 问题咨询 ]配置goinception审核，检测查询插入sql，报inception错误

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#248]
### 问题描述
·goinception·审核，检测·查询插入·sql，报了一个·inception·错误。·非查询插入·语句能正常检测。
![image](https://user-images.githubusercontent.com/33362111/58789166-14598f80-8620-11e9-992f-8290e5c78627.png)

![image](https://user-images.githubusercontent.com/33362111/58789063-d3617b00-861f-11e9-9b8b-95f1aececcb8.png)

查询goinception文档，写着是支持·查询插入·的，如下图
![image](https://user-images.githubusercontent.com/33362111/58789014-b2008f00-861f-11e9-8dc9-7bf3a6c2b355.png)

### 版本信息
 - 应用版本/分支：Release v1.6.0 
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
可以贴一下goInception的日志，看起来是检测时崩了，可以升级下最新版的goInception
查看日志：`docker logs goInception -f `

**Comment by lijie861221** [comment]
升级到最新的archery和goincepiton后解决了。
