### ISSUE TITLE
[ 功能建议 ]增加gbase 8a数据库的支持

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#249]
### 目前遇到的问题/使用障碍
原先用utf8字符集的时候，数据库配置为mysql类型能访问gbase 8a数据库，更新archery后字符集为utf8mb4就无法访问gbase 8a了。

### 希望如何解决/实现它
增加gbase 8a数据库的支持或者每个数据库实例能自定义配置字符集。

**Comment by LeoQuote** [comment]
老实讲这个功能点确实有必要 @hhyo 似乎是加一个字段就可以的，就是默认值有些难控制。因为 sql server oracle 可能就没有 utf8mb4 这种编码方式了

**Comment by hhyo** [comment]
可以加个字段，默认空，空则采取现阶段的字符集，否则指定设置的字符集
