### ISSUE TITLE
[ 问题咨询 ]工单提交的邮件内容显示不全

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#254]
### 问题描述
提交工单审核，发生审核邮件的时候，包含的数据库脚本显示不全
![image](https://user-images.githubusercontent.com/40845632/59003694-924caf00-8849-11e9-86f3-e7c19266f6b7.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by hhyo** [comment]
消息只是预览，仅显示前500字符
