### ISSUE TITLE
[ 问题咨询 ]备份数据

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#256]
### 问题描述
请问一下，系统配置里面的“备份选项”，是怎么的机制去备份呢？
![image](https://user-images.githubusercontent.com/40845632/59004802-911d8100-884d-11e9-859a-0a1bf6899bb4.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
这个文案我也是纠结了很久，实际上是一个表示备份选项是否显示的开关。
如果打开这个选项，用户就可以选择备份还是不备份，如果不打开（默认状态）用户就不能选择备份还是不备份，只能备份。

如果有更好的文案建议欢迎提出。
