### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by houdaiye** [hhyo/Archery#258]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
{status: 1,…}
data: {}
msg: "Inception检测语句报错，请注意检查系统配置中Inception配置，错误信息：↵connect() argument 1 must be str, not None"
status: 1
### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

 

我使用的是kubernetes部署archery但是得到了这个错误，怀疑是archery连接inception出了问题

**Comment by LeoQuote** [comment]
我从你的报错信息看，似乎是没有在配置中填写inception的相关信息，请确认有没有填写inception信息。

**Comment by houdaiye** [comment]
我在archery的setting.py的配置中，没有发现inception相关的配置

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

**Comment by houdaiye** [comment]
多谢您了，已经配置上inception，并测试没有问题
