### ISSUE TITLE
开启osc执行特别别慢[ 问题咨询 ]

### ISSUE THREAD

**Issue by fancy-lee** [hhyo/Archery#269]
### 问题描述
阿里rds-mysql对一张400W的1.15G的表修改，开启osc执行超过12小时才复制了4w行，没有开启goinception,      inception所有参数都没有调，请问为什么会这么慢？

### 版本信息
 - 应用版本/分支：Release v1.5.2
 - 部署方式：Docker

**Comment by hhyo** [comment]
补充一下issue标题，具体可以看inception文档关于pt-osc的部分，同时可以看pt-osc的官方文档，调整相关参数

**Comment by fancy-lee** [comment]
感觉应该不是osc功能的问题，应该是平台处理慢，我关闭了osc功能还是很慢

**Comment by hhyo** [comment]
> 感觉应该不是osc功能的问题，应该是平台处理慢，我关闭了osc功能还是很慢

既然有猜测，就可以直接验证下这个结论

对同一个表，分别执行如下操作

- 通过平台DDL
- 直接操作MySQL DDL

记录两个耗时，贴上来

**Comment by fancy-lee** [comment]
通过用python2.7手写脚本执行对自建的inception进行测试：自建的数据库上执行没有问题能够正常执行结束，在rds上同表同数据量的情况却执行不完。这应该可以肯定osc慢和平台无关，是inception对rds支持的不够好导致大表osc执行慢，看到goinception集成的ghost中有ghost_aliyun_rds这个参数，不知道能否解决osc慢的问题？

**Comment by hhyo** [comment]
不通过inception，直接使用pt工具呢

**Comment by fancy-lee** [comment]
> 不通过inception，直接使用pt工具呢

直接用pt是没有问题的,刚才用了goinception开启了ghost和ghost_aliyun_rds还是很慢
![image](https://user-images.githubusercontent.com/23489502/59753638-293c5100-92b7-11e9-8bd8-711ec5ac73d8.png)

**Comment by hhyo** [comment]
![image](https://user-images.githubusercontent.com/8842982/59754866-8afdba80-92b9-11e9-9fec-06ad5fb42900.png)

直接挂起状态了，参考https://github.com/github/gh-ost/blob/master/doc/throttle.md#status-thresholds

多研究下pt和gh-ost的参数，按需调整测试下

**Comment by fancy-lee** [comment]
调大这两个参数完美解决：
inception_osc_max_thread_connected 
inception_osc_critical_thread_connected
