### ISSUE TITLE
[ 功能建议 ]动态增加查询TAB页面，查询和优化合并

### ISSUE THREAD

**Issue by fancy-lee** [hhyo/Archery#270]
### 目前遇到的问题/使用障碍
1.SQL查询只有一个TAB页面，不够用，跳转刷新查询语句在编辑里就没有了
2.sql查询和优化查询放到一个页面，很多时候在查询的时候就想看一下优化建议，同时真执行后能看到结果和执行计划
### 希望如何解决/实现它
1.增加查询tab页面
2.查询的同时也可以看到优化建议、执行计划和结果
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
补充下issue标题

- 可以通过增加多个结果页处理
- 查询和优化的前端代码已经很复杂，不考虑合并

这两个需求确实存在合理的地方，但是目前没有计划调整，希望有专业的前端参与进来，欢迎提交PR

issue不关，可以挂在这里

**Comment by hhyo** [comment]
已可以增加多个tab页
