### ISSUE TITLE
[ bug ] travis-ci 没有通过

### ISSUE THREAD

**Issue by AceAttorney** [hhyo/Archery#271]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

提交了一下pr 发现travis-ci 没过

应该是缺少 sql.h 的库文件

### 截图
![image](https://user-images.githubusercontent.com/13723456/59421857-e7686200-8e01-11e9-8546-b161db0503a7.png)

 
### 错误日志
https://travis-ci.org/hhyo/Archery/jobs/545152933

#### centos 
sudo yum install unixODBC-devel

#### ubuntu
sudo apt-get install unixodbc unixodbc-dev

**Comment by hhyo** [comment]
感谢贡献，对比以前的构建记录确认是travis升级了基础镜像导致

可参考链接修改ci配置试试，在 [.travis.yml](https://github.com/hhyo/Archery/blob/master/.travis.yml#L7)  install前添加

```
before_install: 
    - sudo apt-get install unixodbc unixodbc-dev
```
https://docs.travis-ci.com/user/installing-dependencies/#adding-apt-sources

**Comment by LeoQuote** [comment]
关联 pr #263

**Comment by LeoQuote** [comment]
已解决
