### ISSUE TITLE
[ 问题咨询 ] 认证问题

### ISSUE THREAD

**Issue by yzypals** [hhyo/Archery#275]
### 目前遇到的问题/使用障碍
自己写了个api 企业微信做审核通过的，不用登录，登上测试的时候发现 会跳转到登录页面
### 希望如何解决/实现它
我们的工程是不是 哪里写了个页面登录的中开关，我需要了解下 。做api的时候 不可能还要先登录的啊
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
在middleware层，你debug就可以发现的
