### ISSUE TITLE
OpenSearch 查询结果错位

### ISSUE THREAD

**Issue by Maxcj** [hhyo/Archery#2806]
### 重现步骤

使用opensearch进行查询时， 返回的结果是数组形式，对于某些 doc 不存在某列时，会出现结果显示错位的问题

### 预期外的结果

![企业微信截图_17261525832946](https://github.com/user-attachments/assets/8968ac5e-a82c-4f1e-ac6e-e2c2d97bcdae)

### 版本

1.11.3

### 部署方式

Docker

**Comment by feiazifeiazi** [comment]
@Maxcj 我大概理解你的意思，我试一下。下次给些插入示例数据脚本就更好了。

**Comment by feiazifeiazi** [comment]
用SQL语句查询，好像是正常，帮试一下。 @Maxcj
