### ISSUE TITLE
[ 功能建议 ]审核&执行SQL的权限能否进一步细化

### ISSUE THREAD

**Issue by lanjian106103** [hhyo/Archery#281]
### 目前遇到的问题/使用障碍
目前只要有sql_review和sql_execute_for_resource_group权限，就能审核和执行所在资源组的所有SQL上线工单，能否将权限进一步细化，

### 希望如何解决/实现它
可以按照资源组的实例分配权限，比如资源组有10个实例，用户A仅能审核1-5实例，用户B仅能审核6-10实例

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
建议你分离成为两个资源组，即可解决这个问题。

**Comment by lanjian106103** [comment]
这10个实例也可能分别由不同的10个用户审核，分成10个资源组的话，维护起来还是有些繁琐的……

**Comment by LeoQuote** [comment]
我理解你这个需求就是管理起来很困难的需求，如果需要对应到个人和单个实例的权限，就会出来一个 n*m 的矩阵对应关系，如果再加上资源组，管理起来就更加混乱了，还要考虑到人员离职的问题，建议粗放一点的管理，以组为基础管理更加简单明了。

**Comment by LeoQuote** [comment]
我觉得你说的细粒度, 精确到单个实例的权限管理确实也可以考虑, 给系统管理员更多选择.

但是这个工程量应该还是比较大, 要多一种关联关系, 而且目前UI 上不太好做兼容, 我暂时把这个放在长期规划中, 同时也欢迎提出更详细的设计方案, 不管是底层数据库, 代码逻辑 还是 UI 层面的方案.

**Comment by hhyo** [comment]
实例和数据库级别的归属人需求确实存在，没有想到好的处理方法


审核细化到实例的话，用户和实例肯定要建立关联关系，直接越过资源组，资源组存在的意义就不大了

资源组的定义很明确，目前就是用来隔离实例的审核和访问权限的，审批流程也是关联资源组


如果采取讨巧的方法，直接新建一个用户和可审核实例的关联关系，在目前的各个操作节点增加实例关联判断，也可以实现


需求的想法可能比较纯粹，关注审核人这一块隔离，采取统一的资源池，提交人可随意提交，审核这一关卡住就好了，但是感觉这是不太合理的

其实既然实例有不同的审核人，肯定是存在隔离关系的，审核人要隔离，提交人必定也要隔离，即使实例可以直接关联审核人，还是建议去维护资源组，不只是上线，还有其他功能的可访问都靠资源组隔离
