### ISSUE TITLE
[ 功能建议 ] 加入mongodb查询模块

### ISSUE THREAD

**Issue by duge123** [hhyo/Archery#282]
目前环境mongodb的应用还是很普及的，运用也非常多，希望可以在sql查询模块中 加入mongodb的查询支持。谢谢。

**Comment by LeoQuote** [comment]
感谢你的建议，这是我们的开发者指南 https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97 ，接入新数据库类型是比较简单的，只需要按文档做出对应的调整即可。
如果有兴趣可以直接对照修改提出pull request， 只要单元测试全过，覆盖率达标，没有大的逻辑问题就会接受。

**Comment by jackielulu17325** [comment]
按照开发者文档加入了mongo模块,用2周前的老版本可以使用. 这两天更新了新版本后,sql查询--在线查询不显示mongo数据库,是什么情况?

**Comment by jackielulu17325** [comment]
新版本中 /opt/archery/sql/templates/sqlquery.html 中的
 {% for instance in instances %}
                                            {% if instance.db_type == 'mongo' %}
                                                <option value="{{ instance.instance_name }}">{{ instance.instance_name }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </optgroup>
没地方加了.

**Comment by hhyo** [comment]
> 新版本中 /opt/archery/sql/templates/sqlquery.html 中的
> {% for instance in instances %}
> {% if instance.db_type == 'mongo' %}
> {{ instance.instance_name }}
> {% endif %}
> {% endfor %}
> 
> 没地方加了.

 [sqlquery.html#L27](https://github.com/hhyo/Archery/blob/master/sql/templates/sqlquery.html#L27)追加 
```
<optgroup id="optgroup-mongodb" label="MongoDB"></optgroup>
```

 [sqlquery.html#L871](https://github.com/hhyo/Archery/blob/master/sql/templates/sqlquery.html#L871)追加

```
$("#optgroup-mongodb").empty();
```
[sqlquery.html#L884](https://github.com/hhyo/Archery/blob/master/sql/templates/sqlquery.html#L884)追加
```
else if (result[i]['db_type'] === 'mongodb') {
                                $("#optgroup-mongodb").append(instance);
                            }
```

**Comment by jackielulu17325** [comment]
感谢,已解决.

**Comment by LeoQuote** [comment]
@jackielulu17325 方便的话提个pr吧

**Comment by jackielulu17325** [comment]
@LeoQuote 刚实现了在线查询功能,还没怎么测试,代码写的不好,等过两天测测再给提交上来吧..

**Comment by LeoQuote** [comment]
@jackielulu17325 好的，期待

**Comment by LeoQuote** [comment]
已合并至master , 请等待下次 release 更新后即可使用.
