### ISSUE TITLE
走过路过的不要错过, ~~给我们的改进功能投个票吧

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#286]
不知不觉, 在issue 列表里已经积压了很多未完成的功能点了, 欢迎大家在其中给你喜欢, 或者想要的功能点个赞.

这样有利于了解大家的迫切需求, 我们也会在issue中合理选择点赞数比较高的功能点去实现. 现在就点起来把!

PS: 在对应 issue 1楼的右上角有一个  "+🙂"  点击即可给issue点赞.

**Comment by hhyo** [comment]
开源项目一般不缺建议缺贡献，个人精力时间有限，希望社区可以多多贡献，无论是文档还是其他方面
