### ISSUE TITLE
[ 问题咨询 ]审核人查看不了工单

### ISSUE THREAD

**Issue by xingshao-ye** [hhyo/Archery#287]
### 问题描述
问题：审核人收到钉钉消息提醒，但登录archery却查看不了需要审核的工单，
![image](https://user-images.githubusercontent.com/16486392/59817175-7240e380-9351-11e9-9a67-a8bf5145c2f7.png)

![image](https://user-images.githubusercontent.com/16486392/59817202-9ac8dd80-9351-11e9-8024-a394d30ca359.png)
![image](https://user-images.githubusercontent.com/16486392/59817210-a7e5cc80-9351-11e9-898f-eeddd3651cf1.png)
![image](https://user-images.githubusercontent.com/16486392/59817219-b2a06180-9351-11e9-8ff4-99c6702e472f.png)
![image](https://user-images.githubusercontent.com/16486392/59817243-c51a9b00-9351-11e9-97ed-ccab1c20ca5c.png)

### 版本信息
 - 应用版本/分支：Release v1.6.1
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
这个用户在你所给定的组中吗?

**Comment by hhyo** [comment]
#84
