### ISSUE TITLE
[ 问题咨询 ] redis 缓存模块的配置 有支持 redis 密码么？

### ISSUE THREAD

**Issue by earl86** [hhyo/Archery#289]
### 问题描述
 redis 缓存模块的配置 有支持 redis 密码么？
# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "xxxxxxx", 这里有支持么？
        }
    }
}

### 版本信息
 - 应用版本/分支：Release v1.4.3  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
支持，详见django_redis 文档 http://django-redis-chs.readthedocs.io/zh_CN/latest/
