### ISSUE TITLE
[ 问题咨询 ]执行SQL column comment 中文注释乱码

### ISSUE THREAD

**Issue by frank0826** [hhyo/Archery#290]
SQL 上线Tables 相关column  comment  中文注释信息，乱码
Inception  Version： inception-2.1.52.2
mysql Version: 5.7
Archery Version:  1.6.2
部署方式: 手工部署
乱码信息如下:
![image](https://user-images.githubusercontent.com/11606105/59907882-b362f180-943e-11e9-99c7-45232871143c.png)

**Comment by LeoQuote** [comment]
模版里写了要提供版本，你的版本呢？

最新版本里mysql默认是utf8mb4编码、如果编码和默认编码不同请在后台实例配置中修改charset 信息为正确的编码。

**Comment by frank0826** [comment]
1、调整后台实例默认字符集为:utf8

2、调整文件sql/engines/inception.py   
  def execute(self, workflow=None):
          """执行上线单"""
        instance = workflow.instance
         execute_result = ReviewSet(full_sql=workflow.sqlworkflowcontent.sql_content)
          if workflow.is_backup:
              str_backup = "--enable-remote-backup"
         else:
              str_backup = "--disable-remote-backup"
          # 根据inception的要求，执行之前最好先split一下
         sql_split = f"""/*--user={instance.user};--password={instance.raw_password};--host={instance.host}; 
                       --port={instance.port};--enable-ignore-warnings;--enable-split;*/
                          inception_magic_start;
                          use `{workflow.db_name}`;
                                **set names {instance.charset}**
                          {workflow.sqlworkflowcontent.sql_content}
                          inception_magic_commit;"""
         split_result = self.query(sql=sql_split)

Tables  column comment 中文注释显示正常。
3、如图:
 
![image](https://user-images.githubusercontent.com/11606105/59960923-811ac800-9502-11e9-961f-2a9603ef85b9.png)

**Comment by LeoQuote** [comment]
感谢提供的方法，这个关于inception.py 的修改可以顺手提个pr吗？确实是有必要的修改

**Comment by hhyo** [comment]
增加set names后反而出现乱码，不确定是哪里的问题，先回滚
![image](https://user-images.githubusercontent.com/8842982/60750841-d665d780-9fe0-11e9-86c0-fb6066c0a5fb.png)
