### ISSUE TITLE
[ bug ]用户注册时如默认资源组已分配用户，则新用户登录失败

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#291]
### 重现步骤

1.新建资源组，并创建用户赋权给当前资源组
2.设置新建资源组为默认资源组
3.创建新用户
4.登陆新用户是，提示[ERROR]- Internal Server Error: /authenticate/。唯一索引冲突

### 期待结果和实际结果
期待结果：

实际结果:

### 截图

![image](https://user-images.githubusercontent.com/26135288/60001989-58c5d180-969a-11e9-958b-fa562965e9d6.png)

### 错误日志

/downloads/log/archery.log
docker logs archery -f --tail=10

### 版本信息
应用版本/分支：

部署方式：Docker

一般建议使用release版本，其他都是非稳定版本
 - 应用版本/分支：Release v1.6.3
 - 部署方式：Docker

**Comment by hhyo** [comment]
感谢反馈 
可参考[update-or-create](https://docs.djangoproject.com/zh-hans/2.1/ref/models/querysets/#update-or-create)的文档，修改[auth.py](https://github.com/hhyo/Archery/blob/master/common/auth.py#L37) 后给我们提交pr

**Comment by a5546868001** [comment]
改好了，还不会提交pr

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/f27451544b5a93f7f2c45627e1490f44d64b27c3/common/auth.py#L152

把这一行的init去掉，重复init了

一会回去我来做。

**Comment by hhyo** [comment]
注册后不能登录？
这个问题反馈的应该是后台添加用户时就已经关联了资源组，但是用户没有登录过，所以登录时间为空，登录时重复初始化就会报错

**Comment by hhyo** [comment]
@a5546868001 pr的话网上有挺多教程的，可以参考下
