### ISSUE TITLE
sql/tests.py 中的部分单元测试未执行

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#294]
https://codecov.io/gh/hhyo/Archery/src/master/sql/tests.py#L1989 根据codecoverage 的报告, 这部分的单元测试似乎没有实际执行, 不知道发生了什么.

而且这个部分测试我在本机测试时运行的极其慢, 这个测试 class 可能需要将近两分钟才能跑完, 得有空看一下

**Comment by LeoQuote** [comment]
还有构建过程中也有一些报错, 但并未造成单元测试不通过 https://travis-ci.org/hhyo/Archery/builds/549827479#L1356

**Comment by hhyo** [comment]
没执行确实有点诡异，执行慢是因为部分Class继承了TransactionTestCase，报错是因为case就是测试的exception的场景

**Comment by LeoQuote** [comment]
我估计是测试名冲突，得看看class里也没有同名方法

**Comment by hhyo** [comment]
是重复了，还不少
