### ISSUE TITLE
[ bug ] 按GO划分sql语句批量执行的功能好像失效了

### ISSUE THREAD

**Issue by AceAttorney** [hhyo/Archery#296]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

升级1.6.3之后，不能按go划分了。是前端修改了数据提交的方式了么？

### 期待结果和实际结果
期待结果：

这是升级前的

![image](https://user-images.githubusercontent.com/13723456/60076900-4f506e00-975b-11e9-82d2-5790e44bcfc3.png)

实际结果:

这是升级后的，同一个sql重新提交了一下
![image](https://user-images.githubusercontent.com/13723456/60076941-68f1b580-975b-11e9-9137-f4fedf91649a.png)

### 错误日志
日志应该没有报错，就是分割的功能有问题了。

### 版本信息
应用版本/分支：
1.6.3

部署方式：手工部署

**Comment by hhyo** [comment]
可以debug一下，同时可以查看版本变更内容，看起来没有涉及相关类容的调整
