### ISSUE TITLE
[ 问题咨询 ] 请问新用户如何申请其他资源组权限

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#297]
### 问题描述
请问新用户如何申请其他资源组权限，目前在权限申请里面只能看到自己当前的资源组，哪个权限可以看到所有的资源组并进行申请

### 版本信息
 - 应用版本/分支：Release v1.6.3  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
目前无法申请加入资源组, 只能由管理员将用户加入资源组.

**Comment by a5546868001** [comment]
那新注册用户就没办法申请别的资源组了，这个有可能增加功能么，可以自由选择所有资源组资源

**Comment by hhyo** [comment]
目前不会开放所有资源组选择，必须要人工关联
