### ISSUE TITLE
[ bug ]truncate table a; 这种语句，为什么检测出来，既不是DDL，也不是DML？

### ISSUE THREAD

**Issue by xcg** [hhyo/Archery#299]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
create table a(id int);
truncate table a;

### 期待结果和实际结果
期待结果：
1或者2
实际结果:
0

**Comment by LeoQuote** [comment]
语句类型检测依赖的是 sqlparse，inception 和goinception，目前平台对类型没有做相关的区别处理，也没有自己实现的类型判断，所以如果你想知道答案，建议你去以上三个项目中提出issue或者查看文档。

由于和本项目相关性不高本issue将关闭。

**Comment by hhyo** [comment]
演示环境无法重现:http://139.199.0.191/detail/469/

1.6.3新增了自己实现的类型判断，truncate会解析成DDL，1.6.3以前依靠sqlparse解析，具体可以自行验证

同样提问题不提供版本的一律直接关闭
