### ISSUE TITLE
[ 需求 ]支持直接审核MyBatis的XML文件

### ISSUE THREAD

**Issue by hhyo** [hhyo/Archery#3]
- 第一阶段
在SQL上线DDL语句时支持提交MyBatis的XML文件，自动解析成SQL语句，和DDL语句一起在工单详情展示，供DBA人肉审核
- 第二阶段
按照审核规则（可依靠soar）自动审核XML解析的语句，给出修改建议，分值低的语句自动驳回。

**Comment by kai23333** [comment]
请问一下,支持直接审核MyBatis的XML文件,这个功能现在有了吗

**Comment by hhyo** [comment]
@kai23333 目前还没有

**Comment by hhyo** [comment]
可参考
![image](https://user-images.githubusercontent.com/8842982/49136969-259aaa00-f326-11e8-9928-b87e8d117b76.png)

**Comment by kai23333** [comment]
请问,如果mapper.xml文件里带有if标签的语句也可以拿出来吗,我通过读取mapper.xml,if标签是解析不出来的,这个是可以解析出来吗?

**Comment by hhyo** [comment]
> 请问,如果mapper.xml文件里带有if标签的语句也可以拿出来吗,我通过读取mapper.xml,if标签是解析不出来的,这个是可以解析出来吗?

是可以的，动态SQL就只有那几个固定的标签，最初的想法是利用MyBatis内部getBoundSql的方法来生成SQL，但是只实现一部分，过程中发现parameterType是可以在其他地方定义的，XML并不包含所有信息。

**Comment by hhyo** [comment]
对应分支：https://github.com/hhyo/archery/tree/feature/mybatis

**Comment by kai23333** [comment]
老师好，我想问一下这个parameterType在哪里自己定义，我解析到where后面比如有if标签就没有了（小菜鸡一枚）

**Comment by hhyo** [comment]
> 老师好，我想问一下这个parameterType在哪里自己定义，我解析到where后面比如有if标签就没有了（小菜鸡一枚）

参考  https://github.com/hhyo/mybatis-mapper2sql

以及Archery平台的SQL分析模块

**Comment by kai23333** [comment]
这里看过了，我用的是java，没大看明白。。。，还是谢谢老师

**Comment by hhyo** [comment]
按照最初的需求，将xml文件纳入SQL上线的DDL工单中，用作前置审核

**Comment by saigu** [comment]
您好，请问这里将xml文件转为sql，是带占位符带吗？soar支持带占位符带sql诊断吗？

**Comment by hhyo** [comment]
@saigu 带占位符，soar也支持，具体可以访问demo站点的SQL分析模块体验

**Comment by stronglxp** [comment]
试用了一下发现互斥的if解析有问题。如下语句
```
<select id="queryWoBillInfoByBillId" resultType="java.util.Map">
        select
        spb.deal_code as "account",
        swb.contact_phone as "contactPhone",
        (select bpb2 .city_code from baf.baf_pub_bureau bpb2 where bpb2.bureau_id=spb.nativenet_id) as "cityId",
        (select bpb.business_name from baf.baf_pub_business bpb where bpb.business_id = spb.specialty_id) as "proType",
        swb.sub_name as "userName",
        swb.inst_address as "address"
        from
        <if test="isHis == 0">
            pub.svr_pub_bill spb,
            wo.svr_wo_bill swb
        </if>
        <if test="isHis == 1">
            pub.svr_pub_bill_his spb,
            wo.svr_wo_bill_his swb
        </if>
        where
        spb.bill_id = swb.bill_id
        and spb.bill_id = #{billId}
    </select>
```
两个if标签只需要保留一个即可，如果两个都保留语句就会有问题。这一块请问能支持一下吗？
