### ISSUE TITLE
[ 问题咨询 ]创建表设置字段为json类型会报错error

### ISSUE THREAD

**Issue by zengyananaaa** [hhyo/Archery#304]
### 问题描述
提交工单，创建表，设置字段类型为json，点击“SQL检测”，审核信息中会报error：您的SQL存在语法错误，near ‘XXX’ at line 5

### 版本信息
 - 应用版本/分支：Release version：‘3’
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
inception 可能还不支持json 类型, 建议参考 goinception 文档, 如果确实不支持的话, 跟 inception 或 goinception 提 issue https://github.com/hanchuanchuan/goInception

**Comment by hhyo** [comment]
Inception已经停止维护，goInception是支持的，可在演示环境测试

下个版本，MySQL默认审核引擎将会切换为goInception
