### ISSUE TITLE
[ 通过接口正常获取top表空间数据，前端显示异常]

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#307]
### 问题描述
top表空间查看接口获取数据正常，模板初始化呢

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by benevolence-doctor** [comment]
![image](https://user-images.githubusercontent.com/13461419/60695243-a4d30a80-9f13-11e9-9cb4-2da2a86b1e4f.png)

**Comment by hhyo** [comment]
mysql没有开lower_case_table_names，这块可以修改，使用as来处理，等更新

**Comment by benevolence-doctor** [comment]
我看数据库设置为1 应该是不区分大小写，应该改成 2？

**Comment by benevolence-doctor** [comment]
已修改db_diagnostic.py 加上AS处理了 谢谢

**Comment by hhyo** [comment]
麻烦提交一个pr修复这个bug，感谢
