### ISSUE TITLE
[ 问题咨询] 查看回滚的SQL返回为空

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#308]
### 问题描述
前端点击查看回滚的SQL返回为空，但是登陆数据库后可查看到回滚的SQL语句

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker
前端显示：
![image](https://user-images.githubusercontent.com/13461419/60704509-3738d580-9f37-11e9-8b24-f6c5005fda35.png)
数据库显示：
![image](https://user-images.githubusercontent.com/13461419/60704559-64858380-9f37-11e9-9fa4-94b16df40c93.png)

**Comment by hhyo** [comment]
确定对应的是同一个工单？
关于回滚的可以看文档FAQ相关部分

**Comment by hhyo** [comment]
版本用的是1.4.5么，先升级

**Comment by benevolence-doctor** [comment]
怎么查看版本 我用docker-compose 从master分支来的文件 应该算是新的

**Comment by benevolence-doctor** [comment]
list_backup_sql
[["update users set mobile='13051440908' where username='guojun'", '']] 
没有看懂你怎么获取回滚语句的，只看到了你获取上线的SQL语句，请问回滚语句怎么实现的

**Comment by benevolence-doctor** [comment]
看了获取回滚语句源码，知道原因了 谢谢

**Comment by Lovely-red-scarf** [comment]
> 看了获取回滚语句源码，知道原因了 谢谢

请问是什么原因造成的呢  我的也是没有获取回滚语句

**Comment by wximeng** [comment]
我这边也是不能产生回滚语句，数据库表里回滚语句都没有。
根据FAQ 无法产生回滚语句checklist 都检查了一遍，没有找到问题。
还有哪里需要配置吗？

**Comment by LeoQuote** [comment]
如果按照 FAQ 排查了一次问题依然存在, 你可以尝试升级 archery 来看看有没有效果, 如果升级依然没有, 而且也没有报错信息提供的话, 我们也没有什么头绪帮你排查.

**Comment by wximeng** [comment]
> 如果按照 FAQ 排查了一次问题依然存在, 你可以尝试升级 archery 来看看有没有效果, 如果升级依然没有, 而且也没有报错信息提供的话, 我们也没有什么头绪帮你排查.

你好 
docker 升级 archery 后，无法选择数据库，提示
'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte

**Comment by LeoQuote** [comment]
请贴出完整的日志, 从你的日志来看并不知道具体是哪里报错.

**Comment by wximeng** [comment]
这个是网页弹出的提示，docker logs archery 没有打印日志

**Comment by wximeng** [comment]
> 请贴出完整的日志, 从你的日志来看并不知道具体是哪里报错.

能否加下微信请教 w_ximeng

**Comment by wximeng** [comment]
由于更新了archery,原先保存的数据库密码可能被加密不能识别，我重新设置数据库密码可以访问了。
现在的问题是 执行完sql，提示“Execute Successfully Backup successfully--”
但是界面和数据库表里都没有产生回滚语句

**Comment by wximeng** [comment]
time="2019/07/11 16:02:43.298" level=info msg="con:9 new connection 172.18.0.6:51248" file=server.go line=319
time="2019/07/11 16:02:43.299" level=debug msg="con:0 ActivePendingTxn select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')" file=adapter.go line=289
time="2019/07/11 16:02:43.301" level=debug msg="[QUERY] [INTERNAL] cost_time:1.574612ms request_count:2 succ:true con:0 user:<nil> txn_start_ts:409687074615853056 database: table_ids:[13],index_ids:[1],sql:select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')" file=adapter.go line=366
time="2019/07/11 16:02:43.301" level=debug msg="con:9 ActivePendingTxn SET NAMES utf8mb4" file=adapter.go line=289
time="2019/07/11 16:02:43.301" level=debug msg="[QUERY] cost_time:49.141µs  succ:true con:9 user:root@172.18.0.6 txn_start_ts:409687074616377344 database: sql:SET NAMES utf8mb4" file=adapter.go line=366
time="2019/07/11 16:02:43.301" level=debug msg="con:9 ActivePendingTxn set autocommit=0" file=adapter.go line=289
time="2019/07/11 16:02:43.301" level=debug msg="con:9 autocommit=0" file=set.go line=180
time="2019/07/11 16:02:43.301" level=debug msg="[QUERY] cost_time:70.236µs  succ:true con:9 user:root@172.18.0.6 txn_start_ts:409687074616377345 database: sql:set autocommit=0" file=adapter.go line=366
time="2019/07/11 16:02:43.332" level=debug msg=setSqlSafeUpdates file=session_inception.go line=2068
time="2019/07/11 16:02:43.332" level=debug msg=mysqlServerVersion file=session_inception.go line=1902
time="2019/07/11 16:02:43.333" level=debug msg="db version: 50616" file=session_inception.go line=1947
time="2019/07/11 16:02:43.333" level=debug msg=initMysqlSQLMode file=session_inception.go line=1951
time="2019/07/11 16:02:43.334" level=debug msg=mysqlExplicitDefaultsForTimestamp file=session_inception.go line=1990
time="2019/07/11 16:02:43.335" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:43.335" level=debug msg=checkChangeDB file=session_inception.go line=5133
time="2019/07/11 16:02:43.335" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:43.335" level=debug msg=checkUpdate file=session_inception.go line=5305
time="2019/07/11 16:02:43.339" level=info msg="con:9 close connection" file=server.go line=321
time="2019/07/11 16:02:44.922" level=info msg="con:10 new connection 172.18.0.6:51256" file=server.go line=319
time="2019/07/11 16:02:44.922" level=debug msg="con:10 ActivePendingTxn SET NAMES utf8mb4" file=adapter.go line=289
time="2019/07/11 16:02:44.923" level=debug msg="[QUERY] cost_time:53.606µs  succ:true con:10 user:root@172.18.0.6 txn_start_ts:409687075041574912 database: sql:SET NAMES utf8mb4" file=adapter.go line=366
time="2019/07/11 16:02:44.923" level=debug msg="con:10 ActivePendingTxn set autocommit=0" file=adapter.go line=289
time="2019/07/11 16:02:44.923" level=debug msg="con:10 autocommit=0" file=set.go line=180
time="2019/07/11 16:02:44.923" level=debug msg="[QUERY] cost_time:85.832µs  succ:true con:10 user:root@172.18.0.6 txn_start_ts:409687075041574913 database: sql:set autocommit=0" file=adapter.go line=366
time="2019/07/11 16:02:44.925" level=debug msg=setSqlSafeUpdates file=session_inception.go line=2068
time="2019/07/11 16:02:44.925" level=debug msg=mysqlServerVersion file=session_inception.go line=1902
time="2019/07/11 16:02:44.926" level=debug msg="db version: 50616" file=session_inception.go line=1947
time="2019/07/11 16:02:44.926" level=debug msg=initMysqlSQLMode file=session_inception.go line=1951
time="2019/07/11 16:02:44.927" level=debug msg=mysqlExplicitDefaultsForTimestamp file=session_inception.go line=1990
time="2019/07/11 16:02:44.928" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:44.928" level=debug msg=checkChangeDB file=session_inception.go line=5133
time="2019/07/11 16:02:44.929" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:44.929" level=debug msg=checkUpdate file=session_inception.go line=5305
time="2019/07/11 16:02:44.932" level=info msg="con:10 close connection" file=server.go line=321
time="2019/07/11 16:02:52.283" level=info msg="con:11 new connection 172.18.0.6:51292" file=server.go line=319
time="2019/07/11 16:02:52.284" level=debug msg="con:0 ActivePendingTxn select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')" file=adapter.go line=289
time="2019/07/11 16:02:52.285" level=debug msg="[QUERY] [INTERNAL] cost_time:1.361592ms request_count:2 succ:true con:0 user:<nil> txn_start_ts:409687076971216896 database: table_ids:[13],index_ids:[1],sql:select HIGH_PRIORITY * from mysql.global_variables where variable_name in ('autocommit', 'sql_mode', 'max_allowed_packet', 'time_zone', 'block_encryption_mode', 'tidb_skip_utf8_check', 'tidb_index_join_batch_size', 'tidb_index_lookup_size', 'tidb_index_lookup_concurrency', 'tidb_index_lookup_join_concurrency', 'tidb_index_serial_scan_concurrency', 'tidb_hash_join_concurrency', 'tidb_projection_concurrency', 'tidb_hashagg_partial_concurrency', 'tidb_hashagg_final_concurrency', 'tidb_backoff_lock_fast', 'tidb_constraint_check_in_place', 'tidb_ddl_reorg_worker_cnt', 'tidb_opt_insubquery_unfold', 'tidb_distsql_scan_concurrency', 'tidb_max_chunk_size', 'tidb_enable_cascades_planner', 'tidb_retry_limit', 'tidb_disable_txn_auto_retry')" file=adapter.go line=366
time="2019/07/11 16:02:52.285" level=debug msg="con:11 ActivePendingTxn SET NAMES utf8mb4" file=adapter.go line=289
time="2019/07/11 16:02:52.285" level=debug msg="[QUERY] cost_time:45.542µs  succ:true con:11 user:root@172.18.0.6 txn_start_ts:409687076971479040 database: sql:SET NAMES utf8mb4" file=adapter.go line=366
time="2019/07/11 16:02:52.286" level=debug msg="con:11 ActivePendingTxn set autocommit=0" file=adapter.go line=289
time="2019/07/11 16:02:52.286" level=debug msg="con:11 autocommit=0" file=set.go line=180
time="2019/07/11 16:02:52.286" level=debug msg="[QUERY] cost_time:56.278µs  succ:true con:11 user:root@172.18.0.6 txn_start_ts:409687076971741184 database: sql:set autocommit=0" file=adapter.go line=366
time="2019/07/11 16:02:52.288" level=debug msg=checkBinlogIsOn file=session_inception.go line=2091
time="2019/07/11 16:02:52.290" level=debug msg=setSqlSafeUpdates file=session_inception.go line=2068
time="2019/07/11 16:02:52.290" level=debug msg=mysqlServerVersion file=session_inception.go line=1902
time="2019/07/11 16:02:52.291" level=debug msg="db version: 50616" file=session_inception.go line=1947
time="2019/07/11 16:02:52.291" level=debug msg=initMysqlSQLMode file=session_inception.go line=1951
time="2019/07/11 16:02:52.292" level=debug msg=mysqlExplicitDefaultsForTimestamp file=session_inception.go line=1990
time="2019/07/11 16:02:52.293" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:52.293" level=debug msg=checkChangeDB file=session_inception.go line=5133
time="2019/07/11 16:02:52.293" level=debug msg=processCommand file=session_inception.go line=654
time="2019/07/11 16:02:52.293" level=debug msg=checkUpdate file=session_inception.go line=5305
time="2019/07/11 16:02:52.296" level=debug msg=checkBinlogIsOn file=session_inception.go line=2091
time="2019/07/11 16:02:52.297" level=debug msg=checkBinlogFormatIsRow file=session_inception.go line=1872
time="2019/07/11 16:02:52.298" level=debug msg=executeRemoteStatement file=session_inception.go line=1704
time="2019/07/11 16:02:52.298" level=debug msg=fetchThreadID file=session_inception.go line=2020
time="2019/07/11 16:02:52.298" level=debug msg=executeRemoteStatementAndBackup file=session_inception.go line=1791
time="2019/07/11 16:02:52.298" level=debug msg=mysqlFetchMasterBinlogPosition file=session_inception.go line=1840
time="2019/07/11 16:02:52.299" level=debug msg=executeRemoteStatement file=session_inception.go line=1704
time="2019/07/11 16:02:52.299" level=debug msg=fetchThreadID file=session_inception.go line=2020
time="2019/07/11 16:02:52.299" level=debug msg=mysqlFetchMasterBinlogPosition file=session_inception.go line=1840
time="2019/07/11 16:02:52.299" level=debug msg="开始备份" file=session_inception.go line=933
time="2019/07/11 16:02:52.302" level=debug msg=writeBackupRecord file=session_backup.go line=87
time="2019/07/11 16:02:52.302" level=debug msg=flushBackupRecord file=session_backup.go line=99
time="2019/07/11 16:02:52.304" level=info msg="con:11 close connection" file=server.go line=321

**Comment by LeoQuote** [comment]
从日志看是不是goinception 的问题.... 忧伤.... @hhyo 是不是新版本默认用 goinception 了?

**Comment by wximeng** [comment]
确实，我没有启用 “是否启用goInception”,现在有回滚语句了。

**Comment by wximeng** [comment]
不确定是不是goinception的问题。我又测试了两条sql，都是update
现在有两个问题
1.有两个数据库，有一个库能产生回滚语句，另一个不行。
2. 另一个没有产生回滚的数据库，sql执行完是提示“Execute Successfully Backup successfully”。

这是什么原因？

**Comment by LeoQuote** [comment]
如果不提供日志的话, 没有办法说是什么原因

**Comment by wximeng** [comment]
我先确认一个问题，
执行一条update语句，执行完成，事实上没有修改原数据。比如一个年龄是18，update 年龄等于18，这条update会产生回滚语句吗？

**Comment by hhyo** [comment]
没有默认启用goInception

截个图嘛，至少需要提供下相关信息，不然这怎么答啊

-  [ ]  FAQ相关信息是否已确认
- Archery版本
- 使用goInception还是Inception，以及相关应用的版本
- MySQL版本
- 提交的语句
- 执行的结果
- 查看回滚语句的结果
- 执行后MySQL生成的binlog信息
- 日志信息

尽可能一次提供更多的辅助定位信息，之所以项目不开沟通群，就是希望大家知道issue不能及时回复，需要尽可能完善所提交问题，否则一来一往可能一周时间都没了

- 有演示环境，能在演示环境重现尽可能重现后提供相关步骤
- 不能重现的，竭尽所能提供各项信息

**Comment by hhyo** [comment]
> 我先确认一个问题，
> 执行一条update语句，执行完成，事实上没有修改原数据。比如一个年龄是18，update 年龄等于18，这条update会产生回滚语句吗？

FAQ第7条
![image](https://user-images.githubusercontent.com/8842982/61036519-dbb98c80-a3fb-11e9-998a-e91e460519ee.png)

无数据影响，不产生binlog，自然不会备份

**Comment by wximeng** [comment]
> 没有默认启用goInception
> 
> 截个图嘛，至少需要提供下相关信息，不然这怎么答啊
> 
> * [ ]   FAQ相关信息是否已确认
> * Archery版本
> * 使用goInception还是Inception，以及相关应用的版本
> * MySQL版本
> * 提交的语句
> * 执行的结果
> * 查看回滚语句的结果
> * 执行后MySQL生成的binlog信息
> * 日志信息
> 
> 尽可能一次提供更多的辅助定位信息，之所以项目不开沟通群，就是希望大家知道issue不能及时回复，需要尽可能完善所提交问题，否则一来一往可能一周时间都没了
> 
> * 有演示环境，能在演示环境重现尽可能重现后提供相关步骤
> * 不能重现的，竭尽所能提供各项信息

问题解决了，非常感谢你们的回复。抱歉了。
确实没有仔细了解回滚语句产生的条件。
我一直在使用同一条sql测试，sql没有影响数据。

**Comment by wximeng** [comment]
> > 我先确认一个问题，
> > 执行一条update语句，执行完成，事实上没有修改原数据。比如一个年龄是18，update 年龄等于18，这条update会产生回滚语句吗？
> 
> FAQ第7条
> ![image](https://user-images.githubusercontent.com/8842982/61036519-dbb98c80-a3fb-11e9-998a-e91e460519ee.png)
> 
> 无数据影响，不产生binlog，自然不会备份

非常感谢回复。
