### ISSUE TITLE
[ 备份库名过长导致回滚语句生成失败 ]

### ISSUE THREAD

**Issue by shenjianxin** [hhyo/Archery#309]
### 问题描述
执行上线工单成功，备份失败，执行信息如下：
`Backup: 备份库名 'rm-hp3oyau9st72lxxxxxx.mysql.huhehaote.rds.aliyuncs.com-3306-xxxxxxx' 过长.
Backup: 备份库名 'rm-hp3oyau9st72lxxxxxx.mysql.huhehaote.rds.aliyuncs.com-3306-xxxxxxx' 过长.
Incorrect database name ''.
Incorrect database name ''.`

### 版本信息
 - 应用版本/分支：Release v1.6.1
 - 部署方式：Docker

**Comment by hhyo** [comment]
建议给https://github.com/hanchuanchuan/goInception
提交issue，一般这种建议使用cname来缩短连接名

**Comment by funet8** [comment]
遇到同样的问题，阿里云的rds，怎么解决啊？

**Comment by funet8** [comment]
https://www.funet8.com/4210.html

**Comment by LeoQuote** [comment]
可以设置 cname 解析的, 这样会短一些

**Comment by funet8** [comment]
> 可以设置 cname 解析的, 这样会短一些
噢，用一个A域名cname解析到阿里云RDS上？

我把阿里云rds域名改为IP连接，但是IP可能会改变

**Comment by LeoQuote** [comment]
cname 就是 CNAME 记录啊, 不是 A 记录

**Comment by funet8** [comment]
> cname 就是 CNAME 记录啊, 不是 A 记录

嗯，我明白的，A.com域名 cname解析到 rm-XXXXXXXX.mysql.rds.aliyuncs.com
非常感谢

**Comment by hhyo** [comment]
goInception已经会自动截断，切换就好了
