### ISSUE TITLE
[问题咨询]dial tcp 172.20.0.7:3306: connect: connection refused.

### ISSUE THREAD

**Issue by st1266** [hhyo/Archery#310]
### 问题描述
使用Docker部署，sql上线审核通过后执行报错，连接拒绝

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/52566924/60714803-555e0000-9f4e-11e9-88d1-0520ba488ba9.png)

**Comment by hhyo** [comment]
版本瞎填
