### ISSUE TITLE
[ 问题咨询 ]dial tcp 172.20.0.7:3306: connect: connection refused.

### ISSUE THREAD

**Issue by st1266** [hhyo/Archery#311]
问题描述
使用Docker部署，操作sql上线时，审核通过，执行报错。报错的IP 172.20.0.7并不是所选实例的IP。是docker的设置不对吗？

版本信息
应用版本/分支：Release version  v1.6.4
部署方式：Docker
![image](https://user-images.githubusercontent.com/52566924/60715904-ba1a5a00-9f50-11e9-84ac-382f7e3687fb.png)

**Comment by hhyo** [comment]
检查下goinception备份库地址的设置，这个看起来是连接不上备份库，如果你是使用的自己的mysql，需要修改下inception下config.toml的相关信息
