### ISSUE TITLE
[ 功能建议 ] 不同的实例走不同的审核流程

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#315]
### 开发、测试和生产环境不同的数据库想走不同审核流程，例如：
开发和测试环境SQL上线时：开发者---开发负责人
生产环境SQL上线时：开发者--开发负责人--管理员

**Comment by LeoQuote** [comment]
已有根据资源组单独设置审批流的功能, 见文档 https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%B7%A5%E4%BD%9C%E6%B5%81

本issue关闭

**Comment by benevolence-doctor** [comment]
配置项管理---系统管理--其他管理中
DEFAULT_AUTH_GROUP
DEFAULT_RESOURCE_GROUP
不支持多个吗，例如：DEFAULT_RESOURCE_GROUP为开发者，开发者--dev
这样默认用户我即让他即能操作开发环境又能操作生产环境，但是走的审批流程不一样
如果我给他默认开发者(即开发环境)，后台虽然可以把它加入多个组，但是并没有关联对应的实例

**Comment by LeoQuote** [comment]
你可以手动将他加入一些资源组和授权组，目前暂时不支持多个资源组/授权组 的配置，欢迎提出新的issue
