### ISSUE TITLE
[ 问题咨询 ]实例标签关系 关联的时候没有显示 

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#316]
在进行数据库 实例与标签进行关联的时候,不显示 数据库与标签关联这一个选项

**Comment by LeoQuote** [comment]
没有明白你的意思，可以描述一下预期的效果和实际效果吗？

**Comment by Lovely-red-scarf** [comment]
> 没有明白你的意思，可以描述一下预期的效果和实际效果吗？

我在sql上线的时候  选择不到组和实然后更改  实例与组关联的时候 找不到关联项目

**Comment by hhyo** [comment]
没看懂，写明步骤，有图最好可以配图

**Comment by Lovely-red-scarf** [comment]
![image](https://user-images.githubusercontent.com/41297612/60902897-f75d4f80-a2a2-11e9-8f8a-1b09b141e350.png)


就是这样选择不到对应的实例信息 


![image](https://user-images.githubusercontent.com/41297612/60903005-296eb180-a2a3-11e9-9c7a-f87059c20792.png)
在 数据库实例的添加的时候找不到关联的组

**Comment by Lovely-red-scarf** [comment]
> 没看懂，写明步骤，有图最好可以配图

您好大佬 有交流群吗?

**Comment by LeoQuote** [comment]
没有交流群，不提供实时回复。

**Comment by LeoQuote** [comment]
文档看过了吗？？ https://github.com/hhyo/Archery/wiki 有对资源组和权限组关联的说明呀，你是不是没看文档？

**Comment by Lovely-red-scarf** [comment]
> 文档看过了吗？？ https://github.com/hhyo/Archery/wiki 有对资源组和权限组关联的说明呀，你是不是没看文档？

看了的 但是都关联的  这个数据库的没办法和组关联的

**Comment by Lovely-red-scarf** [comment]
> 文档看过了吗？？ https://github.com/hhyo/Archery/wiki 有对资源组和权限组关联的说明呀，你是不是没看文档？

![image](https://user-images.githubusercontent.com/41297612/60903694-612a2900-a2a4-11e9-89f7-2cee0f1e763a.png)
我看表结构和线上的对比好像也少了两个的

**Comment by Lovely-red-scarf** [comment]
> 文档看过了吗？？ https://github.com/hhyo/Archery/wiki 有对资源组和权限组关联的说明呀，你是不是没看文档？

我的实例中没有是否支持上线这个按钮

**Comment by hhyo** [comment]
- 提问按模板，提供你的版本
- 认真看文档，节省大家的时间，你的问题文档都有详细说明

此问题不再回复
