### ISSUE TITLE
[ 问题咨询 ]添加文档

### ISSUE THREAD

**Issue by jackielulu17325** [hhyo/Archery#317]
大佬,我要在相关文档下面添加一个和设计规范类似的文档,添加了md文档,照着dbaprinciples修改了下列脚本:
sql/urls.py
sql/views.py
common/templates/base.html
重启archery报505,是不是还有地方需要改?
py小白,求指点...

**Comment by LeoQuote** [comment]
请提供具体修改和报错信息.

**Comment by jackielulu17325** [comment]
找到问题了,谢谢大神...
