### ISSUE TITLE
[问题咨询] 审核信息显示乱码

### ISSUE THREAD

**Issue by gdsea** [hhyo/Archery#318]
SQL上线时，执行简单的单行插入语句，点击SQL检测后，审核信息显示乱码。
下面为具体乱码信息

æ è¯ç¬¦ 'name' æ¯MySQLå³é®å­/ä¿çå­ï¼ä¸å»ºè®®ä½¿ç

**Comment by hhyo** [comment]
版本？
1.6.4版本使用inception有这个问题，1.6.5已修复

**Comment by gdsea** [comment]
我上周下载的时候没有关注版本，正在测试阶段，现在下载一个1.6.5试试。非常感谢！

**Comment by gdsea** [comment]
升级到1.6.5版本后，审核信息栏的乱码已经没了，感谢作者！
