### ISSUE TITLE
回滚报错

### ISSUE THREAD

**Issue by changeyourt** [hhyo/Archery#32]
(1146, "Table '127_0_0_1_3306_archery.$_$Inception_backup_information$_$' doesn't exist")
您好，我在查看回滚SQL时，报这个错，请问是哪里错了呢？

**Comment by changeyourt** [comment]
是我需要手动创建这个表吗？

**Comment by hhyo** [comment]
参考[无法生成回滚语句](https://github.com/hhyo/archery/wiki/FAQ#%E6%97%A0%E6%B3%95%E7%94%9F%E6%88%90%E5%9B%9E%E6%BB%9A%E8%AF%AD%E5%8F%A5)

**Comment by LeoQuote** [comment]
备份表是不需要手动创建的，
是docker启动的吗？
inception里配置的备份库和archery里配置的备份库信息是对的吗？
———
emmm参考楼上

**Comment by changeyourt** [comment]
@LeoQuote @hhyo 配置的备份库信息是一样的。
昨天我用的是mariadb，今天我换成了mysql，但好像还是报同样的错。
今天多了一个错误：
Backup: Authentication plugin 'caching_sha2_password' cannot be loaded: not a plugin

**Comment by changeyourt** [comment]
Exception: (1049, "Unknown database '127_0_0_1_3306_archery'")
为什么数据库是这样的字符串，不应该只有archery，为什么前面拼凑了地址和端口

**Comment by hhyo** [comment]
还是前面地址，一个个点核实，inception的文档看一遍，就清楚了。

**Comment by changeyourt** [comment]
嗯，都是我自己挖的坑
1、数据库版本用的太高，8.0，以为高于5.6就可以了。
2、没有开启binlog。
谢谢！

**Comment by changeyourt** [comment]
@hhyo 
你好，请问在配置慢查询时src/script/analysis_slow_query.sh这个脚本需要放在哪个路径，文档说放到mysql
所在的实例，但是没有提到路径。

**Comment by LeoQuote** [comment]
放在哪里都可以，只要在该实例上周期性运行即可。

**Comment by changeyourt** [comment]
请问咱们有没有群啊！方便大家讨论archery的使用问题的，这种留言的方式还是太慢了。

**Comment by changeyourt** [comment]
@LeoQuote 管理员新建了一个用户，但是这个用户登录平台时报403，请问需要给这个用户赋予什么权限？

**Comment by changeyourt** [comment]
@LeoQuote 请问下，SQL优化--优化工具主要是做什么的？
选择实例时，我看可以选择主库和从库。
我在SQL输入框中的SQL会去哪执行？还是说只是模拟执行，然后让soar或者sqladvisor来帮我们提优化建议。
它的执行流程是怎样的呢？

**Comment by hhyo** [comment]
不会模拟执行，仅当做参数传递给对应优化工具获取结果。另外，不同的问题建议新开issue，这个关闭。
