### ISSUE TITLE
SQL查询平台 (v1.6.3)[ 问题咨询 ]

### ISSUE THREAD

**Issue by jackielulu17325** [hhyo/Archery#320]
### 问题描述
系统管理-->配置项管理

工单审核流程配置-->SQL上线申请-->选择组,
操作-->变更审批流程 选择后 弹框 "NOT Found"
日志报错:[MainThread:140330558691136][task_id:django.request][base.py:93][WARNING]- Not Found: /group/changeauditors/

请教是什么问题?
### 版本信息
 - 应用版本/分支：v1.6.3
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
请升级到最新版。
