### ISSUE TITLE
[ 问题咨询 ]  SQL上线时，备份失败

### ISSUE THREAD

**Issue by gdsea** [hhyo/Archery#322]
### 问题描述
在SQL上线过程中，点击执行SQL，在工单详情栏出现以下错误信息
审核/执行信息：Backup: Got an error reading communication packets.
当前阶段：Execute Successfully Backup failed

### 版本信息
 - 应用版本/分支：Release v1.6.5
 - 部署方式：Docker

**Comment by gdsea** [comment]
![image](https://user-images.githubusercontent.com/47139853/61100179-c2661e00-a497-11e9-9b49-18e1c1b1aaa6.png)

**Comment by LeoQuote** [comment]
这是文档中的checklist , 请按文档进行排查, 如果已经排查请在issue中附带排查的结果和初步结论, https://github.com/hhyo/archery/wiki/faq#%E6%97%A0%E6%B3%95%E7%94%9F%E6%88%90%E5%9B%9E%E6%BB%9A%E8%AF%AD%E5%8F%A5

**Comment by think-coding** [comment]
@gdsea 你是否使用的 inception 版本？inception 对于关键字的列名，会有备份失败的情况。
解决办法：切换 goInception。

**Comment by gdsea** [comment]
> @gdsea 你是否使用的 inception 版本？inception 对于关键字的列名，会有备份失败的情况。
> 解决办法：切换 goInception。

goinception和inception区别大不大？

另外我的问题处理了，是因为中间件proxysql导致的，改为直连数据库以后，就没有问题了。

**Comment by gdsea** [comment]
> 这是文档中的checklist , 请按文档进行排查, 如果已经排查请在issue中附带排查的结果和初步结论, https://github.com/hhyo/archery/wiki/faq#%E6%97%A0%E6%B3%95%E7%94%9F%E6%88%90%E5%9B%9E%E6%BB%9A%E8%AF%AD%E5%8F%A5

您好，是因为连接数据库时，经过了一层中间件（proxysql），然后备份失败了。直连数据库就成功了。
