### ISSUE TITLE
[功能建议]一人血书，强烈建议SQL上线功能支持postgresSQL

### ISSUE THREAD

**Issue by bucardo111** [hhyo/Archery#323]
### 目前遇到的问题/使用障碍
找了很多类似平台，目前没有发现一个支持postgresql 的SQL上线，国内现在使用postgresql的用户在增多，但是支持pg这一块的几乎空白
### 希望如何解决/实现它
早日支持pg
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
感谢你的建议, 但本issue属于重复issue 
请在这个issue #204  中进行讨论, 不要新开issue , 本issue 关闭.
