### ISSUE TITLE
[ 问题咨询 ]  sql查询的时候显示所有的可查库都是可见的  已经查看了wiki但是一直无法配置 查询申请流程,

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#324]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
请具体描述你遇到的情况，包括你的操作，预期结果和实际结果。

**Comment by hhyo** [comment]
有时间再改改issue模板吧，真的是没办法

**Comment by Lovely-red-scarf** [comment]
> 请具体描述你遇到的情况，包括你的操作，预期结果和实际结果。

我的需求是进行sql查询的时候 能否配置成sql上线一样的 工单审核呢

**Comment by LeoQuote** [comment]
目前暂时不支持每次查询都审核，只能审批发放一段时间的查询权限。

**Comment by Lovely-red-scarf** [comment]
> 目前暂时不支持每次查询都审核，只能审批发放一段时间的查询权限。

好的 谢谢了
