### ISSUE TITLE
[ 问题咨询 ] update语句提示语法错误

### ISSUE THREAD

**Issue by st1266** [hhyo/Archery#326]
问题描述
使用Docker部署，操作sql上线时，SQL检测报错，提示语法错误，但是语法正确。
在另一个测试库里，建相同表，插入相同数据，检测同样的update语句没有问题。
开了goinception，inception.py和goinception.py中的特殊字符问题是已改的版本。

版本信息
应用版本/分支：Release version v1.6.4
部署方式：Docker

线上：
![image](https://user-images.githubusercontent.com/52566924/61260406-a1ac0a00-a7b0-11e9-9714-22cc6be191b4.png)

测试环境：
![image](https://user-images.githubusercontent.com/52566924/61260416-b4beda00-a7b0-11e9-9cf0-e727613893ee.png)

**Comment by st1266** [comment]
线上MySQL版本是percona的5.5.61，测试环境是5.7.26

**Comment by st1266** [comment]
是goinception的问题

**Comment by LeoQuote** [comment]
描述的很详细, 感谢你详细的描述( 虽然我们没帮上忙

**Comment by hhyo** [comment]
可以给https://github.com/hanchuanchuan/goInception
提交issue
