### ISSUE TITLE
[ 功能建议 ] 建议支持解析运行Oracle下PLSQL执行块功能

### ISSUE THREAD

**Issue by ruanct** [hhyo/Archery#327]
### 目前遇到的问题/使用障碍
(1) 无法创建和替换 函数、过程、包
(2) 无法执行PLSQL执行块

以上两点在SQL解析时就不支持，具体SQL解析如下：
![image](https://user-images.githubusercontent.com/47140205/61261229-b6d66800-a7b3-11e9-9434-c776e7b80e04.png)

### 希望如何解决/实现它
(1) 定义PLSQL执行块的 开始与结束的声明，根据该声明来识别出PLSQL执行块，例如：
/* PLSQL BEGIN */

/* PLSQL END */

(2) 识别出的PLSQL执行块，再根据符号(/)来详细分割更小的可执行块。每一个执行块是一个可执行语句。

### 举例
/* PLSQL BEGIN */

declare
begin
end
/

declare
begin
end
/

/* PLSQL END */

**Comment by LeoQuote** [comment]
感谢你的反馈, 目前 oracle 的语法解析是用的 sqlparse 
https://github.com/hhyo/Archery/blob/621eb6c520e9306827161916d852e62d8782fa9c/sql/engines/oracle.py#L210-L220

可以看到是简单的直接split , 在执行的时候也是这样简单的split , 所以会造成执行失败. 

如果要支持 PLSQL , 可以仿照 sql server 使用正则表达式分割语句, 然后所有其他语句都作为一整块运行.

https://github.com/hhyo/Archery/blob/621eb6c520e9306827161916d852e62d8782fa9c/sql/engines/mssql.py#L162-L174

如果有能力的话可以直接改代码提pr , 只要流程没大问题, 单元测试全过就会接受.

但是说实话, 你提供的这种程度复杂度( 有两层嵌套 )的语句, 正则表达匹配会比较累, 实现起来难度较大, 还请量力而行.
@yzypals 你这边用oracle 比较多, 你觉得怎么样?

**Comment by ruanct** [comment]
@LeoQuote 了解，我提的方式只是一个举例，确实复杂些。
如有简洁方法，肯定走简洁方法。可以约定，plsql程序块工单内容必须完全独立，不能和DDL & DML语句混合使用。

**Comment by yzypals** [comment]
这个平台的  定义，   sql 查询 和上线 ，上面说的2个功能 感觉已经高于 这个定义了。
目前我们  没碰到过 这些情况，稍后我去问问 dba ，看看 上面2个需求 和这个平台的匹配度。

**Comment by ruanct** [comment]
@yzypals  确实，我这已经不仅仅作为SQL上线管理使用，在线数据运维也打算纳入到本平台。
目前平台有一整套的SQL审核、执行，工单流程处理，权限控制等待，完全契合这个需求。

**Comment by ruanct** [comment]
各位，本问题暂时解决不了，根源是 cx_Oracle扩展包不支持执行plsql块，底层的cursor.execute() 实际上还是以分号（；）为分隔来执行语句。

截图如下：
工单内容：
![image](https://user-images.githubusercontent.com/47140205/61726657-92c2ea00-ada4-11e9-92b4-f3c0a8264c5a.png)

语句识别：
![image](https://user-images.githubusercontent.com/47140205/61726677-9d7d7f00-ada4-11e9-9734-c259ba5108b1.png)

执行结果：
![image](https://user-images.githubusercontent.com/47140205/61726696-a66e5080-ada4-11e9-8f4f-0ab5a624ab80.png)

**Comment by LeoQuote** [comment]
这个不是cx_oracle做的，你看一下execute方法的逻辑是有切分的，你可以把那一段代码改了

**Comment by yzypals** [comment]
这个功能缺的是oracle sql 解析   这一块 ， 现在用的sqlparse ，不确定能不能很好的支持解析begin  这种句法，  后面会考虑做，应该我们公司要求支持分开分表，   就需要更好的去解析语法了，顺便就把begin 这部分做了。  就是 时间跨度上会比较久。最近事情多 ， 没太多精力弄这个。

**Comment by hhyo** [comment]
#688
这个是不是也在PR里面搞定了

**Comment by ruanct** [comment]
是的，目前的功能可以提交并执行psql的执行块（匿名块），但是有个小问题要注意，执行块如果没有合适的异常处理并抛出，执行完之后不好判断成功与否。
目前的建议是在执行块中加入日志表并记录执行信息，便于结果追查



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小圈圈 <notifications@github.com&gt;
发送时间: 2020年3月28日 09:43
收件人: hhyo/Archery <Archery@noreply.github.com&gt;
抄送: ericruan-cn <330518878@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hhyo/Archery] [ 功能建议 ] 建议支持解析运行Oracle下PLSQL执行块功能 (#327)





 
#688
 这个是不是也在PR里面搞定了

**Comment by hhyo** [comment]
已支持

**Comment by solon-liu** [comment]
![image](https://github.com/hhyo/Archery/assets/24712997/918231e8-3a0d-4221-a5af-e9680ed9ce1e)

其他工具是可以正常运行的PLSQL程序块，这里提交为什么还是会报错呢
