### ISSUE TITLE
[ SOAR优化提示这个是为什么 ]

### ISSUE THREAD

**Issue by ciweigg2** [hhyo/Archery#331]
### 问题描述
SOAR优化中显示
MySQL environment verbose info
test-dsn: ip:3306is disable, please check log.
online-dsn: ip:3306is disable, please check log.
这个要怎么开启才不提示

### 版本信息
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
Demo 能复现吗？有截图吗？有日志吗？

**Comment by mawenbin666** [comment]
> ### 问题描述
> SOAR优化中显示
> MySQL environment verbose info
> test-dsn: ip:3306is disable, please check log.
> online-dsn: ip:3306is disable, please check log.
> 这个要怎么开启才不提示
> 
> ### 版本信息
> * 部署方式：Docker、
> 版本:1.7.4

问下，这个问题得到解决了吗？我的环境也是报这个错。

**Comment by LeoQuote** [comment]
Demo 能复现吗？有截图吗？有日志吗？

**Comment by mawenbin666** [comment]
> Demo 能复现吗？有截图吗？有日志吗？

配置：
![image](https://user-images.githubusercontent.com/22042460/72491693-bcd9fe00-3855-11ea-8f14-ec9f2e1fb61f.png)
报错截图:
![image](https://user-images.githubusercontent.com/22042460/72491845-47226200-3856-11ea-96e1-549acd8cb39c.png)
日志：
2020/01/15 14:54:31.924 [E] [mysql.go:95]  Error 1045: Access denied for user 'soar -test-dsn bluemoon'@'192.168.234.23' (using password: YES)
2020/01/15 15:48:09.745 [E] [mysql.go:95]  Error 1045: Access denied for user 'soar -test-dsn bluemoon'@'192.168.234.23' (using password: YES)

**Comment by hhyo** [comment]
test dns的配置不对，具体可以阅读soar文档，配置无需用双引号，直接写就行

**Comment by mawenbin666** [comment]
> test dns的配置不对，具体可以阅读soar文档，配置无需用双引号，直接写就行

我把SOAR_TEST_DSN配置的双引号去掉也不行。还是报错
界面上显示：
MySQL environment verbose info

test-dsn: 192.168.234.14:3306 is disable, please check log.
soar的log显示：
2020/01/16 13:32:55.776 [E] [mysql.go:95]  Error 1045: Access denied for user '-test-dsn bluemoon'@'192.168.234.23' (using password: YES)
我在archery的docker里面，用mysql客户端去连配置的数据库信息，是可以连通的

**Comment by hhyo** [comment]
这个用户名`-test-dsn bluemoon` 确定对？

soar只是一个插件，具体可以不依靠archery，按照自己的配置执行看是否报错

**Comment by mawenbin666** [comment]
> 这个用户名`-test-dsn bluemoon` 确定对？
> 
> soar只是一个插件，具体可以不依靠archery，按照自己的配置执行看是否报错

可以了，是账号没有配对，最终SOAR_TEST_DSN这样配置才可以
user:passwd@ip:port
没有带双引号
