### ISSUE TITLE
[ 功能建议 ]希望加上sql保存功能并能管理

### ISSUE THREAD

**Issue by duge123** [hhyo/Archery#333]
在sql查询目录下新建一个sql管理的子菜单（图1）与页面（图2），
然后在查询页面上有个保存sql的按钮和选择我保存的sql别名（图3）
这样对查询的效率提高很多，谢谢。

图1：
![image](https://user-images.githubusercontent.com/51983002/61344213-020b7c00-a883-11e9-9432-f894cde7bd59.png)

图2：
![image](https://user-images.githubusercontent.com/51983002/61345128-6d0a8200-a886-11e9-96de-9ba165a32afc.png)

图3：
![image](https://user-images.githubusercontent.com/51983002/61345133-71cf3600-a886-11e9-9eed-27ac7fba1f27.png)

图画的不好，希望能看懂，谢谢

**Comment by LeoQuote** [comment]
历史查询点击后自动进输入框够用吗？（如果有这样的功能

**Comment by duge123** [comment]
有总比没有的好。。也可以在历史查询里面加个sql置顶 通过排序来实现。

**Comment by LeoQuote** [comment]
前端功能不太会做 😅 @hhyo 应该可以监听历史查询那块的click 事件? 然后点击之后就把语句 append 进去, 这样还是挺方便的.

**Comment by hhyo** [comment]
表格有行点击事件可以做，可以同时填充实例和库信息
不过@duge123的想法挺好的，有些统计sql或者常用sql可以保存起来，从查询历史来的话数据可能有点乱

**Comment by LeoQuote** [comment]
也是, 那看怎么做了....感觉这么做要新做个表用来存常用语句,表结构大概是
```
id 
name
content
description
instance_id
created_by
created_at
updated_at
```
后端倒是好说, 前端感觉也还行, 好像有edit sql 的页面就是预先传值进去的吧.

编辑器可以沿用之前的, 就是要加一个save 和 load 函数,用来保存和加载sql 语句

**Comment by hhyo** [comment]
在查询日志中增加收藏和别名属性怎么样？
- 查询日志增加实例、库、别名下拉筛选项
- 增加收藏、取消收藏以及标识/别名的编辑功能，但是不允许编辑语句其他内容
- 所有查询语句均可以一键重新查询/自动填充

**Comment by hhyo** [comment]
演示环境已更新，可升级体验
