### ISSUE TITLE
[SQL上线]

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#336]
执行SQL上线时报错
![微信图片_20190718115152](https://user-images.githubusercontent.com/50727710/61427912-74975d00-a952-11e9-9e12-bc89990fcbfd.png)

但是在系统设置里面没有使用inception，并且archery的配置文件中也没有使用inception
![微信图片_20190718115335](https://user-images.githubusercontent.com/50727710/61427964-b4f6db00-a952-11e9-9b3c-3f8dff427ec1.png)

版本：1.6.5

**Comment by hhyo** [comment]
#319

**Comment by LeoQuote** [comment]
文案可以改一下，话说为什么会出这个问题啊？最新版本修复了吗？

**Comment by hhyo** [comment]
goinception最近版本才支持mysqlclient
