### ISSUE TITLE
[ 问题咨询 ]添加表设置字段为json类型会报错error

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#337]
### 问题描述
采用goinception发现添加字段类型为json时报错，导入goinception模板SQL时将其默认值修改为true了,我在你们公共体验版http://139.199.0.191 测试没有这个问题，需要修改哪个配置

more goinception_param_template.sql|grep json
('goinception','enable_json_type','true',1,'true,false','设置是否允许json类型字段，包括建表、修改列、新增列操作','2019-05-27 15:12:59.000000','2019-05-27 15:12:59.000000'),

### 版本信息
 - 应用版本/分支：Release v1.6.4
 - 部署方式：Docker

**Comment by benevolence-doctor** [comment]
我看体验版是v1.6.6版本的，docker镜像我看最新是1.6.4版本

**Comment by LeoQuote** [comment]
先升级再说.

**Comment by benevolence-doctor** [comment]
目前docker最新的就是1.6.4 已经是最新版本了

**Comment by LeoQuote** [comment]
https://hub.docker.com/r/hhyo/archery/tags 有 1.6.5 版本

**Comment by benevolence-doctor** [comment]
我制作一个1.6.5的镜像试试

**Comment by benevolence-doctor** [comment]
➜  root@dev:docker git:(master) ✗ docker pull hub.docker.com/r/hhyo/archery:v1.6.5 
Trying to pull repository hub.docker.com/r/hhyo/archery ... 
Pulling repository hub.docker.com/r/hhyo/archery
invalid character '<' looking for beginning of value
报错是不是我的方法不对

**Comment by benevolence-doctor** [comment]
默认docker pull 就是从hub.docker.com下的吧 docker pull hhyo/archery:v1.6.5 不行

**Comment by LeoQuote** [comment]
```
docker pull hhyo/archery:1.6.5
```

**Comment by LeoQuote** [comment]
magic.....那我就不太清楚了, @hhyo 你来看看 相关issue #304

**Comment by benevolence-doctor** [comment]
在goincepiton的配置文件config.toml 添加enable_json_type=true

**Comment by LeoQuote** [comment]
用这个方法就可以解决吗? 可以帮忙更新到文档中吗? 可以放在 https://github.com/hhyo/archery/wiki/faq#inception%E7%9B%B8%E5%85%B3 faq 的inception 区域中

**Comment by hhyo** [comment]
嗯，改goinception配置即可

导入的模板文件只是参数模板，和具体配置无关

**Comment by benevolence-doctor** [comment]
@LeoQuote 已更新到FAQ
