### ISSUE TITLE
Docker安装部署Archery问题

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#339]
您好，我初次部署，想采用docker部署，步骤如下：
1. 安装docker和docker-compose
2. 下载源码包: git clone https://github.com/hhyo/archery.git
3. 启动
docker-compose -f docker-compose.yml up -d
这个docker-compose.yml文件是源码包中的archery/src/docker-compose目录下的docker-compose.yml文件吗？

另，binlog2sql和inception、soar、mongodb这些就不需要单独安装了吧，我看compose文件里面有安装？

**Comment by LeoQuote** [comment]
你说得对, 在途中遇到什么问题了吗?
参照我们的文档进行操作即可, 如果文档有什么不对或者不完善的地方的欢迎进行修改, 文档的编辑权限是开放的.

**Comment by hhyo** [comment]
启动需要进入相关目录，因为配置和目录映射是相对路径

**Comment by Myshiner** [comment]
谢谢您的指导
