### ISSUE TITLE
唯一索引创建异常

### ISSUE THREAD

**Issue by eason0420** [hhyo/Archery#34]
在archary中提交唯一索引创建工单，执行时异常,并且显示不使用gh-osc，执行速度也很慢，要250s左右，我在命令行直接执行也就2s左右。
创建普通索引是可以的，但是也是很慢
1> Cannot connect to A=utf8,P=2369,h=11.193.2.110,p=...,u=zhan_admin
No slaves found. See --recursion-method if host a61a01334.cloud.et15 has slaves.
Not checking slave lag because no slaves were found and --check-slave-lag was not specified.
Operation, tries, wait:
analyze_table, 10, 1
copy_rows, 10, 0.25
create_triggers, 10, 1
drop_triggers, 10, 1
swap_tables, 10, 1
update_foreign_keys, 10, 1
Not updating foreign keys because --alter-foreign-keys-method=none. Foreign keys that reference the table will no longer work.
Altering `zhan_public_class`.`tpo_publicclass_signup_users_test`...
# Event Count
# ====== =====
# INSERT 0
`zhan_public_class`.`tpo_publicclass_signup_users_test` was not altered.
You are trying to add an unique key. This can result in data loss if the data is not unique.
Please read the documentation for the --check-unique-key-change parameter.
You can check if the column(s) contain duplicate content by running this/these query/queries:

SELECT IF(COUNT(DISTINCT PassPortId) = COUNT(*),
'Yes, the desired unique index currently contains only unique values', 
'No, the desired unique index contains duplicated values. There will be data loss'
) AS IsThereUniqueness FROM `zhan_public_class`.`tpo_publicclass_signup_users_test`;

Keep in mind that these queries could take a long time and consume a lot of resources

**Comment by eason0420** [comment]
inception_osc_on=OFF  这个地方关了吗？  @hhyo

**Comment by eason0420** [comment]
@LeoQuote   archary我是用的docker最新版本 inception也是hhyo提供的docker版本

**Comment by hhyo** [comment]
关闭后就变成直接执行，现在也不支持gh-ost，业务高峰期操作请注意观察元数据锁的情况，url的bug可以新开个issue

**Comment by wangyi-5102** [comment]
archery 1.9.1 docker部署，开启pt-osc后 goinception 关闭唯一索引检查就可以了
 > inception set osc_check_unique_key_change=false;
