### ISSUE TITLE
[ 功能建议 ]资源组放权给项目组owner

### ISSUE THREAD

**Issue by huoarter** [hhyo/Archery#340]
### 目前遇到的问题/使用障碍

- 添加实例，关联资源组想放权给项目组owner
- 登录认证的用户，自动关联到对应的资源组（这个是否已经有实现？不确定）

### 希望如何解决/实现它
- 支持项目组owner添加实例，并且具有实例测试连通性
- 项目组owner在关联资源的时候，只能关联owner所在的资源组，而不是所有的资源组可见
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
确实是很好的建议, 有这样的功能之后资源组就可以设置owner, 相当一部分的权限可以放给资源组的owner 而不是整个系统的管理员.

稍微有点奇怪的是为什么项目组owner会有账号密码? 设计的话是系统有一个管理员( 一般是DBA) 来创建账号, 在系统中添加实例, 然后顺便分配给对应的项目组.

另外方便透露下目前目前系统接入了多少个实例, 分到了多少个资源组吗? 一周会有多少添加实例并且分组的需求? 

目前的操作即使这些都是一个人做, 应该也可以在5分钟内完成.

**Comment by hhyo** [comment]
给用户实例列表的权限menu_instance
和can add 实例的权限，以及开放管理后台登录应该就行

**Comment by huoarter** [comment]
> 确实是很好的建议, 有这样的功能之后资源组就可以设置owner, 相当一部分的权限可以放给资源组的owner 而不是整个系统的管理员.
> 
> 稍微有点奇怪的是为什么项目组owner会有账号密码? 设计的话是系统有一个管理员( 一般是DBA) 来创建账号, 在系统中添加实例, 然后顺便分配给对应的项目组.
> 
> 另外方便透露下目前目前系统接入了多少个实例, 分到了多少个资源组吗? 一周会有多少添加实例并且分组的需求?
> 
> 目前的操作即使这些都是一个人做, 应该也可以在5分钟内完成.

这个建议主要是想做到完全自助的自动化流程，当然这个需求，我目前可以使用我司内部的workflow来完成。我们这边的数据库做到一个服务一个实例，目前有30多个sql实例，40多个redis实例，还涉及到人员变更项目组，频繁修改而且要严格控制权限，所以有这类需求。当然你说的一个人5分钟内完成，没有问题，但是一个完善的需求是不是要一步一步升华？
还有一点我没有理解，怎么样实现通过ldap认证登录的用户，能否自动关联到对应的资源组？这个要借助我上面说的另外的workflow实现？还是已经有此功能？

**Comment by huoarter** [comment]
> 给用户实例列表的权限menu_instance
> 和can add 实例的权限，以及开放管理后台登录应该就行

如果你这样添加管理后台登录之后，你会发现这个管理员会对所有资源组都有访问权限，这个在严格权限控制这个地方是不合适的。应该是项目组管理员只对项目组关联的资源组才有访问权限。

**Comment by LeoQuote** [comment]
emmmm 你的这个场景确实是需要放权一些, 不然一个人做是有些浪费时间, 不过这个可能要实现一个类似 一个矩阵的权限控制, 可能不会太快实现, 你可能暂时还是要用外部 workflow 来做...
也非常欢迎你直接提交pr, 或者在本issue中具体阐述实现方法.

**Comment by yzypals** [comment]
>怎么样实现通过ldap认证登录的用户，能否自动关联到对应的资源组？这个要借助我上面说的另外的workflow实现？还是已经有此功能？

这个功能原本就有， 有2个地方可以实现，  第一是 系统设置里面有个默认组合默认资源组的设置 ， 还一个 就是setting中ldap配置本身有个选项， 根据ldap的组来划分组（这个我还没实验过）

**Comment by huoarter** [comment]
> > 怎么样实现通过ldap认证登录的用户，能否自动关联到对应的资源组？这个要借助我上面说的另外的workflow实现？还是已经有此功能？
> 
> 这个功能原本就有， 有2个地方可以实现， 第一是 系统设置里面有个默认组合默认资源组的设置 ， 还一个 就是setting中ldap配置本身有个选项， 根据ldap的组来划分组（这个我还没实验过）

你可能没有理解我的意思：不是所有的人都应该加入默认资源组，应该是每个人有对应的资源组自动关联
