### ISSUE TITLE
[ 功能建议 ]希望能解决inception连接的问题

### ISSUE THREAD

**Issue by N0mansky** [hhyo/Archery#341]
### 目前遇到的问题/使用障碍
目前pymysql连接inception会报`ValueError: invalid literal for int() with base 10: 'Inception2'`错误。每次用docker-compose重启容器都要重新改connection.py文件
### 希望如何解决/实现它
建议在docker-compose文件里面或其他地方把connections.py文件一次性改了

**Comment by hhyo** [comment]
感谢反馈。由于每个用户使用的mysqlclient版本不同，connections.py文件内容亦不同，不便于统一替换

有以下途径可以解决

- 修改docker-compose yaml文件，将connections.py文件映射为宿主机修改后的文件
- 自行修改Inception的源码重新编译，修改时去除Inception前缀
https://github.com/hhyo/inception/blob/github/cmake/mysql_version.cmake#L56
- 直接使用修改后的Inception 
https://github.com/hhyo/inception
