### ISSUE TITLE
[ 问题咨询 ]为什么 test 数据库在数据字典中没有显示出来

### ISSUE THREAD

**Issue by N0mansky** [hhyo/Archery#342]
### 问题描述
我有一个 MySQL 的数据库，里面有一个叫 test 的数据库但是在数据字典中，这个库没有显示出来。这是为什么？还有 information_schema这个数据库也没显示
### 版本信息
 - 应用版本/分支：master
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
https://github.com/hhyo/archery/wiki/faq#%E9%80%89%E6%8B%A9mysql%E5%AE%9E%E4%BE%8B%E5%90%8E%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%95%B0%E6%8D%AE%E5%BA%93

下次提问前查一下文档
