### ISSUE TITLE
[ 问题咨询 ]SQL上线单执行SQL最后返回执行异常，怎么查看异常报错信息？？另外单个SQL有执行时间限制说法吗？

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#344]
### 问题描述
SQL上线单执行SQL最后返回执行异常，怎么查看异常报错信息？？另外单个SQL有执行时间限制说法吗？

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
报错信息应该在界面上就有展示，如果没有，可以用管理员账户到admin区域查看django_Q 的日志

SQL上线工单执行无时间限制

**Comment by benevolence-doctor** [comment]
![image](https://user-images.githubusercontent.com/13461419/61612924-7afb4100-ac92-11e9-923d-3a651f53442e.png)
![image](https://user-images.githubusercontent.com/13461419/61612962-92d2c500-ac92-11e9-84ce-6be0e3cdec48.png)
这两处都没有报错信息

**Comment by benevolence-doctor** [comment]
好的 谢谢
