### ISSUE TITLE
[ 问题咨询 ]update 更新大表的一个SQL语句的时候会分批执行吗？

### ISSUE THREAD

**Issue by benevolence-doctor** [hhyo/Archery#346]
### 问题描述
update 更新一个SQL语句的时候会分批执行吗？
例如：update moment set name='abc' where mytype='ceshi';
对于大表select count(1) from moment where mytype='ceshi';可能上百万
请问update更新时候会拆分成子任务进行更新吗？例如limit 1000更新一次然后sleep 1s继续

### 版本信息
 - 应用版本/分支：Release v1.6.5
 - 部署方式：Docker

**Comment by hhyo** [comment]
不会，目前mysql执行完全依赖inception
