### ISSUE TITLE
[ 问题咨询 ]sql优化里面的差慢日志小时时间是错误的

### ISSUE THREAD

**Issue by WhaleKids** [hhyo/Archery#347]
### 问题描述
sql优化里面->查慢日志 小时时间是错误的

### 版本信息
 - 应用版本/分支：Release v1.5.0

  
 - 部署方式：手工部署

一般建议使用release版本，其他都是非稳定版本
 - 应用版本/分支：Release v1.5.0  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
有截图吗? 有日志吗? 预期是什么? 实际是什么?
