### ISSUE TITLE
[ 问题咨询 ]提交工单

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#348]
您好，

我的项目是使用docker部署的，有几个使用的问题咨询一下。
1. 如何提交一个工单，比如要创建一个表或者update一条数据，通过工单提交给dba，在哪里提交工单呢；
2. 我通过“sql审核”--“sql上线”--“提交sql”的方式，添加完sql、上线单名称、组、实例、数据库，点“sql检测”的时候提示“请配置审批流程”；然后我在“系统管理”--“配置项管理”中选择“工单审核流管理”--“sql上线申请”--“dba”组，无法选择“变更审批流程”，如下图：
![image](https://user-images.githubusercontent.com/48242833/61701153-41006c80-ad70-11e9-8957-4cae67963a23.png)

另外，请问有详细一点的使用文档吗？

**Comment by Myshiner** [comment]
另外，docker部署完之后还需要额外单独配置soar/sqlAdvisor/inception/binlog2sql这些程序吗？

**Comment by LeoQuote** [comment]
首先要配置若干个权限组才可以配置审批流程, 权限组相关详见 https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E6%9D%83%E9%99%90%E7%BB%84 

文档开放编辑, 如果有觉得不好的地方欢迎提出或者直接帮我们修改,

**Comment by Myshiner** [comment]
加上了，但是提示inception检测语句报错，如下图：

是需要修改容器中inception配置吗？

**Comment by LeoQuote** [comment]
我没有看到你的图.

如果方便的话, 请在评论中明示或暗示你已经阅读或查询过我上面提到过的文档, 以便节约彼此的时间.

**Comment by hhyo** [comment]
通读一遍相关文档，可以解决大多数的问题

**Comment by Myshiner** [comment]
嗯，我看了部署配置文档，但是有一些看不太明白，因为我是用docker部署的，docker里面其实已经包含了mysql实例和inception/goinception/mongo而且容器都启着的，但是下面的inception配置项中要怎么配置呢
![image](https://user-images.githubusercontent.com/48242833/61772571-305dfe00-ae25-11e9-859f-5f71e5f4bdc4.png)
其中的INCEPTION_HOST是配置啥？
是否需要启动goincetion？

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E

如后续仍提交文档中已说明的内容，将不会回复，希望理解

**Comment by LeoQuote** [comment]
我更新了安装说明文档, 引导用户在安装完成后阅读配置页.

**Comment by Myshiner** [comment]
嗯，非常感谢，我也在慢慢的探索使用中。
