### ISSUE TITLE
[ 问题咨询 ] sql查询无法查看他人的记录  给了所有的权限也不行

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#349]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支： Release v1.6.5

部署方式：手工部署

出现sql查询必须是管理员才可以查看他人提交的查询记录,哪怕给了所有权限也不行

**Comment by LeoQuote** [comment]
符合预期, 目前只有管理员才能查看他人记录.

**Comment by Lovely-red-scarf** [comment]
> 符合预期, 目前只有管理员才能查看他人记录.

好的   希望以后能加个选项因为有些leader的权限局限在查询,不给管理员权限

**Comment by LeoQuote** [comment]
可以按周给leader 提供报表, 使用archery 的查询功能即可.

也可以直接给我们提pr , 具体代码在 

https://github.com/hhyo/Archery/blob/2a5c06d9c60b3b3f2a720a0393ded3101f70c585/sql/query.py#L199-L204

增加一个权限, 然后在这里更改相应的判断即可.

**Comment by Lovely-red-scarf** [comment]
> 可以按周给leader 提供报表, 使用archery 的查询功能即可.
> 
> 也可以直接给我们提pr , 具体代码在
> 
> https://github.com/hhyo/Archery/blob/2a5c06d9c60b3b3f2a720a0393ded3101f70c585/sql/query.py#L199-L204
> 
> 增加一个权限, 然后在这里更改相应的判断即可.

好的  谢谢了
