### ISSUE TITLE
[ 问题咨询 ] 可否设置未到审批人审批时不让他看到这个工单 ,只有流程到了审批人执行时才能显示工单

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#350]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
可否设置未到审批人审批时不让他看到这个工单 ,只有流程到了审批人执行时才能显示工单

### 版本信息
 - 应用版本/分支：Release v1.6.5
 - 部署方式：手工部署

**Comment by hhyo** [comment]
右上角的待办数据只有用户当前可审批数据

列表数据是用户有权限查看的所有数据，两者不冲突
