### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#351]
### 问题描述
具体咨询下整个平台的组件中，**redis**和**mongodb**的具体功能作用是什么，部署安装说明里面看的不理解，感谢解惑，谢谢！
如果我想对组件中的mysql、redis、mongodb进行数据备份，应该备份吗？该怎么备份？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
redis 做队列和缓存, mongodb 是 Themis使用的, 如果你没有用到就可以不设置

应该对mysql 进行备份,  如果你使用Themis, 那么也应该对mongodb进行备份, redis 不需要备份.

具体备份方式请自行搜索.

**Comment by cnlong** [comment]
好的，感谢！
