### ISSUE TITLE
[ 功能建议 ]修改工单名称

### ISSUE THREAD

**Issue by wximeng** [hhyo/Archery#353]
### 目前遇到的问题/使用障碍
已提交的工单，无法修改工单名称和sql内容，只能重新提交。
### 希望如何解决/实现它
希望只有管理员权限可以修改工单名称或者内容。

**Comment by hhyo** [comment]
有需求可以让管理员通过后台管理修改，或者直接变更数据库

**Comment by wximeng** [comment]
谢谢，已处理
