### ISSUE TITLE
[ 功能建议 ]迫切需要把创建审批工作流以REST API方式开放出来，现有系统直接调用自动生成审批工作流！！！

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#354]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
非常感谢你的建议，这个确实是很好的建议，欢迎直接提pr，或者在这个issue中详细描述如何实现需要哪些资源的api，比如工单的各种哪些动作等

**Comment by LeoQuote** [comment]
@hhyo 感觉一个一个接口api化是很好的想法，在这里可以大概讨论下url设计啥的🤔

工单api应该还好，一周就能完成的样子。

深层次的有一个问题：授权咋做，暂时在header里做token吧？

**Comment by hhyo** [comment]
按照目前的代码，改造应该是不复杂的，不过我这方面没有啥经验，可以先讨论下实现方案和计划

**Comment by dba-ws** [comment]
谢谢作者回复！效率真高。建议参考JIRA issue相关的rest api
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

**Comment by dba-ws** [comment]
暂时需要 工单的创建、修改、状态变更回调（可选）
资源组的CRUD
用户的CRUD
其实就是我写程序拿到mysql的slowlog，调用archery的工作流接口，给到对应业务线的研发做优化，dba确认，形成闭环

**Comment by dba-ws** [comment]
授权问题，可以简单用户jwt  或 参考 钉钉 开放平台的 access_token 
https://open-doc.dingtalk.com/microapp/serverapi2/eev437

**Comment by dbmcp** [comment]
> @hhyo 感觉一个一个接口api化是很好的想法，在这里可以大概讨论下url设计啥的🤔
> 
> 工单api应该还好，一周就能完成的样子。
> 
> 深层次的有一个问题：授权咋做，暂时在header里做token吧？

授权问题，可以简单用户jwt 或 参考 钉钉 开放平台的 access_token
https://open-doc.dingtalk.com/microapp/serverapi2/eev437

**Comment by dbmcp** [comment]
> 按照目前的代码，改造应该是不复杂的，不过我这方面没有啥经验，可以先讨论下实现方案和计划
谢谢作者回复！效率真高。建议参考JIRA issue相关的rest api
https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/
暂时需要 工单的创建、修改、状态变更回调（可选）
资源组的CRUD
用户的CRUD
其实就是我写程序拿到mysql的slowlog，调用archery的工作流接口，给到对应业务线的研发做优化，dba确认，形成闭环

**Comment by yzypals** [comment]
这个  我做了个简单的外部审核功能，可以参考下 。 公司企业微信审核， 可以审核通过。

**Comment by LeoQuote** [comment]
@yzypals 放一下链接吧

**Comment by yzypals** [comment]
https://github.com/yzypals/Archery/commit/529a0bd492d948f0fea3b65d777231a8fe578bfe

这个是给公司做的可能不是很标准

**Comment by Liuzhj** [comment]
我们用swagger管理接口的，不知道用这个行不行。如有不对请忽略 。

**Comment by lkxsoul** [comment]
目前这个issue有进度吗 我也需要审批流这方面的Api，集成现有系统直接调用

**Comment by LeoQuote** [comment]
暂时没有进度, 只是尝试了 新增了个 sql_api 文件夹, 里面放了两个api , version 和 debug.

**Comment by lkxsoul** [comment]
其他模块有开放Api吗，例如 Sql 查询 和  Sql 优化方面

**Comment by LeoQuote** [comment]
没有的, 有兴趣可以直接开pr

**Comment by lkxsoul** [comment]
好的 谢谢您的回复

**Comment by yanchao110020** [comment]
archery 现在的api 接口现在通了吗，迫切需要api 接口文档。有谁做过，求交流求指教 q297428196

**Comment by melice** [comment]
请问下，这个接口化有进度了么

**Comment by Gooooodman** [comment]
是得。 用了 几年了。需要与其他平台打通。需要API 接口进行操作
