### ISSUE TITLE
[ bug ] sql查询->show create table xxxx;不能查询了

### ISSUE THREAD

**Issue by jerryhu1234** [hhyo/Archery#355]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：
可以显示查询结果
实际结果:
Uncaught TypeError: Cannot read property '1' of null
    at display_data ((index):945)
    at Object.success ((index):1083)
    at u (jquery.min.a09e13ee94d5.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.a09e13ee94d5.js:2)
    at k (jquery.min.a09e13ee94d5.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.a09e13ee94d5.js:2)
display_data @ (index):945
success @ (index):1083
u @ jquery.min.a09e13ee94d5.js:2
fireWith @ jquery.min.a09e13ee94d5.js:2
k @ jquery.min.a09e13ee94d5.js:2
(anonymous) @ jquery.min.a09e13ee94d5.js:2
load (async)
send @ jquery.min.a09e13ee94d5.js:2
ajax @ jquery.min.a09e13ee94d5.js:2
sqlquery @ (index):1066
(anonymous) @ (index):902
dispatch @ jquery.min.a09e13ee94d5.js:2
y.handle @ jquery.min.a09e13ee94d5.js:2

### 版本信息
应用版本/分支：
V1.6.6
部署方式：Docker

**Comment by LeoQuote** [comment]
已复现, 复现步骤:

打开查询页面, 随意选择一个数据库, 输入 show create table XXX ,点击查询

后端返回正常, 前端报错:

```
TypeError: result.full_sql.match(...) is nullsqlquery:957:58
    display_data http://139.199.0.191/sqlquery/:957
    success http://139.199.0.191/sqlquery/:1095
    jQuery 4
```

报错的相关源码:

https://github.com/hhyo/Archery/blob/27cab96e73d71bfd273a4bc48e8daa68ddf74a50/sql/templates/sqlquery.html#L794-L796

https://github.com/hhyo/Archery/blob/27cab96e73d71bfd273a4bc48e8daa68ddf74a50/sql/templates/sqlquery.html#L645-L647

**Comment by hhyo** [comment]
不以分号结尾可以查，等下版本修复
