### ISSUE TITLE
[ bug ] Installation fails due to conflicting sqlparse version

### ISSUE THREAD

**Issue by NeolithEra** [hhyo/Archery#356]
Hi, users are unable to run archery due to dependency conflict with _**sqlparse**_ package. 

As shown in the following full dependency graph of archery , archery  requires _**sqlparse==0.3.0**_，while **_mybatis_mapper2sql==0.1.8_** requires _**sqlparse==0.2.4**_.

According to pip’s “first found wins” installation strategy, _**sqlparse==0.3.0**_ is the actually installed version. 
However, the intalled version _**sqlparse==0.3.0**_ does not satisfy the later constraint _**sqlparse==0.2.4**_.

### Dependency tree----
```
Archery(version range:)
| +-aliyun-python-sdk-core(version range:==2.3.5)
| +-aliyun-python-sdk-core-v3(version range:==2.5.3)
| +-aliyun-python-sdk-rds(version range:==2.1.1)
| +-cx-oracle(version range:==7.1.3)
| +-django(version range:==2.0.13)
| +-django-auth-ldap(version range:==2.0.0)
| +-django-q(version range:==1.0.1)
| +-django-redis(version range:==4.10.0)
| +-gunicorn(version range:==19.9.0)
| | +-sphinx(version range:)
| | +-sphinx-rtd-theme(version range:)
| +-moz-sql-parser(version range:==2.44.19084)
| | +-mo-future(version range:>=2.44.19084)
| | +-pyparsing(version range:)
| +-mybatis-mapper2sql(version range:==0.1.8)
| | +-sqlparse(version range:==0.2.4)
| +-mysql-replication(version range:==0.19)
| | +-pymysql(version range:)
| +-mysqlclient(version range:==1.3.13)
| +-psycopg2-binary(version range:==2.8.3)
| +-pycryptodome(version range:==3.8.2)
| +-pyecharts(version range:==0.5.11)
| +-pyecharts-snapshot(version range:==0.1.7)
| +-pymongo(version range:==3.8.0)
| +-pymysql(version range:==0.9.3)
| +-pyodbc(version range:==4.0.26)
| +-python-dateutil(version range:==2.8.0)
| +-requests(version range:==2.21.0)
| +-simplejson(version range:==3.16.0)
| +-sqlparse(version range:==0.3.0)
| +-supervisor(version range:)
| +-wtforms-json(version range:==0.3.3)
| | +-WTForms(version range:>=1.0.5)
| | +-six(version range:>=1.3.0)
| +-wtforms-sqlalchemy(version range:==0.1)
```

Thanks for your help.
Best,
Neolith

### Solution

1.	Fix your direct dependency to be sqlparse==0.2.4. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_mybatis_mapper2sql_** to loose the version range of sqlparse to be >=0.2.4.
3.	Remove your direct dependency **_sqlparse_**, and use the version of **_sqlparse_** transatively introduced by **_mybatis_mapper2sql_**.

Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by NeolithEra** [comment]
@hhyo Could you help me review this issue?

**Comment by LeoQuote** [comment]
Thanks for your detailed solutions, plan 2 would be good. Please submit your pr in that project.

Kinda curious how English speakers use this product, currently there’s just little English translation 😂

**Comment by NeolithEra** [comment]
@LeoQuote Thanks for your quick feedback.
I will request mybatis_mapper2sql to loose sqlparse's version range.

**Comment by NeolithEra** [comment]
@LeoQuote I have submitted a PR in mybatis_mapper2sql.
 BTW, a good practice of managing dependency is that loosing dependency version range to reduce the conflicts from upstream and downstream projects.

**Comment by hhyo** [comment]
@NeolithEra Thank you for your advice, if  loosing dependency version range, there may be compatibility issues, because not all dependent library versions are fully downward compatible
