### ISSUE TITLE
[ bug ]作者您好，ORA-01017: invalid username/password; logon denied     可否把oracle的连接tns串让dba自己填写？别的方式连接没有问题，archery报这个错，因为oracle的这个报错不一定是密码不对，没有tns的方式没办法查哪里有问题，oracle功能用不了呀？求解此bug

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#357]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by dbmcp** [comment]
有个疑问，oracle功能底层用的什么方式连接数据库？tns oracle客户端？还是jdbc的方式？jdbc的方式可能需要注意12c的兼容性问题

**Comment by dbmcp** [comment]
![image](https://user-images.githubusercontent.com/44385881/62124971-3f99eb80-b2fe-11e9-8248-c3904a3ba0b4.png)

**Comment by dbmcp** [comment]
服务器直连、远程plsql、navicat连接，密码都没问题

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/sql/engines/oracle.py oracle相关的代码都在这里，用的是python cx_oracle 库

**Comment by hhyo** [comment]
可以在本地测试使用cx_oracle连接，如果有新的连接方式，可以直接提交pr

**Comment by yzypals** [comment]
我合并到最新代码 也报这个错误了  ，  不知道啥情况啊

**Comment by LeoQuote** [comment]
可能和 #345 有关， @chuancyzhang 帮忙看下

**Comment by yzypals** [comment]
今天我合了到最新代码， 发现 也出现这个报错，但是没动代码，就重启，刷新了几次 ，又能正常连接了 。尴尬

**Comment by hhyo** [comment]
看那次pr没有改涉及连接的地方，应该不影响

**Comment by chuancyzhang** [comment]
上次的修改没有涉及连接的地方，使用的SQL也是只需要select权限。
