### ISSUE TITLE
[ 问题咨询 ]docker部署方式怎么升级

### ISSUE THREAD

**Issue by duge123** [hhyo/Archery#358]
### 版本信息
 - 应用版本/分支：Release v1.6.3
 - 部署方式：Docker部署

只看到文档里写怎么安装，问一下docker部署方式的 怎么升级，求升级文档，谢谢。

**Comment by duge123** [comment]
主要是保留数据库里的数据

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/wiki/%E5%8D%87%E7%BA%A7

**Comment by duge123** [comment]
好的。
