### ISSUE TITLE
[ bug ]merge_alter_table配置后无法检测出多条alter语句未合并

### ISSUE THREAD

**Issue by liyingxiao94** [hhyo/Archery#359]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1、配置merge_alter_table参数值为true，并重启archery服务
2、模拟提交三条未合并的alter语句

### 期待结果和实际结果
期待结果：
审核状态提示alter语句合并的警告

实际结果:
![image](https://user-images.githubusercontent.com/22187621/62200390-e098ad00-b3b7-11e9-93aa-45e185d0463a.png)

### 错误日志
没有错误日志

### 版本信息
应用版本/分支：Release v1.5.3
部署方式：Docker

**Comment by LeoQuote** [comment]
版本? goinception还是inception ?

**Comment by liyingxiao94** [comment]
你好，使用inception审核规则可以生效，使用goinception审核规则无法生效，使用的是archery集成的多个容器的v1.5.3版本
![image](https://user-images.githubusercontent.com/22187621/62204169-3cb2ff80-b3bf-11e9-80fa-343d165b81e6.png)

**Comment by hhyo** [comment]
测试下在演示环境能否复现，复现不了可以考虑更新goinception
在实例管理--参数配置中可以直接动态调整goinception参数
