### ISSUE TITLE
工单执行完毕后发送的邮件中url中没带端口号，通过邮件打不开连接

### ISSUE THREAD

**Issue by eason0420** [hhyo/Archery#36]

**Comment by LeoQuote** [comment]
邮件和钉钉的url是从``request.host``上拿来的, 后期我们会增加一个配置, 让管理员可以填写archery的实际网址.

如果你有相关的修改意见也欢迎你提交 pull request.

现在的临时解决方案的话, 建议你用nginx或者什么转发到80端口, 应该可以解决你的端口问题.

**Comment by hhyo** [comment]
#38 fix
