### ISSUE TITLE
[ bug ]表权限级别赋权 报无权限查询

### ISSUE THREAD

**Issue by duge123** [hhyo/Archery#360]
- 应用版本/分支：Release v1.6.3
 - 部署方式：Docker部署

表申请已审批过
用户权限如下
![image](https://user-images.githubusercontent.com/51983002/62207056-c1088100-b3c5-11e9-95cc-1206a2c93643.png)

查询此表时(select * from xxx.table)，报"你无xxx数据库的查询权限！请先到查询权限管理进行申请"

**Comment by duge123** [comment]
刚测试了，最新版本也不行。

**Comment by hhyo** [comment]
能提供详细的复现步骤最好，很明显按照你的表述复现不了问题，这只有在某些查询场景才会出现

关于表权限检验，这一块的逻辑是这样的
1. 首先使用inception的语法树解析查询语句涉及的库表，同权限列表的信息进行核验，并返回核验结果
2. 如果inception解析查询出错，同时关闭了query_check配置项，将会使用sqlparse解析语句涉及的库，仅检验库权限，而因为用户仅有表权限信息没有库权限，所以会返回用户无库权限的信息
3. 如果inception解析出错，但是开启query_check配置项，将会直接返回错误信息

关于inception语法树解析，一般以下情况会出现异常
1. 查询语句包含mysql关键
2. 包含子查询和嵌套查询

如果还有其他场景欢迎补充

**Comment by duge123** [comment]
那应该是没有开启inception的功能 我去配置下
