### ISSUE TITLE
[ 问题咨询 ]  请问不支持存储过程的上线和查询吗

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#361]
### 问题描述
请问不支持存储过程的上线和查询吗?

### 版本信息
 - 应用版本/分支：Release v1.6.5
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
支持有限 见 https://github.com/hhyo/Archery/issues/246

**Comment by Lovely-red-scarf** [comment]
> 支持有限 见 #246好的  谢谢了
