### ISSUE TITLE
[ 功能建议 ]能否在导出时对超过11位的数据进行处理，防止excel使用科学记数法表示

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#362]
### 目前遇到的问题/使用障碍
目前在导出超过11位数字如身份证信息到excel时，会自动采用科学记数法或者最后几位变成0表示（excel自身特性）
### 希望如何解决/实现它
希望在导出时判断数字是否超过11位，如超过11位自动在数字的左上角增加单引号转换成文本或其他方式转换成文本即可
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
可以参照Navicat的实现方式

**Comment by LeoQuote** [comment]
暂时没什么思路，实际上你想要的是强制转换成文本类型吧。你有没有搜过一些信息呢，我们用的是 https://github.com/wenzhixin/bootstrap-table 的export 插件。你可以稍微看一下有没有什么选项，然后加个参数什么的

**Comment by hhyo** [comment]
依赖三方库的功能不方便直接改，可以使用csv格式替换

**Comment by a5546868001** [comment]
好的，那我可以在查询的时候做拼接，然后在导出吧

**Comment by hhyo** [comment]
可以试试
