### ISSUE TITLE
[ 功能建议 ]建议添加功能能够指定特定实例使用osc工具或者ost工具

### ISSUE THREAD

**Issue by mysqlandy** [hhyo/Archery#365]
### 目前遇到的问题/使用障碍
针对审核平台不完全支持非mysql官方版本，如PXC跟 MariaDB Galera Cluster 使用ost工具做ddl时，会造成集群节点崩溃。

### 希望如何解决/实现它
建议添加功能能够指定特定实例使用osc工具或者ost工具
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
我建议你为非官方mysql 版本新增一个 engine , 继承 MysqlEngine, 然后覆盖其中的某些方法. 
不过这些pt-osc也是goInception实现的, 比较尴尬.恐怕是很难做到了.

如果你想尝试覆盖engine的话, 具体见 https://github.com/hhyo/Archery/tree/master/sql/engines 和开发文档 https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97 

欢迎为本项目完善此处的问题, 提交pr等

**Comment by hhyo** [comment]
这块是goInception控制，虽然可以按照某些实例条件判断，然后在执行前设置关闭或者开启osc，但是这需要做好并发控制，配置多个goinception也许是不错的办法

暂时不考添加，不过欢迎pr
