### ISSUE TITLE
提交sql上线和sql查询优化都需要什么权限？

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#366]
### 问题描述
现在想建一个资源组给普通用户使用，用于提交测试环境中执行sql和sql优化及查询用，请问都需要那些权限呢？如下面的权限怎么选？
![image](https://user-images.githubusercontent.com/48242833/62533868-4aaec780-b87a-11e9-8882-b9d4478d4c83.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
这些权限都自己说的很清楚, 请看完权限列表后, 还有问题的话再提问.

**Comment by hhyo** [comment]
文档有相关内容，针对每个权限的作用描述的很清楚
