### ISSUE TITLE
[ 问题咨询 ]sql查询和到处都限制了 最大是1000条 能扩大权限吗?

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#367]
### 问题描述
请问如何设置sql查询和到处大于1000条?

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
#97

**Comment by Lovely-red-scarf** [comment]
> #97

请问怎么设置一条sql可以对多个数据库执行的呢

**Comment by LeoQuote** [comment]
目前查询不支持，上线支持上线完成后快速提交到其他实例。

请在提问时明示或暗示已读过文档，以避免重复提问。

**Comment by Lovely-red-scarf** [comment]
> 目前查询不支持，上线支持上线完成后快速提交到其他实例。
> 
> 请在提问时明示或暗示已读过文档，以避免重复提问。



> 目前查询不支持，上线支持上线完成后快速提交到其他实例。
> 
> 请在提问时明示或暗示已读过文档，以避免重复提问。

您好 已经熟读过wiki了 也进行操作了  但是没找到怎么上线时候提到多个数据库

**Comment by LeoQuote** [comment]
在上线成功后在工单页面有上线到其他实例按钮， 如 http://139.199.0.191/detail/535/

**Comment by Lovely-red-scarf** [comment]
> 在上线成功后在工单页面有上线到其他实例按钮， 如 http://139.199.0.191/detail/535/

如果上线到其他实例还是需要重新进行审批流程的  可以设置实例选择时候多选实例吗?

**Comment by LeoQuote** [comment]
目前不支持，如果你有想法欢迎另开issue讨论，尽量提供完整的想法，最好直接提交pr，目前这个讨论已经偏离了标题。

**Comment by Lovely-red-scarf** [comment]
> 目前不支持，如果你有想法欢迎另开issue讨论，尽量提供完整的想法，最好直接提交pr，目前这个讨论已经偏离了标题。

好的 辛苦了
