### ISSUE TITLE
[ 功能建议 ]大佬 ,希望下个版本来个上线sql可以支持选择多个实例

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#368]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

如果上线到其他实例还是需要重新进行审批流程的 下个版本可以设置实例选择时候多选实例吗?
因为再使用的时候有多个实例选择的执行一个sql的需求  重复审批导致 不便

**Comment by hhyo** [comment]
暂不考虑分库分表的情况，如果是多环境，还是建议单独审批

相关issue #95

**Comment by Lovely-red-scarf** [comment]
> 暂不考虑分库分表的情况，如果是多环境，还是建议单独审批
> 
> 相关issue #95

好的  感谢大佬
