### ISSUE TITLE
[ 问题咨询 ]如何给用户配置查询所有实例，找不到 query_all_instances

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#369]
### 问题描述
在用户配置中找不到授权选项： query_all_instances
是哪里没升级对嘛?

### 版本信息
 - 应用版本/分支：Release v1.6.6
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
请参照文档 https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E6%9D%83%E9%99%90%E7%BB%84

**Comment by lijie861221** [comment]
找到原因了，是1.5.3升级导1.6的时候脚本漏执行了一个导致的。
