### ISSUE TITLE
mysql_slow_query_review_history表中始终没有数据

### ISSUE THREAD

**Issue by changeyourt** [hhyo/Archery#37]
1、相关配置
#配置archery数据库的连接地址
monitor_db_host="127.0.0.1"
monitor_db_port=3306
monitor_db_user="root"
monitor_db_password="123"
monitor_db_database="archery"

#实例慢日志位置
slowquery_file="/usr/local/mysql/data/slow_query.log"
pt_query_digest="/usr/bin/pt-query-digest"

#实例连接信息
hostname="127.0.0.1:3306" # 和archery实例配置内容保持一致，用于archery做筛选

因为我的archery和数据库在一台服务器上，所以配置信息都写的是本地信息。
实例信息也是写的本地地址。

2、慢日志中的记录
/usr/local/mysql/bin/mysqld, Version: 5.7.24-log (MySQL Community Server (GPL)). started with:
Tcp port: 0  Unix socket: /var/lib/mysql/mysql.sock
Time                 Id Command    Argument
# Time: 2019-01-08T01:50:46.146644Z
# User@Host: root[root] @ localhost []  Id:    59
# Query_time: 10.000529  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
SET timestamp=1546912246;
select sleep(10);
/usr/local/mysql/bin/mysqld, Version: 5.7.24-log (MySQL Community Server (GPL)). started with:
Tcp port: 0  Unix socket: /var/lib/mysql/mysql.sock
Time                 Id Command    Argument
# Time: 2019-01-15T08:40:06.033848Z
# User@Host: root[root] @ localhost []  Id:  2690
# Query_time: 10.000361  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
use archery;
SET timestamp=1547541606;
select sleep(10);
# Time: 2019-01-17T07:46:37.068505Z
# User@Host: root[root] @ localhost []  Id:  3207
# Query_time: 20.000389  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 0
SET timestamp=1547711197;
select sleep(20);

**Comment by changeyourt** [comment]
![image](https://user-images.githubusercontent.com/45409457/51312219-c0417a80-1a85-11e9-9cc2-e958d615793e.png)
![image](https://user-images.githubusercontent.com/45409457/51312266-d51e0e00-1a85-11e9-9aa6-c90693b1bcc8.png)
这一条记录也是费了好大劲才进去的。
![image](https://user-images.githubusercontent.com/45409457/51312349-08609d00-1a86-11e9-9c2c-200b68568665.png)
![image](https://user-images.githubusercontent.com/45409457/51312401-2af2b600-1a86-11e9-83b8-fad2ff4c95c0.png)

**Comment by hhyo** [comment]
请提供pt工具的版本，以及执行脚本时是否有异常信息。同时建议删除时间戳文件重新执行脚本，观察表数据。另外数据表是由pt工具自动创建还是使用项目提供的脚本所创建？

**Comment by changeyourt** [comment]
我的pt-query-digest是3.0.12版本的，执行脚本无任何异常。
已删除时间戳文件，重新执行了脚本，但是两张表中依然没有数据。
另外数据表是用项目提供的sql文件创建的。

**Comment by hhyo** [comment]
这边也无法再提供更多帮助信息，你或许可以尝试设置long_query_time=0，多收集一些日志信息再执行，执行时使用sh -x来查看调试信息

**Comment by 007mawenbin** [comment]
> ![image](https://user-images.githubusercontent.com/45409457/51312219-c0417a80-1a85-11e9-9cc2-e958d615793e.png)
> ![image](https://user-images.githubusercontent.com/45409457/51312266-d51e0e00-1a85-11e9-9aa6-c90693b1bcc8.png)
> 这一条记录也是费了好大劲才进去的。
> ![image](https://user-images.githubusercontent.com/45409457/51312349-08609d00-1a86-11e9-9c2c-200b68568665.png)
> ![image](https://user-images.githubusercontent.com/45409457/51312401-2af2b600-1a86-11e9-83b8-fad2ff4c95c0.png)

你的文件解决了吗？可以帮我看下吗
