### ISSUE TITLE
[ 问题咨询 ]点击sql查询 页面报错

### ISSUE THREAD

**Issue by ligerman33** [hhyo/Archery#370]
### 问题描述
一开始正常的，一段时间后登录点击sql查询页面报错，请问有什么建议吗：
![QQ截图20190807175614](https://user-images.githubusercontent.com/30819702/62613765-b0638800-b93c-11e9-9137-9f290f64de61.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：k8s

日志信息：
![QQ截图20190807175700](https://user-images.githubusercontent.com/30819702/62613799-c709df00-b93c-11e9-86b5-5b87adb0c568.png)

**Comment by hhyo** [comment]
确认版本是Release v1.4.5 ？

k8s会自动拉取最新的镜像创建pod么，alias的字段是在v1.6.6版本引入的

**Comment by ligerman33** [comment]
不好意思，是这个：
![QQ截图20190807180922](https://user-images.githubusercontent.com/30819702/62614758-9fb41180-b93e-11e9-91f8-b1f38c932eb6.png)

**Comment by LeoQuote** [comment]
可以指定 tag 为 v1.4.5 快速修复一下。

**Comment by ligerman33** [comment]
嗯嗯， 我写死了1.6.0 目前好了 最新的版本我在研究下怎么弄，您有什么建议吗

**Comment by LeoQuote** [comment]
参照文档中的升级指南即可。

**Comment by ligerman33** [comment]
> 参照文档中的升级指南即可。

好的，谢谢！
