### ISSUE TITLE
[ 问题咨询 ]大佬上线sql报错:表定义不正确,只能有一个TIMESTAMP字段在DEFAULT或ON UPDATE指定CURRENT_TIMESTAMP.

### ISSUE THREAD

**Issue by Lovely-red-scarf** [hhyo/Archery#371]
### 问题描述
执行上线sql: 表定义不正确,只能有一个TIMESTAMP字段在DEFAULT或ON UPDATE指定CURRENT_TIMESTAMP.
![image](https://user-images.githubusercontent.com/41297612/62619826-4356ef00-b94a-11e9-9b7e-c1c1db24b3e1.png)

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：手工部署

已经读过wiki文档

**Comment by hhyo** [comment]
参考goinception文档
