### ISSUE TITLE
SQL执行问题

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#372]
在执行以下SQL时，archery的审核状态一直为确认中，但是并没有执行，goinception里面也找不到processlist，查看goception日志发现提示解析失败，求助
![image](https://user-images.githubusercontent.com/50727710/62670574-468fc080-b9c6-11e9-9a96-80e5c1a82b17.png)

**Comment by LeoQuote** [comment]
看一下后台log，有可能走到inception那了

**Comment by dmz-leon** [comment]
> 看一下后台登录，有可能走到成立那了

后台看过了，也没有到，我把所有服务重启了一下，貌似正常了，但是在之前我只改动了一个soar的配置文件

**Comment by hhyo** [comment]
faq有相关内容，应该djang-q挂了

**Comment by hhyo** [comment]
目前点执行是先修改工单状态为执行中再添加异步执行任务，后面可以调整为状态由django-q修改，这样就可以确认有没有到执行了

**Comment by dmz-leon** [comment]
> 目前点执行是先修改工单状态为执行中再添加异步执行任务，后面可以调整为状态由django-q修改，这样就可以确认有没有到执行了

archery中怎么查看djang-q状态呢，在archery容器里面通过ps -ef查看是够有这个进程么

**Comment by hhyo** [comment]
#22
#99  
#110 
#156 
#229 
#242 
#276

**Comment by LeoQuote** [comment]
我立了好久的flag, 说要做个info页面,  现在还没做, 忧伤 #216
