### ISSUE TITLE
1.6.5版本的archery，执行完sql后，不生成回滚SQL

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#373]
现在使用的是1.6.5版本的archery，执行完SQL后，不生成回滚SQL，页面报错如下
![image](https://user-images.githubusercontent.com/50727710/62688273-1f071b00-b9fb-11e9-948f-992d37fa12f9.png)

**Comment by hhyo** [comment]
具体可以咨询下goinception的实现，和report相关配置有关系

**Comment by dmz-leon** [comment]
> 具体可以咨询下goinception的实现，和report相关配置有关系

是goinception里面的report配置吗？

**Comment by hhyo** [comment]
https://cloud.tencent.com/info/cc3b45206c925be73cd54e091d52e5d3.html

Failed to register slave; too long 'report-password'

可以看下这个，goinception去dump备份日志时，会伪装成slave，而在slave建立连接过程中，mysql有检测相关信息，确认下实例配置，密码配置过长的原因

**Comment by hhyo** [comment]
mysql相关源码

可以看到密码长度不能超过32

定义
https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/sql/sql_const.h#L153

引用
https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/sql/rpl_slave.cc#L141

判断
https://github.com/mysql/mysql-server/blob/4869291f7ee258e136ef03f5a50135fe7329ffb9/sql/rpl_slave.cc#L3089
