### ISSUE TITLE
sql查询不支持加减运算，报错提示脱敏异常？

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#378]
### 问题描述
执行SQL查询：
```
SELECT
 xxx 
FROM
xxxxxx 
  where end_date >= '2019-08-12'
  AND end_date <= '2019-09-06'
```

正常返回结果

执行SQL查询：
```
SELECT
 xxx - 1
FROM
xxxxxx 
  where end_date >= '2019-08-12'
  AND end_date <= '2019-09-06'
```
报错提示：
```
Error
--
数据脱敏异常：不支持该查询语句脱敏！请联系管理员
```
如果是不支持加减运算，为什么会提示脱敏异常？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
首先，提示没有错误

查询支持加减运算，但是脱敏不支持，如果对脱敏没有强制要求，可在配置中关闭inception检测
也可以直接关闭脱敏功能，就不会走到脱敏判断

相关文档：https://github.com/hhyo/archery/wiki/配置项说明#query_check
