### ISSUE TITLE
[ 问题咨询 ] ImportError: cannot import name 'join_keywords'

### ISSUE THREAD

**Issue by WatchLucky** [hhyo/Archery#382]
### 问题描述
安装过程中 
 /data/venv4archery/bin/python3.6  manage.py makemigrations sql   报错

  File "/data/venv4archery/Archery/sql/utils/sql_utils.py", line 13, in <module>
    from moz_sql_parser.sql_parser import join_keywords, keywords
ImportError: cannot import name 'join_keywords'

但是模块 moz_sql_parser 已经安装 

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
moz_sql_parser版本不一致的原因，需要使用
```
pip install moz_sql_parser==2.44.19084
```
一般不要随意升级或者修改依赖版本，否则会出现兼容问题
