### ISSUE TITLE
[ 问题咨询 ]无法提交赋值语句set @st = '2019-07-01 03:00:00'

### ISSUE THREAD

**Issue by jamene** [hhyo/Archery#383]
### 问题描述
无法使用sql查询或sql上线功能提交set变量赋值语句，请问有没有办法可以提交。
### 版本信息
 - 应用版本/分支：Release vv1.6.6
 - 部署方式：Docker部署

**Comment by jamene** [comment]
set @st = '2019-07-01 03:00:00';
set @ed = '2019-07-02 03:00:00';
像这样的语句提交直接判定失败

**Comment by yzypals** [comment]
这种语句 请找dba 改写，  我们碰到过这种问题 ，是可以改写成可以执行的语法的。

**Comment by hhyo** [comment]
目前不支持
