### ISSUE TITLE
指定了太多索引, 最多允许 3 个.

### ISSUE THREAD

**Issue by SakuraGaara** [hhyo/Archery#386]
### 问题描述
指定了太多索引, 最多允许 3 个.

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

记得mysql官方提供的单表索引不能超过6个，创建索引不能超过3个就自动审核不通过，这个限制怎么调整？

**Comment by LeoQuote** [comment]
这个应该是在goinception 或者inception 中修改, 具体可以参考 inception 和goinception的文档

**Comment by SakuraGaara** [comment]
感谢，goinception 或者inception配置中都有相应的参数
