### ISSUE TITLE
[ 问题咨询 ]慢查询日志可以设置保留周期吗？

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#387]
### 问题描述
请问是否可以设置慢查询日志的保存周期，比如只保留一星期或者半个月的，因为多个实例的话保存周期太长加载会比较慢？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
数据就在那两张表里面，想归档或者删除，写定时任务处理就行
