### ISSUE TITLE
[ 问题咨询 ]可以设置osc的开关吗？

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#388]
### 问题描述
如何设置osc开关，如果大表ddl如加索引或者加字段可能会用到osc

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
osc 是在inception中设置的, 修改inception配置后重启inception即可.

**Comment by Myshiner** [comment]
OK，谢谢
