### ISSUE TITLE
[ 功能建议 ] 希望支持分库分表的上线审核和执行

### ISSUE THREAD

**Issue by yetHandsome** [hhyo/Archery#389]

**Comment by hhyo** [comment]
感谢反馈，暂不考虑分库分表的情况

相关issue #95

**Comment by yetHandsome** [comment]
好的，还是非常感谢，我再看看其它实现方式，要说明一点是，我希望的是同样的sql不用提交多次，提交2次就够了，一键上线哪里可以多选，额，说到底就是支持分库分表审核...还以为你没有理解到我的意思，仔细想想是一个意思，要选多个实例执行无法就是因为分库分表了，就是属于分库分表审核执行

**Comment by yzypals** [comment]
这个需求可以  详细点提吗 ，  我们也是有这个需求，  但是 还没到 去实现的阶段。 后期这个功能肯定是要做的。

**Comment by yzypals** [comment]
@yetHandsome

**Comment by yetHandsome** [comment]
好的，抱歉了，我以为说一键上线多库开发过这个代码的，我一说就知道怎么回事就简单的说了一下，其实现在需求就是我现在进行分库了，有100个一样的库要加字段，如果一键上线哪里能直接选择并执行就很简单了，只要执行2次，一次执行完后再一键上线哪里多选其它库执行，不然我还有一个一个执行，执行100多次
