### ISSUE TITLE
1.2.0升级v1.3.8版本，导入数据前，数据库表结构如何升级？

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#39]
已执行 src/init_sql/ 中的 v1.2.0_1.3.0.sql 、v1.3.0_1.3.2.sql、v1.3.6_v1.3.7.sql 三个脚本。
其中，
1.2.0 db_ops 中 sql_group 对应 1.3.8 的 resource_group，
1.2.0 db_ops 中 sql_group_relations 对应1.3.8 的 resource_group_relations 。
这4张表结构一致，可以对应。

但是仍有5个表对不上，
1.2.0 db_ops 中多2张表： django_apscheduler_djangojob、django_apscheduler_djangojobexecution。
1.3.8 archery 中多3张表：django_q_ormq、django_q_schedule、django_q_task。

麻烦提供一个表结构的升级脚本。

**Comment by hhyo** [comment]
你看的是master的表结构，master是还没发布的1.4.0版本，升级1.3.8就执行你说的那两个脚本就行，使用对应release包

**Comment by think-coding** [comment]
了解，schemasync里面有个bug，我抽空提个代码出来。
