### ISSUE TITLE
[ bug ]提交工单创建视图

### ISSUE THREAD

**Issue by zengyananaaa** [hhyo/Archery#390]
### 重现步骤

1、提交创建视图的工单，审核通过
2、执行成功，但点开工单详情，只有use database_name，没有其他的语句
3、查看回滚语句，没有任何信息

### 期待结果和实际结果
期待结果：成功创建视图

实际结果:数据库无任何变动，视图未建立

### 截图
![image](https://user-images.githubusercontent.com/44013446/63161725-57d66e00-c053-11e9-9bf2-949842f73a11.png)
![image](https://user-images.githubusercontent.com/44013446/63161781-75a3d300-c053-11e9-8d55-6a7634ef7bbd.png)

 
### 错误日志
日志无报错

### 版本信息
应用版本/分支：Release v1.4.2

部署方式：Docker部署

**Comment by hhyo** [comment]
不支持视图、存储过程、函数、变量等工单执行
