### ISSUE TITLE
[ 功能建议 ] 可否增加对Phoenix实例的支持

### ISSUE THREAD

**Issue by KironJ** [hhyo/Archery#394]
### 目前遇到的问题/使用障碍
![image](https://user-images.githubusercontent.com/14542197/63334204-7a2afd00-c36d-11e9-900f-f5e0e9500923.png)

### 希望如何解决/实现它
希望增加对Phoenix实例的支持.

### 其他信息
[FineBI](https://www.finebi.com/)配置页面截图. 
![image](https://user-images.githubusercontent.com/14542197/63334360-d7bf4980-c36d-11e9-9ba9-62938d20bef3.png)

**Comment by LeoQuote** [comment]
暂时没有这方面的开发计划, 但是非常欢迎提交pr.
参照我们的开发者手册 https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97 , 按照这里的说明增加一个 Phoenix 的engine 即可, 无需前端适配.

完整的代码可以参考已经merge 的相关pr  #332  #86

**Comment by KironJ** [comment]
言简意赅, 非常感谢
