### ISSUE TITLE
[ bug ]脱敏字段联合查询失效

### ISSUE THREAD

**Issue by keithyzk** [hhyo/Archery#395]
### 重现步骤

```
select email from  activity_email_all_in_one ;
```
![image](https://user-images.githubusercontent.com/20945633/63571369-91a6f780-c5b2-11e9-9694-26b9ba485259.png)

```
select id from test union select email from  activity_email_all_in_one ;
```
![image](https://user-images.githubusercontent.com/20945633/63571499-f7937f00-c5b2-11e9-9415-961fceb13856.png)

```
[2019-08-23 14:30:09,382][MainThread:139779947976512][task_id:default][tasks.py:31][DEBUG]- 删除task：query-1566541808.8708951
DEBUG:default:删除task：query-1566541808.8708951
[2019-08-23 14:30:55,345][MainThread:139779947976512][task_id:default][tasks.py:31][DEBUG]- 删除task：query-1566541854.9246702
DEBUG:default:删除task：query-1566541854.9246702
```
-->
### 版本信息
应用版本/分支：
master
部署方式：Docker

**Comment by hhyo** [comment]
感谢反馈，经验证Inception不支持union语法的解析，解析出的语法树只包含第一条语句信息，导致未命中脱敏规则

现在因为没有完全替代Inception解析，无法兼容此语法，故在脱敏方法中增加了 union&union all 关键字判断，遇到联合查询会返回 **不支持该查询语句脱敏！** 如果系统设置开启查询校验，将会直接驳回，避免数据泄露。

**Comment by hhyo** [comment]
相关问题将会在 #145 中持续跟进
