### ISSUE TITLE
[ 反馈收集 ] 关于精简系统模块

### ISSUE THREAD

**Issue by hhyo** [hhyo/Archery#397]
目前Archery集成的工具平台比较多，部署相对复杂，为了降低部署复杂度，同时聚焦核心功能，会逐步弃用一些使用频率较低的模块，将会在此issues中跟踪反馈，欢迎补充和建议

- [x] 数据库审核（Themis）模块
Themis是前期整合的宜信的数据库审核平台，目前主要用于MySQL的元数据对象分析，慢日志分析，通过整体反馈来看使用频率较低，并且模块相对独立，有一套自己的系统逻辑，比如打分等，维护成本比较高，可考虑使用soar覆盖相关功能
- [ ] Binlog2SQL 模块
Binlog2SQL是将开源项目binlog2sql前台化，但该模块存在一定的效率问题和兼容性问题（基本不再维护），日常使用效率不高，可考虑依靠python-mysql-replication，围绕binlog解析作一些自定义开发

**Comment by LeoQuote** [comment]
themis我是不怎么用...不知道别的怎么样，要是真用的不多可以删掉，或者拿出来做为另一个应用

binlog2sql 可以暂时留着感觉，可以加个banner不建议使用

**Comment by uiwe** [comment]
目前没有找到操作文档，或者一个流程图，我现在花了2个小时在摸索如何使用。期望有使用手册或者流程图，指导使用。

**Comment by LeoQuote** [comment]
@uiwe 有手册, readme 就有文档链接, 看过了吗, 没有流程图, wiki 开放编辑, 欢迎给我们添加, 

这个和本主题不相关, 下次请单开issue

**Comment by jackiesre721** [comment]
Themis 和 SchemaSync 基本用不到

**Comment by zwunix** [comment]
审核引擎有些语句备份不了的。binlog2sql刚好可以作为拯救的一种方式。

**Comment by zwunix** [comment]
Themis也很常用。很多数据模型可以用来审核。

**Comment by zwunix** [comment]
SchemaSync 可以处理生产、灰度、测试、开发等各环境的模型对比需求。

**Comment by zwunix** [comment]
有点好奇，为什么你们会用不到。

**Comment by hhyo** [comment]
Themis会在下个版本移除，其他模块暂时不做改动

**Comment by LeoQuote** [comment]
@zwunix 移除主要的原因还是Themis没人能维护，而且和系统的其他应用完全没有交集，ui也是单独一套。移除后你还是可以单独部署一套themis的，完全没有影响。

**Comment by firstfsx** [comment]
确实没用到过themis ，那么问题来了1.7 啥时候发？

**Comment by yuandajn578** [comment]
@hhyo @LeoQuote 
binlog挖掘是十分重要的功能啊，这个功能不能阉割掉啊，具体用binlog2sql 还是 binlog_rollback 或python-mysql-replication，无所谓，只要稳定、高效即可。谢谢大神们。

**Comment by yuandajn578** [comment]
@hhyo @LeoQuote 
大神，SchemaSync 生成的对比脚本，有时无法直接通过审核引擎的检测，比较麻烦。另外，如果能在SchemaSync 生成的对比脚本页面增加“提交工单”功能，直接提交生成的脚本，就更好了。

**Comment by hhyo** [comment]
> @hhyo @LeoQuote
> 大神，SchemaSync 生成的对比脚本，有时无法直接通过审核引擎的检测，比较麻烦。另外，如果能在SchemaSync 生成的对比脚本页面增加“提交工单”功能，直接提交生成的脚本，就更好了。

主要是外键控制不能支持审核，对比结果一键提交确实是好想法，现在SchemaSync已经作为内部依赖，后续功能可以逐步完善
