### ISSUE TITLE
[ 功能建议 ] 资源组粒度的查询权限控制

### ISSUE THREAD

**Issue by zhanshenwan** [hhyo/Archery#398]
### 目前遇到的问题/使用障碍
用户查询实例无法做到粒度权限控制
### 希望如何解决/实现它
能否增加用户查询功能实现粒度权限控制，不是所有实例可看，也不需要重复针对实例申请查询权限。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
麻烦详细描述"粒度权限控制"的意思.

**Comment by zhanshenwan** [comment]
就是现在用户所属的实例，默认没有查询权限，也没有开关控制，查询数据库权限都需要申请，要么就是开放全部实例查询的权限，希望可以增加类似提交权限的粒度实例那样的。

**Comment by hhyo** [comment]
其实需求和 #340 有关联
