### ISSUE TITLE
[ 问题咨询 ]在线查询null值显示为 -，有些字段值本身为 - 。

### ISSUE THREAD

**Issue by dengpixiong** [hhyo/Archery#401]
### 问题描述
在线查询null值显示为 -，有些字段值本身为 -，无法直接判断字段值，SQL导出及数据导出时 null 值也为 -，不好整理，null 值是否可以显示为空？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
有些字段也本身会是空值，这里是需要优化下，要看表格组件有没有相关配置

**Comment by hhyo** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/3319

有属性data-undefined-text可以设置这个，现在有两个选择

1. 和navicat一样设置为`(NULL)`，这样查询时可以区分是为NULL还是字符串null，但是导出同样不好处理
2. 设置为空，导出处理方便，但是前端查询无法区分

**Comment by LeoQuote** [comment]
(NULL) 就挺好的

**Comment by dengpixiong** [comment]
2.设置为空，导出处理方便 ，我觉的这个设置好一点，字符串 null很少见。

**Comment by dengpixiong** [comment]
在生产中数据导出的需求会很多，而字符串 null很少见，所以我赞成：2.设置为空，导出处理方便。

**Comment by hhyo** [comment]
@dengpixiong 如果设置为空串，和本身是空串的值也存在混淆

还有目前导出实际上不是一个核心和可用的功能，在数据量稍大的情况就会出现浏览器假死，只有后续增加服务端异步导出才能解决这个问题

如果侧重于查询功能完善的话，个人更偏向于使用第一种，同时置灰显示，一看就能区分是null还是not null

导出时可以使用ifnull()来转换，不过就用不了脱敏了，也是比较尴尬

**Comment by hhyo** [comment]
```
select null,null,'null','NULL',''空 limit 100;
```
![image](https://user-images.githubusercontent.com/8842982/65384745-6dc50600-dd58-11e9-804a-7f5255ceecb1.png)
