### ISSUE TITLE
[ 问题咨询 ] SQL查询申请返回行数

### ISSUE THREAD

**Issue by gdsea** [hhyo/Archery#404]
### 问题描述
申请数据库查询权限时，只能选择100,500,1000，这个返回结果集的行数可以手动输入吗？
我想限制为10行

### 版本信息
 - 应用版本/分支：Release v1.6.6
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
目前不能, 是很好的一个功能, 已加入todo

欢迎直接提pr
