### ISSUE TITLE
[ 问题咨询 ] 慢日志不显示

### ISSUE THREAD

**Issue by gdsea** [hhyo/Archery#405]
### 问题描述
web端不显示慢日志，慢日志统计和慢日志明细界面均没有找到匹配的记录。

### 版本信息
 - 应用版本/分支：Release v1.6.6
 - 部署方式：Docker

以下是我的具体配置信息
1、archery库中mysql_slow_query_review_history中已经有数据了，下面是其中一条。
mysql> select * from mysql_slow_query_review_history limit 1\G;
*************************** 1. row ***************************
id: 10
hostname_max: 192.168.1.132:8013
client_max: 192.168.1.132
user_max: pmm
db_max: NULL
checksum: 6E905E29D0B3D1EA1A2193E75E153007
sample: SELECT EVENT_NAME, COUNT_STAR, SUM_TIMER_WAIT
FROM performance_schema.events_waits_summary_global_by_event_name
ts_min: 2019-07-10 19:26:52.000000
ts_max: 2019-08-24 13:16:00.000000

2、检查实例列表
下面是实例列表中的host、port分别为192.168.1.132，8013

3、脚本配置
以下是脚本配置中的实例连接信息
hostname="192.168.1.132:8013" # 和archery实例配置内容保持一致，用于archery做筛选

**Comment by dengpixiong** [comment]
资源组，实例，日期有没有选对？三个检查一下。

**Comment by LeoQuote** [comment]
数据已经进去了, 我猜测是你时间没选对? 你再调整一下时间.

**Comment by gdsea** [comment]
您好，的确是时间范围有问题，非常感谢

**Comment by mawenbin666** [comment]
> 资源组，实例，日期有没有选对？三个检查一下。

您好，我的情况跟楼主一样，
问题描述
web端不显示慢日志，慢日志统计和慢日志明细界面均没有找到匹配的记录，日期范围也扩大到1个月内，但是在数据库mysql_slow_query_review和mysql_slow_query_review_history均有数据。

版本信息
应用版本/分支：Release v1.7.4
部署方式：Docker

1、检查实例列表
下面是实例列表中的host、port分别为192.168.234.14 ,3306

2、脚本配置
以下是脚本配置中的实例连接信息
hostname="192.168.234.14:3306" # 和archery实例配置内容保持一致，用于archery做筛选

**Comment by hhyo** [comment]
修改配置 https://github.com/hhyo/Archery/blob/master/src/docker-compose/archery/settings.py#L233
重启服务，可查看日志打印的SQL语句，到数据库查询确认哪里的数据有缺失
