### ISSUE TITLE
[ 问题咨询 ]sql查询历史导出只能导出当页的记录不能导出全部的记录

### ISSUE THREAD

**Issue by jamene** [hhyo/Archery#407]
### 问题描述
sql查询历史导出成文件，只能导出当前页的记录不能导出全部的记录，有没有办法可以导出所有记录？

### 版本信息
 - 应用版本/分支：Release v1.6.6 
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
不支持全量导出

**Comment by LeoQuote** [comment]
你可以把archery自己的數據庫接入進來用查詢功能查詢導出
