### ISSUE TITLE
[ 问题咨询 ]SQL上线邮件里提示 工单地址：http://127.0.0.1:8000/workflow/59，这个能修改不？

### ISSUE THREAD

**Issue by dengpixiong** [hhyo/Archery#411]
### 问题描述
SQL上线邮件里提示工单地址：工单地址：http://127.0.0.1:8000/workflow/59，这个能修改不？这个不是真实的服务器IP和端口

### 版本信息
 - 应用版本/分支：Release v1.6.6  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
修改这里的配置项就可以 https://github.com/hhyo/Archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#archery_base_url
