### ISSUE TITLE
数据库审核里，发布任务测试，点击查看任何报错如下

### ISSUE THREAD

**Issue by trsenzhang** [hhyo/Archery#412]
![图片](https://user-images.githubusercontent.com/25219083/63919739-edb9c200-ca71-11e9-8d03-4861d93459c5.png)

**Comment by LeoQuote** [comment]
Themis 不建议使用了, 可能后期版本会下掉, 详见 #397 
这个很有可能是你没配置好mongo

**Comment by trsenzhang** [comment]
tks
