### ISSUE TITLE
[ bug ] 1.6.7 用户管理，无法添加用户

### ISSUE THREAD

**Issue by jerryhu1234** [hhyo/Archery#413]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1.6.7 用户管理，无法添加用户，并且选择实例时，遮罩了下拉菜单

**Comment by LeoQuote** [comment]
![图片](https://user-images.githubusercontent.com/4143818/64006301-a2241880-cb44-11e9-9577-2504849ae589.png)

firefox 已复现 @hhyo 有空开个pr解决一下吧

**Comment by hhyo** [comment]
添加用户是todo功能，还没实现  #23
覆盖那个，所有表格没有数据库的下拉框都是这样的情况，包括SQL工单列表的筛选，目前没找到办法处理

**Comment by LeoQuote** [comment]
这个我好像有经验，重开一下我把样式看能不能修一下，footer应该无条件在最底。
