### ISSUE TITLE
[ bug ]查询字段类型是 datetime(6) 时，未显示毫秒数

### ISSUE THREAD

**Issue by jerryhu1234** [hhyo/Archery#414]
desc visitor表;
....
createtime datetime(6);
....
select createtime from visitor;
期望显示结果:
2019-08-30 12:00:00.123456
实际显示结果：
2019-08-30 12:00:00

**Comment by LeoQuote** [comment]
https://github.com/PyMySQL/PyMySQL/blob/383c0438fe74464ad65b9850bd13f310de7a878e/pymysql/converters.py#L147 

看pymysql源码似乎显示应该是正常的，你可以在demo上复现，然后给一个查询语句吗？

主页的demo链接走正常上线流程就可以建表查语句。

**Comment by jerryhu1234** [comment]
已在demo创建visitor表，
实例archery-> schema  arhery_test
select * from visitor;

**Comment by LeoQuote** [comment]
看到返回的消息里确实是有些问题, 不带后面的ms 
```
{"status": 0, "msg": "ok", "data": {"full_sql": "select * from visitor limit 10;", "is_execute": false, "checked": null, "is_masked": false, "query_time": 0.00225, "mask_rule_hit": false, "mask_time": 0.013299, "warning": null, "error": null, "is_critical": false, "rows": [[1, "2019-08-30 12:12:13"]], "column_list": ["id", "createtime"], "status": null, "affected_rows": 1, "seconds_behind_master": null}}
```

**Comment by hhyo** [comment]
json序列化的原因，修改下这个序列化方法
https://github.com/hhyo/Archery/blob/master/common/utils/extend_json_encoder.py#L15

return o.isoformat(' ') 即可，下版本修复
