### ISSUE TITLE
[ 问题咨询 ]在线查询收藏SQL并起别名后，在收藏里看不到别名

### ISSUE THREAD

**Issue by dengpixiong** [hhyo/Archery#416]
### 问题描述
在线查询收藏SQL并起别名后，在收藏里看不到别名

### 版本信息
 - 应用版本/分支：Release v1.6.6  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
这个是设计如此，每个用户收藏的语句不会特别多，在列表增加一列显示意义不大，添加后可以在上面的常用查询看到，或者使用第二个筛选项来筛选
