### ISSUE TITLE
[ 问题咨询 ] 端口安全问题

### ISSUE THREAD

**Issue by gdsea** [hhyo/Archery#423]
### 问题描述
目前采用作者推荐的docker部署以后，所有端口都走tcp6了，centos7防火墙无法对tcp6进行限制，所有端口都暴露在外面，很容易被攻击，这个问题，大家是怎么处理的？

### 版本信息
 - 应用版本/分支：Release v1.6.6
 - 部署方式：Docker
 - 操作系统：CentOS 7.5

**Comment by gdsea** [comment]
[root@databak ~]# netstat -nultp
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:6479            0.0.0.0:*               LISTEN      1353/redis-server 0 
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      796/rpcbind         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1339/sshd           
tcp6       0      0 :::4000                 :::*                    LISTEN      1862/docker-proxy   
tcp6       0      0 :::9123                 :::*                    LISTEN      1896/docker-proxy   
tcp6       0      0 :::33060                :::*                    LISTEN      1347/mysqld         
tcp6       0      0 :::27017                :::*                    LISTEN      1911/docker-proxy   
tcp6       0      0 :::8010                 :::*                    LISTEN      1347/mysqld         
tcp6       0      0 :::6379                 :::*                    LISTEN      1878/docker-proxy   
tcp6       0      0 :::6669                 :::*                    LISTEN      1846/docker-proxy   
tcp6       0      0 :::111                  :::*                    LISTEN      796/rpcbind         
tcp6       0      0 :::22                   :::*                    LISTEN      1339/sshd

**Comment by gdsea** [comment]
禁用ipv6以后，再次查看
[root@databak ~]# netstat -nultp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      1897/docker-proxy   
tcp        0      0 0.0.0.0:9123            0.0.0.0:*               LISTEN      1986/docker-proxy   
tcp        0      0 0.0.0.0:33060           0.0.0.0:*               LISTEN      1325/mysqld         
tcp        0      0 0.0.0.0:27017           0.0.0.0:*               LISTEN      1961/docker-proxy   
tcp        0      0 0.0.0.0:8010            0.0.0.0:*               LISTEN      1325/mysqld         
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      1940/docker-proxy   
tcp        0      0 0.0.0.0:6669            0.0.0.0:*               LISTEN      1915/docker-proxy   
tcp        0      0 0.0.0.0:6479            0.0.0.0:*               LISTEN      1332/redis-server 0 

但是有个问题，我没有对外开放9123端口，然后在外网使用server服务器的公网ip可以正常访问。

**Comment by LeoQuote** [comment]
emmm这个和archery无关，麻烦自行查阅docker和centos ipv6 的相关资料。

**Comment by LeoQuote** [comment]
后续不再暴露不必要的端口, 详见 #425 #424
