### ISSUE TITLE
[紧急：redis存在木马安全问题，生产数据库被删 ]

### ISSUE THREAD

**Issue by st1266** [hhyo/Archery#424]
docker安装archery
版本 1.6.5

在redis的docker中，/data/路径下qytu.so文件，存在root提权操作，通过脚本修改ssh信任，免密登录服务器。
我们安装archery的服务器还运行其他线上业务，在9月2日早8点30分被删掉线上数据库！
![image](https://user-images.githubusercontent.com/52566924/64148978-4f55a400-ce57-11e9-820e-75f433811cac.png)

![image](https://user-images.githubusercontent.com/52566924/64149173-d014a000-ce57-11e9-820f-3d5aefd1eabb.png)

**Comment by LeoQuote** [comment]
感谢反馈! 是redis 提权的问题吗?

**Comment by LeoQuote** [comment]
应该是docker运行的redis 实例对外暴露了端口的问题. 参见 : https://help.aliyun.com/knowledge_detail/37433.html

实在抱歉, archery 可能只考虑到了有防火墙, iptables , 并且只在内网运行的环境, 这种公网运行的场景确实没有考虑到.

我已经提了相关的pr , 在docker-compose 中不再暴露除web程序外的所有程序到主机.

另外安全这方面还是建议遵循最佳实践, 对于有外网IP的机器, 仅对外开放 80, 443 端口, 22 等其他端口只能从内部访问.

对于archery 这类存有重要信息的服务(虽然是加密过的账号密码依然还是有一定风险), 可以开启更加严格的限制比如在nginx 或iptables 上增加 ip限制, 都是可以增强安全防范的有效方法.

**Comment by hhyo** [comment]
很抱歉，示例和文档中没有对相关风险进行提示和说明，可参考@LeoQuote 的回复做好基础的安全措施

Archery也会在相关方面进行改进
