### ISSUE TITLE
[ 问题咨询 ]inception结合数据库中间件用会选错库名。

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#426]
部署方式为docker部署，v1.6.5

我的审核工具是inception，实例连接中配置的实例是sharding-proxy数据库中间件代理的代理IP和用户名密码，实例连接测试都OK，可以联通，但是提交DML工单的时候，比如我选择的是neworiental_okay_platform，sql是insert into test_aa(id, uname) values(3, 'cmoa');但是执行的时候会报Table 'okay_m2m.test_aa' doesn't exist，也就是说它实际执行的库不是我们选的库，这种情况只在DML的时候出现，DDL没问题。
见截图
![image](https://user-images.githubusercontent.com/48242833/64231349-fe5eb200-cf21-11e9-8b22-8a2b679bf8bb.png)

**Comment by hhyo** [comment]
可给goinc项目提交issue

**Comment by yuandajn578** [comment]
@Myshiner 
建议先检查数据库参数 lower_case_table_names 值是否为1

**Comment by Myshiner** [comment]
lower_case_table_names 就是1，不区分大小写啊
