### ISSUE TITLE
[ 问题咨询 ]如果inception和goinception都开启了，系统默认会选哪个作为审核工具？

### ISSUE THREAD

**Issue by Myshiner** [hhyo/Archery#427]
### 问题描述
我在系统设置那里开启了goinception选项，连接也成功的，但是审核工单会走inception还是goinception呢，需要禁止inception吗？怎么禁止inception呢？
### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
参考：https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#go_inception

**Comment by Myshiner** [comment]
好的，看到了
启用goInception后会替换Inception，备份库的配置地址是复用的，将会使用goInception来替代Inception对MySQL进行审核和执行，Inception仅用于查询表权限校验和数据脱敏

谢谢您！
