### ISSUE TITLE
[ 问题咨询 ]V1.6.7 升级 V1.7.0

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#433]
### 问题描述
你好，我是2019.09.06首次安装的最新master分支版本，登录后页面显示版本号为1.6.7
按照升级步骤，执行/opt/archery/src/init_sql/v1.6.7_v1.7.0.sql后重新执行 docker-compose -f docker-compose.yml up -d启动服务，页面显示版本号仍然为1.6.7。
![image](https://user-images.githubusercontent.com/54062997/64467156-79a1ad00-d148-11e9-98ca-176a9922ab46.png)

### 版本信息
 - 应用版本/分支：Release v1.6.7  
 - 部署方式：Docker

**Comment by hhyo** [comment]
1.7.0还未发布，目前最新版本是1.6.7，正式发布版本以release信息为准
