### ISSUE TITLE
[ 问题咨询 ]请问V1.6.7版本，在线查询支持限制查询导出功能吗？

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#434]
### 问题描述
请问V1.6.7版本，在线查询支持限制查询导出功能吗？因为有些数据比较敏感，只有查看，不能导出。

### 版本信息
 - 应用版本/分支：Release v1.6.7
 - 部署方式：Docker

**Comment by hhyo** [comment]
允许查询后限制导出其实是一个伪需求

同时还需要限制复制、截图、录屏、拍照

还要对返回的数据做结构化处理，防止请求截取

才能增加一丢丢获取数据的操作复杂度，不划算

敏感数据可以强制开启脱敏，不过目前这是一个有限的功能，不支持所有查询，参考#145

**Comment by yzypals** [comment]
@yuandajn578 
这个 你去修改下  前端页面
![image](https://user-images.githubusercontent.com/35222142/64600825-61eb5280-d3ee-11e9-91eb-3431a91e5d77.png)
大概715左右  上下会有偏差 你找找
![image](https://user-images.githubusercontent.com/35222142/64600641-19cc3000-d3ee-11e9-8acf-a3d24996b506.png)
 true 改成 false    
我们公司 也有这个需求 ，   我是改了这里  把这个按钮隐藏掉了

**Comment by yuandajn578** [comment]
@yzypals 多谢多谢。
