### ISSUE TITLE
[ 问题咨询 ]版本升级后无法提交工单

### ISSUE THREAD

**Issue by zengyananaaa** [hhyo/Archery#435]
### 问题描述
之前使用的是1.4.2的版本，今天升级到1.6.7版本后，提交工单点击“SQL检测”之后，系统就没有反应了，“美化”“SQL检测”“SQL提交”按钮就都无法点击了。
![image](https://user-images.githubusercontent.com/44013446/64472757-cf507680-d195-11e9-8dc1-bc7e63277682.png)
查看日志也没有报错，请问这是什么原因呢？

### 版本信息
 - 应用版本/分支：Release v1.6.7  
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
日志有输出么，参考FAQ查看日志

同时可访问debug接口获取系统信息，类似
http://139.199.0.191/api/debug

提交相关信息注意数据隐私

**Comment by zengyananaaa** [comment]
我尝试着清了一下浏览器的缓存就可以正常使用了，谢谢啦。
建议可以把清缓存这一条写到升级的文档里面哈。

**Comment by hhyo** [comment]
升级文档有清理缓存的说明

实际上1.6.1以后使用nginx部署，关闭debug就不会有缓存的问题

**Comment by zengyananaaa** [comment]
您好，请问1.6.7的版本在提交工单的时候没有是否选择备份这一项了，怎么设置不备份呢？
因为我们使用的实例大部分都是阿里云的rds，没有权限，默认选择备份的话就没法执行工单了，我只在配置项里看到有是否备份的选项，但是那个现在是off的状态

**Comment by hhyo** [comment]
配置开启备份选项就好

**Comment by zengyananaaa** [comment]
我想要在前端页面改一下，把这个备份框的默认值改为不备份，然后再把这个备份框隐藏起来，请问是改哪个前端的页面/路径文件呢？我之前大概找了一下，没找到🤦🏻‍♀️

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/master/sql/sql_workflow.py#L195

直接改入库的地方最方便，设置值为False

前端隐藏设置关闭那个选项配置就可以

**Comment by zengyananaaa** [comment]
好的，太感谢啦🙏🙏

**Comment by LeoQuote** [comment]
emmm没想到还有这样的需求...默认不显示备份按钮，默认不备份....

**Comment by hhyo** [comment]
rds如果binlog格式不为row，执行会失败，没法备份
