### ISSUE TITLE
V1.6.7版本：请问如何连接docker方式部署的容器内的mysql实例？

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#436]
### 问题描述
V1.6.7版本：请问如何用mysql命令行连接docker方式部署的容器内的mysql实例？
谢谢。

**Comment by LeoQuote** [comment]
如果有外部程序需要直接和内部的mysql 实例交互，答案是不可以。

如果你只是想进到 mysql 命令行内进行一些简单操作， 可以使用 cd src
/docker-compose && docker-compose -f docker-compose.yml exec mysql bash  进入docker mysql 实例的终端，然后再使用 mysql 命令进入 mysql 命令行。

参见文档： https://docs.docker.com/compose/reference/exec/

**Comment by hhyo** [comment]
如果决定用docker部署的话，可以多了解一下相关操作

**Comment by yuandajn578** [comment]
好的，多谢两位大神

**Comment by yuandajn578** [comment]
@LeoQuote 
你好，我想指定workdir进入容器后执行升级脚本：
docker-compose -f docker-compose.yml exec -w /opt/archery/src/init_sql  mysql bash
但是不识别 -w 参数，请教登录mysql实例后，如何 source 宿主机路径下的sql文件呢？
非常感谢。

**Comment by LeoQuote** [comment]
可以用 docker cp 把宿主机的文件 预先cp 进 容器, 然后使用exec 执行

此类问题和docker 相关, 麻烦自行搜索学习或者寻求docker 社群更专业的帮助.

**Comment by yuandajn578** [comment]
感谢。
