### ISSUE TITLE
[ 功能建议 ] 增加一个helm chart ，使用helm 部署到k8s

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#437]
### 目前遇到的问题/使用障碍
docker-compose 是挺快，小规模部署完全没问题，不过好多公司都已经用上了k8s，使用helm可以快速在k8s上部署，并且还有内置的ingress可以用。
### 希望如何解决/实现它
加上一个helm chart
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by yzypals** [comment]
这个 我有空整一个

**Comment by jerryhu1234** [comment]
我写了一个初版

**Comment by LeoQuote** [comment]
如果方便的话请直接提pr

**Comment by jerryhu1234** [comment]
刚已提交。

**Comment by hhyo** [comment]
#467
