### ISSUE TITLE
建议新增功能

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#44]
1.增加DML和DDL页面。
由于 inception 在同一个命令中不能同时执行 DDL 和 DML，由于开发提交SQL非常随意，且页面上没有提示，所以在执行时会出现备份异常或者工单不执行的问题，望从页面上进行区分。

2.增加工单号功能，并区分DDL和 DML 工单。
目前工单名称需要手动填写，开发人员填写名称各有各的风格，不便于和开发沟通过程中对工单的描述及工单的管理、指派。

3.增加自动派单功能。
DBA有多人时，对SQL 审批轮流分配给 DBA组（或指定组）中的成员并优先提醒他，分配方式采用轮转或者根据值班设置分配给指定人员（如周一 09:00~周二 08:59 A值班，周二09:00~ 周三 08:59 B值班）。

**Comment by tom2jack** [comment]
支持Oracle么？

**Comment by LeoQuote** [comment]
@zhaizhifen 目前不支持oracle ，但是目前数据库底层操作已经抽象成了引擎，可以增加相关代码后支持，欢迎修改代码之后提交pr。

另外和本issue无关的事情请新开issue，以免混乱。
