### ISSUE TITLE
[ 功能建议 ] 增加一个新增慢日志的接口

### ISSUE THREAD

**Issue by LeoQuote** [hhyo/Archery#440]
### 目前遇到的问题/使用障碍
慢日志目前用的是mysql直连的方式写入，这就必须要暴露mysql的连接端口，不算特别必要，可以增加一个接口在网页端添加慢日志

### 希望如何解决/实现它
增加一个慢日志接口，添加慢日志。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
这个先关闭~
