### ISSUE TITLE
[ 功能建议 ]慢查日志统计及明细页面能否支持排序及导出功能？

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#441]
### 目前遇到的问题/使用障碍
慢查日志统计及明细页面，目前无法按条件【如：执行总次数|执行时长(95%) | 执行总时长(秒) | 锁定总时长(秒)  | 执行总时长(秒) | 平均执行时长(秒) | 扫描总行数 | 返回总行数】排序，也无法导出为文件。
### 希望如何解决/实现它
建议可以按条件【如：执行总次数|执行时长(95%) | 执行总时长(秒) | 锁定总时长(秒)  | 执行总时长(秒) | 平均执行时长(秒) | 扫描总行数 | 返回总行数】排序，并且可以导出为CSV/TXT等格式的文件
### 其他信息
V1.6.7

**Comment by hhyo** [comment]
慢日志模块暂时不考虑改动(主要是懒)，但是其中有很多可以深挖的功能，欢迎提交pr

**Comment by hhyo** [comment]
#312

新增前端导出：https://github.com/hhyo/Archery/commit/66b39c0f32a2e7697882a7ab3c326c277401b6e8

可在演示环境体验
