### ISSUE TITLE
[ bug ]SQL上线脚本提交7000条SQL，报MYSQL SERVER HAS GONE AWAY

### ISSUE THREAD

**Issue by dengpixiong** [hhyo/Archery#444]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：

实际结果:

### 截图
![图片](https://user-images.githubusercontent.com/54564831/64578820-21221800-d3b3-11e9-91c3-66e157e5e21f.png)

 
### 版本信息
应用版本/分支：v1.6.6

部署方式：Docker

**Comment by hhyo** [comment]
加大Archery MySQL实例的max_allowed_packet值
