### ISSUE TITLE
[ 功能建议 ]增加钉钉@功能

### ISSUE THREAD

**Issue by sh-hanson** [hhyo/Archery#445]
### 目前遇到的问题/使用障碍
钉钉群比较多，使用的人也较多，很多时候提交的工单没有@功能，就被其它消息给淹没了，得不到及时审批。需要人为再通知，比较麻烦

### 希望如何解决/实现它
在用户表中增加手机号码字段，保存注册用户的手机号，使用钉钉@功能

### 其他信息
无

**Comment by LeoQuote** [comment]
我们正在尝试做通知到单个用户的功能，加@ 可能也会考虑。

暂时建议单独建一个工单群并把所有人禁言。

**Comment by sh-hanson** [comment]
工单群我们已经创建了，没禁言，但是平时正常也不会在这个群里交流。
目前的问题是主管一般群比较多，开会比较多，没有@功能，主管看到的只是很多群有新消息，但是跟自己有没有关系就不知道了，可能就忽略了
如果加上@功能，在有新消息的很多群之中，一看就知道跟自己有关的事情需要去处理，这样才能起到审批提醒的效果

**Comment by hhyo** [comment]
@sh-hanson 钉钉通知到个人的PR已经合并，手工部署master分支进行测试，不过master是非稳定版，最终功能以release版本为准

**Comment by sh-hanson** [comment]
好的，这几天我测试一下，感谢

**Comment by sh-hanson** [comment]
> @sh-hanson 钉钉通知到个人的PR已经合并，手工部署master分支进行测试，不过master是非稳定版，最终功能以release版本为准

好的，这几天我测试一下，感谢

**Comment by hhyo** [comment]
很抱歉，暂不考虑通过手机号@的方式，微应用的方式已在本地验证通过。只需要让管理员创建一个应用提供相关信息即可，具体操作文档可能不够完善，如果配置通过可帮忙完善文档，感谢
