### ISSUE TITLE
[ bug ]只申请table级别权限，查询报无权限

### ISSUE THREAD

**Issue by jy3792397** [hhyo/Archery#446]
### 重现步骤
现有库aaa，已申请aaa库下面的表bbb的查询权限 bbb表有 name、code字段，以下两种情况会报错你无aaa数据库的查询权限！请先到查询权限管理进行申请

1. select `code` ,`name` from bbb ，怀疑是关键字的问题，查其他字段就不会报错 比如 select `qwer` from bbb ，select * 也不会报错

类似该issue https://github.com/hhyo/Archery/issues/134

2.嵌套查询 
select * from (select `qwer` from bbb ) t

重新申请aaa库database级别的权限上面两种情况都不会报错

### 版本信息
 - 应用版本/分支：Release v1.6.7  
 - 部署方式：Docke

**Comment by hhyo** [comment]
感谢反馈

可参考 #145 以及FAQ中关于SQL查询检验的部分

提示没有库权限是因为关闭了强制校验，当表权限校验失效时会去判断库权限，避免越权查询
可以开启强制校验或者查看日志文件查看inception返回的信息，比如关闭关键字审核配置就可以正常检验

总之表权限和脱敏目前是有限的功能，不能覆盖全部场景
