### ISSUE TITLE
[ 功能建议 ] 增加数据库备份功能和恢复功能

### ISSUE THREAD

**Issue by shaowin16** [hhyo/Archery#448]
### 系统能通过界面进行数据库备份和恢复
用的最多目前主要是mysql

**Comment by LeoQuote** [comment]
没明白什么意思，有没有链接和截图呢？

**Comment by shaowin16** [comment]
> 没明白什么意思，有没有链接和截图呢？

我的意思是，现在已经有了sql审核，数据库的实例管理了，那么在真实的企业当中，很多时候，一个版本确定之后，上线执行新版本的sql之前，会先对实例中数据库的数据或者表结构进行备份，然后再真实执行工单中的sql，是否会考虑支持这个功能呢？

**Comment by hhyo** [comment]
mysql工单在执行前已经有相关备份操作，具体可以在演示环境测试。
