### ISSUE TITLE
[ bug ]设置了人工审核，但不通过

### ISSUE THREAD

**Issue by SakuraGaara** [hhyo/Archery#451]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

类似这样的语句
`ALTER TABLE  yy_exception
  CHANGE `exception_type` `exception_type` INT(11) UNSIGNED DEFAULT 0  NOT NULL  COMMENT '分类（1:上级评估 2:公司评估 3:个人评估）';`
在修改字段时，使用的alter字段，但是检测为：
类型转换警告: 列 'yy_exception.exception_type' tinyint(3) unsigned -> int(11).

希望能够进行人工审核
在SQL上线配置中已经添加了^alter的关键字，但是还是走的自动审核，希望能够人工审核

### 期待结果和实际结果
期待结果：
期待能人工审核

实际结果:
自动审核不通过

**Comment by LeoQuote** [comment]
此类警告请自行按照 goinception 的文档修改 goinception 的配置. 如果goinception 不支持这个配置, 请在goinception 的项目页提交issue 或pr. 

参考链接:

* goinception 文档 https://hanchuanchuan.github.io/goInception/
* goinception 项目地址 https://github.com/hanchuanchuan/goInception

**Comment by hhyo** [comment]
自动驳回的配置参考：https://github.com/hhyo/archery/wiki/配置项说明#auto_review_wrong

此配置与自动审核无关，符合条件的都会按照配置驳回

只有通过该驳回检测的工单才会进入到自动审核判断，也就是说自动审核只会处理非自动驳回的工单，判断是否需要人工审批
