### ISSUE TITLE
[ bug ]慢日志监控脚本执行异常后更新了last_analysis_time

### ISSUE THREAD

**Issue by liuxinwang** [hhyo/Archery#454]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1. 执行analysis_slow_query.sh
2. 若pt_query_digest执行异常，比如ip配置错误
3. last_analysis_time文件被更新

### 期待结果和实际结果
期待结果：
如果pt_query_digest执行异常，last_analysis_time文件不更新
实际结果:
pt_query_digest执行异常，last_analysis_time文件写入了当前时间
改进建议:
增加异常检测，如果上一步执行成功，更新last_analysis_time，否则不更新
if [ $? -ne 0 ]; then
    echo "failed"
else
    echo `date +"%Y-%m-%d %H:%M:%S"`>last_analysis_time_$hostname
fi
### 版本信息
应用版本/分支：v1.6.7

部署方式：Docker、手工部署
Docker

**Comment by LeoQuote** [comment]
感谢你的反馈, 看到你已经提出了脚本修改建议, 可以直接提pr 我们来看看.
