### ISSUE TITLE
REMOTE_BACKUP error in Using GoInception 

### ISSUE THREAD

**Issue by richard2017** [hhyo/Archery#455]
I use GoInception ,and test connection ,it is ok ,and i also set REMOTE_BACKUP_HOST,
REMOTE_BACKUP_PORT,,REMOTE_BACKUP_USER,REMOTE_BACKUP_PASSWORD.
But when i use SQL 上线，执行，然后报错
“Invalid remote backup information.”

**Comment by LeoQuote** [comment]
请按模板提问, 按照模板提供必须的信息.

You must use the issue templete to open a valid issue.
