### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by richard2017** [hhyo/Archery#456]
### 问题描述
I use GoInception ,and test connection ,it is ok ,and i also set REMOTE_BACKUP_HOST,
REMOTE_BACKUP_PORT,,REMOTE_BACKUP_USER,REMOTE_BACKUP_PASSWORD.
But when i use SQL 上线，执行，然后报错
“Invalid remote backup information.”

### 版本信息
 - 应用版本/分支：Release v1.6.7
 - 部署方式：手工部署

**Comment by hhyo** [comment]
#455

**Comment by hhyo** [comment]
检查goInception本身的备份库配置是否正确，参考
https://github.com/hhyo/Archery/blob/master/src/docker-compose/inception/config.toml#L66
