### ISSUE TITLE
[ bug ] 系统库因屏蔽，还可以查询

### ISSUE THREAD

**Issue by jerryhu1234** [hhyo/Archery#459]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
在【 sql查询】中，可以用以下sql查询到系统库下的表如：
select * from information_schma.tables where table_name = 'meiqia';
看是否去掉不让查询，还是就这样了。

在sql查询中，虽然选择了库，但使用如库.表名，在同一个schema中，一样可以查询到其他库的数据。
看是否需要改进？
### 版本信息
应用版本/分支：
V1.6.7
部署方式：Docker

**Comment by hhyo** [comment]
非管理员查询会提示没有库权限，可以测试验证一下
