### ISSUE TITLE
无法加载数据库实例列表

### ISSUE THREAD

**Issue by zeusYi** [hhyo/Archery#46]
<img width="624" alt="wx20190131-185239 2x" src="https://user-images.githubusercontent.com/22519964/52049796-a6c22780-2589-11e9-8a24-2f8df0332b7c.png">

无法加载数据库实例列表

**Comment by LeoQuote** [comment]
我们很愿意帮你解决问题，但是请按模版发issue，提供问题重现步骤，系统配置，后台日志等，这样有利于我们帮你定位问题。

另外请在提问前通读我们很短但是很有用的文档，可以节约彼此的时间。

**Comment by zeusYi** [comment]
能否加下我的微信远程帮我看下 wx: y1394315612

**Comment by zeusYi** [comment]
> 我们很愿意帮你解决问题，但是请按模版发issue，提供问题重现步骤，系统配置，后台日志等，这样有利于我们帮你定位问题。
> 
> 另外请在提问前通读我们很短但是很有用的文档，可以节约彼此的时间。

很紧急大佬，远程帮我看下吧

**Comment by hhyo** [comment]
FAQ内有解答
