### ISSUE TITLE
[ 问题反馈 ]Archery/src/docker-compose/目录的CI检查失败

### ISSUE THREAD

**Issue by Jonnyan404** [hhyo/Archery#464]
### 目前遇到的问题/使用障碍
我不知道是否有影响！！！
### 希望如何解决/实现它
希望可以检查一下。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
![image](https://user-images.githubusercontent.com/20352705/65845908-9196d600-e36e-11e9-9316-5dcb5d4c8a96.png)

**Comment by hhyo** [comment]
三方的加密组件存在字符集的问题，目前是使用docker-buld-test的分支构建的镜像上传的，已经本地测试验证过

**Comment by LeoQuote** [comment]
并不是这个目录CI检查失败, 而是8天前的一次提交检查失败, 请以master 和需要部署的release 为准

**Comment by Jonnyan404** [comment]
> 并不是这个目录CI检查失败, 而是8天前的一次提交检查失败, 请以master 和需要部署的release 为准

好的
