### ISSUE TITLE
[ 问题咨询 ]docker版本的*限制未起作用？

### ISSUE THREAD

**Issue by Jonnyan404** [hhyo/Archery#468]
### 问题描述
SQL查询操作（我连接的是mssql），*这个限制并未起作用。
只需要对 `select * from xxx` 进行美化一下或者执行
```
select top 100
  *
from
  xxx
```
即可跳过限制。
### 版本信息
 - 应用版本/分支：Release v1.7.0
 - 部署方式：Docker

**Comment by hhyo** [comment]
回过来看这个正则貌似没有问题，能匹配到格式化后的语句，等搭建mssql环境再做验证
https://github.com/hhyo/Archery/blob/1b1b1e56801120e9af2f9dbe770727825b0eca26/sql/engines/mssql.py#L81

**Comment by Jonnyan404** [comment]
> 回过来看这个正则貌似没有问题，能匹配到格式化后的语句，等搭建mssql环境再做验证
> https://github.com/hhyo/Archery/blob/1b1b1e56801120e9af2f9dbe770727825b0eca26/sql/engines/mssql.py#L81
但实际上，我确实通过美化或者手动输入，即可跳过。
而且，可以忽略掉系统设置项（即系统设置是否开启，对此都没有影响）。

**Comment by hhyo** [comment]
很抱歉最近才找到环境验证，临时修改正则即可 `star_patter = r"(^|,|\s)\*(\s|\(|$)"`

代码将合并至下个版本
