### ISSUE TITLE
[ 问题咨询 ]添加阿里云认证信息报错

### ISSUE THREAD

**Issue by sun642514265** [hhyo/Archery#469]
### 问题描述
添加阿里云认证信息AccessKeyID + AccessKeySecret，点击保存后，直接报错：Server Error（500）

### 版本信息
 - 应用版本/分支：Release v1.7.0
 - 部署方式：Docker

**Comment by hhyo** [comment]
请参考文档提供日志信息

**Comment by sun642514265** [comment]
找到问题原因了，是因为archery数据库中aliyun_access_key表中的 ak和secret字段类型长度太小导致的，

alter table aliyun_access_key modify column ak varchar(200) not null;

**Comment by sun642514265** [comment]
alter table aliyun_access_key modify column secret varchar(200) not null;
