### ISSUE TITLE
[ 问题咨询 ]max_execution_time的参数设置没有生效，MySQL实例是阿里云的RDS

### ISSUE THREAD

**Issue by jess0018** [hhyo/Archery#470]
### 问题描述
max_execution_time的参数设置没有生效，MySQL实例是阿里云的RDS

### 版本信息
 - 应用版本/分支：Release v1.6.7 
 - 部署方式：Docker

**Comment by hhyo** [comment]
请升级到v1.7.0，该版本已解决此问题

**Comment by jess0018** [comment]
了解了，多谢。
能否告知一下具体的问题原因？

**Comment by hhyo** [comment]
可参考https://github.com/hhyo/Archery/commit/0299c04794970de5d5867ab025efc8437a5a70a7 获取同步延迟的部分，在v1.6.7版本中调整了查询时获取同步延迟的时间(可翻阅release note)，放到执行语句前，但是获取同步延迟操作后默认会关闭链接，等真正执行查询语句时会自动重新创建连接，导致在查询前添加的异步kill任务kill的是上一个线程id，具体应该可以在日志文件中找到错误日志，提示找不到该线程

简单修改获取同步延迟方法，使其保持连接就可以了

**Comment by hhyo** [comment]
关联PR #125 #302，可了解具体实现思路

**Comment by jess0018** [comment]
好的，非常感谢
