### ISSUE TITLE
[ 问题咨询 ]查询脱敏功能报错

### ISSUE THREAD

**Issue by tigerbin** [hhyo/Archery#471]
### 问题描述
查询脱敏功能报错

### 版本信息
 - 应用版本/分支：Release v1.7
 - 部署方式：Docker、手工部署

![image](https://user-images.githubusercontent.com/13775090/66635205-3d7ad400-ec41-11e9-9e9c-2fbb548ea801.png)

上线sql 功能用的是goInception,查询sql功能是必须要用Inception?

goInception 报错信息 session_inception.go:418: [error] con:4 解析失败! near '/*--user=root;--password=123456;--host=192.168.1.200' at line 1

[2019-10-10 15:27:20,612][MainThread:139640179046144][task_id:default][data_masking.py:37][WARNING]- 数据脱敏异常，错误信息：Traceback (most recent call last):
  File "/opt/Archery/sql/utils/data_masking.py", line 32, in data_masking
    query_tree = inception_engine.query_print(instance=instance, db_name=db_name, sql=sql)
  File "/opt/Archery/sql/engines/inception.py", line 179, in query_print
    if print_info['errlevel'] == 0 and print_info['errmsg'] == 'None':
KeyError: 'errlevel'

**Comment by hhyo** [comment]
查询脱敏和表权限校验依赖Inception的语法解析，相关配置的地方也有说明

**Comment by tigerbin** [comment]
> 查询脱敏和表权限校验依赖Inception的语法解析，相关配置的地方也有说明

你的意思是既需要配置Inception，又需要配置goInception?Inception还是必配的？

**Comment by tigerbin** [comment]
看到最新的说明了。。。close the topic
