### ISSUE TITLE
[ 问题咨询 ]升级1.7.0 后使用SQL优化工具提示配置异常

### ISSUE THREAD

**Issue by firstfsx** [hhyo/Archery#476]
### 问题描述
升级1.7.0 后使用sql 优化工具时 提示： 请配置SQLAdvisor路径！ / 请配置soar_path和test_dsn！
之前 1.6.5 一切正常 ，已尝试清空库配置重新录入，问题依旧。
烦请协助提供解决思路，感谢

参数配置
SQLADVISOR_PATH  /opt/archery/src/plugins/sqladvisor
SOAR_PATH  /opt/archery/src/plugins/soar
SOAR_TEST_DSN    user:pwd@ip:port

### 版本信息
 - 应用版本/分支：Release v1.7.0 
 - 部署方式：Docker

**Comment by hhyo** [comment]
可访问debug接口查看返回的配置信息是否正常
参考：http://139.199.0.191/api/debug
如果不正常可尝试在系统配置界面重新保存，清除redis缓存，v1.7.0使用加密工具对系统配置数据进行了加密，建议升级后重新保存配置

**Comment by firstfsx** [comment]
系统配置界面重新保存过，sql_config表对应的加密字段也清除重新保存过。
debug 接口界面：

Request Method: | GET
-- | --
http://ip:9123/api/debug
2.0.13
ResponseError
MOVED 10617 10.200.73.14:6381
/opt/venv4archery/lib/python3.6/site-packages/redis/connection.py in read_response, line 717
/opt/venv4archery/bin/python3
3.6.5
['/opt/archery',  '/opt/venv4archery/bin',  '/opt/venv4archery/lib/python36.zip',  '/opt/venv4archery/lib/python3.6',  '/opt/venv4archery/lib/python3.6/lib-dynload',  '/usr/local/python3/lib/python3.6',  '/opt/venv4archery/lib/python3.6/site-packages']

**Comment by firstfsx** [comment]
# 附缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://ip:6381/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": ""
        }
    },
    "dingding": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://ip:6381/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": ""
        }
    }
}

**Comment by LeoQuote** [comment]
1.7.0 开始redis 默认开启了密码, 麻烦检查一下相关配置?

**Comment by firstfsx** [comment]
> 1.7.0 开始redis 默认开启了密码, 麻烦检查一下相关配置?

意思是必须要设置密码？目前密码是留空的

**Comment by LeoQuote** [comment]
程序里没有强制要求redis 有密码, 但是新版的docker-compose 中为redis 设置的密码, 建议修改settings.py 中的密码, 和docker-compose 的密码对应上.

**Comment by hhyo** [comment]
日志文件内应该有Redis连接报错的日志吧，调整配置重启服务，django_q应该也启动失败了

**Comment by firstfsx** [comment]
> 日志文件内应该有Redis连接报错的日志吧，调整配置重启服务，django_q应该也启动失败了

drano_q 是正常的  其他模块都正常  唯独sql 优化异常

**Comment by hhyo** [comment]
麻烦提供错误日志，这是最有助于定位问题的东西，/api/debug 500了，会记录堆栈日志

**Comment by firstfsx** [comment]
> 麻烦提供错误日志，这是最有助于定位问题的东西，/api/debug 500了，会记录堆栈日志

容器日志及debug 页面请见附件
[log.zip](https://github.com/hhyo/Archery/files/3720321/log.zip)

**Comment by hhyo** [comment]
`django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MOVED 4252 `

搜索相关错误，猜测是默认的client_class是不支持连接集群导致，参考：https://blog.csdn.net/chinacmt/article/details/52858018

在 set key 时报错，所有用到系统配置的地方应该都是不可用的，可尝试提交SQL上线检测试试

可尝试使用Redis集群客户端的配置方式看看
https://django-redis-chs.readthedocs.io/zh_CN/latest/#id23
```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.HerdClient",
        }
    }
}
```

**Comment by firstfsx** [comment]
更换本地redis 后已解决。非常感谢

**Comment by axiaochen** [comment]
麻烦问下这个配置是在哪个配置文件上修改的，
参数配置
SQLADVISOR_PATH /opt/archery/src/plugins/sqladvisor
SOAR_PATH /opt/archery/src/plugins/soar
SOAR_TEST_DSN user:pwd@ip:port****
