### ISSUE TITLE
[ bug ] v1.7.0数据库升级脚本执行报错

### ISSUE THREAD

**Issue by TingRuDeng** [hhyo/Archery#477]
### 重现步骤

执行sql升级脚本v1.6.7_v1.7.0.sql

### 期待结果和实际结果
实际结果:
失败，报错 ERROR 1048 (23000) at line 7: Column 'content_type_id' cannot be null

### 版本信息
应用版本/分支：Release v1.7.0

部署方式：Docker

### 本人解决方案
我在升级脚本里加了set @content_type_id=(select id from django_content_type where app_label='sql' and model='permission');

**Comment by hhyo** [comment]
#463
感谢反馈，release包确实有这个问题，已经修复并且在release note进行了特别说明

**Comment by LeoQuote** [comment]
@hhyo 要不发个1.7.1 的新版?

**Comment by hhyo** [comment]
@LeoQuote 可以
