### ISSUE TITLE
[ bug ]V1.7.0 实例管理-会话管理页面导出的会话列表SQL语句不完整

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#479]
### 重现步骤

![image](https://user-images.githubusercontent.com/54062997/67073035-c56c5b00-f1b8-11e9-9ac1-1e647267d6f2.png)

### 期待结果和实际结果
期待结果：
SQL语句完整
实际结果:
SQL语句不完整
### 截图
![image](https://user-images.githubusercontent.com/54062997/67073152-02385200-f1b9-11e9-9d01-800b5323b259.png)

### 版本信息
应用版本/分支：1.7.0

部署方式：Docker

**Comment by yuandajn578** [comment]
@hhyo 大神，这个BUG已经修复了吗？

**Comment by hhyo** [comment]
对，可以查看fix的commit记录，导出时先选择显示完整INFO

**Comment by yuandajn578** [comment]
多谢大神，辛苦了！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小圈圈 <notifications@github.com&gt;
发送时间: 2019年10月20日 10:16
收件人: hhyo/Archery <Archery@noreply.github.com&gt;
抄送: yuandajn578 <12173670@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hhyo/Archery] [ bug ]V1.7.0 实例管理-会话管理页面导出的会话列表SQL语句不完整 (#479)
