### ISSUE TITLE
RDS的python api更新了，获取RDS慢查询有问题了

### ISSUE THREAD

**Issue by sky1006** [hhyo/Archery#48]
aliyun_rds.py

    for SlowLog in sql_slow_log:
        SlowLog['SQLHASH'] = str(SlowLog['SQLHASH'])
        SlowLog['CreateTime'] = Aliyun.aliyun_time_format(SlowLog['CreateTime'])

**Comment by hhyo** [comment]
依赖sdk的版本不升级也无法使用？不过现在我没有rds实例无法测试验证，欢迎帮修改下提交pr⭐

**Comment by sky1006** [comment]
依赖的sdk 不升级也无法使用
