### ISSUE TITLE
[ 功能建议 ]慢查日志页面，建议增加自定义排序、过滤筛选功能

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#482]
### 目前遇到的问题/使用障碍
慢查日志页面，无法自定义排序，也无法过滤筛选相应的慢SQL，
### 希望如何解决/实现它
慢查日志页面，建议增加自定义排序、过滤筛选功能，方便按需查看慢SQL，十分感谢！

**Comment by hhyo** [comment]
已增加模糊搜索，排序和过滤暂不考虑增加
