### ISSUE TITLE
[ 问题咨询 ]sql查询 -> 在线查询 ： 设置 MAX(最大限制行数) 后点击查询，提示如下报错  "页面提交参数可能为空"

### ISSUE THREAD

**Issue by eqieyiran** [hhyo/Archery#484]
### 问题描述
sql查询 -> 在线查询 ： 设置 MAX(最大限制行数) 后点击查询，提示如下报错

Error
--
页面提交参数可能为空

设置：
ADMIN_QUERY_LIMIT=10000

### 版本信息
 - 应用版本/分支：Release v1.4 
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
可以提供一下后台日志吗？ 后台可能会有traceback什么的

**Comment by hhyo** [comment]
#151

升级新版就好

**Comment by eqieyiran** [comment]
我用下面的命令查询日志，在执行查询操作的过程中 日志没有变化

# 日志查看和问题排查
docker logs archery -f --tail=50
