### ISSUE TITLE
[ bug ]慢查日志统计与明细页面导出的SQL语句不完整

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#485]
### 期待结果和实际结果
期待结果：
导出完整的SQL语句
实际结果:
统计页面导出结果：
![image](https://user-images.githubusercontent.com/54062997/67191151-bc32f680-f423-11e9-9f26-3b859243a3b4.png)

明细页面导出结果：
![image](https://user-images.githubusercontent.com/54062997/67191705-a96cf180-f424-11e9-8bc5-240f706e851c.png)

### 版本信息
应用版本/分支 v1.7.0/master：

部署方式：Docker

**Comment by yuandajn578** [comment]
@LeoQuote @hhyo 
两位大神，这个BUG与会话管理页面无法导出完整info内容，是一个类型的。
受累了。

**Comment by hhyo** [comment]
不知道你是否愿意尝试贡献代码？上个issue中修改代码的commit记录应该很明确，大致看下应该就知道如何修改

感谢你提出的各类建议，如果能参与贡献最好不过

**Comment by yuandajn578** [comment]
我是DBA，对开发不太熟悉，我先看看上个issue中修改代码的commit记录吧，争取尽快熟悉咱们的代码，最终可能还是需要大神们修复。

**Comment by yuandajn578** [comment]
@hhyo 
我参考上个issue中修改代码的commit记录，修改了本地的对应文件，然后重启了archery容器，但是会话管理页面导出的结果中未包含完整Info列，是不是我的修改有误呢？
![image](https://user-images.githubusercontent.com/54062997/67193886-a8d65a00-f428-11e9-9d03-0f379e085d00.png)

**Comment by hhyo** [comment]
![image](https://user-images.githubusercontent.com/8842982/67197471-6e23f000-f42f-11e9-82d1-a13628437e6f.png)

先选择再导出

**Comment by yuandajn578** [comment]
好的，我正在从重新从源码build 镜像，多谢多谢。

**Comment by yuandajn578** [comment]
> 如果是用docker的话是需要重新从源码build 镜像的.

大神，我本地修改HTML源码之后，尝试重新从本地的源码build 镜像，一直没成功，还请大神不吝赐教具体的build镜像步骤。多谢了。

**Comment by hhyo** [comment]
@yuandajn578 目前没有将基础镜像独立出来，由于集成组件多，在线build会很慢，国内网络不好还会超时

如果没有依赖变更的话，可以将镜像内的工程目录映射到本地，具体操作可以自行检索

**Comment by yuandajn578** [comment]
多谢了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小圈圈 <notifications@github.com&gt;
发送时间: 2019年10月22日 19:40
收件人: hhyo/Archery <Archery@noreply.github.com&gt;
抄送: yuandajn578 <12173670@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[hhyo/Archery] [ bug ]慢查日志统计与明细页面导出的SQL语句不完整 (#485)




@yuandajn578 目前没有将基础镜像独立出来，由于集成组件多，在线build会很慢，国内网络不好还会超时
 
如果没有依赖变更的话，可以将镜像内的工程目录映射到本地，具体操作可以自行检索
