### ISSUE TITLE
查询的导出 如果值是null 的情况下，导出成sql 还有页面显示都是"-",还有导出的sql不带表名

### ISSUE THREAD

**Issue by yetHandsome** [hhyo/Archery#487]
查询的时候如果值是null 的情况下，导出成sql 还有页面显示都是"-",还有导出的sql不带表名
![image](https://user-images.githubusercontent.com/35953746/67387836-38673e80-f5ca-11e9-8414-1b31a8d872b4.png)

**Comment by LeoQuote** [comment]
请按模板提供 版本和自己的期望.
