### ISSUE TITLE
[ bug ]  V1.3.7跟1.3.8 有一个查询显示问题，跟导出成sql 文件无非正确展示null问题

### ISSUE THREAD

**Issue by yetHandsome** [hhyo/Archery#488]
### 重现步骤
查询功能

查询一个带 null 结果的数据

从 /query/ 接口返回结果来看，能正确返回 null 值
![image](https://user-images.githubusercontent.com/35953746/67389035-5fbf0b00-f5cc-11e9-988a-8635ca0a5128.png)

但是页面显示成 - ,比如下图中 idx 字段

![image](https://user-images.githubusercontent.com/35953746/67388789-e58e8680-f5cb-11e9-82e8-2140c1ea61ce.png)

### 期待结果和实际结果
期待结果：
希望无论是页面还是，导出成sql 的文件都能正确显示null ,否则导出的数据无非正确再次使用

还希望能正确显示表名（这个之前自己弄过非常麻烦放弃了）
实际结果:

![image](https://user-images.githubusercontent.com/35953746/67389194-b1679580-f5cc-11e9-89d1-37e7262c7d4d.png)

 
### 错误日志

无
### 版本信息
应用版本/分支：
V1.3.7跟1.3.8
部署方式：Docker

**Comment by LeoQuote** [comment]
最新版本是1.7.0，请升级到最新版本后重试，这个问题在之前的更新中已修复。

**Comment by hhyo** [comment]
不带表名这个没法处理，因为还有语句构建的临时表，导出后就手动替换一个表名，并没有多麻烦

**Comment by yetHandsome** [comment]
好的，谢谢各位大佬，我看看最新版

**Comment by hhyo** [comment]
#401

**Comment by yuandajn578** [comment]
> 最新版本是1.7.0，请升级到最新版本后重试，这个问题在之前的更新中已修复。

大神，我用的V1.7.0导出结果集为SQL文件，结果字段中的NULL值在文件中变成了'(null)'，导致无法正常导入数据库中，尤其是无法导入数值型的字段，报错，无法转换。

**Comment by LeoQuote** [comment]
设计是这样的，符合预期，麻烦自行处理一下。
