### ISSUE TITLE
[ 问题咨询 ]MongoDB实例的连接信息怎么配置

### ISSUE THREAD

**Issue by jess0018** [hhyo/Archery#490]
### 问题描述
MongoDB实例的连接信息怎么配置？我用是阿里云的MongoDB；填了连接地址：
mongodb://root:****@dds-XXX.mongodb.rds.aliyuncs.com:3717,dds-XXX.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-xxxxxxxx
或
dds-xxx.mongodb.rds.aliyuncs.com
都提示连接失败

### 版本信息
 - 应用版本/分支：Release v1.7.0  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
请提供详细的报错日志. 

另外建议查询阿里云的文档, 搞清楚阿里云mongo 对调用的限制.

**Comment by jess0018** [comment]
确认了，用root账号可以连接；普通只授权一个库的账号报Authentication failed.错误。

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/4a09cb191a9b9be1303e0d5026c7d76ccb12270d/sql/engines/mongo.py#L17 具体连接的逻辑在这里。

**Comment by hhyo** [comment]
#582
