### ISSUE TITLE
权限管理和上线申请中的审批备注全部为空，无法显示

### ISSUE THREAD

**Issue by withmi** [hhyo/Archery#493]
我自己docker搭建的archery，审批的时候可以填入备注，但是审批后，回去看备注无法找到，为空。我看github上提供的平台，我也没找到有审批完的流程中有备注信息。
![image](https://user-images.githubusercontent.com/20091748/67564253-31206c00-f755-11e9-879f-462aba3e1eaf.png)
![image](https://user-images.githubusercontent.com/20091748/67564273-37164d00-f755-11e9-83b5-d3af94854a5e.png)
![image](https://user-images.githubusercontent.com/20091748/67564290-3c739780-f755-11e9-982e-a08ac463a919.png)

**Comment by hhyo** [comment]
目前权限申请工单审批通过的备注不会记录，仅在通知中显示，上线工单是有记录的，审批驳回的备注都会记录

其实你可以在演示环境测试一下的，看了几个都没有是因为大家本来就没填写
http://139.199.0.191/detail/685/

**Comment by withmi** [comment]
谢谢，明白了。
还有问题，我按照流程配置了goInception，开启了QUERY_CHECK，用另外一个号申请了查询权限流程，出现一个无法验证语句权限错误。麻烦指导下。
![01](https://user-images.githubusercontent.com/20091748/67568366-9af14380-f75e-11e9-8041-352289543c9f.png)
![02](https://user-images.githubusercontent.com/20091748/67568369-9dec3400-f75e-11e9-984a-9e58d7367e2e.png)
![03](https://user-images.githubusercontent.com/20091748/67568374-a0e72480-f75e-11e9-92d0-5e3fc9bdfbd8.png)
![04](https://user-images.githubusercontent.com/20091748/67568375-a2b0e800-f75e-11e9-8284-b67a52fb9134.png)
有没有交流群呢?

**Comment by hhyo** [comment]
你的截图中就有答案
