### ISSUE TITLE
[ 功能建议 ]SQL上线支持MongoDB

### ISSUE THREAD

**Issue by jess0018** [hhyo/Archery#494]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

![image](https://user-images.githubusercontent.com/9248376/68001706-31ae8a80-fca0-11e9-99b1-33b7975a8c5f.png)
SQL上线不支持MongoDB吗？ 演示站点也报错

### 版本信息
 - 应用版本/分支：Release v1.7.0  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
不支持, 仅支持查询

**Comment by LeoQuote** [comment]
欢迎贡献, 参考我们的[开发者指南](https://github.com/hhyo/Archery/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97) 修改 engine 即可 https://github.com/hhyo/Archery/blob/master/sql/engines/mongo.py

**Comment by dwf3201** [comment]
1.70 及以后版本  支持线上查询啊

**Comment by dwf3201** [comment]
![image](https://user-images.githubusercontent.com/25315267/68176006-228c4d00-ffbe-11e9-88cf-bcad86e0e376.png)

**Comment by 2002wmj** [comment]
支持增加这个功能，可以只需要简单的提交，审核，执行即可。

**Comment by LeoQuote** [comment]
实现起来并不难，可以考虑遵照上面提到的开发者指南增加若干方法即可。

**Comment by fancy-lee** [comment]
> 支持增加这个功能，可以只需要简单的提交，审核，执行即可。

我已经支持，准备pr,目前我们已经在线上使用，部分细节还需打磨，想要尝鲜，加我QQ:53316620

**Comment by LeoQuote** [comment]
直接提pr就行, 在pr里讨论.

**Comment by hhyo** [comment]
这个还没人提pr😂

**Comment by fancy-lee** [comment]
> 这个还没人提pr😂

我争取这两天提一版

**Comment by 2002wmj** [comment]
希望能支持mongo的提交功能，现在mongo用的还蛮多的。

**Comment by hhyo** [comment]
#900
