### ISSUE TITLE
[在线查询 bit 类型字段无法正常显示]

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/Archery#495]
1、进入SQL查询模块
2、点击在线查询
3、选择-MySQL->archer_test
4、输入SQL
select * from tz limit 100;

### 期待结果和实际结果
期待结果：
![image](https://user-images.githubusercontent.com/45680060/68067054-a0f9ac80-fd7c-11e9-91b6-c5ad50750467.png)

实际结果:
![image](https://user-images.githubusercontent.com/45680060/68067059-a9ea7e00-fd7c-11e9-8575-a2859388bafe.png)

### 截图
实际无法显示bit类型字段结果
![image](https://user-images.githubusercontent.com/45680060/68067065-c2f32f00-fd7c-11e9-87b1-ab4c2487de49.png)

**Comment by hhyo** [comment]
感谢反馈，已解决
![image](https://user-images.githubusercontent.com/8842982/68067578-00a78600-fd84-11e9-9ca1-ba187a856f03.png)
