### ISSUE TITLE
SQL上线：选中资源组，实例下拉框没数据，确定资源组是关联实例的。

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#497]
SQL上线：选中资源组，实例下拉框没数据，确定资源组是关联实例的。

### 重现步骤
1. 选中资源组
2. 实例下拉框没数据
3. 日志也没报错

![image](https://user-images.githubusercontent.com/33362111/68108714-8e6da780-ff23-11e9-8e0c-9f5e7a58bddd.png)

### 版本信息
应用版本/分支：1.7.1

部署方式：Docker部署

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/FAQ#%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E8%B5%84%E6%BA%90%E7%BB%84%E5%AE%9E%E4%BE%8B

三点请逐一排查，看描述应该是实例没有关联上线标签

**Comment by lijie861221** [comment]
> https://github.com/hhyo/archery/wiki/FAQ#%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E8%B5%84%E6%BA%90%E7%BB%84%E5%AE%9E%E4%BE%8B
> 
> 三点请逐一排查，看描述应该是实例没有关联上线标签

确实关联上了。后来开启debug模式，发现sql_instance_tag 表中的激活状态为0，修改为1就好了.
问过同事有没有什么操作，说是就加了一个实例，不知道哪里操作把这个值修改了。
尝试了下无法重现这个bug/误操作。
