### ISSUE TITLE
[ bug ]archery平台配置mongodb查询，设置脱敏字段不生效

### ISSUE THREAD

**Issue by dwf3201** [hhyo/Archery#498]
在archery平台，配置mongodb库查询，因库内包含敏感字段，类似：电话号码 ，脱敏字段配置完成后，后台查询仍然可以看到脱敏信息（电话号码之类）。
 
![image](https://user-images.githubusercontent.com/25315267/68175556-99284b00-ffbc-11e9-8893-be9fd96939ed.png)

### 版本信息1.7.0
应用版本/分支：
部署方式：Docker

**Comment by dwf3201** [comment]
脱敏字段配置已配置，规则类型，手机号，激活状态：激活，库表字段  
查询命令： hello1.find({})
查询结果： 
Result
--
{"_id": 1, "name": "hello", ****"mobile": "13812345678",**** "_class": "com.diamond.mongo.entity.Hello"}
{"_id": {"$oid": "5dbbf537a4f9f64324003ed4"}, "name": "hello121", "mobile": "138123467138", "_class": "com.diamond.mongo.entity.Hello1"}

**Comment by LeoQuote** [comment]
目前 mongo 不支持脱敏.

**Comment by hhyo** [comment]
脱敏的，暂且就这样子了
