### ISSUE TITLE
[ 问题咨询 如何升级]

### ISSUE THREAD

**Issue by firehalt** [hhyo/Archery#499]
### 问题描述
项目已经部署在生产环境，如何升级？
1.现在生产环境版本1.7.0,不影响使用的情况下如何升级

**Comment by hhyo** [comment]
参考升级文档即可

**Comment by LeoQuote** [comment]
不支持滚动升级等 no downtime 升级方法, 必须停服升级.
停服升级参照文档即可.

**Comment by yuandajn578** [comment]
@LeoQuote  @hhyo 
两位大神，按照升级步骤，wget https://github.com/hhyo/Archery/blob/master/archery/settings.py
得到的setting.py是网页格式
![image](https://user-images.githubusercontent.com/54062997/68457499-6a6bd800-023b-11ea-8f32-abf1a7a6543c.png)

**Comment by LeoQuote** [comment]
下载GitHub上一个文件就不用我教了吧，自己搜搜吧
