### ISSUE TITLE
普通权限用户sql查询时报list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by chenweida123** [hhyo/Archery#50]
**重现步骤**
1.普通用户申请查询权限，管理员审批通过
2.普通用户选择相应的库进行查询报list indices must be integers or slices, not str
3.管理员用户查询任何表不会出现此错误。

**错误日志**
[2019-02-15 16:57:57,076][MainThread:139963200444224][task_id:default][query.py:578][ERROR]- Traceback (most recent call last):
  File "/opt/archery/sql/query.py", line 495, in query
    limit_num = priv_check_info['data']['limit_num']
TypeError: list indices must be integers or slices, not str

**Comment by LeoQuote** [comment]
请问你使用的是什么版本 ?  是master还是什么? 是使用docker启动的还是clone代码直接启动的? 

我们的新版本可能已经修复了这个问题.

@hhyo 要是有问题的话应该是 query_priv_check 函数有问题, 返回的结果不符合要求.

**Comment by hhyo** [comment]
@LeoQuote 是的，遗漏了一个else，晚上修复
