### ISSUE TITLE
[ 问题咨询 ]执行sql上线报错

### ISSUE THREAD

**Issue by firehalt** [hhyo/Archery#500]
### 问题描述
执行执行sql上线报错，版本1.7.0，所有用户执行都报一样的错误，全部权限设置了还是一样，请问这个权限在哪里设置

![image](https://user-images.githubusercontent.com/29405113/68177172-7dc03e80-ffc2-11e9-99b8-c55d5922305a.png)

**Comment by hhyo** [comment]
不允许在只读实例中执行工单，使用`select @@read_only;`查看实例状态

**Comment by firehalt** [comment]
我都是admin账号执行，可以给我截图看看哪里具体设置哪里吗
![image](https://user-images.githubusercontent.com/29405113/68187976-136bc600-ffe3-11e9-9eaa-ffaaaba696e6.png)
