### ISSUE TITLE
[ 系统下拉菜单选中后，下拉菜单为什么不自动收缩回去，还得在空白处点击一下 ]

### ISSUE THREAD

**Issue by zhuleiandy888** [hhyo/Archery#502]
看图：
![image](https://user-images.githubusercontent.com/13164631/68297553-34f7ab00-00d2-11ea-9de8-5e4d1245d3fb.png)

建议：
    选中后收缩回去

**Comment by hhyo** [comment]
请提供具体操作路径以及版本号
再者可以到demo环境中看是否可以重现

**Comment by zhuleiandy888** [comment]
如图：
![image](https://user-images.githubusercontent.com/13164631/68355397-1a611880-014a-11ea-8387-077bff979b26.png)

官网demo中也是一样，你这个应该是表单插件或框架的问题截图：
![image](https://user-images.githubusercontent.com/13164631/68355493-7166ed80-014a-11ea-984c-443133d7ce63.png)

**Comment by zhuleiandy888** [comment]
![image](https://user-images.githubusercontent.com/13164631/68357450-60b97600-0150-11ea-9cb9-59776f76899a.png)
谷歌游览器 有问题，火狐的没事。

**Comment by hhyo** [comment]
抱歉在MacOS中Chrome 版本 77.0.3865.120（正式版本），以及Safari 版本13.0.2 (15608.2.30.1.1)中均无法重现你描述的问题

**Comment by zhuleiandy888** [comment]
win下的这个版本有问题，估计是兼容性问题，我同事的MAC chrome 78 版本的有这个问题
