### ISSUE TITLE
[ 问题咨询 ]需要定制更改一下前端页面，是否可以开源页面源代码？

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#506]
### 问题描述
大佬，我们对一些表单页面有定制更改的需求，适配老板的要求，是否可以开源页面源代码？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
Archery所有代码都是开源的，前端代码主要在https://github.com/hhyo/Archery/tree/master/sql/templates

具体使用的组件库可以查看依赖清单

**Comment by dbmcp** [comment]
找到了，谢谢
