### ISSUE TITLE
[ 功能建议 ]SQL查询权限控制问题

### ISSUE THREAD

**Issue by gitzhuyongfu** [hhyo/Archery#507]
### 目前遇到的问题/使用障碍
1.申请了表查询的权限的时候，如果此时没有申请数据库权限，那么无法进行表查询。
2.如果申请了数据库权限，那么，这个数据库下的所有表都能进行查询，此时就无法限制对表的查询控制
### 希望如何解决/实现它
1.如果申请了表查询权限，那么就可以查询此数据库的此表，其他表无查询权限
2.如果申请了数据库权限，则可以允许查询此数据库下的所有表数据而无需再进行表查询的权限申请！

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
感谢反馈

其实目前就是这样实现的，只不过SQL解析优先用的inception，不一定可以解析出所有语句的库表信息，当遇到解析不出的语句时，会再次去用sqlparse获取库信息判断库权限，从而出现上面描述的现象，是一种折中的处理方式

有改造意向，不过没确定最终方案，可参考 #145

**Comment by hhyo** [comment]
已处理
