### ISSUE TITLE
[ 问题咨询 ]使用sql上线功能，回滚功能用不了

### ISSUE THREAD

**Issue by gitzhuyongfu** [hhyo/Archery#508]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 部署方式：Docker、手工部署

上线sql位置点击查看回滚SQL,出现有报错信息为1146,xxxxxx$_$Inception_backup_information$_$' doesn't exist".

请问这个配置是怎么配置的？

**Comment by hhyo** [comment]
关于回滚的issue有很多，文档也说明的很详细了，麻烦自己检索排查一下
