### ISSUE TITLE
左侧菜单闪现问题

### ISSUE THREAD

**Issue by changeyourt** [hhyo/Archery#51]
使用的是镜像部署，访问主页面时
点击前：
![image](https://user-images.githubusercontent.com/45409457/52926192-bbffca00-336f-11e9-8deb-8a49fcee8dd0.png)

点击时：
![2](https://user-images.githubusercontent.com/45409457/52926144-91ae0c80-336f-11e9-895d-963d6e53638b.png)

**Comment by LeoQuote** [comment]
你的意思是，左侧的选单在点击任何链接时，都会出现“所有子选单都被展开”的情况吗？

如果是这个问题的话，左侧的选单用的应该是bootstrap的navbar-collapse功能，这个问题好像对实际使用影响也不大，对此确实没有做太多的雕琢，如果你有修改的意见可以直接提pr。

**Comment by changeyourt** [comment]
好。
