### ISSUE TITLE
[ 问题咨询 ] 会话管理是否支持阿里云实例

### ISSUE THREAD

**Issue by gitzhuyongfu** [hhyo/Archery#513]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

配置了阿里云rds认证，但是会话实例没有获取到，请问是否支持阿里会话管理信息获取？

### 版本信息
 - 应用版本/分支：Release v1.7.1  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
没有获取到的具体表现？是接口报错还是仅仅无数据返回，可以在浏览器控制台查看接口是否报错
再者确认是否配置的是管理权限的key，进程获取是clouddba的功能，需要管理权限
然后获取会话列表可以筛选命令为ALL、默认的Query状态不一定有进程在

**Comment by gitzhuyongfu** [comment]
![image](https://user-images.githubusercontent.com/39439367/68558785-878beb00-0475-11ea-951a-0e1a4307f82e.png)

都没有报错，仅仅无数据返回，已确认配置权限的key

**Comment by hhyo** [comment]
表空间和慢日志获取是否正常？
锁信息不依赖rds，基本也很少会看到锁信息
可以自己起一个连接`select sleep(100);`，然后再回过来看进程

**Comment by gitzhuyongfu** [comment]
表空间和慢日志获取都获取不到，检查了access-key都是配置了权限的，docker logs -f 看容器日志没有报错，这个问题需要从哪里进行排查？
![image](https://user-images.githubusercontent.com/39439367/68560097-7d202000-047a-11ea-9105-3a5f6d3ea4b5.png)

**Comment by hhyo** [comment]
不知道你有没有按照我说的尝试，上面说的都是排查方法
还有确认下实例是否有关联rds_id

**Comment by gitzhuyongfu** [comment]
key如果不配置的话会报错的，已检查没有报错，说明key没有问题，也已经配置过实例ID的了
![image](https://user-images.githubusercontent.com/39439367/68560980-ab9ffa00-047e-11ea-8d09-8c0e95628ff2.png)

**Comment by hhyo** [comment]
可同步查看rds管理后台相关功能，是否有数据返回
