### ISSUE TITLE
[ 问题咨询 ]sql上线出现access denied问题

### ISSUE THREAD

**Issue by gonedays** [hhyo/Archery#514]
### 问题描述
1. goinception备份库已经创建专门的账号，非root；
2. 数据库实例也已经创建专门的账号，非root；
3. sql上线审核通过
4.sql上线执行时，出现Access denied for user 'root'@'172.xxxxx' (using password: YES)"
实在找不到哪里有用到root账号，因为都配置了单独的账号了，还请帮忙看看。
这个应该是goinception返回的执行错误，查看docker日志里也可以看到。

### 版本信息
 - 应用版本/分支：Release v1.7.0  
 - 部署方式：Docker

**Comment by hhyo** [comment]
检查goInception的配置文件中备份用户的配置
https://github.com/hhyo/Archery/blob/master/src/docker-compose/inception/config.toml#L68

**Comment by gonedays** [comment]
> 检查goInception的配置文件中备份用户的配置
> https://github.com/hhyo/Archery/blob/master/src/docker-compose/inception/config.toml#L68

确实是里面配置了root账号,但是我在Archery的“配置项管理”菜单中，goinception的部分配置了备份库的账号和密码，这个不能生效吗？还是依然会去使用config.toml里的账号？

**Comment by hhyo** [comment]
Archery的配置是用于获取回滚语句，不会替换goInception本身的配置信息
完善了wiki说明：https://github.com/hhyo/Archery/wiki/配置项说明#remote_backup_host

wiki开放编辑，如果有写的不清晰的地方希望大家可以共同完善

**Comment by gonedays** [comment]
> Archery的配置是用于获取回滚语句，不会替换goInception本身的配置信息
> 完善了wiki说明：[https://github.com/hhyo/Archery/wiki/配置项说明#remote_backup_host](https://github.com/hhyo/Archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#remote_backup_host)
> 
> wiki开放编辑，如果有写的不清晰的地方希望大家可以共同完善

OK，非常感谢~

**Comment by gonedays** [comment]
> Archery的配置是用于获取回滚语句，不会替换goInception本身的配置信息
> 完善了wiki说明：[https://github.com/hhyo/Archery/wiki/配置项说明#remote_backup_host](https://github.com/hhyo/Archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#remote_backup_host)
> 
> wiki开放编辑，如果有写的不清晰的地方希望大家可以共同完善

我在wiki的[配置项说明](https://github.com/hhyo/Archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E)中的<Inception配置>增加了下面这段，让不熟悉的朋友可以减少弯路：
需要注意的是，该配置信息，仅仅用于archery从备份库查询回滚语句使用，该配置信息不会被goInception服务使用，goInception连接备份库使用的数据库连接信息应在其自身的config.toml中配置。
