### ISSUE TITLE
企业微信消息关联到微信无法显示信息

### ISSUE THREAD

**Issue by yishidecengjing** [hhyo/Archery#517]
问题描述
企业微信有消息关联到微信的功能，但是提示“”暂不支持次消息类型“”，例如我用zabbix告警做类似操作没有问题，所以我猜测可能是企业微信的通知不是文本格式，请问可以解决吗。

版本信息
 - 应用版本/分支：Release v1.7.1  
 - 部署方式：Docker部署

**Comment by yishidecengjing** [comment]
@Deng-TR 大佬，我直接把 "msgtype": "markdown",改为"msgtype": "text",可以吗

**Comment by Deng-TR** [comment]
企业微信应用推送的消息格式确实是markdown，如果想支持微信可以改成text类型，可以参考https://work.weixin.qq.com/api/doc#90000/90135/90250文档把下面两个文件中涉及的企业微信消息格式进行修改即可
sql/notify.py  179、181行
common/utils/sendmsg.py  中所有的wx_msg_content值

**Comment by TingRuDeng** [comment]
企业微信应用推送的消息格式确实是markdown，如果想支持微信可以改成text类型，可以参考https://work.weixin.qq.com/api/doc#90000/90135/90250文档把下面两个文件中涉及的企业微信消息格式进行修改即可
sql/notify.py （所有的wx_msg_content值）
common/utils/sendmsg.py  （180行改成 "msgtype": "text",    182行改成"text"）

**Comment by yishidecengjing** [comment]
好的，多谢两位大佬
