### ISSUE TITLE
1.7.1版本密码问题

### ISSUE THREAD

**Issue by bucardo111** [hhyo/Archery#519]
### 问题描述
11月12号从1.7.0升级到1.7.1版本，然后实例管理里面测试连接在1.7.0版本时添加的postgres实例，测试连接成功，然后SQL上线也成功进行，但是11月18号再次执行SQL上线时报
![image](https://user-images.githubusercontent.com/44635177/69031905-28e6e400-0a16-11ea-9ed1-8e8af13b1a4a.png)密码错误，但实际密码是正确的（密码未做过修改），然后重新编辑实例配置，保存以后能成功连接，但是查看实例时发现密码显示为明文密码

### 版本信息
 - 应用版本/分支：Release v1.7.1 
 - 部署方式：Docker部署

请问是否属于升级后的bug?

**Comment by hhyo** [comment]
感谢反馈，抱歉按照你的描述无法重现，不能确认问题，提供相关信息作为参考

参考v1.7.1升级说明 https://github.com/hhyo/Archery/releases/tag/v1.7.1

统一数据加密方式后数据在前台会展示明文，但实际上数据库保存的是加密
使用settings.py的SECRET_KEY进行加密，修改SECRET_KEY会导致以前的加密数据失效

**Comment by bucardo111** [comment]
好的，了解。另外请问下pg上线执行函数调用报错的问题，例如事先已在pg数据库中创建了函数func_modify_in_num()，然后SQL上线时执行sql : select func_modify_in_num()会报错：仅支持DML和DDL语句，查询语句请使用查询功能。

**Comment by hhyo** [comment]
SQL上线不支持select语句
