### ISSUE TITLE
[ 功能建议 ] mongo查询不支持 sort() limit()等方法

### ISSUE THREAD

**Issue by jy3792397** [hhyo/Archery#520]
这些方法还挺常用的，貌似不支持

**Comment by hhyo** [comment]
mongo查询由@jackielulu17325 贡献  参考#332 
具体有哪些常用的，应该可以扩充此列表，但是后续query好像做了正则提取，可能导致语法错误
https://github.com/hhyo/Archery/blob/cc75761084217e6dfa3c1bc7b02a620495181258/sql/engines/mongo.py#L40

有兴趣可以修改后提交PR

**Comment by hhyo** [comment]
有兴趣的朋友可以参考  [redash](https://github.com/getredash/redash/blob/master/redash/query_runner/mongodb.py)项目来进行相关查询改造

**Comment by 2002wmj** [comment]
希望能支持下，目前count()也不能支持
