### ISSUE TITLE
[ 问题咨询 ]工单执行时use 库名报错

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#521]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.6.5  
 - 部署方式：Docker

在执行工单时工单第一步use库名提示

Execute: 无法获取线程号.
--
导致后面任务无法执行
 
![image](https://user-images.githubusercontent.com/26135288/69111042-520b8100-0ab7-11ea-8d00-005ec52edd56.png)

**Comment by hhyo** [comment]
参考：https://github.com/hanchuanchuan/goInception/releases/tag/v1.1.2

升级goInception版本即可

**Comment by a5546868001** [comment]
好的，感谢我试下
