### ISSUE TITLE
[ 问题咨询 ]设置了SQL上线中的自动审批，但是不生效

### ISSUE THREAD

**Issue by a5546868001** [hhyo/Archery#524]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.7.2
 - 部署方式：Docker
从1.6.5升级到1.7.2后原先设置的自动审批功能不生效

![image](https://user-images.githubusercontent.com/26135288/69214230-485e4800-0ba1-11ea-981f-cb67876a33c8.png)

![image](https://user-images.githubusercontent.com/26135288/69214207-38deff00-0ba1-11ea-9805-d9c581e130ef.png)

**Comment by hhyo** [comment]
auto_review_tag是sql_instance_tag表的tag_code ，不是tag_name

**Comment by a5546868001** [comment]
已更改，感谢支持

**Comment by yuandajn578** [comment]
> auto_review_tag是sql_instance_tag表的tag_code ，不是tag_name
@hhyo 
大神，V1.7.1,我设置了auto_review_tag是sql_instance_tag表的tag_code ，即“can_write”，但是仍然不能自动审批执行符合条件的语句，这是为何呢？
