### ISSUE TITLE
[ 问题咨询 ]oracle查询在没有配置脱敏规则、字段的情况下几乎所有字段都会被动态脱敏掉

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#525]
### 问题描述
oracle查询在没有配置脱敏规则、字段的情况下几乎所有字段都会被动态脱敏掉，关闭DATA_MASKING后正常。
DATA_MASKING关闭后，脱敏规则和脱敏字段配置是否都会失效？
![image](https://user-images.githubusercontent.com/44385881/69218876-9a589b00-0bac-11ea-9990-ae7d6edc5830.png)

### 版本信息
 - 应用版本/分支：Release v1.7.1 
 - 部署方式：Docker

**Comment by dbmcp** [comment]
DATA_MASKING关闭后，单独配置的别的mysql的脱敏规则和脱敏字段配置是否都会失效？

**Comment by LeoQuote** [comment]
没有看到你的异常脱敏的情况, 可以截图看一下吗?

**Comment by dbmcp** [comment]
![image](https://user-images.githubusercontent.com/44385881/69221284-d6422f00-0bb1-11ea-8c6c-7c830f3fbd41.png)
修改时间会被脱敏

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/12d47ed8eab4b7ee3509151645d4df678fe2e6dd/sql/utils/data_masking.py#L259-L269 

再确认一下 DataMaskingRules 表中有没有脱敏规则

**Comment by dbmcp** [comment]
这个数据库是新增的配置，确认没有在后台配置任何脱敏字段

**Comment by hhyo** [comment]
@LeoQuote  oracle和mssql一样是直接匹配所有规则的，忽略了脱敏字段的配置，对整个查询结果生效，脱敏的正则规则尽量不要通配，匹配指定格式应该可以缓解这个问题

后面这一块可以调整

**Comment by dbmcp** [comment]
![image](https://user-images.githubusercontent.com/44385881/69232972-ff20ef00-0bc6-11ea-9aa3-7e62f1d4c1ee.png)
![image](https://user-images.githubusercontent.com/44385881/69233009-0f38ce80-0bc7-11ea-91e5-bc2739967ea8.png)
![image](https://user-images.githubusercontent.com/44385881/69233053-25468f00-0bc7-11ea-9a9e-fb9d01f785bf.png)

看了源码sql.engines.oracle.py 和 sql.engines.mysql.py

**Comment by dbmcp** [comment]
脱敏调用的方法不一样，oracle直接匹配所有规则，不走脱敏字段配置

**Comment by dbmcp** [comment]
尝试一整天严格的分组正则，做不到不误伤oracle的字段值。。。
坐等大佬调整代码，死等...

**Comment by hhyo** [comment]
#145
