### ISSUE TITLE
[ 功能建议 ]希望Archery可以在上线工单时，允许添加附件功能，比如图片、Word文档

### ISSUE THREAD

**Issue by chuancyzhang** [hhyo/Archery#526]
### 目前遇到的问题/使用障碍
目前我们在使用Archery时，发现有些开发人员只顾着提交SQL，但是不说明为什么要提交这个工单，且无法提供一定的说明文件表示这个SQL是业务要求执行还是修复故障，所以希望能增加一个附件功能，让提交SQL工单的人员可以上传证明文件。

### 希望如何解决/实现它
在上线工单时，增加一个按钮，可以上传附件，或者是现有的上传SQL文件的按钮可以不限于SQL文件。工单在按流程审批时可以让相关审核人员下载、或者线上查阅文件，以确定这个工单符合业务需求，能解决相关问题。

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
![image](https://user-images.githubusercontent.com/23111194/69223506-7437f880-0bb6-11ea-82d9-300b1ab10a61.png)

**Comment by hhyo** [comment]
确实存在这个问题，不过添加附件和图片会有点重，会考虑添加一个链接地址输入框，可以输入公司内部wiki或者jira链接，记录变更需求信息，点击工单名称进行跳转查看

目前暂时可以让开发人员在提交工单的最前面增加注释段来说明变更需求信息

`/*需求信息xxx*/`

**Comment by chuancyzhang** [comment]
@hhyo ，这样也可以

**Comment by chuancyzhang** [comment]
@hhyo 非常感谢支持

**Comment by hhyo** [comment]
已合并，等下版本更新
