### ISSUE TITLE
[ bug ]阿里云RDS MySQL上线功能SQL解析问题

### ISSUE THREAD

**Issue by wmbxx** [hhyo/Archery#527]
#292 # 重现步骤
1、当数据库为阿里云RDS MySQL时，SQL上线功能，解析出的sql内容为：inception_magic_start。
2、如果使用相同的SQL上线，在阿里云ECS上安装的MySQL，可以正常使用SQL上线功能。

### 截图

<img width="1410" alt="222" src="https://user-images.githubusercontent.com/11939911/69225334-240e6580-0bb9-11ea-8167-b638f9ba2ddd.png">

### 版本信息
应用版本/分支：

 - 应用版本/分支：Release v1.7.0 
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
可尝试升级goInception

**Comment by wmbxx** [comment]
升级了goInception为1.13后，问题还是没有解决。请再帮看下是什么问题。
 # ./goInception -V
Release Version: v1.1.3
Git Commit Hash: b70e4169d882eecc675f2fb7270ebfd6604ddc21
Git Branch: master
UTC Build Time: 2019-11-13 21:34:08
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by hhyo** [comment]
参考goInception调用方式直接调用，不使用Archery提交试试，方便确认是哪个地方的问题
https://hanchuanchuan.github.io/goInception/demo/
