### ISSUE TITLE
[ 问题咨询 ]开启goinception审核报权限问题

### ISSUE THREAD

**Issue by thickhang** [hhyo/Archery#530]
### 问题描述
1.开启goinception审核，检测工单时报错：Error 1044: Access denied for user 'readonly'@'%' to database 'mysql'
一样的用户权限，如果不开goinception，使用inception一切都是正常的。

2.查询页面，输入limit 12,5  这个offset并不起作用。
求解答。

### 版本信息
 - 应用版本/分支：Release v1.6.7  
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
- goInception检测默认会去连接mysql库，需要授予账号mysql库的权限
- 查询limit的问题参考 #143
