### ISSUE TITLE
[ inception 执行卡死 ]

### ISSUE THREAD

**Issue by chenjinlei1122** [hhyo/Archery#533]
### 问题描述
使用inception在执行一个同时包含drop，create的工单时会卡死，一直在执行中，拆成两个工单执行没有问题。想问一下这是不是inception本身的bug，有没有遇到类似的问题，如何解决的，非常感谢。

**Comment by chenjinlei1122** [comment]
use test123;
drop table if exists Student;
create table Student(id int not null auto_increment primary key comment "学号", student_name varchar(64) not null comment "姓名") engine=InnoDB default charset=utf8mb4 comment="学生表";

例如这样的，就会一直显示执行中。

**Comment by hhyo** [comment]
http://139.199.0.191/detail/771/
抱歉，无法重现

**Comment by chenjinlei1122** [comment]
是用inception执行的吗？

**Comment by hhyo** [comment]
是的，系统配置中可以切换，可以自行测试各种场景
