### ISSUE TITLE
[ 问题咨询 ] 1.7.2 版本点击sql检测一直提示nothing to repeat at position 0

### ISSUE THREAD

**Issue by WatchLucky** [hhyo/Archery#535]
### 问题描述
提交工单，点击sql 检测 ，一直弹出nothing to repeat at position 0
日志无任何输出， 浏览器调试没有发现任何错误
### 版本信息
 - 应用版本/分支：Release v1.7.2 
 - 部署方式：Docker

**Comment by hhyo** [comment]
https://www.cnblogs.com/Frange/p/9057132.html

检查配置项CRITICAL_DDL_REGEX的正则表达式是否正确

**Comment by WatchLucky** [comment]
配置了*drop* , 改成^drop|^DROP ,问题解决，谢谢。
