### ISSUE TITLE
[ bug ] binlog2sql 模块 back-interval 传值问题

### ISSUE THREAD

**Issue by WatchLucky** [hhyo/Archery#536]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

 在binlog2sql 模块，根据提示操作 获取sql  
 报错 -- back-interval    expected one argurment 
 
### 截图
![image](https://user-images.githubusercontent.com/9958812/69476911-b82b3780-0e1a-11ea-9de2-50bb66452ee3.png)

原因：
 
![image](https://user-images.githubusercontent.com/9958812/69476941-15bf8400-0e1b-11ea-915a-ef2f02f74842.png)

back-interval 参数需要传值

 
### 版本信息
应用版本/分支：1.7.2

部署方式：Docker

**Comment by hhyo** [comment]
感谢反馈，已处理
