### ISSUE TITLE
关于tidb实例，上线变更遇到的问题。

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#537]
### 问题描述
**我把tidb实例，添加到mysql实例后。
执行任何变更都提示 “实例read_only=1，禁止执行变更语句!”
我注释了sql/engines/mysql.py 以下语句，依然提示上面的报错，请问还要修改哪里。**
    def execute_workflow(self, workflow):
        """执行上线单，返回Review set"""
        # 判断实例是否只读
        #read_only = self.query(sql='select @@read_only;').rows[0][0]
        #if read_only:
        #    result = ReviewSet(
        #        full_sql=workflow.sqlworkflowcontent.sql_content,
        #        rows=[ReviewResult(id=1, errlevel=2,
        #                           stagestatus='Execute Failed',
        #                           errormessage='实例read_only=1，禁止执行变更语句!',
        #                           sql=workflow.sqlworkflowcontent.sql_content)])
        #    result.error = '实例read_only=1，禁止执行变更语句!',
        #    return result

版本信息
 - 应用版本/分支：Release v1.7.2
 - 部署方式：Docker

**Comment by hhyo** [comment]
修改完代码后重启服务和Django-Q
