### ISSUE TITLE
[ bug ]添加权限不显示 工具插件

### ISSUE THREAD

**Issue by kcxg** [hhyo/Archery#538]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
给用户添加 了 工具插件权限,但是用户登录后不显示

### 截图
![image](https://user-images.githubusercontent.com/31840413/69526442-27349780-0fa5-11ea-9611-56fa00d9dff8.png)
![image](https://user-images.githubusercontent.com/31840413/69526452-2b60b500-0fa5-11ea-8273-3f1f5187574c.png)

### 版本信息
应用版本/分支：

部署方式：Docker

**Comment by hhyo** [comment]
感谢你的报告，已处理，可按照commit记录修改数据库权限代码，具体将会再下个版本发布
