### ISSUE TITLE
默认资源组 设置项 无效

### ISSUE THREAD

**Issue by changeyourt** [hhyo/Archery#54]
我创建了资源组 test_resource，并将实例 master加入了该资源组。
同时创建了用户 test_user，给该用户授予了SQL上线和SQL上线工单权限。
将test_resource设置为默认资源组。
当test_user登录后，提交工单时，无法找到实例。
必须要手动将test_user加入到test_resource后，test_user才能看到实例。

**Comment by LeoQuote** [comment]
默认资源组关联是在用户创建的时候做的，所以老用户只能手动关联。你可以新建一个用户再试试

**Comment by LeoQuote** [comment]
抱歉上一个回复有一些偏差。默认权限组和资源组的关联是在登录页面页面上注册用户，以及ladap**首次**登录的时候才会做的，其他情况都需要手动调整权限。

**Comment by changeyourt** [comment]
嗯，我刚也测试了下，用户首次登录时会被关联到 默认权限组 ，但是默认资源组好像首次登录不行，成功注册用户时，该用户会被关联到 默认资源组。ldap没有测试。
因为我看 设置框 中提示：每次用户登录会自动关联，所以我就认为设置项无效。

**Comment by LeoQuote** [comment]
我刚刚检查了代码逻辑, 用户只要从未登录过(使用``last_login``字段判断)就会做默认权限组和默认资源组的关联, 不管是页面注册, admin页面添加, 还是ldap用户都会. 另外文案也已更新到master , 等下一个发布就会体现在界面上了.
