### ISSUE TITLE
[ 功能建议 ]增加数据同步操作，例如可以从生产选择若干表数据同步至灰度或测试，不可逆向。频率可单次或定时执行。

### ISSUE THREAD

**Issue by zwunix** [hhyo/Archery#541]
### 目前遇到的问题/使用障碍
日常同步数据需求

### 希望如何解决/实现它
增加数据同步操作，例如可以从生产选择若干表数据同步至灰度或测试或开发环境，灰度同步至测试或开发环境，测试同步至开发环境，不可逆向。频率可单次或定时执行。必要可引用脱敏的规则进行数据处理后传送至目标环境。

### 其他信息
无

**Comment by hhyo** [comment]
DTS有很多现成的方案和工具，如果能集成也是DBA的好帮手，但是很抱歉目前并没有相关计划
