### ISSUE TITLE
[ bug ]V1.7.1，自动审批失效

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#545]
### 重现步骤
1、配置自动审批；
2、执行符合自动审批的SQL语句

### 期待结果和实际结果
期待结果：
自动审核并执行SQL语句，工单状态为“正常结束”

实际结果:
工单状态为“等待审核人审核”

### 截图
![image](https://user-images.githubusercontent.com/54062997/69688442-06815480-1101-11ea-8215-3cc7e059194e.png)
![image](https://user-images.githubusercontent.com/54062997/69688589-78f23480-1101-11ea-81e7-fbfafda8d3e1.png)
![image](https://user-images.githubusercontent.com/54062997/69688649-9c1ce400-1101-11ea-9fa6-d30b95d075c8.png)

### 错误日志
无

### 版本信息
应用版本/分支：1.7.1

部署方式：Docker

**Comment by hhyo** [comment]
正则表达式包含`||`，会匹配所有字符

**Comment by yuandajn578** [comment]
> 正则表达式包含`||`，会匹配所有字符

确实是多写了一个|，修正之后，可以自动审核了，但是不能自动执行，有计划支持自动执行吗？

**Comment by hhyo** [comment]
不会有自动执行，可以开放执行权限给提交人

**Comment by dbmcp** [comment]
1.7.2有这个bug吗
