### ISSUE TITLE
[ 问题咨询 ] 列 'name' 不允许为null(表 'test_name')

### ISSUE THREAD

**Issue by withmi** [hhyo/Archery#546]
### 问题描述
列 'name' 不允许为null(表 'test_name').
列 'sort' 不允许为null(表 'test_name').
列 'operator_id' 不允许为null(表 'test_name').
列 'operator_name' 不允许为null(表 'test_name').
列 'create_time' 不允许为null(表 'test_name').
列 'update_time' 不允许为null(表 'test_name').
列 'is_del' 不允许为null(表 'test_name').

在哪里设置可以去掉SQL上线功能中新增表中默认字段为不为空。现在想关闭默认检查字段不为空的检测。因为我们开发有些字段没有值的时候，必须为空。或者有什么好的替换方案吗？

### 版本信息
 - 应用版本/分支：Release v1.7.0
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
审核这块是用的goincepion 或者inception , 你看一下inception 和goinception 的配置.
