### ISSUE TITLE
[ bug ] sql查询时time字段格式显示错误。

### ISSUE THREAD

**Issue by 2002wmj** [hhyo/Archery#547]
### 重现步骤
我在官方的demo上面创建了一张表重现这个问题。结果应该是13:15:00却显示成47700.
![image](https://user-images.githubusercontent.com/16568733/69698810-4bb57e80-1121-11ea-8687-197674eff5b2.png)

![image](https://user-images.githubusercontent.com/16568733/69698718-10b34b00-1121-11ea-8922-0477c67ffc77.png)
![image](https://user-images.githubusercontent.com/16568733/69698734-190b8600-1121-11ea-9c2b-cdaf18dad090.png)

**Comment by hhyo** [comment]
应该和 #414 类似
