### ISSUE TITLE
为什么要选择使用django-q？

### ISSUE THREAD

**Issue by 0x3091e** [hhyo/Archery#548]
如题，为什么不选择celery？是因为django-q支持只运行一次的计划任务吗？

**Comment by LeoQuote** [comment]
当时考虑celery 我个人的体验用着不太舒服, django-q 试用了一下感觉还不错, 就用上了, 如果你对这方面有兴趣可以换.

参见当时的pr #22

**Comment by 0x3091e** [comment]
谢谢回复，django-q的schedule_type支持ONCE，方便定时任务的管理，这点确实不错。
