### ISSUE TITLE
[ 问题咨询 ] goInception Execute: exec: "pt-online-schema-change": executable file not found in $PATH.

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#549]
### 问题描述
执行DDL语句时，报如下错误：
Execute: exec: "pt-online-schema-change": executable file not found in $PATH.

我用的是goinception，我看goinception的容器里面有usr/local/bin/pt-online-schema-change，并且在$PATH变量里面。
/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
![image](https://user-images.githubusercontent.com/13861904/69722486-3efd4e80-1152-11ea-88f8-159e05a78712.png)

### 版本信息
 - 应用版本/分支：Release v1.7.0
 - 部署方式：Docker

**Comment by hhyo** [comment]
可升级goinception试试

**Comment by czxin788** [comment]
> 可升级goinception试试

感谢，升级后还是这样，后来我知道原因了，是没加x权限导致的，加上就好了。

排错步骤：
[root@archery chenzx]# docker exec -it  goinception sh
/ # ls /usr/local/bin/pt-online-schema-change 
/usr/local/bin/pt-online-schema-change

/ # /usr/local/bin/pt-online-schema-change 
sh: /usr/local/bin/pt-online-schema-change: Permission denied


/ # whoami 
root


/ # cd /usr/local/bin/
/usr/local/bin # ls -l
total 476
-rwxr-xr-x    1 root     root         54744 Aug  2  2018 dumb-init
-rw-r--r--    1 root     root        426996 Nov 19 15:40 pt-online-schema-change


/usr/local/bin # chmod +x pt-online-schema-change 


就这样，加上x权限就好了。

谢谢作者。
