### ISSUE TITLE
[ 建议 ] 操作按钮布局调整

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#55]
SQL线上的操作日志、实例管理、测试、资源组管理 等按钮，在最右侧，当需要调整配置时，点击不便，而且需要比对最左侧列，确认没有点错。

建议将按钮放在“名称”列后面，这样方便操作

**Comment by LeoQuote** [comment]
感谢你的建议。

据我所知表格的最左边是ID，中间一般是名称，最右边是对应操作，这样从左到右看应该是很符合直觉和我的操作习惯的。 

所以没明白你的不方便点在哪里，可以告诉我具体链接，有截图就更好了。

**Comment by think-coding** [comment]
![default](https://user-images.githubusercontent.com/35367394/53324043-c1828480-391a-11e9-8b1c-c0ba6461f6cc.png)
类似这样，因为在实例、资源组里，项目多的时候，需要左右对照确定没有点串行，所以操作起来有些不方便。

**Comment by LeoQuote** [comment]
![1161551174905_ pic](https://user-images.githubusercontent.com/4143818/53404334-6622c600-39f0-11e9-8b8d-22162f0146b6.jpg)

你好， 我尝试了一下重新排列， 但是感觉还是不太符合习惯， 我的习惯是杂项和操作之类的放在尾部的。

而且鼠标悬停列会有颜色加深的css效果， 很方便就可以double check

如果还是觉得不方便， 还可以使用表格右上方的第三个选项， 选择隐藏一些列。这样你在看的时候应该会方便不少。

如果你实在觉得不方便， 这个排布的代码是在 [这里](https://github.com/hhyo/archery/blob/master/sql/templates/sqlworkflow.html#L147) , 只需要更改js里的字段顺序就可以。
