### ISSUE TITLE
[ 功能建议 ]脱敏规则类型能自己添加吗，后台脱敏字段配置页面里选择Instance能否增加模糊搜索

### ISSUE THREAD

**Issue by jy3792397** [hhyo/Archery#550]
1.脱敏规则类型能自己添加吗，貌似现在是写死的，只有手机号、证件号码、邮箱、其他。。。这几种，数据库里也没找到，不同需求可能隐藏的正则不同，比如有的需要隐藏前2位，有的需要隐藏前3位。。。
2.后台脱敏字段配置页面里选择Instance能否增加模糊搜索

**Comment by hhyo** [comment]
类型就是一个枚举值，只要两个表匹配就可以

添加规则建议参考Faq中的脚本，可自动定时更新
