### ISSUE TITLE
[ bug ]从1.7.1开始Dashboard页面用户权限出现严重bug

### ISSUE THREAD

**Issue by dbmcp** [hhyo/Archery#552]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

#### 
![image](https://user-images.githubusercontent.com/44385881/69857260-81499b80-12ca-11ea-9b98-fb139a01ddea.png)

初步判断：
![image](https://user-images.githubusercontent.com/44385881/69857333-beae2900-12ca-11ea-8209-96d7b0ba730d.png)
上图中cache_page设计是出于什么考虑？是否是导致这个bug的原因？

**Comment by hhyo** [comment]
感谢反馈，问题之前已确认是cache_page导致，使用cache_page是因为方便，不需要单独处理缓存
- 暂时不要给Dashboard菜单权限给普通用户

其实各个菜单都有权限控制，看到也不会存在越权操作

**Comment by dbmcp** [comment]
感谢您回复，主要是我们用户多，有的页面权限是不完全控制的，比如工具插件（别的没顾上点），被群众骂惨了，临时用1.7.0的Dashboard代码覆盖1.7.2的暂时没问题了
期待最新稳定版修复bug，感谢！

**Comment by hhyo** [comment]
这个其实发现一段时间，只是感觉权限控制的挺严就没着急修，看来还是有影响，现在已经修复，周末更新一版，方便的话可使用hhyo/ archery:master 的镜像协助验证一下，已自动build
