### ISSUE TITLE
查询页面统计oracle数据库中的一张表的数据量不准确

### ISSUE THREAD

**Issue by lijie861221** [hhyo/Archery#556]
版本：1.7.2
docker部署

表中实际数据量有120万，但是在审核平台统计出只有100条，不管怎样统计都是100条，很是奇怪。修改最大行数为500，统计结果就是500.

**Comment by lijie861221** [comment]
语句是select count(1) from table ,查看后台日志实际执行的sql为select count(1) from table where rownum <= 100

**Comment by hhyo** [comment]
参考 #143 
如果想查询更多数据可以在权限管理修改查询行数并在查询界面选择[最大查询行数]

**Comment by lijie861221** [comment]
> 参考 #143
> 如果想查询更多数据可以在权限管理修改查询行数并在查询界面选择[最大查询行数]
我现在是用oracle查询的。

**Comment by hhyo** [comment]
所有类型的实例，查询语句\结果集都会按照页面行数限制进行改写或者切片

**Comment by lijie861221** [comment]
> 所有类型的实例，查询语句\结果集都会按照页面行数限制进行改写或者切片
统计结果随着设置的返回的行数在变。
比如我设置500行，统计结果显示500；设置返回数量为1000，统计结果显示1000
sql语句是一个很简单的：select count(1) from table;

**Comment by hhyo** [comment]
很抱歉，个人不太熟悉Oracle的语法，Oracle引擎由其他社区成员贡献，如果按照上面的例子，目前只能尽可能大的修改限制行数了

后续再看如何修复

**Comment by hhyo** [comment]
#688 此pr已处理该问题
