### ISSUE TITLE
[ 问题咨询 ] SQL上线不显示资源组信息

### ISSUE THREAD

**Issue by wang20075274** [hhyo/Archery#557]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
我的实例关联了支持上线，goInception 也是通的，但是sql提交组列表不显示，什么原因？
### 版本信息
 - 应用版本/分支：Release v1.7.2 
 - 部署方式：手工部署

**Comment by hhyo** [comment]
请查看文档

**Comment by wang20075274** [comment]
> 请查看文档

看文档了，文档里说是支持上线标签加资源组关联，都关联了也没显示，不过查询是显示了。就上线的数据库资源没显示。

**Comment by wang20075274** [comment]
> 请查看文档

![image](https://user-images.githubusercontent.com/58112043/70287871-71badd00-180b-11ea-8072-709ec2a89e11.png)
![image](https://user-images.githubusercontent.com/58112043/70287916-9a42d700-180b-11ea-9a3d-14674e273f91.png)

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/FAQ#无法选择资源组实例

**Comment by wang20075274** [comment]
> [https://github.com/hhyo/archery/wiki/FAQ#无法选择资源组实例](https://github.com/hhyo/archery/wiki/FAQ#%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E8%B5%84%E6%BA%90%E7%BB%84%E5%AE%9E%E4%BE%8B)

我哥，
![image](https://user-images.githubusercontent.com/58112043/70290651-88653200-1813-11ea-97e0-e891e924519e.png)
你这个设置太坑了，是就不显示，文档也没有啊……^_^

**Comment by hhyo** [comment]
文档开放编辑，欢迎补充

确认在查询能显示是少了伪删除判断，这个在后面修复

**Comment by iammoden** [comment]
> > [https://github.com/hhyo/archery/wiki/FAQ#无法选择资源组实例](https://github.com/hhyo/archery/wiki/FAQ#%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E8%B5%84%E6%BA%90%E7%BB%84%E5%AE%9E%E4%BE%8B)
> 
> 我哥，
> ![image](https://user-images.githubusercontent.com/58112043/70290651-88653200-1813-11ea-97e0-e891e924519e.png)
> 你这个设置太坑了，是就不显示，文档也没有啊……^_^

一脸懵逼的找了几个小时，太感谢你了。哥哥！
