### ISSUE TITLE
[ 功能建议 ] 增加ssh隧道功能

### ISSUE THREAD

**Issue by wang20075274** [hhyo/Archery#558]
### 希望如何解决/实现它
建议增加ssh隧道的功能，解决内网连接问题。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
没太理解，内网连接主要指哪方面？

**Comment by wang20075274** [comment]
比如说，需要通过网关访问的，不能直接连接的数据，需要通过一个可以连接此数据库的服务跳转，类似navicat ssh代理的功能。

**Comment by wang20075274** [comment]
> 没太理解，内网连接主要指哪方面？

比如说，需要通过网关访问的，不能直接连接的数据，需要通过一个可以连接此数据库的服务跳转，类似navicat ssh代理的功能。

**Comment by LeoQuote** [comment]
直接在外部设置一个ssh网关，然后archery填这个地址不就行了……

这个不属于核心功能，navicat可能重在开发体验，这边更加侧重于上线流程和审核

**Comment by wang20075274** [comment]
> 直接在外部设置一个ssh网关，然后archery填这个地址不就行了……
> 
> 这个不属于核心功能，navicat可能重在开发体验，这边更加侧重于上线流程和审核

嗯，是的，目前是这么实现的，感觉如果能在程序里配置会方便些...,用的jumpserver服务器代理就有这个功能。建议吧，谢谢

**Comment by LeoQuote** [comment]
jumpserver的核心就是ssh跳板，和archery的定位还是有一些差别

**Comment by wang20075274** [comment]
> jumpserver的核心就是ssh跳板，和archery的定位还是有一些差别

好的，谢谢

**Comment by Liesport758** [comment]
有考虑过tab页支持收藏多条语句
