### ISSUE TITLE
[ 问题咨询 ] MsSQL查询脱敏异常

### ISSUE THREAD

**Issue by liuxinwang** [hhyo/Archery#559]
### 问题描述
MsSQL数据源SQL查询结果全部为****，有开启动态脱敏功能，并没有配置MsSQL表字段有脱敏规则，只配置了部分MySQL实例库表字段的脱敏字段。

### 版本信息
 - 应用版本/分支：Release v1.7.1  
 - 部署方式：Docker

**Comment by hhyo** [comment]
参考 #145 #525

**Comment by hhyo** [comment]
后续版本处理，除MySQL外其他目前只能做到全局匹配，如果让规则直接关联实例和现有存在设计冲突，不只是否有其他合适的建议
