### ISSUE TITLE
[ 问题咨询 ]不同用户对同一个库需要不同权限，能共用一个实例，还是哪里配置来区分

### ISSUE THREAD

**Issue by omyhub** [hhyo/Archery#561]
### 问题描述
测试db我需要给开发和测试不同的权限，我要配置2个实例，各自用不同的连接权限吗？

### 版本信息
 - 应用版本/分支：Release v1.7.1 
 - 部署方式： 手工部署

**Comment by LeoQuote** [comment]
可以, 比较推荐用archery 自己的权限控制, 查询和上线的权限均可设置

**Comment by omyhub** [comment]
这个有看到，貌似 查询和上线是和实例绑定的，我是指不用用户组对同一个实例拥有不同权限，不知可否设置

**Comment by LeoQuote** [comment]
这个没做, 目前上线是通过上线流程控制的, 可以设置上线流程中需要特定用户组的审批

**Comment by hhyo** [comment]
不同的权限具体是指？
如果是希望限制到库级别，目前是没有的，平台最小权限是实例

**Comment by omyhub** [comment]
应该是我使用上有点偏门，有dev，test的数据库实例，想让开发人员能写dev，读test；测试人员能读dev，写test。关闭这个问题吧，

**Comment by omyhub** [comment]
感谢回复~~！
