### ISSUE TITLE
[ 问题咨询 ] sql上线模块，实例列表为空

### ISSUE THREAD

**Issue by peng19832** [hhyo/Archery#562]
![image](https://user-images.githubusercontent.com/9590209/70519177-79191800-1b76-11ea-9922-427521d3974a.png)

### 问题描述
1、在SQL上线模块中，请问需求链接，填什么？
2、SQL上线时，选择组后，实例列表为空，是为什么？

### 版本信息
 - 应用版本/分支：Release v1.7.3  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
@hhyo  需求链接应该可以显示"可选", 本来就是个可选项

**Comment by hhyo** [comment]
可以调整为可选，#539

**Comment by peng19832** [comment]
@LeoQuote 大佬，那选择组后，实例列表是空的，是个啥情况呢？

**Comment by LeoQuote** [comment]
先过一遍文档吧 https://github.com/hhyo/archery/wiki/faq#%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E8%B5%84%E6%BA%90%E7%BB%84%E5%AE%9E%E4%BE%8B
