### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by liuxinwang** [hhyo/Archery#563]
### 问题描述
从v.1.6.7版本升级到v1.7.1后，采用goinception对ddl审核时，对于point类型审核不通过问题；
v.1..6.7版本是否有该问题没有测试，直接搭建v.1.7.1版本测试point类型审核是可以通过的。
猜测是否是升级导致的无法对point类型审核通过

如以下建表语句：
create table t1(
id bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
c1 point default NULL COMMENT 'c1',
PRIMARY KEY (id)
)COMMENT 't1'

审核信息 提示：
ine 3 column 9 near " default NULL COMMENT 'c1',
PRIMARY KEY (id)
)COMMENT 't1'" (total length 174)

咨询goinception作者后，对docker-compose中goinception执行升级修改：
image: hanchuanchuan/goinception --> image: hanchuanchuan/goinception:latest
执行命令：docker-compose -f docker-compose.yml up -d
升级后依然存在该问题

goinception log:
time="2019/12/11 11:24:15.380" level=error msg="con:3 解析失败! line 3 column 9 near \" default NULL COMMENT 'c1',\nPRIMARY KEY (id)\n)COMMENT 't1'\" (total length 168)" file=session_inception.go line=397
time="2019/12/11 11:24:15.380" level=error msg="                            create table t1(\nid bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',\nc1 point default NULL COMMENT 'c1',\nPRIMARY KEY (id)\n)COMMENT 't1'" file=session_inception.go line=398

### 版本信息
 - 应用版本/分支：Release v1.7.1  
 - 部署方式：Docker

**Comment by hhyo** [comment]
可不依靠平台直接调用goInception来确认是哪里的问题，goInception文档中有相关调用方法

**Comment by liuxinwang** [comment]
问题找到了，是因为当时docker-compose构建的 image: hanchuanchuan/goinception已经是当时的latest，然后显示指定latest并没有重新build；
通过到dockerhub上面获取到最新版本image: hanchuanchuan/goinception:v1.1.5
执行命令：docker-compose -f docker-compose.yml up -d 解决了该问题
