### ISSUE TITLE
[ 功能建议 ] 建议简化/整合用户权限

### ISSUE THREAD

**Issue by peng19832** [hhyo/Archery#564]
### 目前遇到的问题/使用障碍
现在，创建新用户，分配权限时，比较繁琐。
比如，允许用户查询，就需要好几个权限（菜单权限、sql权限...）。

### 希望如何解决/实现它
希望可以简化权限，比如角色

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
可以详细描述你需要的几个权限吗? 尽可能做到易用是项目的追求, 如果能详细提供你的需求就更好了.

**Comment by hhyo** [comment]
可参考文档说明，权限组实际上就是角色，用户可拥有所在权限组的所有权限
通用权限由权限组统一控制，特殊权限单独关联到用户
