### ISSUE TITLE
[ 问题咨询 ]在线查询流程疑问

### ISSUE THREAD

**Issue by daixh302** [hhyo/Archery#566]
### 问题描述
现在权限的设置太复杂，我想在 在线查询 中申请在线查询，审批后才可以查询，具体需要在后台配置哪些权限？

### 版本信息
 - 应用版本/分支：Release v1.7.3 
 - 部署方式：手工部署

**Comment by hhyo** [comment]
如果能够认真看文档的话，应该问题不大

目前的权限粒度比较细，主要分为菜单权限和操作权限，可以实现比较精准的控制

对于每个权限的作用在文档中有比较详细的说明，查询的话具体配置下列权限就可以申请

` ` ` 
菜单 SQL查询
    
菜单 在线查询 
   
菜单 查询权限申请 
   
申请查询权限    

提交SQL查询
` ` ` 

再者需要给用户index的访问权限，默认index是sql工单，可在系统配置中修改

**Comment by daixh302** [comment]
谢谢，已经解决了，发现选中的权限里面，我把‘可查询所在的资源组内的所有实例’的权限放进去了，导致之前不管是否审核，在线查询总是可查询，把这个去掉就好了。
