### ISSUE TITLE
[ 问题咨询 ]修改微信企业号的关联应用agent_id和secret后收不到消息

### ISSUE THREAD

**Issue by shmily90** [hhyo/Archery#567]
### 问题描述
在企业工公众号中新建了应用
在通知配置中，修改了微信企业号的agent_id和secret，改为新建应用的agent_id和secret，提交工单，微信收不到通知消息，将agent_id和secret改回原来正常使用的应用对应值，再次提交工单，微信还是收不到通知消息。

### 版本信息
 - 应用版本/分支：Release v1.7.2  
 - 部署方式：Docker

**Comment by hhyo** [comment]
具体可查看日志

**Comment by shmily90** [comment]
![image](https://user-images.githubusercontent.com/57162494/70674437-eb960f00-1cc0-11ea-95f1-f1b5a59ad4ab.png)
errorcode:41001 
![image](https://user-images.githubusercontent.com/57162494/70674995-b25e9e80-1cc2-11ea-84fb-89cf9f5742e1.png)
怀疑是不是在更改aggentid和secret时先清空了access_token,也没有去获取新的access_token

**Comment by hhyo** [comment]
尝试删除downloads目录下的access_token.json文件重试一下

**Comment by shmily90** [comment]
删除access_token.json文件后重新配置企业微信agent和secret，以及重启整个服务都没有重新生成这个文件，还是发不了消息

**Comment by shmily90** [comment]
通过企业微信接口调用工具，生成了token之后复制到access_token.json可以实现发送消息的功能，不知道2个小时有效期过期之后会不会自动去更新，我再关注下。

**Comment by shmily90** [comment]
微信会每2个小时自动重新生成一次新的token，然而服务并没有在token失效后主动去获取新的token更新到access_token.json文件中，应该是一个bug

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/master/sql/utils/wx_api.py#L28
参考这个方法，可以打印出获取token的响应是什么

**Comment by shmily90** [comment]
看了下这个方法 
![image](https://user-images.githubusercontent.com/57162494/70698508-9c70ce00-1d02-11ea-95dc-b509c527129e.png)
我理解的中间的逻辑是会去判断access_token.json文件的修改时间，现在时间和文件最后一次修改时间的差值大于过期时间的时候，就会重新获取token更新这个文件
![image](https://user-images.githubusercontent.com/57162494/70698725-05f0dc80-1d03-11ea-9889-5650f16f4a0b.png)
但是现在时间差已经超过2h,token的过期时间了，怎么没有去重新获取，并没有更新access_token.json这个文件

**Comment by hhyo** [comment]
`r_json['errcode'] == 0`才会更新
所以才让你确认下获取token的响应是什么：https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=&corpsecret=

**Comment by shmily90** [comment]
![image](https://user-images.githubusercontent.com/57162494/70699508-37b67300-1d04-11ea-826a-334fbdb3b8ca.png)
errcode返回的确是0

**Comment by hhyo** [comment]
注意隐私，刚刚的信息删除了，记得修改掉相关配置

可加几个log输出debug一下整个消息推送流程

**Comment by hhyo** [comment]
还请帮忙获取master的镜像做下验证

**Comment by shmily90** [comment]
原因找到了，不过还没有验证是我这边的问题还是bug

**Comment by shmily90** [comment]
![image](https://user-images.githubusercontent.com/57162494/70760458-a20ef800-1d84-11ea-9064-b5fe11e5c502.png)
打印日志出来的时候发现secret前面自动多了一个空格，所以通过fetch_url去访问的时候报了40001错误，无效的secret，加了个strip函数去除空格暂时把问题解决了，后续有时间的时候看下是secret是怎么存库和缓存，又是怎么get到的。

**Comment by hhyo** [comment]
昨天晚上的commit，修改了ak存取方式，同时消息格式也统一为text了，由于没有信息不方便测试，你可以通过拉取master镜像验证一下，注意master分支是不稳定版本，model可能也有变化，不要和现有DB共用

`docker pull hhyo/archery:master`

**Comment by hhyo** [comment]
> ![image](https://user-images.githubusercontent.com/57162494/70760458-a20ef800-1d84-11ea-9064-b5fe11e5c502.png)
> 打印日志出来的时候发现secret前面自动多了一个空格，所以通过fetch_url去访问的时候报了40001错误，无效的secret，加了个strip函数去除空格暂时把问题解决了，后续有时间的时候看下是secret是怎么存库和缓存，又是怎么get到的。

那就是在系统配置保存时多了空格

**Comment by shmily90** [comment]
好的  git刚开始接触，有些用法还不了解怎么做，见谅啊，谢谢帮忙解决问题
