### ISSUE TITLE
[ 功能建议 ]BLOB字段浮动显示

### ISSUE THREAD

**Issue by xhhao4** [hhyo/Archery#568]
### 目前遇到的问题/使用障碍
Oracle数据库的表中有个BLOB字段，里面存储的是BINARY格式的xml内容，SQL查询结果直接显示长串字符
### 希望如何解决/实现它
希望前端检测到内容是BINARY格式的数据后，能自动隐藏，点击后弹出一个窗口格式化显示内容

**Comment by LeoQuote** [comment]
听起来不太好做, 我们的table 用的是 bootstrap-table https://github.com/wenzhixin/bootstrap-table , 好像没看到有可以自定义字段然后响应点击事件, 然后解析binary什么的.

**Comment by LeoQuote** [comment]
后端返回也是序列化后的东西, 所以如果是blob类型, 应该会序列化失败, 所以这个涉及到的方面还挺多的, 欢迎贡献.

**Comment by xhhao4** [comment]
好的，明白了
