### ISSUE TITLE
[ bug ] 用户可访问其他资源组的实例

### ISSUE THREAD

**Issue by charnet1019** [hhyo/Archery#569]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

简单描述问题出现场景和重现步骤，如
1.  创建mysql实例testmysql.
2. 创建权限组dev和资源组dev
3. 添加用user1并关联权限组dev和资源组dev
4. user1登录后在在线查询中可选择其他资源组的实例

### 期待结果和实际结果
期待结果：只可访问和自己绑定的资源组实例

实际结果: 用户可访问其他资源组的实例

### 版本信息
应用版本/分支： 1.7.3

部署方式：Docker

**Comment by hhyo** [comment]
检查权限组的权限信息，是否存在可查询全部实例的权限，具体可参考文档权限组说明

**Comment by charnet1019** [comment]
不好意思回复晚了，是权限组的问题
