### ISSUE TITLE
[ 问题咨询 ] archery权限申请的记录在哪里

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#572]
archery审核平台的权限申请记录，管理员账号可以查询到吗？可以的话，在哪里可以查询到？

**Comment by hhyo** [comment]
SQL查询 权限管理列表就是申请记录

**Comment by dmz-leon** [comment]
> SQL查询权限管理列表就是申请记录

权限管理列表没有申请时间

**Comment by dmz-leon** [comment]
> SQL查询权限管理列表就是申请记录

权限管理列表没有记录权限申请时间

**Comment by hhyo** [comment]
不进具体的权限清单，外面的列表就是工单历史，列表和详情都有申请时的所有信息
