### ISSUE TITLE
[ 问题咨询 ]如何修改ldap信息的缓存时间

### ISSUE THREAD

**Issue by recoba87** [hhyo/Archery#574]
### 问题描述
因为我们的应用场景，想设置redis的key ttl过期，请问要哪里设置，或者如果把redis关闭不使用

### 版本信息
 手工部署

**Comment by hhyo** [comment]
目前只有配置项是不会过期，其他key都有过期设置，应该占用空间有限

**Comment by recoba87** [comment]
不是空间问题，我们接了ldap，最近有用户登录密码错误的问题，经查发现是因为dn信息是存在redis里的，如果ldap有用户转了ou，而redis里还是老的dn地址，这样会导致缓存的dn和实际ldap的dn不一致，导致用户登录不上，所以我们想把ttl设置都5秒过期，每次登陆都去取ldap的dn就不会错了

**Comment by hhyo** [comment]
检索了项目使用的ldap组件代码，参考 https://github.com/django-auth-ldap/django-auth-ldap/pull/42
增加AUTH_LDAP_CACHE_TIMEOUT=0 配置项应该可以处理这个问题

**Comment by recoba87** [comment]
你好，增加了AUTH_LDAP_CACHE_TIMEOUT=0 配置  测试了下用户dn信息还是会缓存到redis

**Comment by LeoQuote** [comment]
贴一下 你们环境的pip freeze ，确认一下当前的组件版本

**Comment by recoba87** [comment]
aliyun-python-sdk-core-v3==2.13.10
aliyun-python-sdk-rds==2.1.1
arrow==0.15.2
blessed==1.16.1
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
cryptography==2.8
cx-Oracle==7.1.3
Django==2.0.13
django-auth-ldap==1.3.0
django-mirage-field==0.0.3
django-picklefield==2.0
django-q==1.0.2
django-redis==4.10.0
gunicorn==19.9.0
idna==2.8
Jinja2==2.10.3
jmespath==0.9.4
MarkupSafe==1.1.1
mo-future==2.48.19205
moz-sql-parser==2.44.19084
mybatis-mapper2sql==0.1.9
mysql-replication==0.19
mysqlclient==1.3.13
phoenixdb==0.7
prettytable==0.7.2
protobuf==3.10.0
psycopg2-binary==2.8.3
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycparser==2.19
pycryptodome==3.8.2
pyecharts==1.5.0
pyldap==3.0.0.post1
pymongo==3.8.0
PyMySQL==0.9.3
pyodbc==4.0.26
pyparsing==2.4.2
python-dateutil==2.8.0
python-ldap==3.2.0
pytz==2019.3
redis==3.3.11
requests==2.21.0
simplejson==3.16.0
six==1.12.0
sqlparse==0.3.0
supervisor==4.1.0
tqdm==4.36.1
urllib3==1.24.3
wcwidth==0.1.7

**Comment by recoba87** [comment]
aliyun-python-sdk-core-v3==2.13.10
aliyun-python-sdk-rds==2.1.1
arrow==0.15.2
blessed==1.16.1
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
cryptography==2.8
cx-Oracle==7.1.3
Django==2.0.13
django-auth-ldap==1.3.0
django-mirage-field==0.0.3
django-picklefield==2.0
django-q==1.0.2
django-redis==4.10.0
gunicorn==19.9.0
idna==2.8
Jinja2==2.10.3
jmespath==0.9.4
MarkupSafe==1.1.1
mo-future==2.48.19205
moz-sql-parser==2.44.19084
mybatis-mapper2sql==0.1.9
mysql-replication==0.19
mysqlclient==1.3.13
phoenixdb==0.7
prettytable==0.7.2
protobuf==3.10.0
psycopg2-binary==2.8.3
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycparser==2.19
pycryptodome==3.8.2
pyecharts==1.5.0
pyldap==3.0.0.post1
pymongo==3.8.0
PyMySQL==0.9.3
pyodbc==4.0.26
pyparsing==2.4.2
python-dateutil==2.8.0
python-ldap==3.2.0
pytz==2019.3
redis==3.3.11
requests==2.21.0
simplejson==3.16.0
six==1.12.0
sqlparse==0.3.0
supervisor==4.1.0
tqdm==4.36.1
urllib3==1.24.3
wcwidth==0.1.7

**Comment by hhyo** [comment]
升级django-auth-ldap至1.6以上版本，重启服务

ldap个人目前使用的不多，相关使用和配置问题还请参考django-auth-ldap文档
