### ISSUE TITLE
[ 问题咨询 ]慢查日志功能，通过pt-query-digest无法往archery库中插入数据

### ISSUE THREAD

**Issue by shmily90** [hhyo/Archery#577]
### 问题描述
![image](https://user-images.githubusercontent.com/57162494/71233398-6ea60d80-2330-11ea-8dbd-710dcd2702a4.png)
脚本配置信息，hostname已配置，在执行脚本的时候，访问archery中的mysql_slow_query_review，和mysql_slow_query_review_history都没有数据，单独把脚本中关键步骤拿出来执行
![image](https://user-images.githubusercontent.com/57162494/71233524-d65c5880-2330-11ea-999c-7b67bb0a50f9.png)
hostname_max的值传了空，想了解下是怎么获取这个hostname_max，找了半天没知道投诉，求助

### 版本信息
 - 应用版本/分支：Release v1.7.2  
 - 部署方式：Docker

**Comment by shmily90** [comment]
![image](https://user-images.githubusercontent.com/57162494/71237879-a36c9180-233d-11ea-888c-a7e6bf0f6c8d.png)
sh -x 也没看出什么问题，只要把archery中的mysql_slow_query_review_history表hostname_max非空约束去掉，数据就能正常插入了，问题的确就出在获取hostname这里，求助。。

**Comment by shmily90** [comment]
![image](https://user-images.githubusercontent.com/57162494/71240435-16790680-2344-11ea-8015-a038614d20cc.png)
把获取client那段删掉问题解决了。。。

**Comment by hhyo** [comment]
或许是slow log中没有client信息导致解析异常
``` 
# Time: 2019-12-20T09:14:38.129137-00:00
# User@Host: inception[inception] @  [172.18.0.7]  Id:  4718
# Query_time: 0.024631  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0use archery;
SET timestamp=1576833278;
show create table `aliyun_rds_config`;
```
