### ISSUE TITLE
[ 问题咨询 ]SQL提交时候的需求链接填什么？

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#579]
### 问题描述
![1577067665(1)](https://user-images.githubusercontent.com/40845632/71331844-cc279d80-256e-11ea-8a88-abfddba5f110.jpg)

sql提交的时候，这里的需求链接必填项，大概填什么呢？不太理解
（截的图片上传访问不了，不好意思。。。）

### 版本信息
 - 应用版本/分支：Release v1.7 
 - 部署方式：Docker

**Comment by cnlong** [comment]
![1577067665(1)](https://user-images.githubusercontent.com/40845632/71331802-a8fcee00-256e-11ea-92a0-4850b3474606.jpg)

**Comment by hhyo** [comment]
可以多使用issue检索 #539 
在最新版本v1.7.4中，需求链接已修改为可选项，可参考Release Note
项目没有v1.7版本号，v1.7.0版本也并没有引入需求链接，issue提供的信息请务必准确，方便定位问题

**Comment by cnlong** [comment]
收到，使用的是v1.7.3
