### ISSUE TITLE
是否支持腾讯云数据库和阿里云数据库

### ISSUE THREAD

**Issue by changeyourt** [hhyo/Archery#58]
**重现步骤**
本次issue不是问题，而是简答的问题。

**截图**
本issue暂无截图。

**错误日志**
本issue暂无错误日志。

**版本信息**
docker部署。

**Comment by hhyo** [comment]
- 可以正常访问实例，能给账号开放相应权限，理论上就可以正常使用
- 针对阿里云RDS还可以进行会话和慢日志管理，具体可见：[RDS管理](https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E9%98%BF%E9%87%8C%E4%BA%91rds%E7%AE%A1%E7%90%86)
