### ISSUE TITLE
goinception配置报错

### ISSUE THREAD

**Issue by cnlong** [hhyo/Archery#580]
### 问题描述
配置项管理中的系统配置中，配置goinception时候，填入docker容器的名称goinception和4000端口号，点击测试goinception连接，报错“Internal Server Error”

请问这个是因为goception的服务没有起来吗？求解，感谢！

### 版本信息
 - 应用版本/分支：Release v1.7.3 
 - 部署方式：Docker

**Comment by hhyo** [comment]
麻烦提供一下日志信息

**Comment by cnlong** [comment]
只看到archery中有一条这个报错：MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
goinception中到没看到什么具体报错信息

**Comment by cnlong** [comment]
goinception中有这样一个报错

level=error msg="[kv:8]invalid transaction\ngithub.com/pingcap/errors.AddStack\n\t/share/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/share/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12\ngithub.com/hanchuanchuan/goInception/kv.RunInNewTxn\n\t/root/hcc/github.com/hanchuanchuan/goInception/kv/txn.go:67\ngithub.com/hanchuanchuan/goInception/ddl.(*ddl).genGlobalID\n\t/root/hcc/github.com/hanchuanchuan/goInception/ddl/ddl.go:429\ngithub.com/hanchuanchuan/goInception/ddl.(*ddl).CreateSchema\n\t/root/hcc/github.com/hanchuanchuan/goInception/ddl/ddl_api.go:52\ngithub.com/hanchuanchuan/goInception/executor.(*DDLExec).executeCreateDatabase\n\t/root/hcc/github.com/hanchuanchuan/goInception/executor/ddl.go:137\ngithub.com/hanchuanchuan/goInception/executor.(*DDLExec).Next\n\t/root/hcc/github.com/hanchuanchuan/goInception/executor/ddl.go:76\ngithub.com/hanchuanchuan/goInception/executor.(*ExecStmt).handleNoDelayExecutor\n\t/root/hcc/github.com/hanchuanchuan/goInception/executor/adapter.go:270\ngithub.com/hanchuanchuan/goInception/executor.(*ExecStmt).Exec\n\t/root/hcc/github.com/hanchuanchuan/goInception/executor/adapter.go:234\ngithub.com/hanchuanchuan/goInception/session.runStmt\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/tidb.go:148\ngithub.com/hanchuanchuan/goInception/session.(*session).executeStatement\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/session.go:844\ngithub.com/hanchuanchuan/goInception/session.(*session).execute\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/session.go:917\ngithub.com/hanchuanchuan/goInception/session.(*session).Execute\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/session.go:865\ngithub.com/hanchuanchuan/goInception/session.mustExecute\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/bootstrap.go:773\ngithub.com/hanchuanchuan/goInception/session.doDDLWorks\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/bootstrap.go:696\ngithub.com/hanchuanchuan/goInception/session.bootstrap\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/bootstrap.go:224\ngithub.com/hanchuanchuan/goInception/session.runInBootstrapSession\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/session.go:1278\ngithub.com/hanchuanchuan/goInception/session.BootstrapSession\n\t/root/hcc/github.com/hanchuanchuan/goInception/session/session.go:1212\nmain.createStoreAndDomain\n\t/root/hcc/github.com/hanchuanchuan/goInception/tidb-server/main.go:174\nmain.main\n\t/root/hcc/github.com/hanchuanchuan/goInception/tidb-server/main.go:141\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337" file=terror.go line=342

**Comment by hhyo** [comment]
拉取最新goInception镜像升级即可
