### ISSUE TITLE
[ 问题咨询 ]grant语句无法提交上线吗

### ISSUE THREAD

**Issue by huangyue5207** [hhyo/Archery#583]
### 问题描述
grant语句似乎无法被提交执行，即使配置的账号有grant的权限。

### 版本信息
 - 应用版本/分支：Release v1.6.2  
 - 部署方式：Docker

**Comment by hhyo** [comment]
目前不支持原生工单，近期也还没计划实现
新版已实现完整的用户授权管理，可以升级体验
