### ISSUE TITLE
[ 问题咨询 ]mysql实例数据库连接字符串超过60

### ISSUE THREAD

**Issue by Elipha** [hhyo/Archery#584]
### 问题描述
Archery在提交SQL上线后自动审核不通过，提示数据库实例字符串超过60字符(String '***' is too long for host name (should be no longer than 60).)。我将mysql的user表的host字段和db表的host字段长度修改成char(160)仍然没有解决，请各位大神帮忙，谢谢！

### 版本信息
 - 应用版本/分支：Release v1.7.2  
 - 部署方式：手工部署

**Comment by Elipha** [comment]
mysql实例数据库连接字符串超过60

**Comment by LeoQuote** [comment]
这个是由于备份的时候硬限制造成的限制，所以你应该用dns的cname或者什么把连接用的主机名缩短才可以，修改字段长度是没有用的

**Comment by Elipha** [comment]
> 
> 
> 这个是由于备份的时候硬限制造成的限制，所以你应该用dns的cname或者什么把连接用的主机名缩短才可以，修改字段长度是没有用的

我是连接微软云的PaaS DB，由于Azure Paas是禁ping的，所以不能返回IP，在实例列表中操作栏位里有测试连接的功能，显示是连接成功的。同样的，我用阿里云的RDS来测试，没有出现这个问题。

**Comment by hhyo** [comment]
可以看一下具体日志或者审核的信息，确认下是哪里返回的异常

**Comment by Elipha** [comment]
> 
> 
> 可以看一下具体日志或者审核的信息，确认下是哪里返回的异常

  Inception的日志如下，没有看出有异常，Archery的日志也没有什么发现。
27 Query     /*--user=al_user@sgsdbcne2mysqlautolimstestuat;--password=***;--host=sgsdbcne2mysqlautolimstestuat.mysql.database.chinacloudapi.cn;
                            --port=3306;--enable-check=1;*/
                            inception_magic_start;
                            use `autolims`;
                            insert into t(id,msg) values(12,'this is a test');
                            inception_magic_commit

**Comment by hhyo** [comment]
查阅一些信息，这个错误应该是inception本身所基于的mysql5.6版本抛出的异常，可尝试切换到goInception或者给域名添加cname解析，缩短连接

**Comment by hhyo** [comment]
待确认

**Comment by Elipha** [comment]
@hhyo ,有进展么？

**Comment by LeoQuote** [comment]
> 
> 
> 查阅一些信息，这个错误应该是inception本身所基于的mysql5.6版本抛出的异常，可尝试切换到goInception或者给域名添加cname解析，缩短连接

看看回复?

**Comment by Elipha** [comment]
用goinception已解决问题，Azure PaaS DB需开启log_bin，谢谢大家
