### ISSUE TITLE
[ 功能建议 ] 新注册用户登录，报数据加载失败

### ISSUE THREAD

**Issue by peng19832** [hhyo/Archery#585]
### 目前遇到的问题/使用障碍
开启自行注册，新注册用户登录，报数据加载失败
![image](https://user-images.githubusercontent.com/9590209/71548645-51d29f80-29ec-11ea-9f6e-3a1e91ed2c20.png)

### 希望如何解决/实现它
新用户登录，有点不太友好，可否加个引导页面，或初始欢迎页面。
比如，提示联系管理员开启权限，或申请需要的权限的工单。

**Comment by hhyo** [comment]
可设置默认权限组，配置相关初始权限，用户注册登录时会自动关联

**Comment by peng19832** [comment]
> 可设置默认权限组，配置相关初始权限，用户注册登录时会自动关联

喔，好的，谢谢

**Comment by peng19832** [comment]
> 可设置默认权限组，配置相关初始权限，用户注册登录时会自动关联

我在配置只允许查询的默认权限组，给了"菜单 在线查询"和“提交SQL查询”权限，也尝试加了几个其他的权限，但还是要弹这个窗口，请问依赖的基础权限是哪些呢？
![image](https://user-images.githubusercontent.com/9590209/71578300-894b6400-2b32-11ea-982c-55e9a6e46e6f.png)

**Comment by hhyo** [comment]
默认index是打开SQL审核列表，所以需要列表菜单权限和列表数据权限，如果希望默认进入查询页面可以修改系统配置中的index配置项，具体建议查看文档中的权限说明

**Comment by peng19832** [comment]
谢谢解答，明白了
