### ISSUE TITLE
[ 问题咨询 ] https配置

### ISSUE THREAD

**Issue by peng19832** [hhyo/Archery#586]
### 问题描述
请问，怎么配置https，连接加密？

### 版本信息
 - 应用版本/分支：Release v1.7.4  
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
可以参考 django 文档 https://docs.djangoproject.com/en/2.2/topics/security/#ssl-https 

然后在上一层比如 nginx 做 https -> http (django) 的转发即可.

这篇文章也可以参考一下:

https://juejin.im/post/5b2909bbf265da597901d2d5

这方面的文档还是空白, 欢迎补充.

**Comment by peng19832** [comment]
好的，我搞搞看，搞定补充上来

**Comment by peng19832** [comment]
我通过增加一个443端口映射，可以跳转https的加密连接。
但是，用https用户无法登录，报403错误forbidden
![image](https://user-images.githubusercontent.com/9590209/72144849-3300df80-33d4-11ea-810e-c068ded4dba2.png)
![image](https://user-images.githubusercontent.com/9590209/72144868-3eeca180-33d4-11ea-8909-919c94b55639.png)
![image](https://user-images.githubusercontent.com/9590209/72144886-4b70fa00-33d4-11ea-9346-35b7fd4119d0.png)

**Comment by LeoQuote** [comment]
看一下后台日志, 403 不一定是django 返回的, 可以看一下具体返回的body

**Comment by peng19832** [comment]
@LeoQuote 
nginx和supervisor，都开了debug日志。
supervisor日志没有异常打印。
nginx的debug信息中，在访问/authenticate/?时，报出了403
[debug.log](https://github.com/hhyo/Archery/files/4051904/debug.log)

**Comment by LeoQuote** [comment]
supervisor 的日志意义不大，看一下archery的日志，日志在archery 的 logs 或者 download/logs下面

**Comment by peng19832** [comment]
> supervisor 的日志意义不大，看一下archery的日志，日志在archery 的 logs 或者 download/logs下面

@LeoQuote 
archery的日志debug也开启的，只有第一次启动打印的这几句：
![image](https://user-images.githubusercontent.com/9590209/72230677-09250400-35f2-11ea-83e0-5dea27d2c7b1.png)

**Comment by LeoQuote** [comment]
实在不行你用runserver 启动服务器，然后再看控制台的日志，这个日志应该是很全的。

**Comment by peng19832** [comment]
喔，用runserver的方式，是正常的。
奇怪了
@LeoQuote

**Comment by LeoQuote** [comment]
这个你得自己去找找原因了，可能是你gunicorn 或者哪里配置不对。

**Comment by hhyo** [comment]
Archery域名已配置https ，具体和你上述的配置并无差异
https://archerydms.com/
