### ISSUE TITLE
[ bug ] goinception不支持commit语句

### ISSUE THREAD

**Issue by heistt** [hhyo/Archery#588]
应用版本/分支：
goinceotion1.1.4 
archery-1.7.1

部署方式：手工部署
goinception不支持commit语句，显示为error
![image](https://user-images.githubusercontent.com/18729728/71607888-2b615f80-2bb8-11ea-8d36-d632156cfd46.png)

切换为inception后，则变为warning
![image](https://user-images.githubusercontent.com/18729728/71607933-606db200-2bb8-11ea-8eeb-9da4b44d6e7a.png)

**Comment by LeoQuote** [comment]
从你的描述来看, 这似乎是goinception 的问题, 可以去 goinception 项目反馈此问题, 会利于问题的解决, archery 只是原样返回inception/goinception 的检查结果.

**Comment by hhyo** [comment]
https://github.com/hanchuanchuan/goInception/issues/146
