### ISSUE TITLE
[ 咨询建议 ] SQL审核上线审批流程

### ISSUE THREAD

**Issue by peng19832** [hhyo/Archery#589]
### 问题描述
大佬，我在用testuser01提交sql上线，要配置审批流程。
配置界面，这几项，我有点迷糊：
1、审批权限组列表、当前审批权限组、下级审批权限组，之间啥关系呢？
2、审核状态，是可选的，那每个工单，都要配一个流程吗？
3、申请人也需要填写，意思是最好只允许一个人提交上线工单？
![image](https://user-images.githubusercontent.com/9590209/71650914-76b07500-2d54-11ea-9ce8-cd63116f2b2a.png)

还有这个语法错误，是否符号解析有问题：
就是个简单的create语句
create table test_lee(id int unsigned auto_increment, name varchar(20), primary key(`id`))
![image](https://user-images.githubusercontent.com/9590209/71651346-cb092400-2d57-11ea-954d-f433de71205a.png)

还有建议：
1、组id，在选择组名称的时候，自动带上去；
2、关联业务id，可否改为可选项？

### 版本信息
 - 应用版本/分支：Release v1.7.4  
 - 部署方式：Docker

**Comment by hhyo** [comment]
审批流程的配置在系统配置中，你这个是工作流的审批列表

**Comment by peng19832** [comment]
> 审批流程的配置在系统配置中，你这个是工作流的审批列表

噢，尴尬，原来配错地方了。
我配好了，执行SQL检测，又报了这个，也没有配置自动驳回create语句，语句我单独执行没有问题：
![image](https://user-images.githubusercontent.com/9590209/71651999-01956d80-2d5d-11ea-9433-b4ac88ffc755.png)

**Comment by LeoQuote** [comment]
这不审核信息都写了吗? access denied 啥的, 你先把这错误消除了吧

**Comment by peng19832** [comment]
> 这不审核信息都写了吗? access denied 啥的, 你先把这错误消除了吧

这个我去库里手工执行过，是可以create成功的呢，就是在平台上会报这个拒绝。
我给了mysql库的访问权限通过了，这个是个风险点吧，可以看mysql里的表

**Comment by peng19832** [comment]
### 问题描述
环境：mgr + proxysql
配置：资源组里，配置了proxysql出来的服务端口
问题：测试审核语句通过后，点击上线执行失败，报错：
![image](https://user-images.githubusercontent.com/9590209/71660237-58af3880-2d85-11ea-9f38-3c788fb832ca.png)
尝试把实例端口改为后端mysql的主库端口，可以正常执行上线。

**Comment by hhyo** [comment]
proxysql和mgr，配置了读写分离吧，Archery执行前会通过select @@read_only来检查节点状态，这时候被proxy路由到读节点，就会禁止执行，其实proxysql不支持slave协议，没办法备份，平台还是配置主节点比较好

**Comment by peng19832** [comment]
> proxysql和mgr，配置了读写分离吧，Archery执行前会通过select @@read_only来检查节点状态，这时候被proxy路由到读节点，就会禁止执行，其实proxysql不支持slave协议，没办法备份，平台还是配置主节点比较好

这个的话，可不可以在实例数据库实例类型里，增加proxy，选择后，读写路由交给proxy判断

**Comment by hhyo** [comment]
也可以实现，不过通过proxy操作无法获取到binlog信息，也就没法备份

**Comment by peng19832** [comment]
> 也可以实现，不过通过proxy操作无法获取到binlog信息，也就没法备份

这个获取binlog信息，是要什么权限呢？
mgr日志是各节点完整同步的，理论上拿到任何节点的日志，都一样

**Comment by hhyo** [comment]
mysql节点无法通过change master到proxysql来建立主从关系，这也是同样的道理，通过proxysql是不能dump binlog的

**Comment by peng19832** [comment]
> mysql节点无法通过change master到proxysql来建立主从关系，这也是同样的道理，通过proxysql是不能dump binlog的

那我怎么修改下，可以临时解决这个read_only的问题？

**Comment by hhyo** [comment]
在proxysql上面给archery管理账号配置一条路由规则，强制路由到master就可以

**Comment by peng19832** [comment]
好的，谢谢，我试试看

**Comment by hhyo** [comment]
#409
