### ISSUE TITLE
[ 功能建议 ]  建议增加 查看SQL上线历史工单权限

### ISSUE THREAD

**Issue by frank0826** [hhyo/Archery#590]
目前业务研发只能查看当前用户自己提交的sql 上线工单,不能查询组内其他同学提交的工单;授权同组内的用户可以查看本组内所有人提交的工单,仅且只有读权限

**Comment by LeoQuote** [comment]
目前是有审核权限的可以看到组内所有工单

https://github.com/hhyo/Archery/blob/edf7fa5667eca4df5ad26fb2b207049b2c75726c/sql/sql_workflow.py#L70-L77

**Comment by hhyo** [comment]
嗯，目前是有审核权限或者组内执行权限的可以看到所有的，其他访问做了鉴权

**Comment by hhyo** [comment]
无后续反馈，关闭处理
