### ISSUE TITLE
[ 问题咨询 ]如何查看目前的archery版本

### ISSUE THREAD

**Issue by DBAyan** [hhyo/Archery#593]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
以demo 为例, http://139.199.0.191/api/info 可以看到简单的版本信息, 在用超级管理员账号登录后 http://139.199.0.191/api/debug 可以看到详细的参数.

比较旧的版本可以在登录界面看到版本号
