### ISSUE TITLE
[ 功能建议 ]增加对多个阿里云主账号下的AccessKey的支持

### ISSUE THREAD

**Issue by zwunix** [hhyo/Archery#596]
### 目前遇到的问题/使用障碍
由于存在多个阿里云主账号的RDS资源，不方便对所有的资源进行管理

### 希望如何解决/实现它
增加对多个阿里云主账号下的AccessKey的支持

**Comment by hhyo** [comment]
多账号，又得回归配置表了，对云实例的接入目前其实做的不多

**Comment by zwunix** [comment]
应该很多中小企业都是用云的咯

**Comment by hydgladiator** [comment]
是有新的版本支持多阿里云认证信息么？

**Comment by hydgladiator** [comment]
从哪个版本开始支持多个阿里云主账号下的AccessKey？？

**Comment by hhyo** [comment]
> 从哪个版本开始支持多个阿里云主账号下的AccessKey？？

https://github.com/hhyo/Archery/releases/tag/v1.7.11

**Comment by hydgladiator** [comment]
请问是否有 k8s部署的方式？ discussion中无法添加问题

在 2022年6月14日，下午7:05，小圈圈 ***@***.******@***.***>> 写道：



从哪个版本开始支持多个阿里云主账号下的AccessKey？？

https://github.com/hhyo/Archery/releases/tag/v1.7.11
