### ISSUE TITLE
sql上线选择不到实例

### ISSUE THREAD

**Issue by 0000005** [hhyo/Archery#597]
### 问题描述
我创建了实例，也创建了资源组，也绑定了之间的关系。如下图：
![image](https://user-images.githubusercontent.com/9690089/72324226-6057d100-36e5-11ea-89d6-a3f97cbb30c3.png)
![image](https://user-images.githubusercontent.com/9690089/72324233-664db200-36e5-11ea-8141-69cf76855129.png)
![image](https://user-images.githubusercontent.com/9690089/72324239-6b126600-36e5-11ea-9fec-aa6948b7a747.png)
![image](https://user-images.githubusercontent.com/9690089/72324408-d5c3a180-36e5-11ea-92a5-7dd291598cbd.png)

但是，使用sql上线模块，无法选择到实例。是我哪里操作有问题吗？
### 版本信息
 - 部署方式：Docker-compose
 - 应用版本/分支：hhyo/archery:1.7.4

**Comment by hhyo** [comment]
实例编辑时给实例关联支持上线的标签，这点文档实例管理中有说明
>通过实例标签：支持上线、支持查询来控制实例是否在SQL上线/查询中显示

**Comment by 0000005** [comment]
谢谢
