### ISSUE TITLE
[ bug ] 查看回滚sql异常

### ISSUE THREAD

**Issue by 0000005** [hhyo/Archery#599]
### 重现步骤

1、创建一个上线工单
2、审核通过后，进行手工执行。（然而我并不知道这里的手工执行是什么意思，于是我什么都没做）
3、弹出框确定已经手工执行。
4、点击查看回滚sql，结果报错。

执行的sql为（就是archery里面的表）：update archery.auth_permission set id=1111 where id=112312

### 期待结果和实际结果
期待结果：
看到回滚sql
实际结果:
报错
### 截图
![image](https://user-images.githubusercontent.com/9690089/72333210-63a78880-36f6-11ea-9bc2-97d1f48d6992.png)

 
### 错误日志
![image](https://user-images.githubusercontent.com/9690089/72333240-6dc98700-36f6-11ea-984b-b8850b66b35c.png)

### 版本信息
应用版本/分支：hhyo/archery:1.7.4 
部署方式：Docker

**Comment by 0000005** [comment]
另外，手工执行到底是啥意思，什么场景能用到，能解释下吗？

**Comment by hhyo** [comment]
步骤写的很详细，其实可以先看看文档
https://github.com/hhyo/archery/wiki/%E9%85%8D%E7%BD%AE%E9%A1%B9%E8%AF%B4%E6%98%8E#mannual

**Comment by 0000005** [comment]
手工执行是不是意味着，没有经过archery执行，archery的作用仅仅只是记录一下。
我完全可以通过navicat去执行。所有也就没有“回滚sql”。
这样理解对吗？

**Comment by hhyo** [comment]
对，手工执行archery仅记录，改工单状态，不操作执行

**Comment by 0000005** [comment]
好的 
谢谢
