### ISSUE TITLE
SOAR无执行权限

### ISSUE THREAD

**Issue by eason0420** [hhyo/Archery#6]
我是用docker1.3.5 运行的， 用sqladvisr优化建议报错如下

ERROR:default:Traceback (most recent call last):
  File "/opt/archery/sql/sql_advisor.py", line 56, in sqladvisor
    stdout, stderr = p.communicate()
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 1554, in _communicate
    self.stdout.errors)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 740, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 453: invalid start byte

**Comment by hhyo** [comment]
在[体验地址](http://13.251.244.118/)可以重现该问题吗，或者尝试不使用archery，直接命令行查看输出什么结果。

**Comment by eason0420** [comment]
可以了，应该是写的SQL问题， 现在又另一个问题，我新建一个用户，分配他部分权限，SQLAdvisor和SQLTunning都可以，但是SOAR无执行权限。我看权限明细里没有执行SOAR这一权限.
我是用docker1.3.5版本初始化的权限，这里面没有执行SOAR

**Comment by hhyo** [comment]
这块在model文件遗漏了，仅写在release版本说明里面，自己手动增加一下也可以。
```
-- 增加执行SOAR权限
set @content_type_id=(select id from django_content_type where app_label='sql' and model='permission');
INSERT INTO auth_permission (name, content_type_id, codename) VALUES ('执行SOAR', @content_type_id, 'optimize_soar');
```

**Comment by eason0420** [comment]
ok，谢了
