### ISSUE TITLE
[ 问题咨询 ]如何设置脱敏字段和脱敏规则

### ISSUE THREAD

**Issue by 0000005** [hhyo/Archery#607]
### 问题描述
我没找到可以设置脱敏字段和脱敏规则地方，文档好像也没说。

### 版本信息
 - 应用版本/分支：hhyo/archery:1.7.4
 - 部署方式：Docker

**Comment by 0000005** [comment]
而且开启了，好像也没有默认规则，或者说没效果
![image](https://user-images.githubusercontent.com/9690089/72509353-60d99e80-3882-11ea-9647-a62f20e27012.png)
![image](https://user-images.githubusercontent.com/9690089/72509420-7f3f9a00-3882-11ea-8afb-44e699a9822d.png)

**Comment by 0000005** [comment]
是我的用法有问题吗

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#sql%E6%9F%A5%E8%AF%A2

https://github.com/hhyo/archery/wiki/faq#%E8%84%B1%E6%95%8F%E6%9F%A5%E8%AF%A2%E8%A7%84%E5%88%99%E6%9C%AA%E7%94%9F%E6%95%88

**Comment by 0000005** [comment]
脱敏表名支持正则吗，因为会有很多动态分表的名称
![image](https://user-images.githubusercontent.com/9690089/72516338-718f1200-388c-11ea-9619-0fef67dadb2c.png)

**Comment by 0000005** [comment]
比如 t_pms_inhouse_order_2020111213

**Comment by hhyo** [comment]
正则匹配？好想法！
不过目前不支持，hhh参考faq的快捷配置脚本吧

**Comment by 0000005** [comment]
好的，我看看
