### ISSUE TITLE
sql 优化模块 无法选择实例

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/Archery#608]
点击 sql优化 大菜单
点击 优化工具  
右侧的  请选择实例 不显示任何实例  
事实是我已经添加了两个实例。

**Comment by hhyo** [comment]
用户只能查看所在资源组关联的实例，确认用户是否关联了资源组，实例是否关联了资源组

可以先看文档，理解里面的隔离逻辑

**Comment by anchen418857063** [comment]
我用的是超级管理员 archery 用户登陆进去的，这个应该不需要关联实例就可以看见吧

**Comment by hhyo** [comment]
需要提供更多实例配置信息，SQL优化模块仅支持MySQL，非MySQL实例不会展示

**Comment by anchen418857063** [comment]
好的，谢谢。
