### ISSUE TITLE
工作流问题

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/Archery#609]
设置了工作流 A->B 
A具有提交SQL申请权限

B具有审核 及 执行权限
两个用户均有实例 权限
问题：
在A 提交了工单后 B 用户登陆系统后无法 看到 A提交申请审核的工单。

请问是否 只有 超级管理员角色 才有 审核的权限？

**Comment by hhyo** [comment]
多看文、多检索issue、再者请按模板提交

https://github.com/hhyo/archery/wiki/FAQ#审核人无法查看申请人提交的工单

**Comment by hhyo** [comment]
#84
