### ISSUE TITLE
[ bug ]提交工单时，清空已选定的可执行时间范围不起作用，

### ISSUE THREAD

**Issue by xxlrr** [hhyo/Archery#613]
### 重现步骤
1. 在提交SQL页面，完整填写工单内容后，选中一个合法的可执行时间范围并确定
2. 再次选定可执行时间范围并点击清空，可见可执行时间范围文本框内容已被清空
3. 点击SQL提交按钮提交工单
4. 页面跳转到刚提交的工单详情页面发现可执行时间范围仍然存在

### 期待结果和实际结果
期待结果：
工单内可执行时间范围为空
实际结果:
残留被清空前的可执行时间范围

### 截图
![aaa](https://user-images.githubusercontent.com/50319294/72695395-5154a100-3b73-11ea-8f0c-ac73b301e5c8.gif)

### 错误日志
无错误

### 版本信息
应用版本/分支：Archery v1.7.4 / Master

部署方式：手工部署

### 修补建议
在清空事件中增加可执行时间范围重置代码
![bbb](https://user-images.githubusercontent.com/50319294/72695582-fd968780-3b73-11ea-844f-0a50ab570ca0.png)

**Comment by hhyo** [comment]
感谢反馈，作日已修复，见https://github.com/hhyo/Archery/commit/59a8d93bd38d04cb0c0259958d07d413c1c9f3a6

1.7.5版本后续发布
