### ISSUE TITLE
[ bug ]在管理后台添加阿里云 access key 报错 ak 太长

### ISSUE THREAD

**Issue by lxkaka** [hhyo/Archery#614]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

在管理后台添加阿里云 access key 时报错如下  
`DataError at /admin/sql/aliyunaccesskey/add/
(1406, "Data too long for column 'ak' at row 1")`

### 期待结果和实际结果
期待结果：添加阿里云 ak 和 secret 成功

实际结果: 报错 `(1406, "Data too long for column 'ak' at row 1")`

### 版本信息
应用版本/分支：v1.6.7

部署方式：helm(k8s)

**Comment by LeoQuote** [comment]
这个表在当前版本中已经没了, 你可以alter 一下把这个字段扩长一些, 比如 200/500 这样

**Comment by lxkaka** [comment]
好的, 感谢!
