### ISSUE TITLE
[ bug ]提交SQL资源组选择时出现“客串”问题

### ISSUE THREAD

**Issue by fancy-lee** [hhyo/Archery#615]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 期待结果和实际结果
期待结果：
提交SQL选择资源组后，选择机器时只显示本资源组的机器
实际结果:
提交sql选择组后，除mysql以外的数据库会显示之前【选择过】组的机器（如图1的操作），如果选择其它组的机器还可以提交成功
### 截图
![image](https://user-images.githubusercontent.com/23489502/72779141-0069a900-3c56-11ea-8fa0-1d39ea6cbcbd.png)
![image](https://user-images.githubusercontent.com/23489502/72779609-7a4e6200-3c57-11ea-9f28-cf52d28fc3d8.png)

 
### 版本信息
应用版本/分支：

部署方式：手工部署
 v1.7.2

**Comment by hhyo** [comment]
感谢反馈，由于暂时不支持mongodb的上线，所以切换时未作重置处理，会出现在这个现象，后续处理

**Comment by fancy-lee** [comment]
怎么处理？我现在已经支持mongo了，正在内测中，到时候提pr

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/59a8d93bd38d04cb0c0259958d07d413c1c9f3a6/sql/templates/sqlsubmit.html#L602

照样增加一行就可以了

**Comment by fancy-lee** [comment]
完美解决

**Comment by fancy-lee** [comment]
感谢

**Comment by LeoQuote** [comment]
期待你的pr
