### ISSUE TITLE
[ 问题咨询 ]archery配置企业微信，无法收到推送消息

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#619]
archery已升级到1.7.5版本，配置企业微信的CorpId，AgentId和Secret后，审批消息仍无法收到

**Comment by LeoQuote** [comment]
发一下后台日志看看

**Comment by hhyo** [comment]
升级1.7.6，昨天临时修复的版本~

**Comment by hhyo** [comment]
`itertools.chain()`返回的是迭代器，邮件遍历后就获取不到钉钉用户信息了

**Comment by dmz-leon** [comment]
> 升级1.7.6，昨天临时修复的版本~

1.7.5是还没修复好？

**Comment by hhyo** [comment]
> > 升级1.7.6，昨天临时修复的版本~
> 
> 1.7.5是还没修复好？

修复了ak存储的，但是整合发送方法，引入了一个新的问题，可以升级1.7.6确认下

**Comment by dmz-leon** [comment]
> > > 升级1.7.6，昨天临时修复的版本~
> > 
> > 
> > 1.7.5是还没修复好？
> 
> 修复了ak存储的，但是整合发送方法，引入了一个新的问题，可以升级1.7.6确认下

钉钉的机器人推送一直是能收到审批通过的推送消息，申请审批的消息没办法进行推送吗？

**Comment by hhyo** [comment]
申请审批这边验证是可以接受到的

**Comment by dmz-leon** [comment]
> 申请审批这边验证是可以接受到的

申请审批的验证是指有审批权限的账户审批通过的消息吧，那么申请人发起申请的消息能收到吗？
比如我申请一个数据库的查询权限这个动作，能有推送消息收到吗？

**Comment by hhyo** [comment]
https://demo.archerydms.com/detail/932/

![image](https://user-images.githubusercontent.com/8842982/73710689-a8e03880-473f-11ea-8bec-0431814be4d6.png)

你可以修改demo环境的机器人地址为你自己的测试地址，验证一下

**Comment by dmz-leon** [comment]
> https://demo.archerydms.com/detail/932/
> 
> ![image](https://user-images.githubusercontent.com/8842982/73710689-a8e03880-473f-11ea-8bec-0431814be4d6.png)
> 
> 你可以修改demo环境的机器人地址为你自己的测试地址，验证一下

这个是除了配置资源组的webhook地址 还有其他需要配置的吗？

**Comment by hhyo** [comment]
开启Webhook通知同时配置Webhook地址，该资源组的通知就都会通过机器人推送

修改setting.py中的日志等级为DEBUG可以打印更多通知信息，多看看日志
https://github.com/hhyo/Archery/blob/4d3abf4f485456c67f9a447e10bebe5c5292c787/archery/settings.py#L236

**Comment by dmz-leon** [comment]
> 开启Webhook通知同时配置Webhook地址，该资源组的通知就都会通过机器人推送
> 
> 修改setting.py中的日志等级为DEBUG可以打印更多通知信息，多看看日志
> https://github.com/hhyo/Archery/blob/4d3abf4f485456c67f9a447e10bebe5c5292c787/archery/settings.py#L236

能加个微信或者qq的联系方式吗？想详细沟通一下

**Comment by hhyo** [comment]
可邮件沟通，不过更建议通过issue，企业微信的通知问题如果在1.7.6已确认解决，请关闭issue，谢谢

**Comment by dmz-leon** [comment]
> 可邮件沟通，不过更建议通过issue，企业微信的通知问题如果在1.7.6已确认解决，请关闭issue，谢谢

[2020-02-04 14:40:37,652][MainThread:140257648260928][task_id:default][wx_api.py:32][ERROR]- 获取企业微信access_token出错:{'errcode': 40013, 'errmsg': 'invalid corpid, hint: [1580798437_47_852d2e4df68f308e287bfa3d985ce528], from ip: 114.116.2.182, more info at https://open.work.weixin.qq.com/devtool/query?e=40013'}
[2020-02-04 14:40:37,907][MainThread:140257648260928][task_id:default][sendmsg.py:182][ERROR]- 企业微信推送失败


> 可邮件沟通，不过更建议通过issue，企业微信的通知问题如果在1.7.6已确认解决，请关闭issue，谢谢

**Comment by dmz-leon** [comment]
> > 可邮件沟通，不过更建议通过issue，企业微信的通知问题如果在1.7.6已确认解决，请关闭issue，谢谢
> 
> [2020-02-04 14:40:37,652][MainThread:140257648260928][task_id:default][wx_api.py:32][ERROR]- 获取企业微信access_token出错:{'errcode': 40013, 'errmsg': 'invalid corpid, hint: [1580798437_47_852d2e4df68f308e287bfa3d985ce528], from ip: 114.116.2.182, more info at [https://open.work.weixin.qq.com/devtool/query?e=40013'}](https://open.work.weixin.qq.com/devtool/query?e=40013'%7D)
> [2020-02-04 14:40:37,907][MainThread:140257648260928][task_id:default][sendmsg.py:182][ERROR]- 企业微信推送失败
> 
> > 可邮件沟通，不过更建议通过issue，企业微信的通知问题如果在1.7.6已确认解决，请关闭issue，谢谢

[2020-02-04 14:40:37,652][MainThread:140257648260928][task_id:default][wx_api.py:32][ERROR]- 获取企业微信access_token出错:{'errcode': 40013, 'errmsg': 'invalid corpid, hint: [1580798437_47_852d2e4df68f308e287bfa3d985ce528], from ip: 114.116.2.182, more info at https://open.work.weixin.qq.com/devtool/query?e=40013'}
[2020-02-04 14:40:37,907][MainThread:140257648260928][task_id:default][sendmsg.py:182][ERROR]- 企业微信推送失败

推送企业微信还需要自己配置接口吗？

**Comment by hhyo** [comment]
invalid corpid

检查下配置，注意前后空格，这个后面这边也得过滤下

**Comment by dmz-leon** [comment]
> invalid corpid
> 
> 检查下配置，注意前后空格，这个后面这边也得过滤下

我检查了一下配置，现在日志里面没有一点企业微信的信息了

**Comment by hhyo** [comment]
推送成功会打印debug日志，请确认已设置日志等级为debug
https://github.com/hhyo/Archery/blob/52f5533968dc042098ffcf9d6ad2e9d534af3ff1/common/utils/sendmsg.py#L161

**Comment by dmz-leon** [comment]
> 推送成功会打印debug日志，请确认已设置日志等级为debug
> https://github.com/hhyo/Archery/blob/52f5533968dc042098ffcf9d6ad2e9d534af3ff1/common/utils/sendmsg.py#L161

权限申请的时候，企业微信推送的请求里面，总是取不到touser这个参数

**Comment by hhyo** [comment]
版本？
同时通知对象可以参考文档，确保满足需求

**Comment by dmz-leon** [comment]
> 版本？
> 同时通知对象可以参考文档，确保满足需求

1.7.6的版本，现在是审批通过的消息可以通过企业微信推送，但是申请审批的消息，收不到

**Comment by hhyo** [comment]
按照消息文档说明列出你的几个配置出来看看吧
https://archerydms.com/modules/#_6
