### ISSUE TITLE
上传8M多的SQL文件报错

### ISSUE THREAD

**Issue by arnoldlee128** [hhyo/Archery#621]
### 问题描述
我在上传8M多的SQL 文件的时候，在点击SQL检测等待一会返回信息：Bad Request

### 版本信息
 - 应用版本/分支：Release v1.7.4 
 - 部署方式：Docker

![深度截图_选择区域_20200205213633](https://user-images.githubusercontent.com/54702004/73846518-9f4df200-485f-11ea-9353-9546fc0b7425.png)

**Comment by hhyo** [comment]
可进docker容器确认下nginx的日志信息，同时也关注下archery本身的日志

**Comment by arnoldlee128** [comment]
nginxlog日志： 
POST /simplecheck/ HTTP/1.1" 400 13830 "https://sql.mydevops.tools/submitsql/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
docker logs archery log　并没有发现日志

**Comment by hhyo** [comment]
这个是access.log，看下error.log
