### ISSUE TITLE
[ 功能建议 ]建议慢查日志页面增加分享功能，以便嵌入其它平台

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#622]
### 目前遇到的问题/使用障碍
慢查日志页面无分享功能，无法嵌入其它平台
### 希望如何解决/实现它
建议慢查日志页面增加分享功能，以便嵌入其它平台

**Comment by hhyo** [comment]
目前外部对接和open api暂时都没有实现的计划
