### ISSUE TITLE
[ 问题咨询 ]sql查询菜单下的查询申请

### ISSUE THREAD

**Issue by cheekboy** [hhyo/Archery#626]
### 问题描述
sql查询菜单下可以看到某个实例下的库  那么查询申请是在什么时候会用到？ 目前看没有意义 
是权限配置有问题么？

**Comment by hhyo** [comment]
用户默认可以看到所在资源组的查询实例，以及可以查看表结构，但是真正在查询数据时会去检验用户权限，这时候就必须要用户去申请

**Comment by hhyo** [comment]
如果你的用户没有申请权限就可以查询数据，有三个可能
- 用户是超级管理员
- 用户拥有可查询所有实例的权限
- 用户拥有可查询所有资源组实例的权限

以上三种情况，不会去检验用户是否申请了权限，具体每个权限的作用可以看文档权限组的说明

**Comment by cheekboy** [comment]
了解了  谢谢哈
