### ISSUE TITLE
[ 问题咨询 ] SQL上线时，如果先选择了sql文件，然后选择分组和数据库时，sql会被清除掉

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#628]
目前使用的1.7.7版本的archery
SQL上线时，如果先选择了sql文件，然后选择分组和数据库时，sql会被清除掉

**Comment by hhyo** [comment]
需要按照选择的实例来展示提示信息，确实是会清除

**Comment by dmz-leon** [comment]
> 需要按照选择的实例来展示提示信息，确实是会清除

之前习惯性先选择sql文件，然后选择示例和数据库，这个可以改进吗？

**Comment by hhyo** [comment]
可以调整为把提示信息插入到文本最前面

**Comment by dmz-leon** [comment]
> 可以调整为把提示信息插入到文本最前面

怎么调整呢
