### ISSUE TITLE
人工终止审核工单，无邮件通知

### ISSUE THREAD

**Issue by RoseTang-c** [hhyo/Archery#629]
重现步骤：

1、开发人员提交工单，有邮件通知
2、DBA发现工单SQL语句有问题，终止工单。这个时候开发人员收不到审核不通过的邮件。

邮件服务器正常。其他流程邮件正常接收。

**Comment by LeoQuote** [comment]
请按格式提供所需要的信息, 谢谢

**Comment by hhyo** [comment]
麻烦提供一下版本和部署方式，还有确认一下日志文件信息，如果每次都可以重现，可以修改settings.py的日志等级为debug，查看详细的日志输出
