### ISSUE TITLE
[ bug ]多次刷新SQL工单详情时，工单内容出现重复

### ISSUE THREAD

**Issue by hhyo** [hhyo/Archery#63]
仅v1.4.0以前产生的旧数据会出现该情况，新数据不会

**重现步骤**
- 打开工单详情：http://139.199.0.191/detail/6/
- 多次刷新，详情的SQL列表出现重复

**截图**
![image](https://user-images.githubusercontent.com/8842982/54005625-1cc33b00-4195-11e9-89a3-950c8903e6d7.png)

**错误日志**
无，仅前端展示异常

**版本信息**
 - 应用版本   v1.4.3
 - 部署方式   Docker

**Comment by LeoQuote** [comment]
出现原因是 https://github.com/hhyo/archery/blob/master/sql/engines/models.py#L42 使用了空列表作为默认参数初始化对象属性, 并且在代码中使用了原地修改的方法修改对象属性， 这就等同于修改了对象的默认值。

解决方案是将对象属性的默认值改为``None``， 然后在init中判断，如果是None就置为空列表``[]``

这样的话，这个空列表是新生成的空列表， 而不是默认参数的那个列表，也就不会影响到之后生成的心对象

参考：
 https://stackoverflow.com/questions/366422/what-is-the-pythonic-way-to-avoid-default-parameters-that-are-empty-lists

**Comment by LeoQuote** [comment]
经测试已修复. http://139.199.0.191/detail/6/
