### ISSUE TITLE
【bug】审核不通过，备注过长时，回车换行符不起作用

### ISSUE THREAD

**Issue by RoseTang-c** [hhyo/Archery#630]
复现步骤：
1、开发人员提交工单
2、DBA审核，发现工单有错误，在备注处写好审核不通过原因，内容举例：
a、主键错误
b、索引命名错误
c、默认值错误

3、终止流程
4、当开发人员查看终止流程原因时，备注内容如下：
a、主键错误b、索引命名错误c、默认值错误

页面显示有点不友好，都没有回车换行了。若原因过长，看着要命。

**Comment by hhyo** [comment]
确实有发现这个问题，后续改进

**Comment by RoseTang-c** [comment]
我们公司正打算使用Archery来审核，我已部署完成，下周打算通知公司所有开发人员使用Archey，这个bug能尽快安排吗？
