### ISSUE TITLE
[ 功能建议 ]列表显示希望默认是“工单完整名字”

### ISSUE THREAD

**Issue by RoseTang-c** [hhyo/Archery#632]
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
为了页面显示，默认截取20字符，同时鼠标停留会显示完整信息
如果显示完整名称，工单名50字，整个页面展示就乱了

**Comment by byp-yezi** [comment]
> 为了页面显示，默认截取20字符，同时鼠标停留会显示完整信息 如果显示完整名称，工单名50字，整个页面展示就乱了

版本1.9.1；导出为csv时，工单名称不是完整的，能解决这个问题嘛。

**Comment by hhyo** [comment]
列表右侧可以选择显示完整名称列再导出

**Comment by byp-yezi** [comment]
> 列表右侧可以选择显示完整名称列再导出

好的，看到了。多谢
