### ISSUE TITLE
[ 问题咨询 ] docker build过程中一直失败，构建失败

### ISSUE THREAD

**Issue by shangjing105** [hhyo/Archery#636]
### 问题描述
docker build过程中一直失败，构建失败

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker

在使用源码docker build过程中一直下载失败，不能构建成功。

错误信息：
http://repo.percona.com/percona/yum/release/7/RPMS/noarch/repodata/98754aa39f7494e49dd59896c3490cc718ec4c46b3a12718d652b599e4903c80-primary.sqlite.bz2: [Errno 12] Timeout on http://repo.percona.com/percona/yum/release/7/RPMS/noarch/repodata/98754aa39f7494e49dd59896c3490cc718ec4c46b3a12718d652b599e4903c80-primary.sqlite.bz2: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.

希望帮忙解决下，感谢。

建议将wiki文档，dockerfile构建步骤完善下。感谢

**Comment by LeoQuote** [comment]
这个问题应该是网络问题，你了解下怎么翻一下墙，或者看一下有没有国内镜像。

docker构建这块因为比较简单也一直没人提过所以没写。

wiki是开放编辑的，欢迎贡献。

**Comment by shangjing105** [comment]
需要翻墙比较麻烦，Mac系统怎么更换国内yum镜像？
dockerfile能不能简化一些，构建的镜像小一点。

**Comment by hhyo** [comment]
依赖多，同时为了避免项目体积过大，构建资源全部采用在线下载，所以对网络要求高，建议使用dockerhub，避免本地构建

如果有优化方案可以直接提交PR

**Comment by shangjing105** [comment]
项目更改了一些东西，想重新构建然后部署，但是怎么构建都失败。
在本地已经有下载的依赖资源的情况下，可以给一份如何将本地资源加载进去，不从网络下载的dockerfile吗？
不从网络下载，直接从本地加载进去。非常感谢！

**Comment by LeoQuote** [comment]
如果你是k8s , 可以通过emptydir 和 init container 配合更新代码.

**Comment by LeoQuote** [comment]
如果是本地可以用docker 的volume直接挂载进去

**Comment by shangjing105** [comment]
问题已解决，网络问题。
