### ISSUE TITLE
[ 问题咨询 ] 提交sql审核工单报 inception_magic_start是怎么回事

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#638]
### 问题描述
sql审核----提交sql------选择具体实例信息-----填写sql语句：create table czx (id int); ----sql审核报错
![image](https://user-images.githubusercontent.com/13861904/75001514-90408400-549c-11ea-973c-321c48d829af.png)
![image](https://user-images.githubusercontent.com/13861904/75001525-9a628280-549c-11ea-869d-8cf71a27c0d5.png)

使用的是goinception：
![image](https://user-images.githubusercontent.com/13861904/75002260-bcf59b00-549e-11ea-946f-b6cb8292f95a.png)

### 版本信息
 - 应用版本：Release v1.7.6
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
检查下你的数据库连接对不对

**Comment by czxin788** [comment]
> 检查下你的数据库连接对不对

![image](https://user-images.githubusercontent.com/13861904/75005833-9dfd0600-54aa-11ea-9ce8-54c35a0b495b.png)

实例列表里面的数据库连接是通的，但是还是不行。

**Comment by LeoQuote** [comment]
🤔 为啥port 是0 也能连接成功.....

**Comment by czxin788** [comment]
> 检查下你的数据库连接对不对

![image](https://user-images.githubusercontent.com/13861904/75005833-9dfd0600-54aa-11ea-9ce8-54c35a0b495b.png)

实例列表里面的数据库连接是通的，但是还是不行。

> 🤔 为啥port 是0 也能连接成功.....

谢谢，把0改成3306就正常了。
我还以0是默认的意思呢

**Comment by LeoQuote** [comment]
为0的话不应该连接成功, 可能是mysqldb 那边连接成功了....但是goinception没连接成功, 看了下源码mysqlclient 的默认port 也是0, 可能是这个原因.

https://github.com/PyMySQL/mysqlclient-python/blob/4c1950148ba10e23017bd5190f9da6bdb347e6b3/MySQLdb/_mysql.c#L415 

感觉要么无视, 要么改goinception.

**Comment by czxin788** [comment]
感谢感谢，辛苦了

**Comment by hhyo** [comment]
https://github.com/hanchuanchuan/goInception/blob/c3982056fe6b493139c6f5478f73fb4008a9f01a/session/errors.go#L405
```
ER_SQL_INVALID_SOURCE:               "不正确的数据源信息.",
```

https://github.com/hanchuanchuan/goInception/blob/090583b5baae7f4e12ff1f1501116b5026229030/session/session_inception.go#L2844
```
	// 不再检查密码是否为空
	if s.opt.host == "" || s.opt.port == 0 || s.opt.user == "" {
		log.Warningf("%#v", s.opt)
		s.AppendErrorNo(ER_SQL_INVALID_SOURCE)
		return
	}
```

这应该比较清晰了

**Comment by LeoQuote** [comment]
感觉可以再清晰一些，“不正确的数据源信息：端口不存在或为0，或用户名为空”

**Comment by hhyo** [comment]
> 感觉可以再清晰一些，“不正确的数据源信息：端口不存在或为0，或用户名为空”

哈哈，是的，我是说问题看起来比较清晰，此处 @hanchuanchuan 大佬

**Comment by hanchuanchuan** [comment]
感谢建议，后续会优化goinception～
