### ISSUE TITLE
本地pycharm打开项目，启动django服务，sql无法执行

### ISSUE THREAD

**Issue by sky1006** [hhyo/Archery#64]
>【bug】工单执行完成后，页面不会刷新，需要手动刷新，才会变成结束状态

**重现步骤**
1.4.3，提交sql，审核，执行，然后状态一直是执行中，实际查看数据库发现，语句是没有发送到数据库执行。
好像缺个服务，1.4.2没有这种情况；
同样的代码放到docker里面启动，就正常

**错误日志**
没有错误日志

**版本信息**
 - 应用版本：1.4.3
 - 部署方式：手工部署, pycharm 启动

**Comment by LeoQuote** [comment]
使用 qcluster 启动异步任务worker再重试一下。

```
python manage.py qcluster
```

或者在settings中将异步任务配置为非异步

https://django-q.readthedocs.io/en/latest/configure.html#sync

**Comment by sky1006** [comment]
配置为非异步 正常了
