### ISSUE TITLE
[ 问题咨询 ]改表结构时候，默认使用pt工具报错

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#640]
### 问题描述
执行
alter table test engine = innodb;审核执行后，执行异常，报错：

Use of uninitialized value $host in string eq at /usr/bin/pt-online-schema-change line 4353.
--
--

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：手工部署
pt工具为yum安装3.0.12版本。/usr/bin/目录下。

**Comment by hhyo** [comment]
如果使用goinception，可配置goinception中的osc配置`osc_recursion_method`为none
参考 https://www.percona.com/forums/questions-discussions/percona-toolkit/13270-pt-online-schema-change-fails-with-use-of-uninitialized-value-host
https://cloud.tencent.com/document/product/236/11277

建议先不使用平台，自行通过pt工具执行，调整出合适的配置
