### ISSUE TITLE
[ 问题咨询 ]工单详情里面的数据是通过rows｜safe获得的吗？

### ISSUE THREAD

**Issue by xqd0924** [hhyo/Archery#641]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
1.7.5版本以前是通过模板返回，1.7.5版本以后是通过接口异步获取，可参考#603
