### ISSUE TITLE
[ 问题咨询 ] 执行 SQL 检测时受影响行数显示不正确

### ISSUE THREAD

**Issue by ak1ra-komj** [hhyo/Archery#643]
### 问题描述

在执行 SQL 上线时, 某 `update` 语句自动审核不通过, 报"预计一次更新(27022行)超过 5000 行", 反复执行 SQL 检测这个数字还在不断变化, 实际执行查询时, 符合条件的记录事实上只有 1300 多条;

相关 `update` 语句:
```
update m_version_manage set update_status = 2
where
  (version = 'v2.5.0' or version = 'v2.5.1') and channel = 1;
```

相关 `select` 语句:
```
select count(*) from m_version_manage
where
	(version = 'v2.5.0' or version = 'v2.5.1') and channel = 1;

返回:
count(*)
1334
```

这个问题可能的原因是什么? 在已有 issue 中没找到相关的, 不确定是不是 bug, 先提交为 问题咨询.

### 版本信息
 - 应用版本/分支：Release v1.7.2  
 - 部署方式：Docker

**Comment by hhyo** [comment]
Inception和goInception审核返回的影响行数默认都是explain的结果，和innodb统计数据、语句是否命中索引等都有比较大的关系，goInception有提供获取真实行数的选项，考虑到count的效率问题，平台暂未引用此选项，具体可查看goInception文档

**Comment by ak1ra-komj** [comment]
明白;

那像我这种情况应该怎么解决呢? 你说的 goInception 获取真实行数的选项是 `real_row_count` 吧[1], 看起来要规避这个问题可以通过给 goInception 提供自定义选项, 但是我在 Archery 的设置中没有找到为 goInception 自定义调用选项的地方, 现在这样可行吗? 如果现阶段无法自定义选项那么还有别的办法规避这个显示不准确的问题吗? 以及后续有无增加为 goInception 或平台用到的其它工具提供自定义选项的功能?

update:

我试了下在 goInception 的配置文件 `inception/config.toml` 中增加 `real_row_count = true` 后单独重启 `goinception` 容器, 重新检测上面这段 update 语句, 看起来并没有生效.

[1]. https://hanchuanchuan.github.io/goInception/params.html

**Comment by hhyo** [comment]
暂不支持自定义调用选项，可自行修改
https://github.com/hhyo/Archery/blob/b8bc33f0f068e0ca5041791314590695c9fe9d7b/sql/engines/goinception.py#L35

**Comment by sudofeng** [comment]
明了明了。。

**Comment by luozhijunroy18** [comment]
sql_execute = f"""/*--user='{user}';--password='{password}';--host='{host}';--port={port};--execute=1;--ignore-warnings=1;{str_backup};--sleep=200;--sleep_rows=100*/

**Comment by luozhijunroy18** [comment]
https://github.com/hhyo/Archery/blob/339edd9ed6e9db2362ac1fe69eb25ba927775644/sql/engines/goinception.py#L84
