### ISSUE TITLE
[ bug ]使用导出功能 导出数据，出现数据不完整情况

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#645]
将查询结果导出时候，user_id数据库中显示为9615649975234172，导出到csv格式，显示为：9615649975234170。最后一位变成了0.

**Comment by gaoqiang-0327** [comment]
V1.7.7版本。手动部署

**Comment by LeoQuote** [comment]
其他格式有没有错误, 比如excel , sql等. 确认一下是数据问题还是前端问题

**Comment by gaoqiang-0327** [comment]
EXCEL也是这种情况。SQL和TXT不会。但是txt格式是加逗号的，用EXCEL打开后在一个单元格里，还得手动拆分。

**Comment by LeoQuote** [comment]
试一下用文本处理问题比如 vscode 打开 csv 文件, 排除一下excel 的格式问题

**Comment by LeoQuote** [comment]
你看能不能只查询userid那一列, 把导出的csv和excel文件传上来我看看. 我估计是显示问题, 数据是对的.

**Comment by gaoqiang-0327** [comment]
[test_userid.xlsx](https://github.com/hhyo/Archery/files/4265655/test_userid.xlsx)

**Comment by gaoqiang-0327** [comment]
我用UE编辑器打开CSV格式的是正常的，可能是EXCEL的问题

**Comment by gaoqiang-0327** [comment]
这个EXCEL，当一串数字大于15位的时候，格式就变了，后面的就变成了0。在开头得加个引号变成文本格式的才行。

**Comment by LeoQuote** [comment]
哦, 这个有人报过....excel是有点难弄, 你还是用csv吧 #362 

百度经验: https://jingyan.baidu.com/article/46650658df537af549e5f89d.html
