### ISSUE TITLE
[问题资询]SQL上线

### ISSUE THREAD

**Issue by jackiesre721** [hhyo/Archery#650]
### 问题描述
在SQL上线页面选择MySQL后会出现注释
`-- 请在此输入SQL，以分号结尾，仅支持DML和DDL语句，查询语句请使用SQL查询功能`
在做添加列DDL操作时报,DML测试时没问题
`Execute: 未正确解析SQL: -- 请在此输入SQL，以分号结尾，仅支持DML和DDL语句，查询语句请使用SQL查询功能。 alter table test add passtest int(4) default '0' comment 'goIncetion测试加列'.`

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
分号呢? 有分号吗?

**Comment by jackiesre721** [comment]
没分号

**Comment by LeoQuote** [comment]
....那有分号会好吗?

**Comment by jackiesre721** [comment]
试了也是不行

**Comment by hhyo** [comment]
演示环境能否重现？

**Comment by jackiesre721** [comment]
可以的重现还是报一样的错误,应该是到goincetion的问题

**Comment by hhyo** [comment]
https://github.com/hanchuanchuan/goInception/pull/164
可升级至 goInception v1.2.1
