### ISSUE TITLE
[ 问题咨询 ] Error 1115: Unknown character set: 'utf8mb4'.

### ISSUE THREAD

**Issue by tiger0526** [hhyo/Archery#651]
### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：Docker
 
 在SQL上线里面提交sql检测报:inception_magic_start

上线的SQL数据库是5.7以下，请问要怎么解决呢

**Comment by hhyo** [comment]
goinception有一个配置选项可以指定默认连接字符集，可自行调整

**Comment by tiger0526** [comment]
非常感谢您的回答，我有试过改./inception/config.toml 里面的support_charset                         ="utf8"，这个还是不行，请问是我改错地方了吗，都是docker里面启动的

**Comment by tiger0526** [comment]
谢谢啊！已经解决了，找到了要设置什么参数了

**Comment by xuzheng0017** [comment]
> 谢谢啊！已经解决了，找到了要设置什么参数了

能分享下设置的什么参数吗？

**Comment by woshiyanghai** [comment]
请问修改哪个参数？

**Comment by xuzheng0017** [comment]
> 请问修改哪个参数？

[https://hanchuanchuan.github.io/goInception/options.html](url)
`default_charset`
