### ISSUE TITLE
[ 问题咨询 ]通过bandit漏洞扫描发现比较多漏洞

### ISSUE THREAD

**Issue by jackiesre721** [hhyo/Archery#652]
### 问题描述
` pip install bandit`
`/usr/local/python3/bin/bandit -r Archery-1.7.7/`
### 版本信息
 - 应用版本/分支：Release v1.7.7  
 - 部署方式：手工部署

 
`Code scanned:
	Total lines of code: 16298
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 32.0
		Medium: 67.0
		High: 2.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 67.0
		Medium: 30.0
		High: 4.0`

**Comment by LeoQuote** [comment]
欢迎提pr 帮我们在ci中加上bandit 检查
