### ISSUE TITLE
我看项目中发的post请求没带csrf参数，但是没报403的错误，请问是怎么做到的？[ 问题咨询 ]

### ISSUE THREAD

**Issue by xqd0924** [hhyo/Archery#653]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
和项目无关, 建议先自己动手找一找django相关资料, 对照源码自己探索一下.

**Comment by hhyo** [comment]
网上资料查询应该可以找到解决办法
Archery的解决方案是在ajaxSetup时统一处理
https://github.com/hhyo/Archery/blob/5e199a7f63854d95f91bb6927cc0c947950b8b15/common/templates/base.html#L281-L302
