### ISSUE TITLE
[ 问题咨询 ]哪些情况下会archery会触发类似 select * from `db`.`table` limit 1;这种查询

### ISSUE THREAD

**Issue by xiaoganzi** [hhyo/Archery#654]
### 问题描述
我们使用archery查询tidb数据库；后台发现tidb的server里面经常获取到类似下面这种sql：
select * from `db`.`table` limit 1;
这种sql在我们的数据库里面执行时间较长。会影响archery和tidb的正常运行；
想咨询下：
1.哪些情况下会触发这种探活sql？
2.如何避免这种sql的执行？

万分感谢各位大佬给出解答！

### 版本信息
 - 应用版本/分支：Release v1.6.7
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
Archery并不会主动发出查询，可查看查询历史中是否有用户操作执行
