### ISSUE TITLE
进入docker的bash命令行后一会就自动退出docker bash状态

### ISSUE THREAD

**Issue by 52lingbaby** [hhyo/Archery#655]
### 问题描述
1、执行docker exec -ti archery /bin/bash后一会就自动退出docker bash状态
2、没有/opt/venv4archery/bin/activate

**Comment by LeoQuote** [comment]
版本？

**Comment by baoziyucha** [comment]
有后续解决吗？我再进入kafka容器的时候也遇到了这种情况。
