### ISSUE TITLE
[ 问题咨询 ]提交上万行insert语句，SQL检测卡死无响应

### ISSUE THREAD

**Issue by huangyue5207** [hhyo/Archery#656]
### 问题描述
SQL文件可以提交10M以内的SQL，但我提交一个2M的文件，上万行的insert语句，在SQL检测的时候直接卡死，server CPU直接跑满。请问有什么解决方案么？

### 版本信息
 - 应用版本/分支：Release v1.6.1 
 - 部署方式：Docker

**Comment by hhyo** [comment]
参考#223 升级新版即可
