### ISSUE TITLE
[ 问题咨询 ]添加数据库实例，如何让密码隐藏？

### ISSUE THREAD

**Issue by hanzixiaoshu** [hhyo/Archery#657]
### 问题描述
实例列表中，添加数据库实例，密码项显示明文，如何让显示密文形式？

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
数据库密码在存入的时候就已经加密了，不信你可以自己select 出来看

**Comment by hanzixiaoshu** [comment]
库里存的是加密状态，但是控制台页面查看数据库实例详情的时候，密码字段显示的是明文。

**Comment by hanzixiaoshu** [comment]
![image](https://user-images.githubusercontent.com/12489036/76317278-e9bb0680-6316-11ea-92a1-a139e036ed23.png)

**Comment by hhyo** [comment]
前端不考虑隐藏，需要隐藏可参考v1.7.1以前的版本修改

**Comment by hanzixiaoshu** [comment]
这个功能挺好的，为什么新版本中去掉了？应该有很多使用者都不愿密码直接显示，是出于其他什么考虑吗？

**Comment by hhyo** [comment]
实现实例用户管理功能时引入的加密库，实例管理也一并统一处理了

**Comment by hanzixiaoshu** [comment]
哦哦，明白，我单独写了一个加解密规则，前端已经显示成加密状态了，保存、更新数据库实例密码，都没有问题，多谢。

**Comment by Liuzhj** [comment]
> 哦哦，明白，我单独写了一个加解密规则，前端已经显示成加密状态了，保存、更新数据库实例密码，都没有问题，多谢。

同样的需求，能否借鉴一下？

**Comment by hanzixiaoshu** [comment]
我现在有个问题，sql查询都没有问题，但是提交sql上线时，点击sql检测，就提示密码不正确，inception连接数据库方式貌似和sql查询那块不一样，现在不知道该改哪里。

**Comment by LeoQuote** [comment]
那可能是你的密码加密那部分出问题了, 提个pr 一起看看吧, 不一定要合.

**Comment by hanzixiaoshu** [comment]
已经解决，谢谢。
参考1.7.0之前的版本，将自己写的加密方式在models.py替换一下就可以了，其他不用动
