### ISSUE TITLE
慢日志插入不到数据库，也无报错

### ISSUE THREAD

**Issue by shoohyun** [hhyo/Archery#658]
我的脚本配置如下，192.168.2.181是archery数据库，192.168.2.165是被分析的mysql：
![image](https://user-images.githubusercontent.com/13430470/76390967-5b439500-63a9-11ea-8163-9c465a673a54.png)
![image](https://user-images.githubusercontent.com/13430470/76391063-947c0500-63a9-11ea-9876-6629541cc611.png)
hostname也与archery配置上的一致
![image](https://user-images.githubusercontent.com/13430470/76391190-e4f36280-63a9-11ea-8f09-b2f61159695a.png)
表是用这个脚本创建的
执行analysis_slow_query.sh 无报错
![image](https://user-images.githubusercontent.com/13430470/76391377-621ed780-63aa-11ea-9290-56b69a5513a3.png)
数据库表里没有慢SQL，但是慢日志里是有的
![image](https://user-images.githubusercontent.com/13430470/76391448-84185a00-63aa-11ea-8476-597c1cdf79a8.png)

请问下是哪里配置错误了

**Comment by shoohyun** [comment]
版本是1.7.7

**Comment by hhyo** [comment]
参考 #377
确认执行的log，可删除时间文件全量分析

**Comment by catsun26** [comment]
我的最新版1.9.1和你一样的问题，请问这个问题解决了吗
