### ISSUE TITLE
mysql语句执行后没有执行结果是怎么回事呀？[ 问题咨询 ]

### ISSUE THREAD

**Issue by xqd0924** [hhyo/Archery#659]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
这样描述问题，并且不按要求提供版本信息部署方式，很抱歉没人能帮得到你

**Comment by xqd0924** [comment]
是v1.7.3版本的，我看到源码了，是rows没有存内容，不知道为什么这样做？
