### ISSUE TITLE
[ 问题咨询 ] 权限管理要如何撤销和修改已经审批通过的权限

### ISSUE THREAD

**Issue by hui2fei** [hhyo/Archery#662]
### 问题描述
权限管理要如何撤销和修改已经审批通过的权限？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker
 
之前申请了权限，限制了查询结果集为10行。现在需要重新申请为100行。重复申请回提示“你已拥有XXX权限，不能重复申请”

**Comment by hhyo** [comment]
点开申请权限边上的权限管理按钮进入列表就清楚了
