### ISSUE TITLE
[ 问题咨询 ]阿里云RDS管理

### ISSUE THREAD

**Issue by ybbo** [hhyo/Archery#663]
### 问题描述
阿里云RDS管理
1、“调用阿里云SDK”
 --这个怎样调用？有没有配置的步骤。
2、“在其他配置管理-全部后台数据中，添加阿里云账号的accesskey信息、实例对应关系”
--这个只有一项“阿里云rds配置”，点开后没有“阿里云账号的accesskey信息、实例对应关系”，“实例对应关系”配置项有，但是“accesskey信息”这个没有

### 版本信息
 - 应用版本/分支：Release vv1.7.4
 - 部署方式：Docker

**Comment by hhyo** [comment]
文档没更新，现ak配置已转移到系统配置中
