### ISSUE TITLE
[ 功能建议 ] 用日志挖掘实现oracle的备份功能

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#666]
### 目前遇到的问题/使用障碍
 archery对mysql的支持非常完美，虽然也支持oracle，但是对oracle只支持查询和执行，不支持备份和审核，还是有很大的遗憾。
现在，我们急需要一个oracle的备份功能，于是我想到了oracle自带的功能——日志挖掘，它可以实现sql语句的备份功能。

### 希望如何解决/实现它
日志挖掘

### 其他信息
具体方法：
http://blog.itpub.net/28916011/viewspace-2680457/

**Comment by LeoQuote** [comment]
欢迎贡献. 实现engine 的备份对应方法即可.

**Comment by jan-song** [comment]
数据修改回滚实现，在oracle.py脚本加入如下函数：  
  @property
    def auto_backup(self):
        """是否支持备份"""
        return True

    @staticmethod
    def get_backup_connection():
        archer_config = SysConfig()
        backup_host = archer_config.get('inception_remote_backup_host')
        backup_port = int(archer_config.get('inception_remote_backup_port', 3306))
        backup_user = archer_config.get('inception_remote_backup_user')
        backup_password = archer_config.get('inception_remote_backup_password')
        return MySQLdb.connect(host=backup_host,
                               port=backup_port,
                               user=backup_user,
                               passwd=backup_password,
                               charset='utf8mb4',
                               autocommit=True
                               )
    def ora_backup_insert(self, rows = [], id = 0):
        # 回滚SQL入库
        # 创建连接
        try:
            conn = self.get_backup_connection()
            cur = conn.cursor()
            cur.execute(f"""create database if not exists ora_backup;""")
            cur.execute(f"use ora_backup;")
            cur.execute(f"""CREATE TABLE if not exists `sql_rollback` (
                            `id` bigint(20) NOT NULL AUTO_INCREMENT,
                            `redo_sql` mediumtext,
                            `undo_sql` mediumtext,
                            `workflow_id` bigint(20) NOT NULL,
                            PRIMARY KEY (`id`),
                            key `idx_sql_rollback_01` (`workflow_id`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;""")
            if len(rows) > 0:
               for row in rows:
                   redo_sql=f"{row[0]}"
                   redo_sql=redo_sql.replace("'","\\'")
                   undo_sql=f"{row[1]}"
                   undo_sql=undo_sql.replace("'","\\'")
                   sql = f"""insert into sql_rollback(redo_sql,undo_sql,workflow_id) values('{redo_sql}','{undo_sql}',{id});"""
                   cur.execute(sql)
        except Exception as e:
            logger.warning(f"备份失败，错误信息{traceback.format_exc()}")
            return False
        finally:
               # 关闭连接
            if conn:
               conn.close()
        return True
    def get_rollback(self, workflow):
        """
        获取回滚语句，并且按照执行顺序倒序展示，return ['源语句'，'回滚语句']
        """
        list_execute_result = json.loads(workflow.sqlworkflowcontent.execute_result)
        workflow_id = workflow.sqlworkflowcontent.workflow_id
        # 回滚语句倒序展示
        list_execute_result.reverse()
        list_backup_sql = []
        try:
            # 创建连接
            conn = self.get_backup_connection()
            cur = conn.cursor()
            sql = f"""select redo_sql,undo_sql from sql_rollback where workflow_id = {workflow_id} order by id;"""
            cur.execute(f"use ora_backup;")
            cur.execute(sql)
            list_tables = cur.fetchall()
            for row in list_tables:
                redo_sql = row[0]
                if row[1] is None:
                    undo_sql = ' '
                else:
                    undo_sql = row[1]
                # 拼接成回滚语句列表,['源语句'，'回滚语句']
                list_backup_sql.append([redo_sql,undo_sql])
        except Exception as e:
            logger.error(f"获取回滚语句报错，异常信息{traceback.format_exc()}")
            raise Exception(e)
        # 关闭连接
        if conn:
            conn.close()
        return list_backup_sql


######### 修改如下函数：
    def execute_workflow(self, workflow, close_conn=True):
        """执行上线单，返回Review set"""
        sql = workflow.sqlworkflowcontent.sql_content
        execute_result = ReviewSet(full_sql=sql)
        # 删除注释语句，切分语句，将切换CURRENT_SCHEMA语句增加到切分结果中
        sql = sqlparse.format(sql, strip_comments=True)
        split_sql = [f"ALTER SESSION SET CURRENT_SCHEMA = {workflow.db_name};"] + sqlparse.split(sql)
        line = 1
        statement = None
        try:
            conn = self.get_connection()
            cursor = conn.cursor()
            # 逐条执行切分语句，追加到执行结果中
            cursor.execute(f"alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'")
            cursor.execute(f"select sysdate from dual")
            rows = cursor.fetchone()
            begin_time = rows[0]
            for statement in split_sql:
                statement = statement.rstrip(';')
                with FuncTimer() as t:
                    if statement !='':
                       cursor.execute(statement)
                       conn.commit()
                execute_result.rows.append(ReviewResult(
                    id=line,
                    errlevel=0,
                    stagestatus='Execute Successfully',
                    errormessage='None',
                    sql=statement,
                    affected_rows=cursor.rowcount,
                    execute_time=t.cost,
                ))
                line += 1
        except Exception as e:
            logger.warning(f"Oracle命令执行报错，语句：{statement or sql}， 错误信息：{traceback.format_exc()}")
            execute_result.error = str(e)
            #conn.rollback()
            # 追加当前报错语句信息到执行结果中
            execute_result.rows.append(ReviewResult(
                id=line,
                errlevel=2,
                stagestatus='Execute Failed',
                errormessage=f'异常信息：{e}',
                sql=statement or sql,
                affected_rows=0,
                execute_time=0,
            ))
            line += 1
            # 报错语句后面的语句标记为审核通过、未执行，追加到执行结果中
            for statement in split_sql[line - 1:]:
                execute_result.rows.append(ReviewResult(
                    id=line,
                    errlevel=0,
                    stagestatus='Audit completed',
                    errormessage=f'前序语句失败, 未执行',
                    sql=statement,
                    affected_rows=0,
                    execute_time=0,
                ))
                line += 1
        finally:
            # 生成回滚SQL
            cursor.execute(f"select sysdate from dual")
            rows = cursor.fetchone()
            end_time = rows[0]
            logmnr_start_sql = f'''begin
                                       dbms_logmnr.start_logmnr(
                                       starttime=>to_date('{begin_time}','yyyy-mm-dd hh24:mi:ss'),
                                       endtime=>to_date('{end_time}','yyyy/mm/dd hh24:mi:ss'),
                                       options=>dbms_logmnr.dict_from_online_catalog + dbms_logmnr.continuous_mine);
                                       end;'''
            undo_sql = f'''select sql_redo,sql_undo from v$logmnr_contents where
                                   SEG_OWNER <> 'SYS'
                                   and session# = (select s.sid from v$session s where s.sid = (select sid from v$mystat where rownum = 1 ))
                                   and serial# = (select serial# from v$session s where s.sid = (select sid from v$mystat where rownum = 1 )) order by scn desc'''
            logmnr_end_sql = f'''begin
                                            dbms_logmnr.end_logmnr;
                                            end;'''
            workflow_id = f"{workflow.sqlworkflowcontent.workflow_id}"
            cursor.execute(logmnr_start_sql)
            cursor.execute(undo_sql)
            rows = cursor.fetchall()
            cursor.execute(logmnr_end_sql)
            self.ora_backup_insert(rows=rows, id=workflow_id)
            if close_conn:
                self.close()
        return execute_result

**Comment by czxin788** [comment]
厉害，我能看懂大概。
希望archery早日实现，坐等大佬加入该功能。

**Comment by hhyo** [comment]
@jan-song 辛苦提个PR?
