### ISSUE TITLE
[ 问题咨询 ]非Mysql实例的SQL审核

### ISSUE THREAD

**Issue by Liuzhj** [hhyo/Archery#667]
### 问题描述
在SQL审核功能处，对于非Mysql实例，有没有比较好的办法？ 

能不能基于inception/goinception实现对非mysql实例的审核，我知道不同的数据库SQL规则可能有些不同，但对于一些标准（如SQL99）规范出一个通用的审核规则。对不同的数据库自定义不同的审核规则？

因为我们用到了多种数据库，有mysql，postgresql，mssql，oracle，nosql数据库等，偏向postgresql，但sql审核功能查看文档只支持mysql数据库。

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
这方面是平台的难点, 目前看到的是对于SQL语句没有统一可用的SQL 解析引擎, 所以暂时没想到怎么做, SQL 审核的相关代码都在engine 内, 你可以随意修改代码, 包括把语句发送给外部引擎分析, 获取分析报告, 然后正常继续流程. https://github.com/hhyo/Archery/wiki/development

**Comment by LeoQuote** [comment]
长期问题, 有待解决, 非Mysql 的审核引擎相关问题建议都在这里讨论.

**Comment by yizhong010** [comment]
Oracle 什么时候能够支持审核Oracle 什么时候能够支持审核Oracle 什么时候能够支持审核
