### ISSUE TITLE
[ 功能建议 ] 能否在归档功能上根据不同工单配置不同归档时间

### ISSUE THREAD

**Issue by falcondance** [hhyo/Archery#668]
### 目前遇到的问题/使用障碍
由于业务需求，需要在不同的时间点进行归档，目前归档只能统一配置一个时间调用，使用不友好

### 希望如何解决/实现它
在申请归档页面提供归档时间选项，针对每个工单提供归档时间选择。

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
两种实现方案
- 每个归档任务配置一个schedule
- 原有schedule支持传入配置id，可以此建多个schedule调度

欢迎感兴趣的同学提交PR
