### ISSUE TITLE
更新实例信息中实例名称导致用户查询权限失效[ bug ]

### ISSUE THREAD

**Issue by think-coding** [hhyo/Archery#67]
由于实例增多，前期实例命名方式不便于区分。
故，在更新实例名称后，导致用户查询权限失效，改回之前的实例名称后正常。

说明archery程序中是用输入的实例名称进行关联的，可否更新代码使用实例host、port 生成uuid关联，替换之前的方案。

**重现步骤**
更新已有查询权限用户的可访问实例名称。

**版本信息**
 - 应用版本   1.3.8
 - 部署方式，手工部署

**Comment by LeoQuote** [comment]
感谢提出这个建议，这个问题一直都想改，但是因为历史原因涉及的东西太多，一直拖着没做。

anyway 已列入下个版本的修订计划

目前的建议临时解决方案是。。。。别改， 😂

**Comment by hhyo** [comment]
目前受影响的应该有等待执行的工单，以及查询权限和脱敏字段配置，修改时注意把这几块对应的表数据一起修改掉即可。
