### ISSUE TITLE
[ 功能建议 ]sql上线是否可以支持一组能包含测试，生产概念的数据库实例并在此基础上设置审批执行流

### ISSUE THREAD

**Issue by sunsky-cn** [hhyo/Archery#670]
建议能设定一组实例，并设置流转顺序并设置对应审批流。进而实现sql上线的从测试环境实例到预生产到生产实例的完整审批工作流。规范sql上线的整个测试提交流程

**Comment by hhyo** [comment]
目前同一组内想配置不同的审批流程以及权限隔离确实不太好实现，算是一个比较大的改动，#612

**Comment by sunsky-cn** [comment]
我觉得是很有价值的功能点，实际工作由于上线环境管理不规范，导致上线实际执行的sql有可能会有问题，就在于，没有真正经过其他环境验证（其他环境错漏后有人修复了，但是没有体现在上线sql上）

**Comment by sunsky-cn** [comment]
我想可以定一个工作流和另一个工作流的串行吧，比如一个实例审批流程定义好后，自动进入另一个审批流，这2个流一个是对应测试环境的实例的审批，另一个是对应比如生产的，只要能自动串起来就好

**Comment by sunsky-cn** [comment]
以上是我的一些建议，和想法。

**Comment by hhyo** [comment]
测试和生产用不同组隔开就行，审批流可单独配置，没必要关联起来

**Comment by sunsky-cn** [comment]
问题是不好确保sql在不同环境之间流转是否有缺漏，而导致上线失败

**Comment by sunsky-cn** [comment]
真心希望大神们能开发这个功能，对于规范上线帮助相当大，谢谢！
