### ISSUE TITLE
建表时提示字段数据类型不支持

### ISSUE THREAD

**Issue by Elipha** [hhyo/Archery#671]
### 问题描述
提交SQL上线，建立表的时候，提示字段blob/text类型不支持，有解决方案吗？
![图片](https://user-images.githubusercontent.com/59275066/76936394-de2a9980-692d-11ea-8834-ddec8bfd7f8b.png)

  | create table test1(id int,msg text) | 0 | error | Type blob/text is used in column 'msg'.
-- | -- | -- | -- | --

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：手工部署

**Comment by lxkaka** [comment]
@Elipha hello, 请问一下你怎么解决的

**Comment by Elipha** [comment]
> @Elipha hello, 请问一下你怎么解决的
看一下inception get variables;
将enable_blob_type参数调整为 true

**Comment by lxkaka** [comment]
@Elipha  谢谢，我们 inception， goinception  这个的配置都是 true。我确认一下是不是生效的
