### ISSUE TITLE
[ 问题咨询 ]开启钉钉个人消息通知中，Archery2Ding、DingDeptIDs两项说明

### ISSUE THREAD

**Issue by hanzixiaoshu** [hhyo/Archery#672]
### 问题描述
在开启钉钉个人消息通知中，Archery2Ding、DingDeptIDs有详细的配置说明吗？

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker、手工部署

**Comment by hanzixiaoshu** [comment]
部门id、userid已经取到，不明白Archery2Ding是什么意思？哪个字段对应哪个？

**Comment by hhyo** [comment]
就是指Archery用户的username和钉钉个人信息中的哪个字段对应

**Comment by hanzixiaoshu** [comment]
Archery中username字段的值和钉钉个人信息中对应字段的值一致，才可以发送消息成功吗？

**Comment by hanzixiaoshu** [comment]
这里Archery2Ding的作用是什么呢？

**Comment by hhyo** [comment]
发送钉钉消息需要知道用户的钉钉Id，这个就是相当于是一个映射关系，当然如果你添加用户时就绑定了dinguser_id，不要也没关系，这个就是提供给系统自动维护dinguser_id的

**Comment by hanzixiaoshu** [comment]
嗯， 测试发送个人钉钉消息成功收到一次消息后，后面再提交上线sql就收不到了。
另外，发送个人消息，只是在整个流程终结后，才会发送，审批过程是不会发送的吧？

**Comment by hhyo** [comment]
参考https://archerydms.com/modules/notify/

**Comment by hanzixiaoshu** [comment]
嗯，通知触发场景以及通知对象搞清楚了，谢谢。
现在碰到了另一个问题，首次提交上线工单可以成功接收到钉钉工作通知消息，然后再次申请提交上线工单就收不到了，手动将redis缓存清掉后，又可以接收到了，之后再次提交又不行了，必须每次手动清理redis缓存

**Comment by hanzixiaoshu** [comment]
缓存问题找到原因了，第一次可以推送消息成功，是因为调消息接口时token是直接从token接口获取的，获取到token以后便放到了缓存里，第二次推送消息时，token是从缓存里取到的，恰巧取到的token值是bytes类型（b'fbeiuwfuwhedbqsjcb123'），所以只需要将从缓存取到的bytes类型转成str类型（fbeiuwfuwhedbqsjcb123）就可以了

**Comment by hanzixiaoshu** [comment]
开启钉钉个人消息通知，配置好以后，点击用户同步，为什么数据库中的ding_user_id没有写入？此步骤只是将userid写入到了缓存，同步成功后，需要重新登录用户，这时就会调用get_ding_user_id函数，再看一下，数据库中的ding_user_id已经有了

**Comment by hanzixiaoshu** [comment]
通知触发场景以及通知对象已经看明白了，但是按照这个配置，提交申请、终止流程、审核通过（非最终审核通过）、审核通过（最终审核通过）、审核不通过，都收不到钉钉个人通知，只有在执行结束后，申请人（dev）可以收到一次个人通知。
配置如下：
dev账号关联“正式环境”资源组，关联“开发人员权限组”
audit账号关联“正式环境”资源组，关联“dba权限组”
审批流程只有dba权限组一级
这是哪里的问题？是权限组需要做单独的配置吗？还是需要特定的权限？

**Comment by hhyo** [comment]
可以看日志，应该每个环节都有日志信息

**Comment by hanzixiaoshu** [comment]
/opt/archery/logs/archery.log下没有日志信息，这个文件里只会打印一些报错日志，最后修改了notify.py文件，if判断中增加了sys_config.get('ding_to_person')，然后可以了。

def notify_for_audit(audit_id, **kwargs):
    """
    工作流消息通知，不包含工单执行结束的通知
    :param audit_id:
    :param kwargs:
    :return:
    """
    # 判断是否开启消息通知，未开启直接返回
    sys_config = SysConfig()
    wx_status = sys_config.get('wx')
    if not sys_config.get('mail') and not sys_config.get('ding') and not sys_config.get('ding_to_person') and not wx_status:
        logger.info('未开启消息通知，可在系统设置中开启')
        return None

**Comment by hhyo** [comment]
嗯，默认日志等级是error，配置调整一下就可以

这个改动可以提个pr修复一下

**Comment by hanzixiaoshu** [comment]
好的
