### ISSUE TITLE
[ 问题咨询 ]对接LADP失败

### ISSUE THREAD

**Issue by Liuzhj** [hhyo/Archery#674]
### 问题描述

已做的操作

- 修改了`src/docker-compose/archery/settings.py`文件
- 停止docker-compose down
- 启动docker-compose up -d

ldap的域名可以解析和ping通。

文档中集成ldap里需要一个管理员用户，可我们没有管理员用户呀。没有用户还能对接吗？ 文档中好简单，没有其他的信息可供参考了。

![image](https://user-images.githubusercontent.com/14147011/77044948-4a270380-69fb-11ea-8ed7-f25333ef0866.png)

![image](https://user-images.githubusercontent.com/14147011/77045309-e3eeb080-69fb-11ea-8abb-84910ff73ad9.png)

### 版本信息
 - 应用版本/分支：Release v1.7
 - 部署方式：Docker

**Comment by Liuzhj** [comment]
也没有找到相关的日志可以查看，`docker-compose logs `

**Comment by LeoQuote** [comment]
需要一个有读权限的用户. 其他的看那个module 的文档. 欢迎补充.

**Comment by Liuzhj** [comment]
@LeoQuote 还是不行，对接不成功ldap，配置信息都填写了，新用户默认权限组也配置了，还是不能正常登录。
请问下网站登录的日志在哪里？ 还有django的日志在哪里？
使用docker-compose logs没看到有相关的日志呢。

**Comment by hhyo** [comment]
日志信息看wiki faq
