### ISSUE TITLE
[ 问题咨询 ]修改goinception配置后报错

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#678]
Execute: Error 1045: Access denied for user 'root'@'xxx.xxx.xxx.xxx' (using password: YES).

**Comment by hhyo** [comment]
需要自行修改goInception配置文件

**Comment by dmz-leon** [comment]
> 需要自行修改goInception配置文件

只是修改了merge_alter_table和check_column_position_change这两个参数，请问，以上报错是涉及到那个参数？

**Comment by hhyo** [comment]
目前发现这个错误是goinception的备份库配置错误，可以检查一下goInception配置文件

**Comment by dmz-leon** [comment]
> 目前发现这个错误是goinception的备份库配置错误，可以检查一下goInception配置文件

出现问题前没有修改过配置文件，检查后发现备份库的配置也是正常的

**Comment by dmz-leon** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        备份库的配置backup_host，backup_port，backup_user和backup_password的配置都是正确的 此前也没有修改过配置文件
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Leon3D Department · System Operations Engineer       Cel：+86-15605327157—————————————————————————————————————————————Web： www.echemi.com             Email：leon@echemi.com              QQ：541219094            

    











        
    
     

    在2020年4月11日 15:47，小圈圈<notifications@github.com> 写道： 




目前发现这个错误是goinception的备份库配置错误，可以检查一下goInception配置文件

**Comment by hhyo** [comment]
可以开启goInception的日志具体排查下，这种错误都会记录具体原因

**Comment by dmz-leon** [comment]
> 可以开启goInception的日志具体排查下，这种错误都会记录具体原因

报错信息也就只有这两行
2020-04-14 12:10:24 ERROR Error 1045: Access denied for user 'root'@'114.116.2.182' (using password: YES)
time="2020/04/14 12:10:24.365" level=error msg="Error 1045: Access denied for user 'root'@'114.116.2.182' (using password: YES)" file=osc.go line=578

**Comment by hhyo** [comment]
日志等级调整为debug，开启general log，查看上下文日志

**Comment by dmz-leon** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    显示了备份过程 具体报错信息还是没有说明。。。
    
        
            
        
    
    
         
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Leon3D Department · System Operations Engineer       Cel：+86-15605327157—————————————————————————————————————————————Web： www.echemi.com             Email：leon@echemi.com              QQ：541219094            

    











        
    
     

    在2020年4月14日 12:43，小圈圈<notifications@github.com> 写道： 




日志等级调整为debug，开启general log，查看上下文日志

**Comment by dmz-leon** [comment]
> 日志等级调整为debug，开启general log，查看上下文日志

![微信截图_20200414130855](https://user-images.githubusercontent.com/50727710/79189845-6466cc80-7e55-11ea-91ee-afdcc39c9242.png)
