### ISSUE TITLE
[ bug ]

### ISSUE THREAD

**Issue by leo-pan** [hhyo/Archery#68]
您好！少了一个模块，谢谢！
![image](https://user-images.githubusercontent.com/19898557/54404617-1db51900-470f-11e9-9986-5b46c475c227.png)
![image](https://user-images.githubusercontent.com/19898557/54404663-4210f580-470f-11e9-91aa-d149b230f294.png)

**Comment by LeoQuote** [comment]
不符合issue规范，请按模版规范提交
