### ISSUE TITLE
[ 问题咨询 ]查看oracle的表结构没有注释

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#680]
### 问题描述
给开发开通查询权限，但是发现不能看oracle表的列注释，希望能加个列是看表和列注释的。
![image](https://user-images.githubusercontent.com/13861904/77315354-5fc16380-6d42-11ea-9a3c-f056fa615da5.png)

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
不了解oracle，可以自行修改提交pr，修改engine内的sql语句就可以
