### ISSUE TITLE
[ 问题咨询 ]goinception配置文件的参数详解哪里可以找到

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#681]
goinception配置文件的参数详解哪里可以找到。goinception的git打不开了。想修改参数，无从下手。。。

**Comment by LeoQuote** [comment]
和本项目不相关, goinception的参数参见 
https://github.com/hanchuanchuan/goInception 
https://hanchuanchuan.github.io/goInception/
