### ISSUE TITLE
[ 问题咨询 ]SQL提交，连接Azure PaaS SQLSERVER DB报错

### ISSUE THREAD

**Issue by Elipha** [hhyo/Archery#685]
### 问题描述
添加Azure PaaS Sqlserver实例，在实例后面操作栏位有测试连接功能，连接测试是正常的。使用SSMS客户端用同样的帐号和密码是可以连接的。但是在提交SQL上线的时候，选择实例的时候报错。如下：
('28000', "[28000] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '***'. (18456) (SQLDriverConnect)")
请问Archery是否不支持Sqlserver PaaS DB?

### 版本信息
 - 应用版本/分支：Release v1.7.7  
 - 部署方式:手工部署

**Comment by LeoQuote** [comment]
sql server 方面的授权对我来说一直是一个迷, 看一下这里的代码

https://github.com/hhyo/Archery/blob/77865fc04a22cf9c4023e22ac7d108a74d569d01/sql/engines/mssql.py#L15-L23

这里用的连接串是这样的 `SERVER={0},{1};UID={2};PWD={3} ` 可以在paas 文档那边找一找开发者手册, 看一看他们要求的连接串是怎么写.

**Comment by Elipha** [comment]
> sql server 方面的授权对我来说一直是一个迷, 看一下这里的代码
> 
> https://github.com/hhyo/Archery/blob/77865fc04a22cf9c4023e22ac7d108a74d569d01/sql/engines/mssql.py#L15-L23
> 
> 这里用的连接串是这样的 `SERVER={0},{1};UID={2};PWD={3} ` 可以在paas 文档那边找一找开发者手册, 看一看他们要求的连接串是怎么写.

谢谢！问题已经解决！

**Comment by LeoQuote** [comment]
可以在这里说一下解决方案, 方便后面的人解决.
