### ISSUE TITLE
[ 功能建议 ] 配置项管理页面的inception和goinception区分建议

### ISSUE THREAD

**Issue by hanchuanchuan** [hhyo/Archery#687]
### 目前遇到的问题/使用障碍

配置页面的inception和goinception区分，容易有歧义
![image](https://user-images.githubusercontent.com/18544383/77602272-f90d9700-6f47-11ea-9e36-a7fc532dfa2a.png)

### 希望如何解决/实现它

建议调整为单选按钮的形式，相对来说辨识度更高

**Comment by hhyo** [comment]
目前inception还是必须要，脱敏依赖，不能单选

**Comment by hanchuanchuan** [comment]
嗯嗯，理解的。
可以更清晰一点，标识出脱敏服务是Inception，而审核服务可以选择和切换。
以及在点击两个 [测试连接] 前看能否校验下面几个文本框内是否有值，
或者把测试连接的按钮放在对应地址下面，让新用户可以更清晰的看出来两者是有关联关系的。

只是建议哈，作为小白用户，提的问题可能会比较局限。

**Comment by hhyo** [comment]
🉑，找时间整下
