### ISSUE TITLE
[ bug ]在使用过程中，有一个模块没有，出现报错

### ISSUE THREAD

**Issue by leo-pan** [hhyo/Archery#69]
在使用过程中，有一个模块没有，出现报错

重现步骤
在使用过程中，有一个模块没有，出现报错

**截图**
![image](https://user-images.githubusercontent.com/19898557/54405078-6c16e780-4710-11e9-8d7a-bf5646e38faa.png)
![image](https://user-images.githubusercontent.com/19898557/54405116-85b82f00-4710-11e9-8fb5-4bdc4fab7a65.png)

版本信息

应用版本 1.3.8
部署方式，手工部署

**Comment by LeoQuote** [comment]
请贴出实际报错信息， 并详细说明重现步骤（点击了哪些页面，提交了哪些信息等）

**Comment by leo-pan** [comment]
> 请贴出实际报错信息， 并详细说明重现步骤（点击了哪些页面，提交了哪些信息等）

我再查看源码源码的时候，就发现无法引用这个模块。然后我再GitHub上面查看也是少get_engine这个模块。作者您是否可以建个QQ群呢？
from sql.engines import get_engine

**Comment by LeoQuote** [comment]
请以程序运行结果为准。

**Comment by leo-pan** [comment]
作者您是否可以建个QQ群呢？

**Comment by LeoQuote** [comment]
你得自己跑起来， 就会发现这里是可以import的。

``get_engine`` 在``engines`` 的 ``__init__.py`` 下， 为什么init下的函数可以正常import 你可以搜一下 python import的相关教程， 文档， 搜索的关键词是``Python import``

**Comment by LeoQuote** [comment]
近期应该不会考虑建qq群， QQ群实时性太强， 本项目是个开源项目， 实时交流可能会给开发者带来不必要的压力， 有问题可以开issue， 我们也会尽快回复。

**Comment by leo-pan** [comment]
谢谢
