### ISSUE TITLE
导航栏的todo从哪里传进去的？[ 问题咨询 ]

### ISSUE THREAD

**Issue by xqd0924** [hhyo/Archery#690]
## 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
代码相关的问题，建议多使用全局检索，项目主页也有依赖模块的清单和地址，还请多多阅读文档，issue还是用来提交问题反馈和功能建议
