### ISSUE TITLE
[ 问题咨询 ] 请问archery支持oracle数据库查询脱敏吗

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#691]
### 问题描述
请问archery支持oracle数据库查询脱敏吗。
我测试发现，如果给oracle数据库设置脱敏，那么查询oracle的所有表的所有字段都被脱敏了。

### 版本信息
 - 应用版本/分支：1.7.7
 - 部署方式：Docker、

**Comment by hhyo** [comment]
多搜索一下？
#525
