### ISSUE TITLE
[ bug ]使用工具插件pt-achive的时候出现Cannot find encoding "utf8mb4" at /usr/lib64/perl5/IO/File.pm line 181. 错误

### ISSUE THREAD

**Issue by kukukafei** [hhyo/Archery#692]
系统环境  centos7 
pt工具集版本   percona-toolkit-3.1.0-2.el7.x86_64.rpm

配置归档以后报Cannot find encoding "utf8mb4" at /usr/lib64/perl5/IO/File.pm line 181. 错误

归档失败日志：
pt-archiver --no-version-check --source h=192.168.**,u=****,p=***,P=3306,D=***,t=sync_pos_saleflow --where "gmt_create>'2019-04-25 14:16:16'" --progress 5000 --statistics --charset utf8mb4 --limit 10000 --txn-size 1000 --sleep 1 --file /usr/local/Archery/downloads/archiver/测试数据库-***-sync_pos_saleflow.txt --bulk-delete
TIME                ELAPSED   COUNT

2020-03-30T09:26:29       0       0

Cannot find encoding "utf8mb4" at /usr/lib64/perl5/IO/File.pm line 181.
Cannot open :encoding(utf8mb4) /usr/local/Archery/downloads/archiver/测试数据库-***-sync_pos_saleflow.txt: 无效的参数

官方的bug反馈：
https://jira.percona.com/browse/PT-1713
instead of using --charset= parameter, please try this pt-archiver command where A= is used in the DSN part

**Comment by hhyo** [comment]
有兴趣可以fix提个pr

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/commit/77865fc04a22cf9c4023e22ac7d108a74d569d01

做了相应调整，貌似也解决不了emoji的归档问题，转换会存在异常，可自行按照命令在本地验证，如果有合适的解决方案可讨论

**Comment by falcondance** [comment]
这个是因为pt-archiver的bulk-insert参数导致的，将args['bulk-insert'] 改为 False，然后source = fr"h={s_ins.host},u={s_ins.user},p={s_ins.password},P={s_ins.port},D={src_db_name},t={src_table_name}" 后加上,A={tb.options['charset'].value，dest同样添加就可以正常归档了

**Comment by hhyo** [comment]
> 这个是因为pt-archiver的bulk-insert参数导致的，将args['bulk-insert'] 改为 False，然后source = fr"h={s_ins.host},u={s_ins.user},p={s_ins.password},P={s_ins.port},D={src_db_name},t={src_table_name}" 后加上,A={tb.options['charset'].value，dest同样添加就可以正常归档了

去除批量操作确实可以正常归档，pt-archiver这块处理的有缺陷
