### ISSUE TITLE
[ 问题咨询 ] aws的redis限制config命令, 导致 archery 不能正常查询

### ISSUE THREAD

**Issue by lework** [hhyo/Archery#694]
### 问题描述
aws的redis限制config命令

### 版本信息
 - 应用版本/分支：Release v1.7.8 
 - 部署方式：Docker

连接aws的redis时，提示unknown command 'CONFIG'

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html
aws 限制执行`config` 命令。

**Comment by hhyo** [comment]
不能用config.的话，看还有没有其他途径可以过去databases，或者列入到实例配置中去

**Comment by lework** [comment]
多谢回复，在配置redis实例时，`数据库` 这个字段是设置多少个db数量的么？
还有就是通过select来判断实例有多少库了
```python
def get_all_databases(self, **kwargs):
    """
    获取数据库列表
    :return:
    """
    conn = self.get_connection()
    result = ResultSet(full_sql='CONFIG GET databases')
    try:
        rows = conn.config_get('databases')['databases']
    except Exception as e:
        logger.warning(f"Redis "CONFIG GET databases" 执行报错，异常信息：{e}")
        db_limit = rows = 32
        for i in range(db_limit):
            sql = "select %s" % i
            try:
                resp = conn.execute_command(sql)
            except Exception:
                rows = i
                break

    db_list = [str(x) for x in range(int(rows))]
    result.rows = db_list
    return result
```

**Comment by LeoQuote** [comment]
对, 前端选db 的候选项是这里设置的, 如果select 更通用的话可以改代码直接提pr, 如果不通用的话, 继承 RedisEngine 做一个 AWSRedis 或者什么的, 覆盖 get_all_databases 方法即可

**Comment by hhyo** [comment]
commit message issue 关联错误，应该是#692

**Comment by LeoQuote** [comment]
这个 select 的方法倒是很有趣, 哈哈, 欢迎直接提 pr

**Comment by hhyo** [comment]
目前暂时在获取失败后默认返回16，希望对超过16的db进行操作还会有问题
