### ISSUE TITLE
[ 问题咨询 ] 慢日志数据缺少数据库名称

### ISSUE THREAD

**Issue by shoohyun** [hhyo/Archery#696]
### 问题描述
慢日志页面展示慢日志选择全部数据库会显示全部慢SQL，但是选择指定的库的话，就不显示
![image](https://user-images.githubusercontent.com/13430470/78123199-65086780-7440-11ea-9096-20a55f5fcc4f.png)

![image](https://user-images.githubusercontent.com/13430470/78123237-70f42980-7440-11ea-9886-f299557ba8c9.png)

而且慢日志页面数据库名选项不显示数据库名称
![image](https://user-images.githubusercontent.com/13430470/78123038-2a063400-7440-11ea-90be-62c0c1722300.png)

是本来就不显示还是哪里出错了
### 版本信息
 - 应用版本/分支：Release v1.7.8  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
这种是pt工具写入库的时候出现异常，可以搜索下pt工具是否存在相关bug，或者可以通过修改脚本优化

**Comment by shoohyun** [comment]
好的，多谢回答
