### ISSUE TITLE
[ bug ]设置自动执行后 无法取消

### ISSUE THREAD

**Issue by dxl3811051** [hhyo/Archery#697]
我在sql审核这边上线sql 然后设置了到时间自动执行  我在中途终止执行 但是到了时间后还是会自动执行sql，这个问题比较严重  如果暂时没有修改的话 请问如何手动取消。

**Comment by hhyo** [comment]
感谢反馈，问题确定是在v1.7.4引入
https://github.com/hhyo/Archery/commit/7bf5714f87307b2f577cdf27f6c680cf99958658

如果目前需要删除定时工单，可以在django管理后台，django-q schedule表中删除定时任务

问题将在周末修复，抱歉

**Comment by dxl3811051** [comment]
谢谢 回复

> 感谢反馈，问题确定是在v1.7.4引入
> [7bf5714](https://github.com/hhyo/Archery/commit/7bf5714f87307b2f577cdf27f6c680cf99958658)
> 
> 如果目前需要删除定时工单，可以在django管理后台，django-q schedule表中删除定时任务
> 
> 问题将在周末修复，抱歉

谢谢回复
