### ISSUE TITLE
归档时在Scheduled tasks设置后还是30s执行一次

### ISSUE THREAD

**Issue by falcondance** [hhyo/Archery#699]
归档时在Scheduled tasks设置后还是30s执行一次，必须调整archery/settings.py中USE_TZ = True才能进行正常的定时执行，但是配置USE_TZ = True后会导致datetime.now()的时间-8小时，出现各种问题，包括上线中的定时执行校验失败，日志中时间差异等等。
有什么好的办法避免使用USE_TZ = True吗？否则改动太大

### 重现步骤
USE_TZ = False时，配置1分钟一次，但实际30s执行一次

### 期待结果和实际结果
期待结果：
可以正常配置归档时间
实际结果:

### 截图
![image](https://user-images.githubusercontent.com/20810423/78229742-f50ee580-7502-11ea-8105-2880d1489333.png)

### 错误日志
USE_TZ = True时上线定时执行报错
![image](https://user-images.githubusercontent.com/20810423/78229863-1f60a300-7503-11ea-9e44-5b445f2402f6.png)

### 版本信息
应用版本/分支：
1.7.8
部署方式：手工部署

**Comment by hhyo** [comment]
相关问题已经在https://github.com/Koed00/django-q/pull/353 修复，并发布于django_q == 1.0.2
确认下你django_q的版本，我这边验证是没有问题的

**Comment by falcondance** [comment]
django_q的版本是1.2.1，而且演示环境好像也有同样的问题。
https://demo.archerydms.com/archive/7/
https://demo.archerydms.com/admin/django_q/success/

archive-7	sql.archiver.archive	2020-04-13 09:48:48	2020-04-13 09:48:48	0.16764	archive-2020-04-13 09:48:48
dakota-winter-romeo-lactose	sql.archiver.add_archive_task	2020-04-13 09:48:48	2020-04-13 09:48:48	0.035283	归档数据
archive-7	sql.archiver.archive	2020-04-13 09:48:18	2020-04-13 09:48:18	0.167309	archive-2020-04-13 09:48:18
mexico-eleven-muppet-hotel	sql.archiver.add_archive_task	2020-04-13 09:48:18	2020-04-13 09:48:18	0.026393	归档数据
archive-7	sql.archiver.archive	2020-04-13 09:47:48	2020-04-13 09:47:48	0.175732	archive-2020-04-13 09:47:48
vegan-mountain-berlin-alpha	sql.archiver.add_archive_task	2020-04-13 09:47:48	2020-04-13 09:47:48	0.026423	归档数据
archive-7	sql.archiver.archive	2020-04-13 09:47:17	2020-04-13 09:47:18	0.18931	archive-2020-04-13 09:47:17
mirror-jupiter-monkey-fix	sql.archiver.add_archive_task	2020-04-13 09:47:17	2020-04-13 09:47:17	0.026867	归档数据
archive-7	sql.archiver.archive	2020-04-13 09:46:47	2020-04-13 09:46:48	0.173972	archive-2020-04-13 09:46:47
ten-quiet-moon-fix	sql.archiver.add_archive_task	2020-04-13 09:46:47	2020-04-13 09:46:47	0.028888	归档数据
.......

**Comment by falcondance** [comment]
django_q 1.2.1 这段bugfix代码被覆盖掉了，需要重新再加上

**Comment by hhyo** [comment]
确实，可先回滚到1.1.0
