### ISSUE TITLE
[建议] 支持统一认证cas SQL上线工单功能 SQL上线标准模板

### ISSUE THREAD

**Issue by frank0826** [hhyo/Archery#70]
1、后期是否支持统一认证系统cas
2、关于sql 上线工单功能，后期是支持 业务需求方自助化执行变更功能，DBA 作为工单、相关DDL、DML 审批、review等，作为风险把控者，提供解决方案等
3、SQL 上线标准模板，以便业务方参照DDL,DML 相关模板，提交标准规范变更

**Comment by LeoQuote** [comment]
1. cas等sso这一块不计划做支持，这方面的系统太多，建议二次开发进行集成。推荐一个django module https://github.com/pennersr/django-allauth

2. 没看懂，你想要的是什么？
3. 关于SQL规范已经有相关文档，类似必须有主键之类的，在主页左边主选单的最下面

我理解你说的模版规范是这个，如果有理解错了希望指出。

**Comment by hhyo** [comment]
- 认证这块，集成sso和前面说一样不考虑，倒是可以开放openapi方便和其他内部系统对接，工单执行结束等事件也是类似，方便集成
- 提交人自助执行，给提交人分配执行权限即可，不过现在拥有执行权限的用户可以执行组内所有工单，这是按照以前一位用户的需求来做的，具体是否仅限制到个人工单还可以继续讨论
-  模板，猜测你指的应该是类似于github提交issues可选模板吧，比如DDL需要强制提交相关查询语句，说明变更详情等，这块有考虑，不过前端能力着实有限，一直搁置中
