### ISSUE TITLE
[BUG]oracle.py查询功能filter_sql函数遇到查询语句的子查询带rownum会有问题，建议进行如下改写,这样count(*)的查询bug也不会有

### ISSUE THREAD

**Issue by jan-song** [hhyo/Archery#700]
def filter_sql(self, sql='', limit_num=0):
        sql_lower = sql.lower()
        # 对查询sql增加limit限制
        if re.match(r"^select", sql_lower):
           sql=f"select a.* from ({sql.rstrip(';')}) a WHERE ROWNUM <= {limit_num}"
        return sql.strip()

**Comment by hhyo** [comment]
建议直接提交pr，谢谢

**Comment by jan-song** [comment]
和备份功能合并一起提了#701，第一次用git,有问题勿恼。 @hhyo
