### ISSUE TITLE
[ 问题咨询 ]使用SQL优化工具插件SQLAdvisor报错：No such file or directory

### ISSUE THREAD

**Issue by kamner** [hhyo/Archery#702]
### 问题描述
使用工具插件SQLAdvisor查看优化建议时，报错：No such file or directory

### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/37998226/78739103-2285e400-7986-11ea-9462-25a74b0f8f23.png)

![image](https://user-images.githubusercontent.com/37998226/78739149-37fb0e00-7986-11ea-90c0-e26d9240b463.png)

**Comment by hhyo** [comment]
docker部署的，文件不在这个目录，具体可以看文档
