### ISSUE TITLE
[ 问题咨询 ] SQL 查询功能权限过大

### ISSUE THREAD

**Issue by hala21** [hhyo/Archery#703]
### 问题描述
实例配置-->实例标签关系-->选择支持查询功 能后，所有的人员都能选择这个实例，不需要权限申请，是哪里使用错误吗？

### 版本信息
 - 应用版本/分支：Release v1.7.0  
 - 部署方式：Docker

**Comment by hhyo** [comment]
资源组内用户可选择组内实例以及查看表结构，如果查询数据则需要申请权限

**Comment by hala21** [comment]
查询功能直接申请某个表的权限，不能查询，说没有库的权限。
申请库的权限后，可以查询。
现在是这样设计的吗？

**Comment by hhyo** [comment]
#446 #360 

在 #553 解决，升级新版即可，建议多使用issue搜索

**Comment by hala21** [comment]
嗯，谢谢！
