### ISSUE TITLE
[ 问题咨询 ] 请问查询mongodb数据怎么知道表有哪些字段

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#704]
### 问题描述
我在用archery的mongodb查询功能，不知道怎么看一个表有哪些列。
我是这么用archery的。
```
db.medDiag.find();
禁止执行该命令！正确格式为：{collection_name}.find() or {collection_name}.find(expression),如 : 'test.find({"id":{"$gt":1.0}})'
```
通过报错提示看，是不让加db前缀的。

于是更改命令：
```
medDiag.find();
filter must be an instance of dict, bson.son.SON, or any other type that inherits from collections.Mapping
```
通过报错提示看，是不能查看所有数据的，必须加过滤条件。
于是更改命令：
```
medDiag.find({"诊断ID" : "286690axxxxxxxxx"});
result:
{"_id": {"$oid": "5cc7axxxxx"}, "areaCode": "guangdong_jy", "诊断ID": "286690aexxxxxx......
```
这回输出正确结果了。

我这里要咨询的是，如果不让看monodb的表结构，或者不让使用db.medDiag.find()命令提前预览数据，我怎么知道这个表有哪些字段呢。

### 版本信息
 - 应用版本/分支：1.7.8
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
mongo 好像没有统一的表结构, 没法在选表的时候就拿到表结构, 我对mongo了解不多, 对mongo查询的检查是在这里

https://github.com/hhyo/Archery/blob/77865fc04a22cf9c4023e22ac7d108a74d569d01/sql/engines/mongo.py#L50-L62

我理解这个是想减少对性能的影响, 如果你有更好的方法欢迎提出, 或者直接提pr.

**Comment by czxin788** [comment]
如果能执行db.medDiag.find(); 语句预览前几条数据也是好的。
这样也能看到大概表结构和一些数据，不知我的理解是否准确。

**Comment by hhyo** [comment]
可参考这里的实现
https://github.com/getredash/redash/blob/6a5445b72670e928c740e6797407e8bd85ee8887/redash/query_runner/mongodb.py#L212
