### ISSUE TITLE
[ 问题咨询 ] 工单“查看提交信息”，审核人看不到

### ISSUE THREAD

**Issue by Liuzhj** [hhyo/Archery#705]
### 问题描述

上线工单审核人员在“SQL上线” 菜单 -> 选择一个工单进入 -> 工单名称旁边 ，没有“查看提交信息”。
但平台管理员可以查看。

请问这样现在是 by design吗？ 
或者分配什么权限，审核人员就能看到“查看提交信息”呢？

![image](https://user-images.githubusercontent.com/14147011/78866915-d9f82480-7a72-11ea-9ea0-36d22af7535e.png)

### 版本信息
 - 应用版本/分支：Release v1.7.8
 - 部署方式：Docker

**Comment by hhyo** [comment]
设计如此
