### ISSUE TITLE
在线查询oracle无法执行分组或排序

### ISSUE THREAD

**Issue by zsylove1987** [hhyo/Archery#707]
在线查询oracle无法执行分组或排序
select code from PUBLIC_NO group by code;
select code from PUBLIC_NO order by code;
select code from PUBLIC_NO  where status='1' group by code;
报ORA-00933: SQL command not properly ended
 希望下个版本改进！

**Comment by jan-song** [comment]
这个问题已经提单了修复方法了，项目组暂未merge代码#701

**Comment by jan-song** [comment]
这个问题已经提供了修复方法了，项目组暂未merge代码，可自行修改oracle.py的filter_sql方法实现#701
