### ISSUE TITLE
立即执行和定时执行 导致重复执行工单[ bug ]

### ISSUE THREAD

**Issue by liuxinwang** [hhyo/Archery#712]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1.开发提交了一个insert的工单到mysql实例，并设置执行时间为13:00 - 14:00
2.dba执行审核通过，设置定时执行时间为13:00
3.开发有可执行自己提交的工单的权限，在定时执行前去修改了定时执行时间为13:30
4.在13:01分开发对未到定时执行的工单执行了上线，该工单结束
5.等到了13:30分系统又自动执行了一次该工单，导致同一工单数据写入了两次。

### 期待结果和实际结果
期待结果：
对审核通过后未到定时执行时间的工单，上线人修改了定时执行时间，上线人在定时执行时间前执行了自己的工单后不再重复执行定时任务。
实际结果:
对审核通过后未到定时执行时间的工单，上线人修改了定时执行时间，线人在定时执行时间前执行了自己的工单后到了定时执行时间重复执行。
### 截图
![image](https://user-images.githubusercontent.com/20015177/79539706-6b8e1480-80b9-11ea-83c1-2f937cd8b805.png)

 
### 错误日志
错误日志中看到在上线人修改了定时执行时间后相应task也删除了，并未看出异常，请参考重现步骤重现即可。

### 版本信息
应用版本/分支：
v1.7.1
部署方式：Docker、手工部署
Docker

**Comment by hhyo** [comment]
感谢反馈，v1.7.9的更新能一定程度解决这个问题，但如果到达定时执行时间工单仍在执行中，还是会出现，下一版本解决
