### ISSUE TITLE
[ 问题咨询 ]平台部署有没有硬件需求说明

### ISSUE THREAD

**Issue by jan-song** [hhyo/Archery#713]
### 问题描述
想咨询一下各位，archery平台，需同事部署goinception和inception（都是docker部署）。部署服务器大概需要多大的内存和CPU，redis也部署在这个服务器上。当前是一台4GB，2核的云主机，跑了1个5M的MySQL的SQL文件，直接导致服务器内存满了，服务器hang机。
### 版本信息
 - 应用版本/分支：Release v1.7.8
 - 部署方式：Docker

**Comment by hhyo** [comment]
使用的应该是Inception吧，Inception审核现在还有一个前置检测用到了sqlpaser的split，会比较消耗性能，用GoInception应该不会有问题

**Comment by Yebolin** [comment]
不用incepthion的话，能直接不启动那个服务么？
