### ISSUE TITLE
[ 问题咨询 ]redis库在线查询，如何开放使用这个几个命令ZSCORE、ZRANGE 

### ISSUE THREAD

**Issue by withmi** [hhyo/Archery#716]
### 问题描述
在线查询中，redis很多命令被屏蔽了，查询起来不方便，想放开这些redis查询命令，ZSCORE   ZRANGE   ZREVRANGE  ZRANGEBYSCORE  ZREVRANGEBYSCORE  ZRANK  ZREVRANK，需要在哪里修改配置或者设置？

### 版本信息
 - 应用版本/分支：Release v1.7.0
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
善用搜索, 在代码库里搜一下报错信息就可以查到了

https://github.com/hhyo/Archery/search?q=%E7%A6%81%E6%AD%A2%E6%89%A7%E8%A1%8C%E8%AF%A5%E5%91%BD%E4%BB%A4&unscoped_q=%E7%A6%81%E6%AD%A2%E6%89%A7%E8%A1%8C%E8%AF%A5%E5%91%BD%E4%BB%A4
