### ISSUE TITLE
[ 问题咨询 ] 无法连接Oracel 9i DB

### ISSUE THREAD

**Issue by liushaoqiu** [hhyo/Archery#717]
### 问题描述
无法连接Oracel 9i DB , 11g Oracle DB可以连上。

### 版本信息
 - 应用版本/分支：Release v1.7.4
 - 部署方式：Docker 

请问Archery是否支持Oracle 9i DB, 或者有没有什么办法支持呢？

**Comment by LeoQuote** [comment]
信息太少了, 日志? 网络?

**Comment by jan-song** [comment]
居然还有9i的库，都淘汰10多年了吧

**Comment by liushaoqiu** [comment]
@LeoQuote 不好意思，不太熟，我们是安装在Windows Docker中，请问日志在哪个文件中呢？
@jan-song  我们ERP用的是Oracle EBS11i, 自带的9i DB.
