### ISSUE TITLE
请问支持redis集群吗

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#720]
redis集群是否支持，谢谢

**Comment by LeoQuote** [comment]
readme 里写了 redis 的支持情况, 只支持查询和执行.

**Comment by czxin788** [comment]
是不是 archery 不支持redis集群。

因为，我用archery连接redis集群中的一个节点，查询时报错，


Error
--
MOVED 5937 172.17.xx.2 :6382

这个好理解，这是因为被查询的redis是个集群，所要查找的key不在被查询的节点上，而是在其他节点上，所以需要moved转移到其他节点上查询才行。

在redis集群中，如果用命令查集群中的key，需要用redis-cli -a xx -h 172.17.xx.xx -p 6382 -c登录，注意是-c参数，这样才能保证登录的是redis集群，不加就是登录的单节点redis。

请问，archery支持redis集群吗
