### ISSUE TITLE
[ bug ]SQL上线编辑器无法支持某些特殊字符

### ISSUE THREAD

**Issue by bhzhu203** [hhyo/Archery#726]
版本：Archery (v1.7.7)

### 重现步骤
SQL文件：
[archery-error.txt](https://github.com/hhyo/Archery/files/4550652/archery-error.txt)

### 期待结果和实际结果
期待结果：
通过
实际结果:
报错：line 9 column 14 near "" (total length 337)

### 截图
![lALPDgtYtNZpn9LNA2jNBVU_1365_872](https://user-images.githubusercontent.com/3523160/80577652-cd476a80-8a39-11ea-8ee7-07e3f8c502bd.png)

部署方式：Docker

**Comment by hhyo** [comment]
无法重现，参考 https://demo.archerydms.com/detail/1160/
