### ISSUE TITLE
[ 问题咨询 ] csrf  问题

### ISSUE THREAD

**Issue by skymoou** [hhyo/Archery#728]
### 问题描述
使用非Google浏览器时候，用户登录系统会报错 forbidden
错误日志如下：
Forbidden (CSRF cookie not set.): /authenticate/

Google浏览器没有这个问题

### 版本信息
 - 应用版本/分支：Release v1.7.9  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
safari 没重现，用钉钉内置的浏览器倒是会遇到，相关代码在这里，如果有修改建议可以提交pr
https://github.com/hhyo/Archery/blob/afcc013435cba378201192d7978d72623dd59a0b/common/templates/base.html#L281-L302
