### ISSUE TITLE
在线查询-1.7.10版本Oracle从库所有SQL都报错了[ bug ]

### ISSUE THREAD

**Issue by zsylove1987** [hhyo/Archery#729]
在线查询-Oracle 从库，查询所有SQL全报错
select * from PUBLIC_NO;
ORA-00604: error occurred at recursive SQL level 2 ORA-16000: database open for read-only access
错误日志：explain plan for select * from public_no
没有添加explain,自动添加上了，查从库报错了

**Comment by jan-song** [comment]
画蛇添足了，查询加了个语法检查功能，standby库需要把这部分代码去掉
sql/engines/oracle.py脚本，318行去掉如下几行：
        # select语句先使用Explain判断语法是否正确
        if re.match(r"^select|^with", sql, re.I):
            explain_result = self.explain_check(db_name=db_name, sql=f"explain plan for {sql}")
            if explain_result['msg']:
                result['bad_query'] = True
                result['msg'] = explain_result['msg']

**Comment by LeoQuote** [comment]
> 画蛇添足了，查询加了个语法检查功能，standby库需要把这部分代码去掉
> sql/engines/oracle.py脚本，318行去掉如下几行：
> # select语句先使用Explain判断语法是否正确
> if re.match(r"^select|^with", sql, re.I):
> explain_result = self.explain_check(db_name=db_name, sql=f"explain plan for {sql}")
> if explain_result['msg']:
> result['bad_query'] = True
> result['msg'] = explain_result['msg']

直接提个pr吧

**Comment by jan-song** [comment]
#732
