### ISSUE TITLE
[ 功能建议 ] rds用户管理

### ISSUE THREAD

**Issue by skymoou** [hhyo/Archery#733]
### 目前遇到的问题/使用障碍
       目前archery里面对数据库用户管理是通过select from mysql.user去获取用户的管理
       但是，对于阿里云rds而言,普通用户是无法访问mysql.user的
       所以，archery目前对数据库用户管理方式并不适用于rds

### 希望如何解决/实现它
       在进行用户管理的时候，可以通过实例类型来判断是否是rds实例
       如果非rds实例可以直接使用select from mysql.user进行
       如果是rds实例可以通过阿里云提供的API接口的用户管理接口集成到数据库用户管理页面
### 其他信息
    
https://help.aliyun.com/document_detail/26263.html?spm=a2c4g.11186623.6.1635.18ec7019Qk3Jz5

**Comment by hhyo** [comment]
感谢建议，目前暂时不会拓展更多云数据库的功能，也没太多精力

**Comment by LeoQuote** [comment]
欢迎提pr，但总感觉，阿里云自带的控制台不香吗？

**Comment by skymoou** [comment]
如果，我要自己写，我需要去看哪一部分的源码？

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/a5a193f93ac7d0ad012058ae1106d13426c8fd33/sql/instance_account.py 主要是这里, 改的话很快的改法就是加个 if else , 不过有功夫的话建议还是类似 engine 一样做个共用的class , 然后mysql , aliyun , 等等各自实现, 这样的话后续的其他数据库的用户管理也有机会接入.
