### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by ouyangxiaoli** [hhyo/Archery#735]
### 问题描述
在通知配置项DDL_NOTIFY_AUTH_GROUP能一次全选所有的权限组吗？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
目前只支持一个权限组，要通知所有的话，可以设置为默认权限组
