### ISSUE TITLE
1.77升级到1.7.10  读的还是原来的1.77目录

### ISSUE THREAD

**Issue by gaoqiang-0327** [hhyo/Archery#738]
手动部署
做升级时候，杀掉原来的启动进程，nginx不动。页面访问依然正常。切换到1.7.10后，打开界面还是显示1.7.7版本，在别的机器打开页面异常。
nginx配置文件：
server{
        listen 80; # 监听的端口
        server_name archery.xxxxxx.com;
        client_max_body_size 20M; # 处理Request Entity Too Large
        proxy_read_timeout 600s;  # 超时时间与Gunicorn超时时间设置一致，主要用于在线查询

        location / {
          proxy_pass http://127.0.0.1:8000;
          proxy_set_header Host $host:9123; # 解决重定向404的问题，和listen端口保持一致，如果是docker则和宿主机映射端口保持一致
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static {
          alias /opt/app/archery/Python-3.6.5/archery-1.7.7/static; # 此处指向settings.py配置项STATIC_ROOT目录的绝对路径，用于nginx收集静态资源
           #alias /opt/app/archery/Python-3.6.5/Archery-1.7.10/common/static;
	}

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
启动命令：
nohup python3 manage.py qcluster &
nohup python3 manage.py runserver 0.0.0.0:9123 --insecure &

**Comment by LeoQuote** [comment]
大哥你启动server 是 9123 , nginx 又是8000
```
    location / {
      proxy_pass http://127.0.0.1:8000;
```
是想干啥?

**Comment by gaoqiang-0327** [comment]
眼花了。。。忘改这个了。。。尴尬

**Comment by gaoqiang-0327** [comment]
dsa

**Comment by LeoQuote** [comment]
生产服务不建议用runserver , 看一下django 的 deployment checklist 
* https://docs.djangoproject.com/zh-hans/3.0/howto/deployment/ 
* https://docs.djangoproject.com/zh-hans/3.0/howto/deployment/checklist/ 

建议用uwsgi 或者 gunicorn 之类的.
