### ISSUE TITLE
[ 问题咨询 ] mysql的查询改写逻辑是什么？

### ISSUE THREAD

**Issue by phantomsoul** [hhyo/Archery#739]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
```select `id` as `site_id`, `nick_name` from `kbd_site_info` where `nick_name` like '%丸子%' order by `created_at` desc limit 10```
执行结果有数据
```select `id` as `site_id`, `nick_name` from `kbd_site_info` where `nick_name` like '%丸子%' order by `created_at` desc limit 10 offset 0```
执行结果没数据
```select `id` as `site_id`, `nick_name` from `kbd_site_info` where `nick_name` like '%丸子%' order by `created_at` desc limit 10 offset 1```
执行结果只有一条数据
### 期待结果和实际结果
期待结果：
根据正常SQL语法的到数据
实际结果:
无法获取数据
### 截图
![微信截图_20200514095218](https://user-images.githubusercontent.com/20916982/81883772-ab68ee80-95c8-11ea-8ab5-a66fc544944c.png)
![微信截图_20200514095234](https://user-images.githubusercontent.com/20916982/81883773-ac9a1b80-95c8-11ea-95c2-ca7ec63d29f0.png)
![微信截图_20200514095202](https://user-images.githubusercontent.com/20916982/81883777-ae63df00-95c8-11ea-8f82-22101f1a55cc.png)

 
### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
#143 #647

**Comment by phantomsoul** [comment]
limit关键字和offet关键字功能是不是写反了，我用Navicat执行第二条语句是有结果返回的。
select `id` as `site_id`, `nick_name` from `kbd_site_info` where `nick_name` like '%丸子%' order by `created_at` desc limit 10 offset 0

**Comment by hhyo** [comment]
简单地说，平台目前不允许offset查询，都会被改写成limit x

**Comment by phantomsoul** [comment]
好的

**Comment by cdz620** [comment]
> 

不支持offset查询是出于什么考虑？是不是有踩过什么坑可以分享一下吗，目前我司在用的时候，有打算开放这个功能

**Comment by cdz620** [comment]
> 简单地说，平台目前不允许offset查询，都会被改写成limit x

@hhyo 
不支持offset查询是出于什么考虑？是不是有踩过什么坑可以分享一下吗，目前我司在用的时候，有打算开放这个功能
