### ISSUE TITLE
[ 问题咨询 ] 导出excel文件有记录日志吗？

### ISSUE THREAD

**Issue by nowindnowave** [hhyo/Archery#743]
你好，刚使用发现用户审核查询是有查询日志，但是用户有没有点击下载excel的按钮没找到日志记录，请问这个是否有添加？导出数据是一个重要的操作，谢谢！

**Comment by hhyo** [comment]
没有相关记录，既然用户已经接触数据了，这个记录也没太大意义，相关讨论可以见 #434
