### ISSUE TITLE
[ bug ]包含"\"xxx\""的json串在生成回滚语句时转义符缺失导致回滚数据与原数据不一致

### ISSUE THREAD

**Issue by skyecool** [hhyo/Archery#751]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1、创建测试表

CREATE TABLE `test_json_text` (
`id` bigint(30) unsigned NOT NULL AUTO_INCREMENT COMMENT '任务id',
`configs` text COMMENT '配置的环境变量',
`mark` varchar(20) DEFAULT NULL COMMENT '测试更新',
PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8mb4 COMMENT = '测试json双引号';

2、客户端工具写入原始数据：

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/25856760/82534141-391f7d80-9b77-11ea-9445-82de5f075651.png">

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/25856760/82534195-518f9800-9b77-11ea-96c5-e4c99c542459.png">

(提交issue 以下原数据也进行了转义，已上图为准)
查询原始数据
mysql> select * from test_json_text\G
*************************** 1. row ***************************
     id: 1
configs: {"receivers":"\"abx@xxx.com,abc@xxx.com,ab@xxx.com,ac@xxx.com,aa@xxx.com,ab@xxx.com\"","subject":"\"新-数据\"","run.priority.level":"1","mail_config":"\"[{'description': '新-数据','path': '/data/dev_test/data-w/sql/xxx_email/email_xxx_abc_ddd_ccc.sql','headers': '[城市][仓库][产品id][产品名称][商品id][商品名称]','is_attachment': 'Y','attachment': '新-装数据'}]\"","roll.back.wait.time":"10","roll.back.times":"3"}
   mark: NULL

3、提交变更工单
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/25856760/82534497-ce227680-9b77-11ea-8b78-10f3904e4de8.png">

update test_json_text set mark='"\"xxx\"" 生产回滚测试' where id='1';

4、查看生成的回滚语句
UPDATE `testdb1`.`test_json_text` SET id=1,configs='{"receivers":""abx@xxx.com,abc@xxx.com,ab@xxx.com,ac@xxx.com,aa@xxx.com,ab@xxx.com"","subject":""新-数据"","run.priority.level":"1","mail_config":""[{''description'': ''新-数据'',''path'': ''/data/dev_test/data-w/sql/xxx_email/email_xxx_abc_ddd_ccc.sql'',''headers'': ''[城市][仓库][产品id][产品名称][商品id][商品名称]'',''is_attachment'': ''Y'',''attachment'': ''新-装数据''}]"","roll.back.wait.time":"10","roll.back.times":"3"}',mark=NULL WHERE id=1;

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/25856760/82531228-839dfb80-9b71-11ea-84c7-8617e8f5ef25.png">

5、提交回滚工单
<img width="951" alt="image" src="https://user-images.githubusercontent.com/25856760/82533647-4be58280-9b76-11ea-9fd6-39a1c234da23.png">

6、查询回滚后的数据与数据变更前原数据不一致

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/25856760/82533261-7b47bf80-9b75-11ea-8068-e0f46cb63306.png">

部署方式：Docker 遇见此问题的版本
版本：Archery (v1.7.0)
版本：Archery (v1.7.10)

**Comment by hhyo** [comment]
感谢细致的反馈，建议参考 https://demo.archerydms.com/detail/1259/   提交一个工单重现一下

**Comment by skyecool** [comment]
现在提交我看不存在这个问题了，https://demo.archerydms.com/detail/1265/
