### ISSUE TITLE
[ 问题咨询 ]实例配置中用户名和密码采用了加密处理，可是在全部后台数据里能看到用户名和密码，请问这样在数据传输过程是加密的吗？

### ISSUE THREAD

**Issue by xqd0924** [hhyo/Archery#753]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
看 mysql server 的设置, 如果mysql server 开启了加密, 那么传输过程中就是加密的.
