### ISSUE TITLE
[ 问题咨询 ] soar 优化时如果有备注会自动截断

### ISSUE THREAD

**Issue by wuxs231** [hhyo/Archery#756]
### 问题描述
使用soar作为优化器，但是如果sql过长的话，会被自动截断，在获取优化建议里面执行会失败，不知道如何解决这个问题呢？

### 版本信息
 - 应用版本/分支：Release v1.7.10
 - 部署方式：手工部署

**Comment by wuxs231** [comment]
你好，已经解决，发现是sql中存在注释的问题，导致代码被截断，希望后续能够兼容注释。同时还发现一个问题，就是case when 里面存在中文的话，也会优化失败，不知道是soar的问题还是archery的问题。

**Comment by LeoQuote** [comment]
应该是soar的问题吧, archery 很简单的, 都是原样输入原样输出, 你可以直接用soar测试一下

**Comment by LeoQuote** [comment]
哈哈, 顺便提一下,我以为soar 已经凉了, 刚刚看还挺活跃, star也很多, 如果是soar的问题, 你可以手动自己升级下看看, 或者去soar的社区问问

**Comment by wuxs231** [comment]
好的，谢谢
