### ISSUE TITLE
[ 功能建议 ]dashboard 页面图表类无法实时更新

### ISSUE THREAD

**Issue by skymoou** [hhyo/Archery#757]
### 目前遇到的问题/使用障碍
dashboard 展示延迟
举例：
    我新增一个上线类型的工单，完成之后返回dashboard页面，图标类的并没有在原有的基础上加一，刷新页面强制更新也不行，要等很久之后才会出现新的图表

### 希望如何解决/实现它
    希望能够比较能够比较直接显示更新的图表
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
缓存 10 分钟, 这个是为了首页加载太慢做的, 首页的dashboard基本上等于全库扫描归类, 很费时间, 没有缓存的话可能会被用户正常请求打趴下.

https://github.com/hhyo/Archery/blob/8b40615ab5a010aba15cef4642b7dc11eee8c1d4/common/templates/dashboard.html#L6

**Comment by skymoou** [comment]
> 缓存 10 分钟, 这个是为了首页加载太慢做的, 首页的dashboard基本上等于全库扫描归类, 很费时间, 没有缓存的话可能会被用户正常请求打趴下.
> 
> https://github.com/hhyo/Archery/blob/8b40615ab5a010aba15cef4642b7dc11eee8c1d4/common/templates/dashboard.html#L6

哦。了解了，感谢解答
