### ISSUE TITLE
[ bug ] sql_workflow.py 修改不生效

### ISSUE THREAD

**Issue by skymoou** [hhyo/Archery#759]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1.通过startup.sh启动项目
2.修改sql_workflow.py 文件，如下：
   workflow_list = workflow.order_by('-create_time')[offset:limit].values(
        "id", "workflow_name", "engineer_display", "**demand_url**",
        "status",  "create_time","is_backup",
        "instance__instance_name", "db_name",
        "group_name", "syntax_type")
添加demand_url列查询

3.修改文件sqlworkflow.html 打开demand_url开关

4.页面展示。需求连接为空，

PS:数据库里面存储的demand_url不为空，是有值的

### 期待结果和实际结果
期待结果：
      sqlworkflow.html 的展示的demand_url数据库里面存储的值
实际结果:
       sqlworkflow.html 的展示的demand_url为空
### 版本信息
应用版本/分支：Release v1.7.10  

部署方式：手工部署

**Comment by LeoQuote** [comment]
二次开发的就自己多研究研究, 学习学习哈. 这个描述最好再有条理一些, 可以列出一下你所有的更改吗?

**Comment by skymoou** [comment]
> 二次开发的就自己多研究研究, 学习学习哈. 这个描述最好再有条理一些, 可以列出一下你所有的更改吗?

总共更改了两个文件
sql_workflow.py 在上文提过了，就增加了damend_url

文件sqlworkflow.html更改如下：

原文：
{
                    title: '工单完整名称',
                    field: 'workflow_name',
                    visible: false // 默认不显示
}

更改后
{
                    title: '需求链接',
                    field: 'demand_url',
                    formatter: function (value, row, index) {
                               return value;
                   }
}


比较奇怪一点
我在1.7.9时候改过，可以正常使用，但是我1.7.9的启动方式不是使用startup.sh启动的

**Comment by LeoQuote** [comment]
看不懂, 不知道你改了哪里. 和项目无关, 关了.
