### ISSUE TITLE
[ 问题咨询 ]是否支持开发环境不审批  生产环境走审批流程

### ISSUE THREAD

**Issue by cheekboy** [hhyo/Archery#761]
### 问题描述
目前是生产环境有审批流程  但是开发环境权限想开放  让开发可以直接查询sql  执行sql？ 目前是否支持？ 谢谢

**Comment by LeoQuote** [comment]
开发环境不能直连吗?  目前应该不支持, 都必须配置审批流

**Comment by LeoQuote** [comment]
demo 上是最新版, 你可以在上面试试, 应该是不行的

**Comment by hhyo** [comment]
目前审批流程不能为空，上线可以指定标签自动审批，查询没办法实现

**Comment by cheekboy** [comment]
已解决
