### ISSUE TITLE
[ 问题咨询 ]执行以下写法的sql会报错

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#764]
UPDATE xxx.xxx a
SET a.package_id = (
	SELECT
		b.package_id
	FROM
		xxx.xxx b
	WHERE
		b.order_detail_id = a.order_detail_id
	and b.order_detail_id not in ('1','2')
	AND IFNULL(b.delflag, '') = '0'
),a.update_by='349',a.update_date=NOW()
WHERE
	IFNULL(a.delflag, '') = '0';

archery执行以上格式的sql会提示子查询内的a.order_detail_id不存在，请问是哪条规则限制了吗？

**Comment by hhyo** [comment]
可以给goInception提交issue，这种场景切换成inception是可以正常执行的

**Comment by hhyo** [comment]
goinception应该已经修复子查询更新的问题，可以拉取最新版本确认下
