### ISSUE TITLE
[ bug ]oracle执行语句时报错日志显示TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by SoHuDrgon** [hhyo/Archery#766]
### 问题截图

![截屏2020-06-03下午4 29 18](https://user-images.githubusercontent.com/11847516/83614520-dfc43f00-a5b7-11ea-9d7d-cf04e7a8723c.png)

### 错误日志

```
[2020-06-03 16:11:27,814][DummyThread-6:140584775803720][task_id:default][oracle.py:284][WARNING]- Oracle 语句执行报错，语句：explain plan for update ORDER_INFO
set TRANS_STAT='1111'
where ORD_ID='00181911752885'
  and ORD_DATE='20200427'，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/oracle.py", line 279, in explain_check
    if rows[0] is None:
TypeError: 'NoneType' object is not subscriptable
```
### 版本信息
应用版本/分支：Release v1.7.11

部署方式：Docker

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/33f66b54a84bb40c9c21400c8365163dc7a83921/sql/engines/oracle.py#L261-L285

是在执行工单前 explain 检查的时候出错了, 没有返回结果我这边因为没有oracle环境, 你可以自己试一下这个explain 语句, 看一下到底是什么错.

这部分代码主要是 @jan-song 做的, 我暂时帮不上什么忙

**Comment by jan-song** [comment]
哪个版本的oracle?看看执行用户有没有SYS.PLAN_TABLE$这个表的查询权限，部署账号建议授权参考：
grant execute on dbms_logmnr to deploy;
grant EXECUTE ANY INDEXTYPE to deploy;
grant DROP ANY PROCEDURE to deploy;
grant DROP ANY VIEW to deploy;
grant DROP ANY INDEX to deploy;
grant INSERT ANY TABLE to deploy;
grant UNDER ANY VIEW to deploy;
grant DROP ANY INDEXTYPE to deploy;
grant ALTER ANY INDEXTYPE to deploy;
grant CREATE MATERIALIZED VIEW to deploy;
grant CREATE SESSION to deploy;
grant DEBUG ANY PROCEDURE to deploy;
grant ALTER ANY PROCEDURE to deploy;
grant CREATE ANY TABLE to deploy;
grant FLASHBACK ANY TABLE to deploy;
grant CREATE ANY INDEXTYPE to deploy;
grant CREATE PROCEDURE to deploy;
grant BACKUP ANY TABLE to deploy;
grant CREATE TABLE to deploy;
grant MERGE ANY VIEW to deploy;
grant CREATE ANY MATERIALIZED VIEW to deploy;
grant ALTER ANY INDEX to deploy;
grant COMMENT ANY TABLE to deploy;
grant MANAGE TABLESPACE to deploy;
grant SELECT ANY DICTIONARY to deploy;
grant UNDER ANY TABLE to deploy;
grant CREATE INDEXTYPE to deploy;
grant DROP ANY MATERIALIZED VIEW to deploy;
grant CREATE ANY VIEW to deploy;
grant CREATE VIEW to deploy;
grant DELETE ANY TABLE to deploy;
grant SELECT ANY TABLE to deploy;
grant DROP ANY TABLE to deploy;
grant ALTER TABLESPACE to deploy;
grant CREATE TABLESPACE to deploy;
grant ALTER ANY MATERIALIZED VIEW to deploy;
grant CREATE ANY PROCEDURE to deploy;
grant CREATE ANY INDEX to deploy;
grant UPDATE ANY TABLE to deploy;
grant LOCK ANY TABLE to deploy;
grant ALTER ANY TABLE to deploy;
grant DROP ANY SEQUENCE to deploy;
grant CREATE SEQUENCE to deploy;
grant ALTER ANY SEQUENCE to deploy;
grant SELECT ANY SEQUENCE to deploy;
grant CREATE ANY SEQUENCE to deploy;
grant select any transaction to deploy;
grant advisor to deploy;

**Comment by SoHuDrgon** [comment]
@jan-song 谢谢，已经解决了，是授权的问题。
