### ISSUE TITLE
慢查询日志显示错乱和不全

### ISSUE THREAD

**Issue by bigplumtree** [hhyo/Archery#769]
![TIM截图20200604155628](https://user-images.githubusercontent.com/52273287/83730910-4e6ad080-a67c-11ea-84f0-e3dda5e30a4c.png)
脚本上的hostname配置的是被监控mysql的ip：port
实例列表配置的名字也是ip：port
不知道哪里出错了
查慢日志的时候选日期显示的也不全 @hhyo

**Comment by hhyo** [comment]
慢日志相关不做更多回复，参考faq中的issue，还有可以了解下pt工具
