### ISSUE TITLE
[ 问题咨询 ]oracle数据库查询报：禁止使用 + 关键词

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#770]
### 问题描述
oracle数据库查询报：禁止使用 + 关键词
![image](https://user-images.githubusercontent.com/13861904/83754431-8551de00-a69e-11ea-87c1-296fc968c9bf.png)

### 版本信息
 - 应用版本/分支：Release v1.7.11 
 - 部署方式：Docker

 -

**Comment by czxin788** [comment]
![image](https://user-images.githubusercontent.com/13861904/83848066-e2ea3700-a73f-11ea-822f-798d4824bc39.png)

oracle的查询，不让使用+关键词查询，我应该怎么解决呢，在线等。

**Comment by czxin788** [comment]
select 2+1 from dual

**Comment by czxin788** [comment]
用+号的时候还是很常用的，比如substr(substring,instr(substring,'"',1,3)+1

希望能解决一下。

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/33f66b54a84bb40c9c21400c8365163dc7a83921/sql/engines/oracle.py#L313

在这里定义的，可以自己修改一下，另外关于禁用的关键字后续可以考虑各engine可以在配置内自定义，这样会比较方便🤔

**Comment by czxin788** [comment]
可以用了，谢谢
