### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by kwz1993** [hhyo/Archery#773]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
请问下为什么一直无法点击提交，我用admin账号，配置了sql上线语法，还是一直置灰状态。如图
![image](https://user-images.githubusercontent.com/62632544/84020207-0833ab00-a9b5-11ea-81c3-b7a1f963627b.png)

### 版本信息
 - 应用版本/分支：v1.7.10
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
要先检测, 再提交
