### ISSUE TITLE
语句执行错误，在客户端工具可以执行，请帮解决一下

### ISSUE THREAD

**Issue by whantt** [hhyo/Archery#774]
UPDATE erui_order.framework_agreement 
SET 
erui_order.framework_agreement.buyer_id = (SELECT erui_buyer.buyer.id
  FROM
    erui_buyer.buyer 
  WHERE
    erui_order.framework_agreement.crm_code = erui_buyer.buyer.buyer_code LIMIT 1);

提示 
列 'framework_agreement.crm_code' 不存在.selete语句请指定where条件.
  在客户端工具可以执行，请帮解决一下

**Comment by hhyo** [comment]
#764
