### ISSUE TITLE
下载SQL回滚报错:connect() argument 1 must be str, not None

### ISSUE THREAD

**Issue by yuanmeng-123** [hhyo/Archery#777]
### 问题描述
在使用Archery SQL审核上线功能时，在下载SQL回滚报错
报错结果：
connect() argument 1 must be str, not None

### 版本信息
 - 应用版本/分支：{"archery": {"version": "1.7.10"} 
 - 部署方式：Docker
![下载回SQL报错](https://user-images.githubusercontent.com/66777476/84372814-4b3c8b00-ac0e-11ea-9750-a77a54dcb681.png)
![Archery日志报错结果](https://user-images.githubusercontent.com/66777476/84373087-ab333180-ac0e-11ea-92c3-119faf8e9f03.png)

**Comment by hhyo** [comment]
系统设置没配置备份库连接信息

**Comment by yuanmeng-123** [comment]
> 系统设置没配置备份库连接信息
感谢，我这边先试一下

**Comment by yuanmeng-123** [comment]
> 系统设置没配置备份库连接信息
你好，我按你说的配置备份库连接，也显示有报错
![备份库配置](https://user-images.githubusercontent.com/66777476/84460868-98b40900-ac9d-11ea-92f2-3c11447afece.png)

**Comment by yuanmeng-123** [comment]
> > 系统设置没配置备份库连接信息
> > 你好，我按你说的配置备份库连接，也显示有报错
> > ![备份库配置](https://user-images.githubusercontent.com/66777476/84460868-98b40900-ac9d-11ea-92f2-3c11447afece.png)

你好，默认那个“Inception”是不用开启的吧，我看官方文档说的，直接用goInception，还是说Inception也要配置

**Comment by hhyo** [comment]
备份库的账号密码没填

**Comment by yuanmeng-123** [comment]
谢谢你，我这边现在解决了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小圈圈"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 中午12:01
收件人:&nbsp;"hhyo/Archery"<Archery@noreply.github.com&gt;;
抄送:&nbsp;"♂Dreamヾ"<499453652@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hhyo/Archery] 下载SQL回滚报错:connect() argument 1 must be str, not None (#777)





 
备份库的账号密码没填

**Comment by yuanmeng-123** [comment]
> 备份库的账号密码没填

你好，能不能再请教个问题，我这边操作SQL上线时，点击SQL检测的时候，我执行的SQL语句中有空值，但是提示不能为空值，不能提交不成功，请问这个在哪里修改呢？
![SQL语句不能为空](https://user-images.githubusercontent.com/66777476/84756858-f2963500-aff5-11ea-9e1e-e32a5e381a78.png)

**Comment by LeoQuote** [comment]
看一下 goinception 或者 inception 的文档吧, 这里应该是改 goincetion 的配置
