### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by lkxsoul** [hhyo/Archery#779]
在使用权限分组分配时，对于 SQL 权限 配置可查询所在资源组内的所有实例权限，用户指定此权限组时，查看菜单依然可以访问所用实例，下图为配置权限分组截图。

![image](https://user-images.githubusercontent.com/54697419/84728416-bfd34900-afc3-11ea-8a72-20d2215d97a4.png)

**Comment by LeoQuote** [comment]
没看懂你期望的是什么, 能不能说一下你期望什么, 实际发生了什么?

**Comment by lkxsoul** [comment]
我期望我设置为可查询所在资源组内的所有实例权限，资源组里目前只有一个实例，但是实际展示的是所用的实例

**Comment by LeoQuote** [comment]
你说的是, 期待是只展示资源组里的那一个实例, 实际上可以看到平台上所有的实例吗? 他可以正常查询所有实例吗?

**Comment by lkxsoul** [comment]
可以正常查询资源组下的实例，目前测试只有展示的是所有的实例，我看 network,中直接调用的 list()方法，可能是没有做这块的查询条件

**Comment by LeoQuote** [comment]
可以看到是符合预期的, 可以看到但是不能查询.

**Comment by lkxsoul** [comment]
那 sql|permission可查询所在资源组内的所有实例权限 这个权限控制的是哪方面的

**Comment by LeoQuote** [comment]
虽然在资源组内, 查询的权限还是要申请的, 有了这个权限就不需要申请了, 权限和描述是一致的啊

**Comment by lkxsoul** [comment]
看来是我理解的和您有误  如果我想展示资源组下所拥有的实例 需要怎么设置  您这方便有什么好的建议吗

**Comment by LeoQuote** [comment]
只要在资源组内的用户都可以看到资源组内的所有实例吧, 你想展示是对所有用户吗?

**Comment by lkxsoul** [comment]
嗯对的 以资源组为维度 同一资源组中可以查看对应资源组关联的实例信息 是针对所有用户的

**Comment by LeoQuote** [comment]
这个做不到的, 有一个方法是把你想要展示的实例放在默认资源组内, 然后把用户都加到默认资源组.

**Comment by lkxsoul** [comment]
我目前就是这么做的  还是可以看到所有的实例阿

**Comment by lkxsoul** [comment]
单独创建的资源组和权限组 针对用户进行同步 最后实例展示的时候 还是所有的实例

**Comment by lkxsoul** [comment]
这种方式好实现吗

**Comment by lkxsoul** [comment]
这种方式好实现吗  用户 -> 用户资源 -> 实例资源 -> 展示实例

**Comment by hhyo** [comment]
#612
用户是否还关联了其他资源组？
是否关联了有可查询所有实例的权限？

确认一下上面两个内容，也可以看一下关联issue的信息

**Comment by lkxsoul** [comment]
若用户关联了有可查询所有实例的权限  那就可以展示所有的实例信息

**Comment by lkxsoul** [comment]
用户是否关联其他资源组 这个并不影响 根据用户ID去用户资源组去查询对应的资源 然后进行下一步即可
若用户关联了有可查询所有实例的权限 那就可以展示所有的实例信息
关联issue的信息和我想了解的部分有出入 我觉得并不影响也不冲突

**Comment by hhyo** [comment]
所以用户关联的其他资源组是不是包含了其他的实例，如果包含，那么在查询页面展示出来就符合预期，查询页面没有选资源组的操作，默认展示用户关联的所有资源组的实例

**Comment by lkxsoul** [comment]
我这边测试的情况是 用户只关联了一个资源组 资源组里子包含一个实例 查询页面展示时  却展示的所有实例

**Comment by hhyo** [comment]
那接上面问题，用户是否关联了可查询所有实例的权限？

管理员默认拥有所有权限

**Comment by lkxsoul** [comment]
用户只关联了一个 实例管理、实例列表、可查询所在资源组内的所有实例 还有个主页权限

**Comment by hhyo** [comment]
哎，问题描述不清楚，浪费的是双方的时间

早说是实例列表的展示问题就好了，实例列表未做任何过滤，仅做权限检验，不建议开放给普通用户

**Comment by lkxsoul** [comment]
你们一个个来 给我弄糊涂了 你早出来 我早就解决了噻

**Comment by lkxsoul** [comment]
谢谢 您的回复

**Comment by lkxsoul** [comment]
有相关的执行计划 放宽到普通用户吗  实现实例列表过滤吗
