### ISSUE TITLE
[ 问题咨询 ]不支持AWS的redis

### ISSUE THREAD

**Issue by billy98** [hhyo/Archery#780]
### 问题描述
AWS云的redis无法使用Archery查询,因为AWS的redis默认是把config命令干掉了的（具体多少命令被干掉了不清楚，也可能影响其他）

### 版本信息
  - 应用版本/分支：Release v1.7.4
  - 部署方式：手工部署

![image](https://user-images.githubusercontent.com/13307862/84745222-ddfe7080-afe6-11ea-8b21-0f342cccf1af.png)

**Comment by LeoQuote** [comment]
解决了, 请升级 ,参见 #694
