### ISSUE TITLE
[ 问题咨询 ]如何添加工单状态标签

### ISSUE THREAD

**Issue by DBAyan** [hhyo/Archery#782]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

 

你好 ，我们的其他应用对archery进行了接口调用，会备份工单SQL的其他相关表的数据的一个功能，他们备份完成会返回给我们几个状态码，我们想要在archery的工单流程标签中添加一些状态，比如“三方备份完成”，“三方备份失败”，我修改了Archery/common/static/dist/js/formatter.js文件和 数据库的models模型，但是前端显示未知状态，麻烦问下是不是还需要修改别的地方？
![image](https://user-images.githubusercontent.com/50700896/84850799-31c29580-b08b-11ea-8e9d-32f965af588a.png)

**Comment by LeoQuote** [comment]
😅 这个状态是用国际化做的, 参考这个pr吧  https://github.com/hhyo/Archery/pull/714

**Comment by LeoQuote** [comment]
更改翻译文件后务必使用 python manage.py compilemessages 编译翻译文件

**Comment by DBAyan** [comment]
麻烦问下翻译文件是哪个文件。。？

**Comment by DBAyan** [comment]
![image](https://user-images.githubusercontent.com/50700896/84852342-27a29600-b08f-11ea-8472-5641ed5e7d61.png)
找到了这个翻译文件，因为不太了解django的国际化，大概是这个意思吗 
![image](https://user-images.githubusercontent.com/50700896/84852445-73edd600-b08f-11ea-8d2d-34a76a85a5e1.png)

**Comment by LeoQuote** [comment]
是的就是这样，中文的也要做的。

**Comment by DBAyan** [comment]
谢谢 已经修改成功
