### ISSUE TITLE
[ 问题咨询 ] 环境问题。docker部署 执行Python manag.py 报错

### ISSUE THREAD

**Issue by DBAyan** [hhyo/Archery#783]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.7.4 
 - 部署方式：Docker

 

![image](https://user-images.githubusercontent.com/50700896/84853419-c16b4280-b091-11ea-834e-d520394bbd36.png)

 docker 安装之后 ，执行python manage.py compilemessages 命令后报错 没有模块，这个问题怎么解决

**Comment by hhyo** [comment]
先切换Python运行环境
