### ISSUE TITLE
[ 功能建议 ]

### ISSUE THREAD

**Issue by jdj199222** [hhyo/Archery#784]
### 目前遇到的问题/使用障碍
一般研发提工单时候并不知道哪个实例有哪些数据库,而对于研发来说最熟悉的是数据库名称,根据我这边使用过的自己研发的数据库运维系统都是研发人员先选择数据库然后过滤出哪些实例包含这个数据库(实例名称可以判断出研发,测试,生产环境),然后再选择环境提交工单.

目前archery是先选择实例,但是如果一个实例上有多个数据库的情况下,并且很多个实例,这样对dba能找出对应的库,但是研发无法确定选择哪个实例进行提工单操作
### 希望如何解决/实现它

提工单部分调换先选库再选包含库的实例进行操作,方便研发提工单. 或者可以配置顺序,望采纳

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
数据库信息来源于实例，同时不排除有同库名的情况，要通过数据库定位实例，还需要再采集和维护一个对应关系

建议定义一个唯一可识别的标识，放到实例名称中，再不行就自己维护一个对应关系的文档吧，平台不考虑改动，感谢建议
