### ISSUE TITLE
SQL Server实例中查询 中文前加N异常

### ISSUE THREAD

**Issue by zhangshunbao** [hhyo/Archery#786]
SQL Server实例，查询  select N'失效',,
error msg:

('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'n'. (207) (SQLExecDirectW)")
--

**Comment by LeoQuote** [comment]
升一下 pyodbc 再试试? 如果恢复了可以顺手提个pr, 我这都没得 sql server 环境了.
