### ISSUE TITLE
Archery SQL上线提示执行的SQL语句不能为null

### ISSUE THREAD

**Issue by yuanmeng-123** [hhyo/Archery#787]
### 问题描述
在使用Archery SQL上线>提交SQL>输入SQL语句中带有null时，在SQL提交及检测时就不能通过，为什么只要语句中有null，就不能提交SQL上线，是不是在哪里有SQL提交语句有阈值的设定呀，还是Archery哪里需要再配置呀；不知道问题出在哪里。
![SQL语句提示不能为空](https://user-images.githubusercontent.com/66777476/85092497-5ac66000-b21c-11ea-9102-f7aff39c7f36.png)

### 版本信息
 - 应用版本/分支： Archery (v1.7.10) 
 - 部署方式：Docker

**Comment by hhyo** [comment]
文档多看看吧，issue别乱提了

**Comment by yuanmeng-123** [comment]
> 文档多看看吧，issue别乱提了

你是，管理员吗？

**Comment by liuwenzhi0318** [comment]
我也在想，有些字段就是允许为 NULL的，这种情况那怎么执行。
