### ISSUE TITLE
[ bug ]

### ISSUE THREAD

**Issue by anchen418857063** [hhyo/Archery#788]
分支：archery 1.7.11 功能bug 脱敏
在脱敏规则中配置了规则：
脱敏规则: 邮箱   (.*)@(.*)
然后通过在线查询发现并没有脱敏：
![image](https://user-images.githubusercontent.com/45680060/85093163-0f14b600-b21e-11ea-813b-9d41ec6bcee1.png)

**Comment by LeoQuote** [comment]
你正则写的对吗 是不是要写成这样 `(.*)@(.*)`

**Comment by anchen418857063** [comment]
(.*)@(.*) 是这样的

**Comment by anchen418857063** [comment]
是的 
![image](https://user-images.githubusercontent.com/45680060/85098650-e1d00400-b22d-11ea-95f6-d653697a87f1.png)

**Comment by anchen418857063** [comment]
是的
![image](https://user-images.githubusercontent.com/45680060/85099661-923f0780-b230-11ea-8911-0104fb3298bd.png)

**Comment by LeoQuote** [comment]
需要隐藏的组是不是 1 ?

**Comment by anchen418857063** [comment]
不管填1还是2 都一样，没有任何效果

**Comment by anchen418857063** [comment]
我QQ：418857063，可以加Q 给你演示

**Comment by LeoQuote** [comment]
可以在demo里重现试试
