### ISSUE TITLE
[ 问题咨询 ]如何通过配置去自动驳回含有join关键字的SQL语句

### ISSUE THREAD

**Issue by DBAyan** [hhyo/Archery#789]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.7.4  
 - 部署方式：Docker

 

你好 我可以用这个功能配置自动驳回含有join的SQL语句吗？我这样试了一下，所有的语句都不能提交了
![image](https://user-images.githubusercontent.com/50700896/85259993-8ce5f500-b49c-11ea-8044-23d8099569f8.png)

**Comment by LeoQuote** [comment]
你这个正则不对, 我们这个是整个匹配单条语句的, https://regex101.com/ 可以在这里测试你的正则
```
^(.*)join(.*)$
```

试试这个规则

**Comment by DBAyan** [comment]
这个规则也没有生效。内部检测是用inception完成的吗？

**Comment by LeoQuote** [comment]
不是, 就是正则匹配, 在archery 内部

**Comment by DBAyan** [comment]
能麻烦问下 代码在什么位置吗？ 正则表达式嗨哟别的方式吗~

**Comment by LeoQuote** [comment]
在项目内搜 critical_ddl_regex 就可以找到代码的

**Comment by DBAyan** [comment]
![image](https://user-images.githubusercontent.com/50700896/85269708-d89f9b00-b4aa-11ea-87c9-d3161dd2ea3b.png)
没有搜到 (⊙︿⊙)

**Comment by DBAyan** [comment]
`学习了一下正则表达式，^(.*)join(.*)$无法生效的原因是因为SQL美化后或者原始SQL中就包换了换行符，只能匹配到不包换换行符的那一行，然后又看了一下你说的你们的规则是匹配整条语句的，然后改成如下规则可以生效

`^([\s\S]*)join([\s\S]*)$|^([\s\S]*)JOIN([\s\S]*)$`

![image](https://user-images.githubusercontent.com/50700896/85282598-9bdd9f00-b4be-11ea-8468-7b47a993322a.png)
