### ISSUE TITLE
[ 问题咨询 ]求助，这是什么原因导致的问题

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#790]
1.7.9版本的archery，执行DML语句报一下错误
![微信图片_20200623143830](https://user-images.githubusercontent.com/50727710/85369458-b9167a00-b55f-11ea-8cc7-767d56bf97e1.png)

**Comment by hhyo** [comment]
这个看截图是使用了pt执行 可以了解下recursion-method参数
