### ISSUE TITLE
[ 功能建议 ] 在查询时的问题

### ISSUE THREAD

**Issue by gesions** [hhyo/Archery#791]
我在实例添加的时候只指定了一个数据库，为啥在查询的时候还能看到所有服务器的库的？
按理说我如果没有指定是可以把所有库显示出来的，但我已经指定了库了为什么还能看到所有库呢？

**Comment by LeoQuote** [comment]
看不懂, 这个用户你想让他只看到一个库, 但是怎么样都做不到, 是吗?

**Comment by gesions** [comment]
你们功能不是先要添加实例吗？我在实例已经指定了某个数据库，按理在查询也只能看到这个啊，现在你们是把这个服务器的所有数据库全部显示出来了。



---原始邮件---
发件人: "Leo Q"<notifications@github.com&gt;
发送时间: 2020年6月28日(周日) 下午5:09
收件人: "hhyo/Archery"<Archery@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Chen Aiguo"<chenaiguo@foxmail.com&gt;;
主题: Re: [hhyo/Archery] [ 功能建议 ] 在查询时的问题 (#791)




 
看不懂, 这个用户你想让他只看到一个库, 但是怎么样都做不到, 是吗?

**Comment by hhyo** [comment]
添加实例填写的数据库决定建立连接时访问的数据库，和展示没有关系，如果需要展示过滤，请通过配置的mysql账号权限进行限制
