### ISSUE TITLE
[ 问题咨询 ] 支持多行查询问题

### ISSUE THREAD

**Issue by cheekboy** [hhyo/Archery#792]
### 问题描述
目前archery默认支持第一行查询   想支持多行查询

后端取消了多行的切分  sqlcontent支持多行  发现还是限制查询第一行 想问题这个功能限制是在inception还是前端

**Comment by hhyo** [comment]
可参考这位大佬的提交 https://github.com/bf-leopard/Archery/commit/17333b6c9b70669884abbe7c981b4f99cfba6b76

有兴趣实现后可以合并到项目中

**Comment by cheekboy** [comment]
好的 感谢
