### ISSUE TITLE
[ 问题咨询 ]插入数据一直显示执行中

### ISSUE THREAD

**Issue by Elipha** [hhyo/Archery#793]
### 问题描述
使用archery发布，插入数据库2000多行数据，**显示一直在执行中**。查了数据库，数据进去了，没有问题，包括后面再使用archery发布，均显示已正常结束。

### 版本信息
 - 应用版本/分支：Release v1.7.7  
 - 部署方式：手工部署

![222](https://user-images.githubusercontent.com/59275066/85986867-70f3cd80-ba1f-11ea-8f23-6becd39b01cb.JPG)

**Comment by LeoQuote** [comment]
意思就是无法复现?

**Comment by hhyo** [comment]
找相关的日志，找不到就忽略吧，这个问题很少有人提供过有效的定位问题信息，数据库手动修改状态即可

文档
https://github.com/hhyo/archery/wiki/FAQ#工单状态一直是执行中

相关issue:
#110
#156
#242
#372

**Comment by xiaozhuang-a** [comment]
我的也是这种情况，没有报错日志，workflow_log中这个工单的流程没有执行结束这一步。

**Comment by xiaozhuang-a** [comment]
![image](https://user-images.githubusercontent.com/61875985/157036963-869475b7-c233-4e11-a5d5-80bf7a1cca2c.png)
