### ISSUE TITLE
[ 问题咨询 ] 生成的静态资源文件夹中的dist文件来自于哪里呢?

### ISSUE THREAD

**Issue by acdiost** [hhyo/Archery#796]
### 问题描述
我想修改登录页面的样式,collectstatic收集dist目录的静态资源文件来自于哪里?

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
在各app 的templates 和static 目录下, 这个不属于项目问题, 建议再学习一下 django 相关的知识

**Comment by acdiost** [comment]
我翻完了static所有目录都没有找到login.css等文件(除了项目根目录的static/dist/有),使用pycharm的全局搜索也没有搜索到相关的关键字(如:user-bottom-div).

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/common/static/dist/css/login.css

**Comment by acdiost** [comment]
非常抱歉,我看我下载的源码确实没有这个目录.添麻烦了.我手动添加上.下次提问前我应该再看看仓库的源码的.抱歉.
