### ISSUE TITLE
[ bug ]sqlserver数据库过滤显示搜索不到表,实际存在

### ISSUE THREAD

**Issue by jdj199222** [hhyo/Archery#799]
版本 1.7.11

sqlserver查询
![image](https://user-images.githubusercontent.com/40590418/86346568-b1f21900-bc8f-11ea-9d5e-900ad84a4931.png)

如上图,sqlserver 2008版本 另譬如member表查询,member表并不是第一个

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/b39dc850b3eb4426a4c23578328252c678e96f5f/sql/engines/mssql.py#L25-L42

这里是取表列表和数据库列表的语句, 你看一下你配置的账号有没有对应的权限

**Comment by hhyo** [comment]
也有可能是缓存，目前实例的库表资源默认有五分钟缓存

**Comment by jdj199222** [comment]
已经测试过了,现在表可以查到了,应该是缓存问题

**Comment by hhyo** [comment]
ddl工单执行结束会主动清理缓存，如果是不在平台内创建的目前只能等缓存过期
