### ISSUE TITLE
inception配置不生效

### ISSUE THREAD

**Issue by ciweigg2** [hhyo/Archery#8]
![image](https://user-images.githubusercontent.com/41536971/48049034-52045000-e1d8-11e8-9ce3-084e39db1c2b.png)

**Comment by hhyo** [comment]
没点击保存配置吧.

**Comment by ciweigg2** [comment]
我填完这些后点击测试就报错这个，连不上，是什么原因？

**Comment by hhyo** [comment]
先点最下面的保存...

**Comment by ciweigg2** [comment]
保存了，是不是inc配置文件要注意些什么

**Comment by hhyo** [comment]
你可以这样看能不能访问
```
docker exec -ti archery /bin/bash
mysql -hinception -P6669
 ```

**Comment by ciweigg2** [comment]
可以了 谢谢
