### ISSUE TITLE
[ 需求 ] 上线工单通知更多用户

### ISSUE THREAD

**Issue by zengyananaaa** [hhyo/Archery#80]
新发布的版本对于SQL上线的工单，审核通过后，只能发送邮件给申请人，请问如何修改脚本，满足工单审核通过后，发送邮件给DBA权限组，或抄送给DBA（以方便DBA及时执行SQL）？
（注：尝试修改过notify.py中审核通过模块中的msg_email_reciver，但是修改后所发送的邮件与之前相比，并未发生任何变化）

**Comment by hhyo** [comment]
可参考SQL执行结束的通知实现， [抄送DBA](https://github.com/hhyo/Archery/blob/master/sql/notify.py#L167) 

PS：issue标题修改一下吧

**Comment by zengyananaaa** [comment]
直接在抄送地址list_cc_addr中强制加上了DBA的邮箱，重启archery，搞定！
谢谢啦！（之前修改的一直不生效是因为没有重启archery[捂脸].jpg）

**Comment by LeoQuote** [comment]
没明白为啥关了又开, 我这里理解成手误了, 如果理解错了请重开issue
