### ISSUE TITLE
[ 问题咨询 ]工单状态都是“排队中”，是什么情况

### ISSUE THREAD

**Issue by zhangxin3166** [hhyo/Archery#800]
### 问题描述
![image](https://user-images.githubusercontent.com/67685405/86363984-2e91f100-bcaa-11ea-9a92-b52cc0117701.png)
所有提交的工单，最终状态都是 排队中，不知道是哪有问题

### 版本信息
 - 应用版本/分支：Release v1.7.10  
 - 部署方式：手工部署

**Comment by hhyo** [comment]
检查Django-q服务状态，提issue前也请多搜索下历史内容和文档
