### ISSUE TITLE
sqlserver 添加distinct关键字查询报错,是驱动版本问题吗?

### ISSUE THREAD

**Issue by jdj199222** [hhyo/Archery#801]
### 问题描述
mysql 使用distinct查询正常,但是sqlserver添加distinct报错如下

![image](https://user-images.githubusercontent.com/40590418/86761480-93699480-c078-11ea-872d-f25637caa839.png)

('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]关键字 'distinct' 附近有语法错误。 (156) (SQLExecDirectW)")
### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
sql server 的相关功能是我做的, 但我现在没条件再去调试这个了, 你可以自己尝试一下, 如果能修复还麻烦提个pr 或者在文档中说明, 非常感谢.

**Comment by jdj199222** [comment]
> sql server 的相关功能是我做的, 但我现在没条件再去调试这个了, 你可以自己尝试一下, 如果能修复还麻烦提个pr 或者在文档中说明, 非常感谢.

方便说下用到哪个模块吗

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/master/sql/engines/mssql.py sql server 的所有相关代码都在这里, 用的是 pyodbc

driver 在这里 https://github.com/hhyo/Archery/blob/b39dc850b3eb4426a4c23578328252c678e96f5f/src/docker/Dockerfile-base#L64-L68

**Comment by jdj199222** [comment]
> sql server 的相关功能是我做的, 但我现在没条件再去调试这个了, 你可以自己尝试一下, 如果能修复还麻烦提个pr 或者在文档中说明, 非常感谢.

确认原因了,select DISTINCT top 10  * from table; 这种语法是正确的 ,但是由于自动加分页导致对于distinct语句转换成了 select  top 10  DISTINCT * from table; 这种错误语法,所以报错,初步解决有distinct时手动添加top 100就可以了

**Comment by LeoQuote** [comment]
@jdj199222 赞, 有空看看能不能提个pr 修复一下 

替换相关的代码在这里: https://github.com/hhyo/Archery/blob/b39dc850b3eb4426a4c23578328252c678e96f5f/sql/engines/mssql.py#L114-L120

**Comment by jdj199222** [comment]
> @jdj199222 赞, 有空看看能不能提个pr 修复一下
> 
> 替换相关的代码在这里:
> 
> https://github.com/hhyo/Archery/blob/b39dc850b3eb4426a4c23578328252c678e96f5f/sql/engines/mssql.py#L114-L120
麻烦看看这样有无问题,我没有测试复杂sql
           def filter_sql(self, sql='', limit_num=0):
        sql_lower = sql.lower()
        # 对查询sql增加limit限制
#        if re.match(r"^select", sql_lower):
#            if sql_lower.find(' top ') == -1:
#                return sql_lower.replace('select', 'select top {}'.format(limit_num),1)
        if re.match(r"^select",sql_lower):
            if re.match(r"^select( *)top",sql_lower):
                return sql.strip()
            else:
                if re.match(r"^select( *)distinct",sql_lower):
                    if re.match(r"^select( *)distinct( *)top",sql_lower):
                        return sql.strip()
                    else:
                        return sql_lower.replace('distinct', 'distinct top {}'.format(limit_num),1)
                else:
                    return sql_lower.replace('select', 'select top {}'.format(limit_num),1)

        return sql.strip()

**Comment by jdj199222** [comment]
def filter_sql(self, sql='', limit_num=0):
        sql_lower = sql.lower()
        # 对查询sql增加limit限制
        if re.match(r"^select",sql_lower):
            if re.match(r"^select( *)top",sql_lower):
                return sql.strip()
            else:
                if re.match(r"^select( *)distinct",sql_lower):
                    if re.match(r"^select( *)distinct( *)top",sql_lower):
                        return sql.strip()
                    else:
                        return sql_lower.replace('distinct', 'distinct top {}'.format(limit_num),1)
                else:
                    return sql_lower.replace('select', 'select top {}'.format(limit_num),1)

        return sql.strip()

**Comment by LeoQuote** [comment]
@jdj199222 大佬直接提pr吧
