### ISSUE TITLE
[ 问题咨询 ] 新用户权限过大

### ISSUE THREAD

**Issue by hxfs** [hhyo/Archery#804]
### 新用户登录权限过大, 如图
- 在未申请权限的情况，用户能够查看所有表结构，这是设计原因还是什么原因
- 用户申请权限能否申请 archery 本身的权限而不是数据库的权限，例如申请 菜单 在线查询 权限

![image](https://user-images.githubusercontent.com/14288267/87001266-a485e300-c1e9-11ea-8d6f-cca9c5725e68.png)

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
第一个问题, 用户能看到所有表以及表结构

应该是用户进来之后的默认资源组里的资源太多了, 可以考虑新建资源组, 把不想让新用户看到的东西放到别的资源组内

第二个问题, 申请查询权限之外的权限:
现在没有这样的功能. 欢迎提pr
