### ISSUE TITLE
[ bug ] binlog2sql相关问题

### ISSUE THREAD

**Issue by kukukafei** [hhyo/Archery#809]
### 重现步骤

Archery/sql/plugins/binglog2sql.py  中 执行generate_args2cmd 的时候，直接使用的是 python +命令，这样的话默认会调用系统自带的python，如果使用虚拟环境的话，会造成无法找到依赖包，或者有python2 和3 的兼容问题。

可以用sys.executable 获取当前python 执行程序路径进行执行。

另外在使用binglog2sql 这个功能是，勾选上--flashback就不显示结果了，也没看到报错信息。

**Comment by LeoQuote** [comment]
感谢反馈，你说的这个问题应该确实是有可能发生，如果这个方案已经尝试试验过，可以直接提pr。

另外也可以考虑在配置项中提供配置 python 路径的功能。

下面那个问题不太了解

**Comment by hhyo** [comment]
建议考虑其他替代方案，binlog2SQL性能满足不了快速回滚的需求

**Comment by kukukafei** [comment]
> 建议考虑其他替代方案，binlog2SQL性能满足不了快速回滚的需求

勾选 --flashback以后不显示结果的原因找到了，由于网络传输的速率较慢，造成nginx 与后端连接超时，连接断开所致。可通过配置超时时间解决
