### ISSUE TITLE
pgsql写错误的密码列表页点击测试也显示连接成功

### ISSUE THREAD

**Issue by sxhyljava** [hhyo/Archery#812]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1、添加pgsql实例
2、添加错误的pgsql密码
3、点击测试，显示：连接成功

### 期待结果和实际结果
期待结果：连接失败

实际结果:  连接成功

### 版本信息
应用版本/分支：v1.7.10

部署方式：手工部署

**Comment by hhyo** [comment]
demo环境无法重现
