### ISSUE TITLE
在线查询功能，pgsql实例，数据库读取报错

### ISSUE THREAD

**Issue by sxhyljava** [hhyo/Archery#813]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

1、添加pgsql实例，用户名为brt，数据库为db_brt_test。
2、sql查询-在线查询-选择pgsql实例，弹出错误：数据库“brt”。

### 期待结果和实际结果
期待结果：读取数据库db_brt_test

实际结果:  貌似读取了用户名。

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by hhyo** [comment]
贴下具体错误日志，单存描述定位不到问题

**Comment by sxhyljava** [comment]
我截图了，您看看。日志没找到
![2](https://user-images.githubusercontent.com/13960745/87620310-ce428b00-c750-11ea-9a93-e6114666a479.jpg)
![1](https://user-images.githubusercontent.com/13960745/87620317-d26ea880-c750-11ea-979c-fbfa1b721c6b.jpg)

**Comment by sxhyljava** [comment]
![1](https://user-images.githubusercontent.com/13960745/87620552-748e9080-c751-11ea-8ffd-5ff0d190d1c3.jpg)
![2](https://user-images.githubusercontent.com/13960745/87620564-79ebdb00-c751-11ea-9559-3879d3faae3a.jpg)
您看看我得截图。

**Comment by LeoQuote** [comment]
截图没用啊大哥, 看一下日志

**Comment by sxhyljava** [comment]
[archery.log](https://github.com/hhyo/Archery/files/4929661/archery.log)
请看一下

**Comment by LeoQuote** [comment]
应该是预期内的 

get database 列表的时候需要 query `"SELECT datname FROM pg_database;"`

https://github.com/hhyo/Archery/blob/c63393cf5d3530f3e3af427013176649acb53aec/sql/engines/pgsql.py#L41-L49

此时get connection 的时候没有指定db,  就用的是username 作为 dbname

https://github.com/hhyo/Archery/blob/c63393cf5d3530f3e3af427013176649acb53aec/sql/engines/pgsql.py#L143-L149

**Comment by LeoQuote** [comment]
@hhyo model  里的 dbname 是干啥的, 好像pg里没用到

**Comment by LeoQuote** [comment]
应该是个bug, model 里的dbname 没用起来

**Comment by LeoQuote** [comment]
@sxhyljava 提pr了👆 可以checkout 下来试试看

**Comment by sxhyljava** [comment]
@LeoQuote 非常感谢
