### ISSUE TITLE
[ bug ] Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by niko-liu** [hhyo/Archery#816]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
腾讯云mariadb服务，配置账号密码测试实例连通性可以通过，但是选择数据库发布sql的时候失败

### 期待结果和实际结果
期待结果：
可以选择生产数据库

实际结果:
Lost connection to MySQL server during query

 
### 错误日志
MySQL语句执行报错，语句：show databases，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

### 版本信息
应用版本/分支：1.7.11

部署方式：Docker-compose、手工部署均出现此问题

**Comment by LeoQuote** [comment]
腾讯的数据库是不是不让 `show databases` ?

**Comment by niko-liu** [comment]
> 腾讯的数据库是不是不让 `show databases` ?

这只是其中一条错误，其余的查询错误报错是一致的，但是使用老版本1.7.9的时候却没有问题
腾讯云的数据库是基于mariadb做了mysql的兼容

**Comment by niko-liu** [comment]
类似的错误还有：

--------------
```
MySQL语句执行报错，语句：SELECT SCHEMA_NAME,DEFAULT_CHARACTER_SET_NAME,DEFAULT_COLLATION_NAME
FROM information_schema.SCHEMATA
WHERE SCHEMA_NAME NOT IN ('information_schema', 'performance_schema', 'mysql', 'test', 'sys');，错误信息Traceback (most recent call last):
  File "/opt/archery/sql/engines/mysql.py", line 153, in query
    effect_row = cursor.execute(sql)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/venv4archery/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
```
------
这些错误，在1.7.9版本上面不会出现

**Comment by LeoQuote** [comment]
引起这个的原因太多了，你是DBA应该很清楚，我建议你用mysqlclient自己连接试试看，排除一下看看到底是哪里的故障

**Comment by niko-liu** [comment]
我通过修改源码解决了
mysqldb在创建连接的时候，把connect_timeout延长，原来写的是10s，延长后不会再抛错误
`self.conn = MySQLdb.connect(host=self.host, port=self.port, user=self.user, passwd=self.password,
                                        db=db_name, charset=self.instance.charset or 'utf8mb4',
                                         conv=conversions,
                                         connect_timeout=100)`

另外打开数据字典的时候，上面修改仍会抛出异常，需要同时注释设置max_execute_time的代码
`
try:
    cursor.execute(f"set session max_execution_time={max_execution_time};")
except MySQLdb.OperationalError:
    pass
`
