### ISSUE TITLE
查询出来的身份证号码在页面显示没有问题，但是导出excel/csv格式后变成了科学计数，能否保持原样导出来或转为文本格式？[ bug ]

### ISSUE THREAD

**Issue by xiezhong1129** [hhyo/Archery#819]
查询出来的身份证号码在页面显示没有问题，但是导出excel/csv格式后变成了科学计数，能否保持原样导出来或转为文本格式？谢谢。

**Comment by LeoQuote** [comment]
大哥你但凡搜一下excel科学计数就不会问出这样的问题，这个是excel的一个技巧，和本项目无关，自己搜一下吧

**Comment by LeoQuote** [comment]
参考 #362 ,不会修复, 不是平台的问题.
