### ISSUE TITLE
怎么查看权限组里面关联了哪些人

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#82]
怎么查看权限组里面关联了哪些人

**Comment by hhyo** [comment]
admin页面用户管理
![image](https://user-images.githubusercontent.com/8842982/55134048-acd81d00-5162-11e9-8f8c-8e3c03c6d480.png)

**Comment by czxin788** [comment]
> admin页面用户管理
> ![image](https://user-images.githubusercontent.com/8842982/55134048-acd81d00-5162-11e9-8f8c-8e3c03c6d480.png)

谢谢，明白了，感谢。
