### ISSUE TITLE
[ bug ]Unknown column 'ssh_tunnel.pkey_path' in 'field list'

### ISSUE THREAD

**Issue by billy98** [hhyo/Archery#825]
### 重现步骤
docker部署的，从1.7.4升级到1.7.12，执行了所有的sql,但是还是报如下错误

### 截图
![image](https://user-images.githubusercontent.com/13307862/88032484-97b1a980-cb70-11ea-9721-dc8f43d1e5cc.png)

**Comment by LeoQuote** [comment]
感谢反馈, 这个是这部分的建表语句写错了, 用这个语句重试一下

```
CREATE TABLE `ssh_tunnel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tunnel_name` varchar(50) NOT NULL,
  `host` varchar(200) NOT NULL,
  `port` int(11) NOT NULL,
  `user` varchar(200) DEFAULT NULL,
  `password` varchar(300) DEFAULT NULL,
  `pkey_path` varchar(300) DEFAULT NULL,
  `pkey_password` varchar(300) DEFAULT NULL,
  `create_time` datetime(6) NOT NULL,
  `update_time` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tunnel_name` (`tunnel_name`)
) ;
```

**Comment by billy98** [comment]
升级到1.7.12 查询pgsql，还是会提示metabase这个库不存在，但是我这个metabase是pg的用户
![image](https://user-images.githubusercontent.com/13307862/88036347-004f5500-cb76-11ea-808a-e0b17a9864c1.png)

**Comment by LeoQuote** [comment]
这个问题参考下这个 https://github.com/hhyo/Archery/issues/813 , 里面有比较详细的解释, 还有什么问题可以回复.

**Comment by billy98** [comment]
没看明白要怎么修复这个问题

**Comment by billy98** [comment]
还有会报这个错

![image](https://user-images.githubusercontent.com/13307862/88041930-b36f7c80-cb7d-11ea-9060-4cddcfba15e9.png)

**Comment by hhyo** [comment]
> 感谢反馈, 这个是这部分的建表语句写错了, 用这个语句重试一下
> 
> ```
> CREATE TABLE `ssh_tunnel` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `tunnel_name` varchar(50) NOT NULL,
>   `host` varchar(200) NOT NULL,
>   `port` int(11) NOT NULL,
>   `user` varchar(200) DEFAULT NULL,
>   `password` varchar(300) DEFAULT NULL,
>   `pkey_path` varchar(300) DEFAULT NULL,
>   `pkey_password` varchar(300) DEFAULT NULL,
>   `create_time` datetime(6) NOT NULL,
>   `update_time` datetime(6) NOT NULL,
>   PRIMARY KEY (`id`),
>   UNIQUE KEY `tunnel_name` (`tunnel_name`)
> ) ;
> ```

这个改一下发个版吧，这有点坑了

**Comment by hhyo** [comment]
> 没看明白要怎么修复这个问题

用管理账号吧，pg使用不多，engine由社区贡献，目前无人维护

**Comment by EliasChiang** [comment]
> ### 重现步骤
> docker部署的，从1.7.4升级到1.7.12，执行了所有的sql,但是还是报如下错误
> 
> ### 截图
> ![image](https://user-images.githubusercontent.com/13307862/88032484-97b1a980-cb70-11ea-9721-dc8f43d1e5cc.png)

您好，该问题是由于我提交的init_sql和代码中的models不一致的问题，由于之前修改时未能充分测试所以未发现，按照@LeoQuote 的方式重建表可以解决该问题
