### ISSUE TITLE
[ 功能建议 ]工单审建议

### ISSUE THREAD

**Issue by Skatexg** [hhyo/Archery#827]
### 目前遇到的问题/使用障碍
当公司有多个项目组是独立时，数据库变更操作的审批人是对应项目组的负责人

用户使用场景：
研发工程师提交数据库变更，然后变更请求流转到对应的项目组技术负责人审批，通过后可以自动或定时执行（这个过程建议有邮件通知）【高风险变更，影响行数过多的，如2000W行，审核不通过，可以直接联系DBA特殊处理】

### 希望如何解决/实现它
为不同的资源组的人员配置不能角色，如：技术负责人、研发工程师，DBA。配置不同的审批流，审批流程关联需要的审批配置流

如有需要可以联系
微信：skatexg

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
感谢反馈，按照目前权限组审核的逻辑应该可以满足上面描述的需求

**Comment by Skatexg** [comment]
权限组没有办法隔离不同的项目组，如果把不同的项目组技术经理放到一个权限组里（rd-leader），会出现技术经理可以审核不是自己项目的请求

**Comment by hhyo** [comment]
审批流程是绑定资源组的，每个人只能审批自己资源组的数据，只要不同的项目对应不同的资源组，就可以做到隔离
