### ISSUE TITLE
[ 功能建议 ]支持sql中带有`转义符

### ISSUE THREAD

**Issue by niko-liu** [hhyo/Archery#829]
### 目前遇到的问题/使用障碍
老系统由于缺乏监管，表名和列名可能会带有关键字，需要用到转义符“`”转义，soar这个命令其实是可以识别转义符的，只要query参数用'' 单引号包裹传输就可以

### 希望如何解决/实现它
代码上不要强制replace("`", "")
subprocess操作的时候，使用'\' + SQL + \''包裹用户输入的sql，就可以成功把转义符传给soar

### 其他信息
我的改动
![image](https://user-images.githubusercontent.com/10355821/88254560-36144b00-cce8-11ea-88ee-3017964639d9.png)
![image](https://user-images.githubusercontent.com/10355821/88254585-49bfb180-cce8-11ea-877b-7fa2164b805c.png)

**Comment by LeoQuote** [comment]
.....麻烦直接提pr吧

**Comment by niko-liu** [comment]
> .....麻烦直接提pr吧

好吧
