### ISSUE TITLE
[ 问题咨询 ]回滚功能提示数据加载失败！(1146, "Table '***_ztest.$$Inception_backup_information$$' doesn't exist")

### ISSUE THREAD

**Issue by zsp108** [hhyo/Archery#831]
### 问题描述
SQL上线功能提交SQL工单执行后，点击查看回滚语句提示数据加载失败！(1146, "Table '******_3066_ztest.$_$Inception_backup_information$_$' doesn't exist")
但是在备份数据库里面查看这张表是存在的并且可以查询到执行记录，对应的回滚表内也有回滚语句生成记录，尝试从goinception切换到inception后测试还是一样会报错
查看archery log记录也跟上面一样提示表不存在的报错，没有其他相关的记录，这个是哪里有设置错误吗？

### 版本信息
 - 应用版本/分支：Release v1.7.12
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/wiki/faq#%E5%9B%9E%E6%BB%9A%E6%8A%A5%E9%94%99 文档看过了吗?

**Comment by zsp108** [comment]
> https://github.com/hhyo/Archery/wiki/faq#%E5%9B%9E%E6%BB%9A%E6%8A%A5%E9%94%99文档看过了吗？

嗯嗯，文档已经看过了，我不是提示权限不足之类的，我是SQL已经执行成功了，点击工单里面查看回滚语句提示回滚表不存在，账号我也是直接用root账号配置inception和goinception的，权限是all privileges *.*的，

使用mysql命令行工具登录配置账号查询 回滚功能提示不存在的表是可以查到的，并且有每次工单的执行记录和回滚语句存在，可以判断这个账号连接上是没有问题的，

**Comment by zsp108** [comment]
备份库配置：
![image](https://user-images.githubusercontent.com/31213457/88271244-7506c880-cd09-11ea-9834-0d3f2ade3da5.png)

测试业务表结构
![image](https://user-images.githubusercontent.com/31213457/88271107-4852b100-cd09-11ea-8ceb-282e30506328.png)
测试实例binlog：
![image](https://user-images.githubusercontent.com/31213457/88271526-d6c73280-cd09-11ea-8f94-2806c13afca7.png)


goinception配置：
![image](https://user-images.githubusercontent.com/31213457/88271355-a089b300-cd09-11ea-9fbd-4dbdf7c00822.png)
inception配置：
![image](https://user-images.githubusercontent.com/31213457/88271417-b1d2bf80-cd09-11ea-800c-935fdace8abe.png)

**Comment by zsp108** [comment]
回滚功能提示表不存在：
![image](https://user-images.githubusercontent.com/31213457/88271836-60770000-cd0a-11ea-821b-2dc56d875112.png)

数据库查询不存在的表有数据
![image](https://user-images.githubusercontent.com/31213457/88271677-1b52ce00-cd0a-11ea-93f4-081bbe9f7874.png)

**Comment by hhyo** [comment]
确认下系统配置中的备份库地址，archery用的是那个

**Comment by zsp108** [comment]
这些是我配置的数据库连接，我是在虚拟机里面建docker，然后直接使用docker-compose创建的mysql镜像，这些数据库配置都是一样的，这个有没有什么办法可以设置系统的调试？看看接口调用的查询之类的吗？
![image](https://user-images.githubusercontent.com/31213457/88352998-775f3600-cd8e-11ea-86b2-175c5dc1d309.png)
![image](https://user-images.githubusercontent.com/31213457/88353006-8219cb00-cd8e-11ea-91a2-6c16b9befb5a.png)
![image](https://user-images.githubusercontent.com/31213457/88353032-978ef500-cd8e-11ea-8c2a-931e5c1c8823.png)
报错日志
![image](https://user-images.githubusercontent.com/31213457/88353270-619e4080-cd8f-11ea-9d32-d45820848f19.png)

**Comment by zsp108** [comment]
或者备份功能这块逻辑是否方便讲下，我再排查下，是否是以下的逻辑？
工单提交了，是由goinception审核并生成回滚语句备份到备份库里面，然后archery是直接去获取备份库里面的备份语句还是有走其他的模块去查询的？

**Comment by zsp108** [comment]
已找到原因，原来是web页面里面的系统设置要设goinception和inception的连接端口账号等信息

**Comment by zsp108** [comment]
已找到原因，原来是web页面里面的系统设置要设goinception和inception的连接端口账号等信息，感谢
