### ISSUE TITLE
[ 功能建议 ] 实例配置页面的密码是明文显示

### ISSUE THREAD

**Issue by zsp108** [hhyo/Archery#832]
### 
建议在配置添加实例页面改进下密码明文显示的问题，设置为*号或者有按钮可以选择是否明文显示密码的选项

### 其他信息

![image](https://user-images.githubusercontent.com/31213457/88367757-20be2000-cdbf-11ea-9fc5-2d0ded5588a2.png)

**Comment by hhyo** [comment]
数据库中存储的是加密，如果希望展示加密后的信息，可参考https://github.com/hhyo/Archery/blob/master/sql/models.py#L615
自行修改
