### ISSUE TITLE
有没有什么方法可以在 发布mysql 存储过程 函数的时候，让SQL工单跳过审核 

### ISSUE THREAD

**Issue by 7101200** [hhyo/Archery#833]
鉴于 goInception 不支持存储过程函数变量等
有没有什么方法可以在 发布mysql 存储过程 函数的时候，让SQL工单跳过审核，直接进入审批流程，然后执行。

**Comment by hhyo** [comment]
目前暂时不支持，pymysql也不支持直接执行存储过程和函数，真需要的话只能使用mysql客户端source sql的方式
