### ISSUE TITLE
[ 问题咨询 ] 可以快速针对某张表全部字段做脱敏吗？

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#835]
### 问题描述
现需要对某些表全部字段做脱敏，archery能快速实现吗？

最终结果为：脱敏的表不能查询或者查询出来每个字段都是'****'

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker部署

**Comment by LeoQuote** [comment]
mysql 能不能直接把这个表的权限收了?

**Comment by ghost** [comment]
emmm，倒是也行，archery可以做还是mysql自带的功能？

**Comment by LeoQuote** [comment]
archery mysql 只能用 inception 脱敏, 具体的代码都在 engine 的masking 里面, 我说的收权限是直接在mysql 把权限收了

**Comment by ghost** [comment]
好的，谢谢
