### ISSUE TITLE
[问题] 请问权限组里面的人看不到发起人的工单是怎么回事

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#84]
**重现步骤**
1、开发组的A用户提交一个上线工单，这个工单的审批流程为运维DBA权限组；
2、运维DBA权限组选择的是所有权限，没选超级用户；
3、我把B用户加入运维DBA权限组；
4、以B用户身份登录archery系统，查看SQL审核--SQL上线里面，并没有A用户提交过了的工单。
请问是我操作的有问题吗？

**截图**

![image](https://user-images.githubusercontent.com/13861904/55138620-dd25b880-516e-11e9-93a5-655042704be5.png)

**版本信息**
 - 应用版本
 - 部署方式，Docker方式部署，昨天部署的

**Comment by hhyo** [comment]
文档资源组部分有写，后续请提供版本号，各版本代码有差异

**Comment by czxin788** [comment]
可以了，把运维DBA B用户也放入开发资源组里面，B用户就能看到A提交的工单了。

看来我是理解错了。
B用户要和A用户放入一个资源组里面才行。

**Comment by LeoQuote** [comment]
这个设计上是不是可以不用审批人和资源组关联?

毕竟审批人不一定需要提交工单

感觉有优化空间

**Comment by hhyo** [comment]
@LeoQuote 关联审批权限组的用户只能审批本身所在资源组的数据，这样做是为了隔离不同资源组的审批流程

因为权限组的设计是和资源组没有关联的，权限组类似角色，资源组类似项目，角色是全局的概念，就比如不同项目组都有项目经理，他们是同一个角色，拥有相同的权限，但能够管理的资源是不同的，不能跨项目审批

如果审批人只要在审批权限组中就可以查看和审批数据，会出现什么问题呢？

两个项目组审批流程都配置审批流程为：项目经理->DBA，那项目经理就可以跨项目审批了，除非给两个项目组都创建单独的项目经理角色，然后修改审批流程

**Comment by LeoQuote** [comment]
@hhyo 感谢解答， 了解， 那就把issue关了吧
