### ISSUE TITLE
[ 功能建议 ] redis查询支持zset相关命令

### ISSUE THREAD

**Issue by dongqianzheng** [hhyo/Archery#840]
### 目前遇到的问题/使用障碍
redis查询这块，目前还不支持有序集合（zset）相关命令，是否考虑支持下。
版本：v1.7.4
### 其他信息
        safe_cmd = ["scan", "exists", "ttl", "pttl", "type", "get", "mget", "strlen",
                    "hgetall", "hexists", "hget", "hmget", "hkeys", "hvals",
                    "smembers", "scard", "sdiff", "sunion", "sismember", "llen", "lrange", "lindex",
                    "zrange","zrangebyscore","zscore","zcard","zcount","zrank"]

**Comment by hhyo** [comment]
可以调整后提交pr，如果能修改为自定义配置更好

**Comment by dongqianzheng** [comment]
没提过。。。我看下怎么提pr。
