### ISSUE TITLE
【问题咨询】普通用户的权限申请通过后依旧无法执行查询sql，只有超级用户才能执行查询sql

### ISSUE THREAD

**Issue by Jacob-Gao** [hhyo/Archery#841]
问题描述

archery从1.66升级到1.7.12后,普通用户的权限申请通过后依旧无法执行查询sql，只有超级用户才能执行查询sql
![a](https://user-images.githubusercontent.com/44131869/89276249-02390e00-d676-11ea-8dcb-34302245dba2.JPG)
![b](https://user-images.githubusercontent.com/44131869/89276274-0a914900-d676-11ea-9284-9c2ed7a677a7.JPG)
![c](https://user-images.githubusercontent.com/44131869/89276281-0cf3a300-d676-11ea-9727-7d5ca14cf594.JPG)

版本信息
应用版本/分支：1.7.12
部署方式：docker部署

**Comment by Jacob-Gao** [comment]
官方FAQ提示：从v1.7.3开始，使用goInception来解析语句，进行表权限校验，注意检查goInception的连接以及goInception对查询实例的连接。我是docker安装，我通过docker logs命令去打印goInception日志，没有任何输出

**Comment by Jacob-Gao** [comment]
已经解决，配置下inspection

**Comment by super-dx** [comment]
@Jacob-Gao  你好  我也遇到了这种问题，能麻烦帮我看下吗？ https://github.com/hhyo/Archery/issues/1450 
我的inception配置是这样的
![image](https://user-images.githubusercontent.com/102796903/162689978-d9ebc697-fe73-4d97-b147-f67447e7b77a.png)
