### ISSUE TITLE
[ 问题咨询 ] 已选择不备份，但是依然报错备份库名 'db_host-3306-db_name' 过长，建议使用别名解析

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#842]
### 问题描述
提交SQL上线后自动审核不通过，但是已选择**不备份SQL**，依然报错：
`备份库名 'db_host-3306-db_name' 过长，建议使用别名解析`

参考了issue [#584](https://github.com/hhyo/Archery/issues/584)， goInception和Inception也都配置上了，平时需要Inception脱敏的功能

请问用`goinception`能在不修改域名长度和保持数据库脱敏的情况下解决这个问题吗？

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
goinception会自动截取，审核执行用goinception，脱敏用inception，不冲突

**Comment by ghost** [comment]
那请问有没有不修改域名长度正常使用的办法？

**Comment by hhyo** [comment]
切换为goinception审核执行就好啦，goinception会自动截取

**Comment by ghost** [comment]
已经解决了，非常感谢大佬 @hhyo 

解决步骤:
`系统管理` - `配置项管理` - `INCEPTION 是否切换为Inception审核`设置为OFF - 保存配置

**Comment by ghost** [comment]
还有一个问题，目前使用archery遇到了一个联合多表查询脱敏失败的情况，看了 #395  #145 

请问这个问题解决了吗？

**Comment by LeoQuote** [comment]
没有, 解决不了, 看 #145

**Comment by ghost** [comment]
好的，谢谢
