### ISSUE TITLE
pg数据库把默认的postgres库过滤掉了

### ISSUE THREAD

**Issue by 5sdba** [hhyo/Archery#845]
最新的1.7.2版本，pg连接源(pgsql.py)，代码里面排除了默认的postgres库：
    def get_all_databases(self):
        """
        获取数据库列表
        :return:
        """
        result = self.query(sql=f"SELECT datname FROM pg_database;", db_name=self.db_name)
        db_list = [row[0] for row in result.rows if row[0] not in ['data_warehouse','postgres','template0', 'template1']]
        result.rows = db_list
        return result

我们用的默认postgres库，大佬可以把这个过滤去掉么

**Comment by LeoQuote** [comment]
你如果想去就直接改代码吧, 对pg 了解不多, 也不知道当时为什么要在过滤的时候去掉这个库

**Comment by 5sdba** [comment]
我用的是docker版本的，改代码我要重新打包，我比较懒~_~

**Comment by chenyu1st** [comment]
我也遇到了这个问题，提了一个pr修复这个问题 https://github.com/hhyo/Archery/commit/b156cc97c4e332bfab03237115a2cb097de51320 @LeoQuote
