### ISSUE TITLE
[ 问题咨询 ] ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by firehalt** [hhyo/Archery#849]
### 问题描述

系统管理-配置项管理-系统设置-Inception配置：填写GO_INCEPTION_HOST地址和端口后，点击测试连接报错
  File "/opt/archery/common/check.py", line 87, in go_inception
    port=int(inception_remote_backup_port),
ValueError: invalid literal for int() with base 10: ''

### 版本信息
 - 部署方式：Docker安装，版本(v1.7.12)，(v1.7.10)都会出现一样的问题

**Comment by hhyo** [comment]
提示信息应该是提示备份库异常，配置下备份库的连接信息。用于查询回滚语句
