### ISSUE TITLE
[ 问题咨询 ]实例配置页面input 类型修改

### ISSUE THREAD

**Issue by zsp108** [hhyo/Archery#851]
### 问题描述
您好，请教下这个页面是在哪里可以进行修改的？我想把这个input修改为password类型的，避免直接显示配置密码在这个页面上
![image](https://user-images.githubusercontent.com/31213457/90595908-69cb8d80-e220-11ea-9c10-1b6aad7ffe6e.png)

### 版本信息
 - 应用版本/分支：Release v1.7.12  
 - 部署方式：Docker部署

**Comment by hhyo** [comment]
可以了解下django admin，看如何设置

**Comment by zsp108** [comment]
这个有具体的模块地址吗？或者在哪个文件夹下的？
