### ISSUE TITLE
[ 功能建议 ] 查询出来的数据结果是否能支持背景水印

### ISSUE THREAD

**Issue by nondevops** [hhyo/Archery#852]
### 目前遇到的问题/使用障碍
数据结果得不到安全保障

### 希望如何解决/实现它
在查询出来的数据结果的背景使用姓名作为水印,防止数据被截图;
同时拷贝数据需要走工单并通过各个部门审核通过后才能执行;
工单流程需要可配置化;

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
我个人对这个功能兴趣不大, 网页上还可以看控制台, 还要配套做加密解密吧. 但是听听你的方案也无妨, 详细说说你想怎么做?

**Comment by nondevops** [comment]
> 我个人对这个功能兴趣不大, 网页上还可以看控制台, 还要配套做加密解密吧. 但是听听你的方案也无妨, 详细说说你想怎么做?

先说下这个需求的背景，当今互联网代码不值钱，值钱的是数据，为防止公司内部有员工泄露数据（截图、拷贝、导出、API接口等形式）的行为，需要将数据作为公司的核心资产保护。

前端展示端：
1.将所有展示了查询结果的页面全部添加水印，水印内容以当前登录用户名作为水印背景；
2.在前端查询不展示重要字段，如password，mobile，username等关键字段，可作为配置项进行配置；

数据提取：
1.所有的数据查询结果，需走数据提取流程工单，经多部门审核通过后，由数据部门酌情处理；

**Comment by LeoQuote** [comment]
简单来说： 做不了，咱不是阿里，也没有阿里那个团队，接口数据没有加密，甚至要非对称加密，谈什么安全，防截图有什么意义，我复制粘贴就能破，难道把前端重做全做成图片渲染的？

安全和方便总要有个取舍，看你自己选哪个。能兼顾的都是大神，吾等也只是凡人，我们能提供的，就是一个方便的查询上线工具，没了。
