### ISSUE TITLE
[ 问题咨询 ]归档日志的开始时间和结束时间一样，是怎么回事，实际执行了好几个小时。

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#853]
### 问题描述
归档日志的开始时间和结束时间一样，是怎么回事，实际执行了好几个小时。
![image](https://user-images.githubusercontent.com/13861904/91142655-b6610e00-e6e3-11ea-8896-4ef059004acb.png)

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

**Comment by hhyo** [comment]
这个计时确实有问题，开发过程中已知

**Comment by zhituanchen** [comment]
您好：
请问一下，我添加归档任务时候提示：审批流程不能为空，请先配置审批流程；请问这个流程在哪里添加呢；
![image](https://user-images.githubusercontent.com/71009460/95950655-87cffb80-0e27-11eb-91e6-37881320d073.png)
该用户权限组：
![image](https://user-images.githubusercontent.com/71009460/95950739-b4841300-0e27-11eb-9678-76237afc46cd.png)
该用户权限组权限：
![image](https://user-images.githubusercontent.com/71009460/95950800-ce255a80-0e27-11eb-93e6-901b188edd8d.png)
我的SQL审批的流程是正常可以走通的；

**Comment by swords1999** [comment]
在models里面class ArchiveLog(models.Model)中start_time = models.DateTimeField('开始时间')就好了

**Comment by czxin788** [comment]
> 在models里面class ArchiveLog(models.Model)中start_time = models.DateTimeField('开始时间')就好了

欢迎提一个pr
