### ISSUE TITLE
[ 问题咨询 ]  一个数据库实例下有多个数据库时的权限控制

### ISSUE THREAD

**Issue by jiaoyilun** [hhyo/Archery#856]
一个数据库实例下有多个数据库，在配置此数据库实例时，指定了数据库名称，但是在前台操作时还是能选择其他数据库，能否控制不显示，没找到相关资料，求解

**Comment by LeoQuote** [comment]
改一下帐号权限让它只能看到这一个数据库

**Comment by jiaoyilun** [comment]
> 改一下帐号权限让它只能看到这一个数据库

你说的是数据库账号吗，数据库用不同用户分开？

**Comment by hhyo** [comment]
嗯，账号过滤，否则show databases也就暴露了
