### ISSUE TITLE
[ 问题咨询 ] 创建表时提示"禁止指定存储引擎"

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#857]
### 问题描述
使用的goInception，执行sql上线时报错
```shell
create table
...

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### 报错
禁止指定存储引擎

### 版本信息
 - 应用版本/分支：Release v1.7.11
 - 部署方式：Docker

**Comment by ghost** [comment]
切换到`Inception`审核解决了该问题

**Comment by wbcmax** [comment]
@hhyo @LeoQuote 

## 问题描述

### 问题1

使用 `Inception` 做审核遇到的问题, 两张表结构一样, 但是sql上线检测失败

```shell
INSERT INTO table2 SELECT * FROM table1 WHERE id IN (1, 2);
```

错误提示:

```shell
INSERT语句请指定字段列表
第 1 组插入数据值列表与字段列表数量不匹配
```

解决办法: 切到 `goInception` 解决了此问题

### 问题2: 

使用 `goInception` 做审核遇到的问题同上, 创建表的时候不能指定存储引擎, 切回 `Inception` 解决了此问题

## 期望结果

是否可以使用一个工具, 同时解决以上两个问题呢？

## 版本信息

- 应用版本/分支：Release v1.8.0
- 部署方式：Docker

**Comment by hhyo** [comment]
用goInception替代就好，能否指定存储引擎是一个配置项，可看goInception的说明文档，了解相关审核规则

**Comment by wbcmax** [comment]
感谢 @hhyo 的指导, `禁止指定存储引擎`的问题已经解决!

解决步骤:

- 修改 `goinception` 的配置项

如果用docker-compose 做了配置文件映射则直接修改容器外的文件

如果没有则进入容器

```shell
docker exec -it goinception sh

vi /etc/config.toml

- enable_set_engine                       =false
改为
+ enable_set_engine                       =true
```

- 重启 `goinception` 容器

```shell
docker restart goinception
```

**Comment by manlinux** [comment]
感谢分享，可以将/etc/config.toml映射到宿主机或者k8s的configmap里，可以方便修改

**Comment by LeoQuote** [comment]
@manlinux k8s 可以用这个 helm chart，支持配置 toml https://github.com/douban/charts/tree/master/charts/archery
