### ISSUE TITLE
iframe嵌套[ 问题咨询 ]

### ISSUE THREAD

**Issue by ghost** [hhyo/Archery#859]
我想问下我们想把这个平台 iframe 嵌入我们的系统里面。 怎么做 

 
'django.middleware.clickjacking.XFrameOptionsMiddleware',
屏蔽掉 之后登陆无法登陆，

**Comment by ghost** [comment]
POST http://10.122.69.73:9123/authenticate/ 403 (Forbidden)

**Comment by LeoQuote** [comment]
不太清楚iframe 的事情, 建议自己了解一下, 不属于我们的功能

**Comment by hhyo** [comment]
应该和csrf有关，具体可以查阅下相关文档
