### ISSUE TITLE
[ 问题咨询 ]dashboard无法显示图表

### ISSUE THREAD

**Issue by mingjia1** [hhyo/Archery#862]
### 问题描述
dashboard可以显示上面的数量，但是显示不出SQL查询统计/上线数量/上线用户/上线统计

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
1.4.5 太老了，升级再看吧

**Comment by mingjia1** [comment]
> 1.4.5 太老了，升级再看吧

现在是1.7.7了
