### ISSUE TITLE
[ 功能建议 ] 希望可以复制权限组

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#865]
### 目前遇到的问题/使用障碍
如果我想增加一个和A权限一样的B权限组，我现在的做法是照着A权限组，一个一个初始化B权限组，非常麻烦。
能不能有个功能直接复制A权限组，另存为B权限组。

**Comment by hhyo** [comment]
暂时不考虑，可通过复制相关表数据来实现
具体涉及auth_group_permissions和auth_group表

**Comment by czxin788** [comment]
明白了，自己拼接sql语句即可，我测试了，可以用

**Comment by czxin788** [comment]
参考sql：
insert into auth_group_permissions (group_id,permission_id) values (8,      136 );

**Comment by czxin788** [comment]
查询权限组有哪些权限的sql语句：

`select ag.name group_name, ap.name permission_name,ap.codename  from  auth_group_permissions agp inner join auth_group ag on  agp.group_id=ag.id inner join auth_permission ap on ap.id=agp.permission_id order by ag.name;`

**Comment by czxin788** [comment]
查看用户有哪些权限

```
select
  登录名,
  姓名,
  last_login,
  group_name,
  permission_name
from
  (
    select
      username 登录名,
      display 姓名,
      group_id,
      last_login
    from
      sql_users u
      inner join sql_users_groups ug on u.id = ug.users_id
  ) user_in_group
  inner join (
    select
      ag.name group_name,
      ap.name permission_name,
      ap.codename,
      agp.group_id
    from
      auth_group_permissions agp
      inner join auth_group ag on agp.group_id = ag.id
      inner join auth_permission ap on ap.id = agp.permission_id
    order by
      ag.name
  ) group_permission on group_permission.group_id = user_in_group.group_id
```
