### ISSUE TITLE
[ 问题咨询 ] 在带有触发器的表执行添加字段的DDL语句会报错

### ISSUE THREAD

**Issue by dmz-leon** [hhyo/Archery#867]
目前使用的archery版本为1.7.9
在带有触发器的表执行添加字段的DDL语句会报一下错误
![微信图片_20200902104735](https://user-images.githubusercontent.com/50727710/91926402-c2fbec80-ed09-11ea-92f8-3e5aa8dc8012.png)

**Comment by hhyo** [comment]
pt-osc是通过创建触发器去做表变更的，原表已存在触发器，同类型的触发器创建会失败，目前goinception和inception也都没有提供相关的配置参数，可以选择切换为gh-ost执行或者关闭osc功能

**Comment by hhyo** [comment]
和 #790 是相同的问题，建议此类错误多查看相关工具的官方文档，亦或是百度一下也可以

**Comment by dmz-leon** [comment]
> pt-osc是通过创建触发器去做表变更的，原表已存在触发器，同类型的触发器创建会失败，目前goinception和inception也都没有提供相关的配置参数，可以选择切换为gh-ost执行或者关闭osc功能

只是在表添加新字段

**Comment by hhyo** [comment]
抱歉，只能帮到这里了

**Comment by Alex-wwei** [comment]
我也遇到同样问题，请问最后解决了吗

**Comment by dmz-leon** [comment]
> 我也遇到同样问题，请问最后解决了吗

没有，后台将在触发器表操作的语句都放到终端执行了

**Comment by dmz-leon** [comment]
> 我也遇到同样问题，请问最后解决了吗
没有解决，后来将这种语句都放到终端执行了
