### ISSUE TITLE
[ 问题咨询 ]inception_magic_start 	con:50 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES).

### ISSUE THREAD

**Issue by hailianghe** [hhyo/Archery#868]
### 问题描述
审批工单的时候报错，查询没问题
报错如下：
![image](https://user-images.githubusercontent.com/29939806/91996604-c32cd400-ed6b-11ea-8882-d55abaf6da37.png)
看了下goinception也是报错
```
time="2020/09/02 22:17:31.590" level=error msg="con:45 con:45 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
time="2020/09/02 22:21:14.133" level=error msg="con:50 con:50 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
```

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker

### 已尝试的方法
查看以前的issue，2月份也有提过类似issue，是默认端口0没修改为3306，但我的已经是3306了

**Comment by hhyo** [comment]
检查goinception的备份库配置，目前备份库无法连接会出现这个异常

**Comment by hailianghe** [comment]
![image](https://user-images.githubusercontent.com/29939806/92061989-2baa9e00-edca-11ea-9cb4-b01e62c31383.png)
备份库都ok的，还是这个错误

**Comment by hhyo** [comment]
> ![image](https://user-images.githubusercontent.com/29939806/92061989-2baa9e00-edca-11ea-9cb4-b01e62c31383.png)
> 备份库都ok的，还是这个错误

这里ok不代表goinception本身的配置ok

**Comment by hailianghe** [comment]
如你所说，Archery/src/docker-compose/inception/config.toml 里面的数据库密码默认是123456，和页面配置的不一致造成的；

**Comment by hailianghe** [comment]
看到好多问题都在这里面有记录 https://github.com/hhyo/archery/wiki/faq#   后续的人有福了

**Comment by CorollaD** [comment]
> ### 问题描述
> 审批工单的时候报错，查询没问题 报错如下： ![image](https://user-images.githubusercontent.com/29939806/91996604-c32cd400-ed6b-11ea-8882-d55abaf6da37.png) 看了下goinception也是报错
> 
> ```
> time="2020/09/02 22:17:31.590" level=error msg="con:45 con:45 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
> time="2020/09/02 22:21:14.133" level=error msg="con:50 con:50 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
> ```
> 
> ### 版本信息
> * 应用版本/分支：Release v1.7.13
> * 部署方式：Docker
> 
> ### 已尝试的方法
> 查看以前的issue，2月份也有提过类似issue，是默认端口0没修改为3306，但我的已经是3306了

哪里配置默认0, 我的是3306 还是报这个错

**Comment by hhyo** [comment]
> > ### 问题描述
> > 审批工单的时候报错，查询没问题 报错如下： ![image](https://user-images.githubusercontent.com/29939806/91996604-c32cd400-ed6b-11ea-8882-d55abaf6da37.png) 看了下goinception也是报错
> > ```
> > time="2020/09/02 22:17:31.590" level=error msg="con:45 con:45 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
> > time="2020/09/02 22:21:14.133" level=error msg="con:50 con:50 Error 1045: Access denied for user 'root'@'172.19.0.3' (using password: YES)" file=session_inception.go func=parseOptions line=2050
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 版本信息
> > 
> > * 应用版本/分支：Release v1.7.13
> > * 部署方式：Docker
> > 
> > ### 已尝试的方法
> > 查看以前的issue，2月份也有提过类似issue，是默认端口0没修改为3306，但我的已经是3306了
> 
> 哪里配置默认0, 我的是3306 还是报这个错

检查goinception的备份库配置
