### ISSUE TITLE
[ 问题咨询 ]	Execute: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation (sql: SHOW MASTER STATUS;). Execute: 无法获取master binlog信息.

### ISSUE THREAD

**Issue by hailianghe** [hhyo/Archery#871]
### 问题描述
工单update一条数据的时候，会报错“Execute: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation (sql: SHOW MASTER STATUS;).Execute: 无法获取master binlog信息.”
![image](https://user-images.githubusercontent.com/29939806/92087186-ccff1780-edfd-11ea-88e7-a67460f6b848.png)
goinception报错：
```
is operation" file=session_inception.go func=mysqlFetchMasterBinlogPosition line=1570
time="2020/09/03 15:50:48.804" level=error msg="con:8 Error 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation" file=conn.go func=raw line=68
time="2020/09/03 15:50:48.804" level=error msg="con:8 Error 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation" file=session_inception.go func=mysqlFetchMasterBinlogPosition line=1570
```
现在不清楚是目标库要super权限查binlog，还是archery的备份库需要设置ROW格式并给super权限

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker

### 已经尝试方法
更改Archery/src/docker-compose/inception下的config.toml，inc.cnf；
重启了goinception,inception 无效果

**Comment by hailianghe** [comment]
问题已解决一半， 给目标库的连接账号赋予replication client权限即可执行， 但是备份报错了
![image](https://user-images.githubusercontent.com/29939806/92091732-b8be1900-ee03-11ea-9e08-05f15ef90b30.png)

**Comment by hhyo** [comment]
可以看goinception文档，了解相关的备份原理，知道执行用户应该有什么权限，备份用户应该有什么权限

备份数据需要在备份实例中建库建表写入数据

**Comment by hhyo** [comment]
如果问题解决欢迎帮助项目完善文档和补充FAQ，WIKI开放编辑
算是给愿意看文档的用户一点帮助

**Comment by hailianghe** [comment]
感觉有点怪异
![image](https://user-images.githubusercontent.com/29939806/92212498-9e983f80-eec4-11ea-864f-cd463015185e.png)
![image](https://user-images.githubusercontent.com/29939806/92212593-c687a300-eec4-11ea-85de-09767128219a.png)
![image](https://user-images.githubusercontent.com/29939806/92212774-0e0e2f00-eec5-11ea-8364-d79b2eb66dd6.png)


提交完工单，新增两个库， 表名还有$$特殊符号的$_$inception_backup_information$_$

**Comment by hailianghe** [comment]
找到问题了， 去连接每个实例的账户需要同时授予Replication Client和Replication Slave权限，缺一不可！！！！ 
我更新下你们的wiki， 你们wiki里面是要Replication Client或者Super中的一个。
