### ISSUE TITLE
[ 问题咨询 ]SQL查询limit 字段不管用

### ISSUE THREAD

**Issue by Xuejicha0** [hhyo/Archery#872]
### 问题描述
使用sql查询功能，limit 字段不管用，比如查询 select * from test limit 10,2;  想从第十条记录里查询两条。但是真正执行的是  select * from test limit 2；  这个问题怎么解决？

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
1. 不写版本
2. 不搜issue
