### ISSUE TITLE
[ bug ]查询数据导出问题

### ISSUE THREAD

**Issue by dongqianzheng** [hhyo/Archery#873]
使用csv或txt导出数据时，如果列的字符串是+开头的话，会在前面自动加上'

### 期待结果和实际结果
期待结果：
不需要加 '，原样导出结果。
实际结果:
![image](https://user-images.githubusercontent.com/26294657/92443215-c4368900-f1e3-11ea-958a-806be9cdddfe.png)

![QQ截图20200908150208](https://user-images.githubusercontent.com/26294657/92443594-4d4dc000-f1e4-11ea-94e7-39bfb3344aea.png)

### 版本信息
应用版本/分支：
1.7.4

部署方式：手工部署

**Comment by dongqianzheng** [comment]
@LeoQuote 这块有办法优化吗。

**Comment by hhyo** [comment]
目前导出依赖前端组件，暂时无法优化
