### ISSUE TITLE
[ 问题咨询 ] sql工单上线，任务状态一直处于排队中

### ISSUE THREAD

**Issue by cn-xiexw** [hhyo/Archery#874]
### 问题描述
sql工单上线，任务状态一直处于排队中；检查了django_q服务也是正常的;
![image](https://user-images.githubusercontent.com/44863464/92545843-9dc82a80-f283-11ea-8767-6a6b0d0e8299.png)
![image](https://user-images.githubusercontent.com/44863464/92545873-b0426400-f283-11ea-90de-266ba768ebc8.png)

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
确认一下相关日志信息

**Comment by cn-xiexw** [comment]
就是因为qcluster.log日志没看到任何错误信息；  后来找到问题的原因了，不知道是不是你们的bug，就是在archery的配置文件settings.py里面的django_q的配置项里面有个sync选项，我设置的是true，就会一直是处于排队中；当我改为false后，sql工单流程就正常走下去了；这是bug么？redis版本为最新的6.0.7

**Comment by LeoQuote** [comment]
这配置项有说明的, 设置成 False 才会发任务, True 的话是本地执行的

**Comment by cn-xiexw** [comment]
什么是本地执行？那后面怎么确认这个工单执行完成了？状态怎么继续下去呢

**Comment by LeoQuote** [comment]
sync false 的时候是发给 Django q worker， true是在webserver上执行

**Comment by cn-xiexw** [comment]
我知道你说的意思，我的意思是，那后面状态怎么继续下去，怎么知道它是否已经执行好了呢

**Comment by karhow** [comment]
qcluster.log日志在哪里，怎么我找不到？

**Comment by karhow** [comment]
![image](https://user-images.githubusercontent.com/32405381/117529777-2d3cfd80-b00c-11eb-8603-79aec3e75395.png)
容器里面只有这个日志
