### ISSUE TITLE
[ 问题咨询 ] 查询行数大于5000怎样设置?

### ISSUE THREAD

**Issue by yh777** [hhyo/Archery#875]
### 问题描述
查询行数大于5000怎样设置?

### 版本信息
 - 应用版本/分支：Release v1.7.2
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
https://github.com/hhyo/archery/wiki/configuration#admin_query_limit

多看文档

**Comment by zhengweigao** [comment]
> https://github.com/hhyo/archery/wiki/configuration#admin_query_limit
> 
> 多看文档

有地方调整普通用户的返回行数限制嘛

**Comment by hhyo** [comment]
> > https://github.com/hhyo/archery/wiki/configuration#admin_query_limit
> > 多看文档
> 
> 有地方调整普通用户的返回行数限制嘛

https://archerydms.com/modules/query/#_7

**Comment by weideguo** [comment]
进入django调试命令行
``` shell
cd /opt/archery
python manage.py shell
```
``` python
from common.config import SysConfig
SysConfig().set('admin_query_limit',20000)
```
可以修改默认的查询上限

**Comment by morewant** [comment]
> > > https://github.com/hhyo/archery/wiki/configuration#admin_query_limit
> > > 多看文档
> > 
> > 
> > 有地方调整普通用户的返回行数限制嘛
> 
> https://archerydms.com/modules/query/#_7

配置了行数权限后进行查询，依然是5000条，会是什么情况导致的？
<img width="1528" alt="image" src="https://github.com/hhyo/Archery/assets/90316664/1ef484d8-c41e-44a6-b35e-c90110da4d5e">
<img width="1609" alt="image" src="https://github.com/hhyo/Archery/assets/90316664/f4cadaa6-79d4-4547-9360-bca33101840e">

**Comment by morewant** [comment]
> > > > https://github.com/hhyo/archery/wiki/configuration#admin_query_limit
> > > > 多看文档
> > > 
> > > 
> > > 有地方调整普通用户的返回行数限制嘛
> > 
> > 
> > https://archerydms.com/modules/query/#_7
> 
> 配置了行数权限后进行查询，依然是5000条，会是什么情况导致的？ <img alt="image" width="1528" src="https://user-images.githubusercontent.com/90316664/284783644-1ef484d8-c41e-44a6-b35e-c90110da4d5e.png"> <img alt="image" width="1609" src="https://user-images.githubusercontent.com/90316664/284783801-f4cadaa6-79d4-4547-9360-bca33101840e.png">

找到原因了，是权限配置中“可查询所在资源组内所有实例”权限导致的，加了该权限申请的权限就不生效
