### ISSUE TITLE
[ 功能建议 ] sql上线时，选择项目分类

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#877]
### 目前遇到的问题/使用障碍

我们的大数据组需要一个功能，就是当数据库有DDL语句时，发通知给他们，现在archery可以满足这个需求。
不过大数据组还需要知道这个DDL语句是属于哪个项目的，我们做了点二次开发，实现了这个功能。

现在想问一下，我们这个功能，官方archery是否需要。如果能合并到官方archery里面，那就太好了，这样以后我们再升级archery时，我们就不用单独升级我们二次开发的代码了。

如果其他小伙伴也有这个需求，那正好也可以方便了他们。

就是不知道，官方archery是否需要这个功能。

我们实现功能的截图如下：
![image](https://user-images.githubusercontent.com/13861904/92887976-7d48cd80-f447-11ea-9abc-c0ad3bf628b3.png)

![image](https://user-images.githubusercontent.com/13861904/92890283-8e92d980-f449-11ea-9d35-641a9470aa5b.png)

**Comment by LeoQuote** [comment]
感谢, 意思是从之前的 资源组 -> 实例, 改成了 分类1 -> 分类2 -> 实例是吗?
如果能有更普适的方案, 比如实例有tag, 通过tag 筛选, 这样显示上会再精简一些.
当然PR 一直都是欢迎的, 如果方便可以先把 PR 提上来我们慢慢看看.

**Comment by czxin788** [comment]
是的，就是在原来实例+资源组基础上，加了两个一级分类和二级分类的下拉选项。
这样开发再提交sql时，他需要选择一下他是为哪个项目提交的sql。

这样，就方便了归类。

当然我们的场景是有个项目团队叫大数据组，他们不清楚开发提交的sql是为了哪个项目的，所以现在强制要求开发工程师提交sql时，填写项目分类。这样当大数据组看到这个sql工单时，就知道是哪个项目的sql了，然后大数据组根据自己需求做相应调整。

不知道我说明白了吗。

**Comment by LeoQuote** [comment]
哦, 也就是说现在项目和实例, 资源组都是没有关联的, 只是一个自定义标签是吗?

**Comment by czxin788** [comment]
是的，只是一个自定义标签，和实例+资源组没有任何关联，不影响原来功能。

当然，这个需求是我们目前需要的。不知道是否具有通用性。

**Comment by LeoQuote** [comment]
我感觉这个不是特别通用, 如果愿意凑合可以用原有的需求链接, 或工单标题实现. 比较通用的方案应该是支持markdown , 在这里我提过. https://github.com/hhyo/Archery/pull/539 

当然你这个方案就是能自己选, 不需要打字, 就也挺好.

**Comment by hhyo** [comment]
工单标签是有需求的，类似于现在挂着的pr就是为了区分上线单的类型，可以做成通用多级标签的形式，不过如果资源组用的好实际上不存在这个问题

**Comment by czxin788** [comment]
想想确实，资源组用的好，确实不存在这个问题。
但是我们资源组划分的就没有那么细，所以才有这个问题。
资源组划分的不细，但是省事省心，哈哈

**Comment by hhyo** [comment]
#284

**Comment by mawenbin666** [comment]
> 是的，就是在原来实例+资源组基础上，加了两个一级分类和二级分类的下拉选项。 这样开发再提交sql时，他需要选择一下他是为哪个项目提交的sql。
> 
> 这样，就方便了归类。
> 
> 当然我们的场景是有个项目团队叫大数据组，他们不清楚开发提交的sql是为了哪个项目的，所以现在强制要求开发工程师提交sql时，填写项目分类。这样当大数据组看到这个sql工单时，就知道是哪个项目的sql了，然后大数据组根据自己需求做相应调整。
> 
> 不知道我说明白了吗。

我们需要这个需求，
现在我们上游业务端改了字段.表名，下游大数据那边也要知道，不然一些表报，ETL程序就会报错，archery官方可以合并吗？
