### ISSUE TITLE
[ 问题咨询 ]点击SQL分析后，查看分析报错

### ISSUE THREAD

**Issue by dixon1688** [hhyo/Archery#878]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
1，点击开始分析
![image](https://user-images.githubusercontent.com/71314116/93179429-3f5de900-f768-11ea-8922-10c65037ff16.png)
![image](https://user-images.githubusercontent.com/71314116/93180263-7bde1480-f769-11ea-805a-b0f247dcd448.png)

2，分析完毕，点击查看
![image](https://user-images.githubusercontent.com/71314116/93179463-4c7ad800-f768-11ea-92fb-1e29c1206765.png)
3，出现报错
![image](https://user-images.githubusercontent.com/71314116/93179570-6caa9700-f768-11ea-8f30-d751827f20de.png)
![image](https://user-images.githubusercontent.com/71314116/93190053-7686c700-f775-11ea-9130-d4a1a20a9c9b.png)

疑问：有安装SOAR,但提示没有该文件？？
### 版本信息

 - 应用版本/分支：Release v1.7.12  
 - 部署方式：Docker
 -->

**Comment by hhyo** [comment]
#870

**Comment by dixon1688** [comment]
> #870  
@hhyo 
![image](https://user-images.githubusercontent.com/71314116/93190381-e1380280-f775-11ea-9019-4e2978e450d9.png)
![image](https://user-images.githubusercontent.com/71314116/93190482-02005800-f776-11ea-8ae4-77c1f67abb76.png)

安装完后，在配置中配置好路径就报这样的错，还有SOAR_TEST_DSN不是必要填写的吧

**Comment by hhyo** [comment]
看配置文档，docker安装的，这个路径不对，test_dsn是否需要配置也建议查看soar文档
