### ISSUE TITLE
[ 问题咨询 ]安装了SOAR，配置了路径，SQL分析报错，提示无此文件或目录

### ISSUE THREAD

**Issue by dixon1688** [hhyo/Archery#879]
> #870  
@hhyo 
![image](https://user-images.githubusercontent.com/71314116/93190381-e1380280-f775-11ea-9019-4e2978e450d9.png)
![image](https://user-images.githubusercontent.com/71314116/93190482-02005800-f776-11ea-8ae4-77c1f67abb76.png)

安装完后，在配置中配置好路径就报这样的错，还有SOAR_TEST_DSN不是必要填写的吧

安装方式：docker
版本 ：1.7.12

**Comment by hhyo** [comment]
参考 #870
