### ISSUE TITLE
[ 问题咨询 ]关于gh-ost执行时是否使用aliyun-rds参数的疑问

### ISSUE THREAD

**Issue by liuxinwang** [hhyo/Archery#880]
### 问题描述
我们目前管理的MySQL实例有自建和阿里云rds两种，在我开启了gh-ost修改表结构功能后，我不确定是否要开启aliyun-rds参数，因为执行的时候可能是在自建实例或者阿里云rds（如果未开启将执行失败）

### 版本信息
 - 应用版本/分支：Release v1.7.1  
 - 部署方式：Docker

**Comment by hhyo** [comment]
目前goinception支持会话层级的参数设置，可以在提交工单时指定
```
inception set ghost_aliyun_rds=on;
```

**Comment by hhyo** [comment]
这个后面可以按照是否关联了云ak信息自动设置会话变量
