### ISSUE TITLE
[ bug ] PgSQL数据库链接，数据库名使用了用户名字段

### ISSUE THREAD

**Issue by chenxinma** [hhyo/Archery#881]
### 重现步骤

1.添加实例配置PgSQL
2.用户名:AAA，数据库：BBB 保存
3.【测试】后提示：FATAL: database "AAA" does not exist

### 期待结果和实际结果
期待结果：
  数据库链接成功
实际结果:
  数据库链接失败
### 截图
![image](https://user-images.githubusercontent.com/31801597/93323193-de591280-f846-11ea-8354-51975308a065.png)

### 版本信息
应用版本/分支：hhyo/archery:1.7.13

部署方式：Docker

**Comment by hhyo** [comment]
与 #813 表现一致，不过这边一直没有办法重现，请提供一下pg的版本和配置用户的权限信息

**Comment by chenxinma** [comment]
版本，其实是GP
PostgreSQL 9.4.24 (Greenplum Database 6.7.1 build commit:a21de286045072d8d1df64fa48752b7dfac8c1b7) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Apr 30 2020 19:32:27

get_all_databases时为什么不用配置的数据库名？db_name在get_all_databases时都没有传递进去。

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/releases/tag/v1.7.12 这个bug 应该在 1.7.12 就修复了, 不太清楚为啥还有....

pg 我这边也没环境, 只能根据代码逻辑写, 最好大佬能帮忙看看 https://github.com/hhyo/Archery/pull/815 这个是我当时的修复pr, 我感觉是修复了, 但是看你的描述依然没有修复

**Comment by hhyo** [comment]
> 版本，其实是GP
> PostgreSQL 9.4.24 (Greenplum Database 6.7.1 build commit:a21de286045072d8d1df64fa48752b7dfac8c1b7) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Apr 30 2020 19:32:27
> 
> get_all_databases时为什么不用配置的数据库名？db_name在get_all_databases时都没有传递进去。

目前配置的db没有意义，是单纯给mongodb使用的，其他数据源都会按照用户权限拉取全部数据库，现在就是拉取全部数据库时报错了，具体日志也可以贴一下

**Comment by chenxinma** [comment]
按用户名create database后可以访问了，但是这样的策略没法实际投入使用。

**Comment by LeoQuote** [comment]
非常感谢反馈, 上面说的 fix 有空你也可以看一下, 涉及到数据库的交互全都在 engines 里面, 修改起来也不复杂, 非常欢迎提修复的pr
