### ISSUE TITLE
[ 问题咨询 ]批量插入数据 当前状态 卡住

### ISSUE THREAD

**Issue by EMinEMh** [hhyo/Archery#883]
### 问题描述
批量插入4000多条数据的工单，执行后工单“进行状态”一直处于“确认中...”，查看数据库已有数据且数据都已插入

### 版本信息
 - 应用版本/分支：Release v1.7.13  
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
有没有看过文档, 文档中有一片关于工单一直卡"确认中" 的解答和排查过程
