### ISSUE TITLE
[ 功能建议 ]数据脱敏规则类型无法自定义

### ISSUE THREAD

**Issue by zhang921106163** [hhyo/Archery#884]
数据脱敏建议增加自定义规则类型，目前只能写6个

**Comment by hhyo** [comment]
规则只是一个枚举定义，可以直接在数据库配置，暂时不考虑提供前台编辑入口

**Comment by zhang921106163** [comment]
> 规则只是一个枚举定义，可以直接在数据库配置，暂时不考虑提供前台编辑入口

表.字段 [data_masking_rules.rule_type]并没有提供具体名称，只是提供了几个数字，请问能具体说明一下在哪里进行配置吗？

**Comment by hhyo** [comment]
写入一条数据即可，每条数据对应一个类型，和脱敏字段表配置表的rule_type相关联

**Comment by zhang921106163** [comment]
> 写入一条数据即可，每条数据对应一个类型，和脱敏细分表配置表的rule_type相关联
事实上我给数据库插入了两条数据，显示效果仍然不理想
![规则类型无法正常显示](https://user-images.githubusercontent.com/57927460/93837248-f5b95500-fcb7-11ea-834a-feadcadd179b.png)
![规则类型下拉菜单无显示](https://user-images.githubusercontent.com/57927460/93837249-f651eb80-fcb7-11ea-9798-6d28f195c853.png)
脱敏字段配置中规则类型下拉菜单中完全看不到这两条数据
![规则类型下拉菜单无显示](https://user-images.githubusercontent.com/57927460/93837378-724c3380-fcb8-11ea-8ea6-d192ec11b7d4.png)
![规则类型无法正常显示](https://user-images.githubusercontent.com/57927460/93837379-737d6080-fcb8-11ea-985d-2983f7608be6.png)
所以我觉得应该在代码里加个枚举类型，通过代码往数据库写数据，同理脱敏字段配置中规则类型下拉菜单也需要这样的枚举代码，请问这两段代码在什么地方？

**Comment by zhang921106163** [comment]
> 写入一条数据即可，每条数据对应一个类型，和脱敏字段表配置表的rule_type相关联

我给mysql插入了两条数据，可脱敏规则配置页面显示仍然不理想，它是这样现实的

     -      (.{3})(.*)(.{3})      2       隐藏前三后三       2020-09-22 09:30:21
     -      (.*)(.{4})$           2       隐藏后四位           2020-09-22 09:31:24

而且在配置脱敏字段时完全看不到这两条信息，只有默认的那几个，所以我觉得应该在代码里增加枚举类型（通过程序来写数据库），我想知道代码文件在什么地方？

**Comment by zhang921106163** [comment]
> 规则只是一个枚举定义，可以直接在数据库配置，暂时不考虑提供前台编辑入口

感谢您的热情回答，给了我解决问题的思路，更改文件（archery/sql/models.py）枚举类型就可以了，不过需要重启程序
