### ISSUE TITLE
[ bug ]开启脱敏校验,子查询无法进行[group by]

### ISSUE THREAD

**Issue by zhang921106163** [hhyo/Archery#885]
1、在线体验--->系统管理--->QUERY_CHECK【ON】--->保存配置
2、sql查询--->在线查询--->MySQL--->weibo--->keyword_comment
3、语句如下：
select
  a.comment_username,
  count(a.comment_content)
from
  (
    select
      comment_username,
      comment_content
    from
      keyword_comment
  )a
  group by a.comment_username limit 10;

4、报错信息（数据脱敏异常：'errlevel'）;  有些sql会出现字段不存在错误, 看样子像是无法识别子查询产生的临时表
5、其他测试: 设置QUERY_CHECK【OFF】，一些复杂sql也会出现字段不存在错误, 事实上在navicat可以正确执行

**Comment by hhyo** [comment]
#145
