### ISSUE TITLE
[ 功能建议 ]实例管理下账号管理过滤account_locked='Y'的账号

### ISSUE THREAD

**Issue by zhengweigao** [hhyo/Archery#886]
### 目前遇到的问题/使用障碍
实例管理下账号管理显示account_locked='Y'的账户信息
### 希望如何解决/实现它
增加选择按钮，可以让禁用的不显示
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
有没有 url ? 不太确定你说的是哪个页面

**Comment by zhengweigao** [comment]
http://xx.xx.xx.xx:9123/instanceaccount/

**Comment by LeoQuote** [comment]
了解了， mysql 的实例账号管理 https://demo.archerydms.com/instanceaccount/
