### ISSUE TITLE
[ 问题咨询 ]archery 现在的api 接口现在通了吗，迫切需要api 接口文档。有谁做过，求交流求指教 q297428196

### ISSUE THREAD

**Issue by yanchao110020** [hhyo/Archery#887]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
功能基本上都没有 api, 一直没人做
