### ISSUE TITLE
[ bug ]archery通过sharding proxy连接数据库报错

### ISSUE THREAD

**Issue by zhengweigao** [hhyo/Archery#889]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

archery通过sharding proxy连接数据库报错，
提示 （10002，‘2Unknown exception: [Unsupported SQL of 'explain select * from base_info']')

### 期待结果和实际结果
期待结果：

实际结果:

### 版本信息
应用版本/分支：1.7.11

部署方式：手工部署

**Comment by hhyo** [comment]
#648
