### ISSUE TITLE
ssh 隧道连接问题

### ISSUE THREAD

**Issue by heyonggs** [hhyo/Archery#890]
### 问题描述
我在使用archery添加实例时需要通过ssh 隧道连接数据库，但是一直连接不上，我的密钥和配置都正确，在navicat上连接是没有问题，不知道是不是还需要修改哪里的配置吗？我是docker部署的最新版1.7.13，报错截图
![image](https://user-images.githubusercontent.com/45379075/94217466-a2900e00-ff14-11ea-9650-d59fbc4d4afc.png)

ssh通道配置截图
![image](https://user-images.githubusercontent.com/45379075/94217679-319d2600-ff15-11ea-8fb9-e45083ec5f05.png)

我在Issue中也查看了相关问题咨询，有一个是修改supervisor.conf中的sync这个配置，我修改完也是报错，希望能帮我解答一下，谢谢

### 版本信息
 - 应用版本/分支：Release v1.7.13 
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
有没有日志呢？有没有防火墙没开？ docker exec 进去 ssh 看看能不能行？

**Comment by hhyo** [comment]
docker启动应该修改这里
https://github.com/hhyo/Archery/blob/737c70c1bafa75ac19d55b45b414df4ebaddb9ae/src/docker/startup.sh#L26

**Comment by heyonggs** [comment]
哇，真好了，我刚开始修改了最外面那个startup.sh中的，刚看你说的这个修改了docker中的果然好了，那这个问题其实前面有个Issuse中的说的是没问题，我理解错了，谢谢了哈，给你一个小心心
![image](https://user-images.githubusercontent.com/45379075/94230547-c7947900-ff34-11ea-93d2-610d0e7d921b.png)

**Comment by littlemon95** [comment]
> 

请问docker里面的startup.sh应该修改什么内容😭
`gunicorn -w 4 -k gevent -b 127.0.0.1:8888 --timeout 600 archery.wsgi:application` 这句代码已经有了，但也还是相同的报错
之前的相关issue我也没有找到，求助😭

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/pull/736#issuecomment-680708912 参考这里

https://github.com/hhyo/archery/wiki/FAQ#%E9%85%8D%E7%BD%AEssh%E9%9A%A7%E9%81%93%E5%90%8E%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5

**Comment by littlemon95** [comment]
> [#736 (comment)](https://github.com/hhyo/Archery/pull/736#issuecomment-680708912) 参考这里
> 
> https://github.com/hhyo/archery/wiki/FAQ#%E9%85%8D%E7%BD%AEssh%E9%9A%A7%E9%81%93%E5%90%8E%E6%97%A0%E6%B3%95%E8%BF%9E%E6%8E%A5

感谢！ 已经正常连接上了！

**Comment by opsonly** [comment]
请问DB跳板机功能在哪里配置，我怎么没有看到，我们本来用的是1.7.11的版本，后面 自己改了一些功能。 现在把1.7.12的功能合并过来后没有发现DB跳板机的相关功能
