### ISSUE TITLE
[ 功能建议 ]SQL上线支持周期行执行

### ISSUE THREAD

**Issue by JayceLau** [hhyo/Archery#893]
### 目前遇到的问题/使用障碍
数据库的运维通常包含一些周期性的数据清理工作，目前需要开发人员每隔一段时间提交一个工单去执行，比较麻烦。
### 希望如何解决/实现它
希望archery能提供统一的视角来进行周期性数据清理工单的提交、审批、执行（周期性）、终止等流程，可以在SQL上线功能中增加周期执行选项，审批通过后，可以自动周期性执行。每隔一段较长的时间（比如3个月），需要重新审批。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
之前有人提过, 建议选用别的工具 #805

**Comment by JayceLau** [comment]
尴尬，也是我，我都不记得了，好的吧

**Comment by hhyo** [comment]
https://archerydms.com/modules/tools/

数据归档可以了解一下

**Comment by JayceLau** [comment]
棒！就是我想要的功能！感谢！
