### ISSUE TITLE
是不是 archery 不支持redis集群。

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#895]
版本信息
应用版本/分支：Release v1.7.11
部署方式：Docker

是不是 archery 不支持redis集群。

因为，我用archery连接redis集群中的一个节点，查询时报错，

Error
--
MOVED 5937 172.17.xx.2 :6382

这个好理解，这是因为被查询的redis是个集群，所要查找的key不在被查询的节点上，而是在其他节点上，所以需要moved转移到其他节点上查询才行。

在redis集群中，如果用命令查集群中的key，需要用redis-cli -a xx -h 172.17.xx.xx -p 6382 -c登录，注意是-c参数，这样才能保证登录的是redis集群，不加就是登录的单节点redis。

请问，archery支持redis集群吗

_Originally posted by @czxin788 in https://github.com/hhyo/Archery/issues/720#issuecomment-699752254_

**Comment by LeoQuote** [comment]
如果现在连接报错就是不支持, 可以修改engine 支持

**Comment by LeoQuote** [comment]
redis 用的是 django-redis 带来的 redis , 代码在这里 https://github.com/hhyo/Archery/blob/master/sql/engines/redis.py

**Comment by nick2wang** [comment]
solved by #1392
