### ISSUE TITLE
[ 功能建议 ]V1.7.13版本，会话管理-事务信息页面不显示阻塞源事务内容

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#896]
### 目前遇到的问题/使用障碍
V1.7.13版本，会话管理-事务信息页面不显示阻塞源事务内容
![image](https://user-images.githubusercontent.com/54062997/94411859-a7baba80-01ab-11eb-8a34-64826ff0e1a1.png)
![image](https://user-images.githubusercontent.com/54062997/94411883-b0ab8c00-01ab-11eb-9812-b6e80aa756ee.png)
![image](https://user-images.githubusercontent.com/54062997/94411939-c28d2f00-01ab-11eb-9be0-7f892752301a.png)

### 希望如何解决/实现它
可以看到阻塞源事务内容，请参考SQL:
SELECT 
p.ID AS conn_id,
P.USER AS login_user,
P.HOST AS login_host,
p.DB AS database_name,
P.TIME AS trx_sleep_seconds,
TIME_TO_SEC(TIMEDIFF(NOW(),T.trx_started)) AS trx_open_seconds,
T.trx_started,
T.trx_isolation_level,
T.trx_tables_locked,
T.trx_rows_locked,
t.trx_state,
p.COMMAND AS process_state,
(
SELECT GROUP_CONCAT(T1.`SQL_TEXT` SEPARATOR ';
') 
FROM performance_schema.events_statements_history AS T1
INNER JOIN performance_schema.threads AS T2
ON T1.`THREAD_ID`=T2.`THREAD_ID`
WHERE T2.`PROCESSLIST_ID`=P.id
) AS trx_sql_text
FROM `information_schema`.`INNODB_TRX` t
INNER JOIN `information_schema`.`PROCESSLIST` p
ON t.trx_mysql_thread_id=p.id
WHERE t.trx_state='RUNNING'
AND p.COMMAND='Sleep'
-- AND P.TIME>3
ORDER BY T.trx_started ASC

![image](https://user-images.githubusercontent.com/54062997/94411962-cb7e0080-01ab-11eb-9230-2b328488b2f1.png)

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
![image](https://user-images.githubusercontent.com/54062997/94412379-5101b080-01ac-11eb-9132-c87b4cb2f128.png)
![image](https://user-images.githubusercontent.com/54062997/94412432-5ced7280-01ac-11eb-8278-dffb48c15557.png)
![image](https://user-images.githubusercontent.com/54062997/94412463-64ad1700-01ac-11eb-97b8-fe596fe99f94.png)
![image](https://user-images.githubusercontent.com/54062997/94412495-6c6cbb80-01ac-11eb-8940-81958c4aaa91.png)

**Comment by LeoQuote** [comment]
你看能不能直接提个 PR , 我对数据库不太懂

**Comment by yuandajn578** [comment]
个人测试通过，已提交PR。
![image](https://user-images.githubusercontent.com/54062997/94421552-4baa6300-01b8-11eb-93b8-ff711f6fc6a8.png)

**Comment by LeoQuote** [comment]
我没看到你的pr

**Comment by yuandajn578** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Leo Q <notifications@github.com&gt;
发送时间: 2020年9月28日 19:34
收件人: hhyo/Archery <Archery@noreply.github.com&gt;
抄送: yuandajn578 <12173670@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hhyo/Archery] [ 功能建议 ]V1.7.13版本，会话管理-事务信息页面不显示阻塞源事务内容 (#896)





 
我没看到你的pr
