### ISSUE TITLE
[ 功能建议 ]V1.7.13版本，提交工单时能否按需多选实例及其schemas

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#897]
### 目前遇到的问题/使用障碍
对于分库分表场景，提交工单时需要在每个库都提交一次工单，非常耗时耗力
### 希望如何解决/实现它
提交工单时按需多选实例及其schemas
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
#543 #95
