### ISSUE TITLE
[ 问题咨询 ]  工单详情页增加查看osc执行语句的入口

### ISSUE THREAD

**Issue by ganlanshu** [hhyo/Archery#898]
### 问题描述
大表ddl 配置成通过osc执行，goinception 里面 osc_print_sql 配置为true，这样 osc 执行的命令会打印在 goinception的log里，
如果想在工单详情页增加查看 osc 语句的地方，有没有方法可以获取到goinception里的 osc日志呢

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式手工部署

**Comment by hhyo** [comment]
查看进度里面可以看到具体的日志，点➕图标

**Comment by ganlanshu** [comment]
试了一下，查看进度按钮左边的 ➕ 图标点开之后，显示的 一直是 "Copying `database_name`.`table_name`:  52% 04:44 remain" 这样的信息，里面的数字会不断变化，没有看到 osc的语句，类似这样的 能看到吗
pt-online-schema-change --alter \"ADD INDEX \\`idx_name\\`(\\`name\\`)\"   --set-vars lock_wait_timeout=60 --charset=utf8  --chunk-time 1  --critical-load Threads_connected:1000,Threads_running:80  --max-load Threads_connected:1000,Threads_running:80  --sleep=0 --recurse=1  --check-interval 5  --alter-foreign-keys-method=none --force

**Comment by hhyo** [comment]
目前只会体现在log中，详情没有办法获取

**Comment by ganlanshu** [comment]
> 目前只会体现在log中，详情没有办法获取

好的，感谢回复
