### ISSUE TITLE
[ bug ]V1.7.13，工具插件中的binlog2sql功能异常

### ISSUE THREAD

**Issue by yuandajn578** [hhyo/Archery#899]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
![1111](https://user-images.githubusercontent.com/54062997/94652195-2fc7ce00-032c-11eb-8c33-ebd896a98f71.jpg)

### 版本信息
应用版本/分支：

部署方式：Docker、手工部署

**Comment by zhituanchen** [comment]
请问这个有解决方法么

**Comment by zhituanchen** [comment]
我之前是同步过lickhouse-mysql-data报错的：
处理方法：
docker exec -it archery bash
cd /opt/venv4archery/lib/python3.6/site-packages/pymysql
vi charset.py
后面添加：
#TODO: remove this
def charset_to_encoding(name):
    """Convert MySQL's charset name to Python's codec name"""
    if name in ('utf8mb4', 'utf8mb3'):
        return 'utf8'
    return name

docker stop archery
docker start archery
然后出现其他报错，继续查看中......：
![image](https://user-images.githubusercontent.com/71009460/95846704-54856200-0d7e-11eb-8f6c-68106739547c.png)

**Comment by zhituanchen** [comment]
查看：https://github.com/danfengcao/binlog2sql/issues/66
安装PyMySQL==0.9.3即可：
步骤：
docker exec -it archery bash
source /opt/venv4archery/bin/activate
pip list
PyMySQL                   0.10.0
(venv4archery) [root@00111dac9d42 archery]# pip uninstall PyMySQL
Found existing installation: PyMySQL 0.10.0
Uninstalling PyMySQL-0.10.0:
  Would remove:
    /opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/*
    /opt/venv4archery/lib/python3.6/site-packages/pymysql/*
Proceed (y/n)? y
  Successfully uninstalled PyMySQL-0.10.0
(venv4archery) [root@00111dac9d42 archery]# pip install PyMySQL==0.9.3
Collecting PyMySQL==0.9.3
  Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 38 kB/s 
Installing collected packages: PyMySQL
Successfully installed PyMySQL-0.9.3
(venv4archery) [root@00111dac9d42 archery]# pip list
PyMySQL                   0.9.3
(venv4archery) [root@00111dac9d42 archery]# exit
exit
[root@mytestuse ~]# docker stop archery
archery
[root@mytestuse ~]# docker start archery
archery
[root@mytestuse ~]# 
解析binlog：
![image](https://user-images.githubusercontent.com/71009460/95848085-286ae080-0d80-11eb-9e34-b652834fe30a.png)

**Comment by yuandajn578** [comment]
多谢多谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhituanchen <notifications@github.com&gt;
发送时间: 2020年10月13日 18:34
收件人: hhyo/Archery <Archery@noreply.github.com&gt;
抄送: yuandajn578 <12173670@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[hhyo/Archery] [ bug ]V1.7.13，工具插件中的binlog2sql功能异常 (#899)





 
查看：danfengcao/binlog2sql#66
 安装PyMySQL==0.9.3即可：
 步骤：
 docker exec -it archery bash
 source /opt/venv4archery/bin/activate
 pip list
 PyMySQL                   0.10.0
 (venv4archery) [root@00111dac9d42 archery]# pip uninstall PyMySQL
 Found existing installation: PyMySQL 0.10.0
 Uninstalling PyMySQL-0.10.0:
 Would remove:
 /opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/*
 /opt/venv4archery/lib/python3.6/site-packages/pymysql/*
 Proceed (y/n)? y
 Successfully uninstalled PyMySQL-0.10.0
 (venv4archery) [root@00111dac9d42 archery]# pip install PyMySQL==0.9.3
 Collecting PyMySQL==0.9.3
 Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
 |████████████████████████████████| 47 kB 38 kB/s
 Installing collected packages: PyMySQL
 Successfully installed PyMySQL-0.9.3
 (venv4archery) [root@00111dac9d42 archery]# pip list
 PyMySQL                   0.9.3
 (venv4archery) [root@00111dac9d42 archery]# exit
 exit
 [root@mytestuse ~]# docker stop archery
 archery
 [root@mytestuse ~]# docker start archery
 archery
 [root@mytestuse ~]#
 解析binlog：

**Comment by hhyo** [comment]
感谢定位，应该是新版本升级了依赖导致，可以提交pr修改下

**Comment by mawenbin666** [comment]
> 查看：[danfengcao/binlog2sql#66](https://github.com/danfengcao/binlog2sql/issues/66)
> 安装PyMySQL==0.9.3即可：
> 步骤：
> docker exec -it archery bash
> source /opt/venv4archery/bin/activate
> pip list
> PyMySQL 0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip uninstall PyMySQL
> Found existing installation: PyMySQL 0.10.0
> Uninstalling PyMySQL-0.10.0:
> Would remove:
> /opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/*
> /opt/venv4archery/lib/python3.6/site-packages/pymysql/*
> Proceed (y/n)? y
> Successfully uninstalled PyMySQL-0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip install PyMySQL==0.9.3
> Collecting PyMySQL==0.9.3
> Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
> |████████████████████████████████| 47 kB 38 kB/s
> Installing collected packages: PyMySQL
> Successfully installed PyMySQL-0.9.3
> (venv4archery) [root@00111dac9d42 archery]# pip list
> PyMySQL 0.9.3
> (venv4archery) [root@00111dac9d42 archery]# exit
> exit
> [root@mytestuse ~]# docker stop archery
> archery
> [root@mytestuse ~]# docker start archery
> archery
> [root@mytestuse ~]#
> 解析binlog：
> ![image](https://user-images.githubusercontent.com/71009460/95848085-286ae080-0d80-11eb-9e34-b652834fe30a.png)


卸载 PyMySQL 0.10.0的时候报错，具体信息如下：
```
venv4archery) [root@ded5340b4336 archery]# pip uninstall PyMySQL
Found existing installation: PyMySQL 0.10.0
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/commands/uninstall.py", line 79,in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 535,in from_dist
    for path in uninstallation_paths(dist):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 67, in unique
    for item in fn(*args, **kw):
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 85, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/opt/venv4archery/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/RECORD'
```

**Comment by mawenbin666** [comment]
> 查看：[danfengcao/binlog2sql#66](https://github.com/danfengcao/binlog2sql/issues/66)
> 安装PyMySQL==0.9.3即可：
> 步骤：
> docker exec -it archery bash
> source /opt/venv4archery/bin/activate
> pip list
> PyMySQL 0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip uninstall PyMySQL
> Found existing installation: PyMySQL 0.10.0
> Uninstalling PyMySQL-0.10.0:
> Would remove:
> /opt/venv4archery/lib/python3.6/site-packages/PyMySQL-0.10.0.dist-info/*
> /opt/venv4archery/lib/python3.6/site-packages/pymysql/*
> Proceed (y/n)? y
> Successfully uninstalled PyMySQL-0.10.0
> (venv4archery) [root@00111dac9d42 archery]# pip install PyMySQL==0.9.3
> Collecting PyMySQL==0.9.3
> Downloading PyMySQL-0.9.3-py2.py3-none-any.whl (47 kB)
> |████████████████████████████████| 47 kB 38 kB/s
> Installing collected packages: PyMySQL
> Successfully installed PyMySQL-0.9.3
> (venv4archery) [root@00111dac9d42 archery]# pip list
> PyMySQL 0.9.3
> (venv4archery) [root@00111dac9d42 archery]# exit
> exit
> [root@mytestuse ~]# docker stop archery
> archery
> [root@mytestuse ~]# docker start archery
> archery
> [root@mytestuse ~]#
> 解析binlog：
> ![image](https://user-images.githubusercontent.com/71009460/95848085-286ae080-0d80-11eb-9e34-b652834fe30a.png)

pymysql==0.93 支持mysql 8.0 的版本吗？

**Comment by zhituanchen** [comment]
Hi:
   从实验看是可以的，数据库测试版本：docker mysql 8.0.21;
具体查看：https://github.com/danfengcao/binlog2sql的查看相关issues
![image](https://user-images.githubusercontent.com/71009460/101708865-25167b80-3ac9-11eb-9524-34ce2afaf72a.png)
