### ISSUE TITLE
[ 问题咨询 ] 慢日志不显示库名

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#90]
**问题描述**
慢日志里面的库名为空
![image](https://user-images.githubusercontent.com/13861904/55221116-bbe2cc00-5243-11e9-9ee3-c695be89f793.png)

**版本信息**
 - 部署方式：Docker
版本号：
[root@archery archery]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
redis               5                   a55fbf438dfd        2 days ago          95MB
mongo               3.6                 e5d5a6ea0737        2 days ago          373MB
mysql               5.7                 98455b9624a9        2 days ago          372MB
hhyo/archery        latest              975a304108b4        4 days ago          1.34GB
hhyo/inception      latest              eec127aecbb8        2 weeks ago         680MB

生产数据库的mysql 版本为5.7.22

**Comment by hhyo** [comment]
数据来源于pt工具的分析 ，可查阅文档[pt-query-digest](https://www.percona.com/doc/percona-toolkit/3.0/pt-query-digest.html) ，以及检查下binlog文件内是否包含数据库名

**Comment by czxin788** [comment]
感谢，我研究一下pt工具集
