### ISSUE TITLE
sql上线语句被截断

### ISSUE THREAD

**Issue by wangnannan** [hhyo/Archery#901]
### 问题描述
我需要根线线上数据，在sql上线申请中填写了2288条update语句，但是在实际的工单中只显示2268条，有20条语句被截断了

### 版本信息
 - 应用版本/分支：goinception v1.2.0

 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
辛苦提供重现步骤

**Comment by hamiguas** [comment]
同样碰到过，sqlserver，插入数据的某些字段超过长度导致被截断，结果仍然是执行成功

**Comment by wangnannan** [comment]
> 辛苦提供重现步骤

提交SQL---粘贴了2288条update语句---在sql上线点击工单名称中 只显示了2268条
