### ISSUE TITLE
[功能建议]增加DDL语句对象的自动备份功能

### ISSUE THREAD

**Issue by wanna545** [hhyo/Archery#903]
### 目前遇到的问题/使用障碍
DDL语句备份时，只是针对语句进行了反向语句备份
### 希望如何解决/实现它
增加对DDL语句对象的整体自动备份功能，主要是表对象数据的备份，保障数据安全性
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
张口就来.....有没有更加详细的方案或者已有的方案呢?
