### ISSUE TITLE
[ 问题咨询 ]在SQL上线时执行SQL检测报错：goInception检测语句报错，请检查系统配置中goInception配置，错误信息：connect() argument 1 must be str ,not none

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#907]
### 问题描述
在SQL上线时执行SQL检测报错：goInception检测语句报错，请检查系统配置中goInception配置，错误信息：connect() argument 1 must be str ,not none
### 版本信息
 - 应用版本/分支：Release v1.7.13  
 - 部署方式：Docker
### 截图信息
![image](https://user-images.githubusercontent.com/71009460/95645400-2b9c6d00-0af1-11eb-878c-cf1b2e4b7b4d.png)

**Comment by hhyo** [comment]
https://archerydms.com/configuration/
