### ISSUE TITLE
[ 功能建议 ]修改密码问题

### ISSUE THREAD

**Issue by RankRao** [hhyo/Archery#908]
### 目前遇到的问题/使用障碍
目前个人用户的修改密码需要跳转到/admin/password_change/，后台管理页面，
而普通用户的【人员状态】指明用户是否可以登录到这个管理站点，为了安全考虑是不勾选的。
这样会导致一个矛盾，为了让用户可以修改自己的密码，必须登录到这个管理站点。
感觉【人员状态】就形同虚设了。

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
django 的自带用户管理就是这样的, 很少直接用这个修改密码的,  可以用ldap 呀, 还有 staff 可以开, 我们现在的设置开了也不会有太大安全隐患吧

**Comment by hhyo** [comment]
可以默认都打开，没什么风险
