### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by 17864219845** [hhyo/Archery#910]
### 问题描述
您好，有个问题我需要咨询下，sql上线过程中，我的状态一直都是停留在排队中。
### 版本信息
 - 应用版本/分支：Release v1.7.13 
 - 部署方式：手工部署

 
![QQ图片20201012170121](https://user-images.githubusercontent.com/51106548/95727379-a2ca3080-0cac-11eb-997c-6a4f079f14b4.png)
![QQ图片20201012170128](https://user-images.githubusercontent.com/51106548/95727384-a493f400-0cac-11eb-854b-9c49320ba37f.png)

**Comment by LeoQuote** [comment]
wiki 里对此类问题有排查方案, 请先看 wiki 再提问
