### ISSUE TITLE
[ 功能建议 ]执行慢SQL，窗口关掉后，后台进程没停止，建议查询窗口关掉后，杀死archery查询SQL进程，避免SQL一直跑

### ISSUE THREAD

**Issue by dengpixiong** [hhyo/Archery#911]
### 目前遇到的问题/使用障碍
在使用查询功能进行执行SQL，其中执行到比较慢SQL，窗口关掉后，后台进程没停止，慢SQL一直在MYSQL中执行，需人工介入处理，慢SQL一直执行有一定的安全隐患。
### 希望如何解决/实现它
建议查询窗口关掉后，杀死archery查询SQL进程，避免SQL一直跑
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
配置项里有个 max excution time, 可以把这个设置的短一些, 关闭窗口这个, 欢迎提pr

**Comment by dengpixiong** [comment]
请问max excution time 单位是什么，我的设置是3600，关闭浏览器后，查询SQL可以一直跑5，6小时

**Comment by dengpixiong** [comment]
> 
> 
> 配置项里有个 max excution time, 可以把这个设置的短一些, 关闭窗口这个, 欢迎提pr

请问max excution time 单位是什么，是SQL上线和查询都能约束么，我的设置是3600，关闭浏览器后，查询SQL可以一直跑5，6小时

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/d12320092f82f7e34e18044f66fd2a7d2fad0443/sql/engines/mysql.py#L144-L153

应该是秒, 但也要你的服务器支持 `set session max_execution_time=xxx`

只约束查询.

**Comment by LeoQuote** [comment]
https://github.com/hhyo/Archery/blob/3343a7022da21f42614f2d71dde40e8e2c79c216/sql/query.py#L89-L101

**Comment by dengpixiong** [comment]
我看了一下，是我的数据库实例版本过低，不支持max_execution_time设置，查了没有这个参数，MYSQL 5.7以后支持。谢谢的回复，感谢！

**Comment by dengpixiong** [comment]
这个是不是增加个功能，在archery服务器端杀死超时的进程好一点？

**Comment by LeoQuote** [comment]
我个人不是很懂数据库这块, mysql 有方法去删除吗? 关闭连接会杀死查询进程吗?

**Comment by hhyo** [comment]
#125  #302

目前MySQL查询应该是两个都有保留，会有异步任务去终止，也有会话超时时间的设置，具体可以测试一下
