### ISSUE TITLE
[ 问题咨询 ] /common/utils/aliyun_sdk.py中RequestServiceOfCloudDBARequest无法import，在aliyunsdkrds中也没有看见相同名字的module

### ISSUE THREAD

**Issue by blookerP** [hhyo/Archery#912]
### 问题描述
尝试使用archery会话管理阿里云rds。如果不注释掉RequestServiceOfCloudDBARequest便无法启动，注释后就无法使用会话管理rds。相应会在/sql/aliyun_rds.py以及/sql/db_diagnostic.py中显示其未被定义。
在aliyun-sdk-rds中查找后未发现相同名字的文件，以至于无法import
请问这个aliyunsdkrds RequestServiceOfCloudDBARequest 模块是原来有最近被更改删去了么？

### 版本信息
 - 应用版本/分支：Release v1.7.13  
 - 部署方式：手工部署
 
![image](https://user-images.githubusercontent.com/51903993/95835047-534d3880-0d70-11eb-87a9-bb7eee31873c.png)
此为注释掉RequestServiceOfCloudDBARequest后的报错，因被注释而未定义

**Comment by hhyo** [comment]
不要升级aliyunsdkrds，sdk中后面删除了cloudDBA的功能

**Comment by blookerP** [comment]
aliyun-python-sdk-rds==2.1.9之后便没有了这个module
