### ISSUE TITLE
大佬好，我按文档配置了ldap，怎么不生效呢？

### ISSUE THREAD

**Issue by zenglingmin168** [hhyo/Archery#915]
### 问题描述
按文档配置了ldap，怎么不生效?

配置如下：
```
# LDAP
ENABLE_LDAP = True
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch,GroupOfNamesType
    # Baseline configuration.
    AUTH_LDAP_SERVER_URI = "ldap://xx.xx.xx.xx:389"
    AUTH_LDAP_BING_DN = 'uid=xxx,ou=Admin,dc=sqqmall,dc=com'
    AUTH_LDAP_BING_PASSWORD = 'xxx'
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        'ou=users,dc=sqqmall,dc=com',
        ldap.SCOPE_SUBTREE,
        '(uid=%(user)s)',
    )
    # Or:
    # AUTH_LDAP_USER_DN_TEMPLATE = 'uid=%(user)s,ou=users,dc=example,dc=com'
    # Set up the basic group parameters.
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        'cn=yunwei,ou=Group,dc=sqqmall,dc=com',
        ldap.SCOPE_SUBTREE,
        '(objectClass=groupOfNames)',
    )
    AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr='cn')
    # Simple group restrictions
    AUTH_LDAP_REQUIRE_GROUP = 'cn=enabled,cn=yunwei,ou=Group,dc=sqqmall,dc=com'
    AUTH_LDAP_DENY_GROUP = 'cn=disabled,cn=yunwei,ou=Group,dc=sqqmall,dc=com'
    # Populate the Django user from the LDAP directory.
    AUTH_LDAP_USER_ATTR_MAP = {
        'first_name': 'givenName',
        'last_name': 'sn',
        'email': 'mail',
    }
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        'is_active': 'cn=active,cn=yunwei,ou=Group,dc=sqqmall,dc=com',
        'is_staff': 'cn=staff,cn=yunwei,ou=Group,dc=sqqmall,dc=com',
        'is_superuser': 'cn=superuser,cn=yunwei,ou=Group,dc=sqqmall,dc=com',
    }
    # This is the default, but I like to be explicit.
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    # Use LDAP group membership to calculate group permissions.
    AUTH_LDAP_FIND_GROUP_PERMS = True
    # Cache distinguished names and group memberships for an hour to minimize
    # LDAP traffic.
    AUTH_LDAP_CACHE_TIMEOUT = 3600
    # Keep ModelBackend around for per-user permissions and maybe a local
    # superuser.
    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
    )
```

### 版本信息
版本：Archery (v1.7.13)
部署方式：Docker

**Comment by LeoQuote** [comment]
有没有关于 ldap 的日志呢, 不生效具体是怎么个不生效?

**Comment by zenglingmin168** [comment]
大佬，错误日志如下：




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhyo/Archery"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:57
收件人:&nbsp;"hhyo/Archery"<Archery@noreply.github.com&gt;;
抄送:&nbsp;"向往美好明天"<3108775440@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hhyo/Archery] 大佬好，我按文档配置了ldap，怎么不生效呢？ (#915)





 
有没有关于 ldap 的日志呢, 不生效具体是怎么个不生效?

**Comment by zhituanchen** [comment]
请问这个解决了么，我配置ldap也是没有生效，看容器日志没有ldap的报错
配置信息：
# LDAP
ENABLE_LDAP = True
if ENABLE_LDAP:
    import ldap
    from django_auth_ldap.config import LDAPSearch

    AUTHENTICATION_BACKENDS = (
        'django_auth_ldap.backend.LDAPBackend',  # 配置为先使用LDAP认证，如通过认证则不再使用后面的认证方式
        'django.contrib.auth.backends.ModelBackend',  # django系统中手动创建的用户也可使用，优先级靠后。注意这2行的顺序
    )

    AUTH_LDAP_SERVER_URI = "ldap://xx.x.x.xxx"
    AUTH_LDAP_BIND_DN = 'CN=Administrator,DC=xxxx,DC=com'
    AUTH_LDAP_BIND_PASSWORD = 'xxxxx'
    AUTH_LDAP_USER_DN_TEMPLATE = "cn=%(user)s,ou=xxxx,DC=xxxx,DC=com"
    AUTH_LDAP_ALWAYS_UPDATE_USER = True  # 每次登录从ldap同步用户信息
    AUTH_LDAP_USER_ATTR_MAP = {  # key为archery.sql_users字段名，value为ldap中字段名，用户同步信息
        "username": "sAMAccountName",
        "display": "displayname",
        "email": "mail"
    }

日志：
![Uploading image.png…]()

**Comment by xupengsoulshow** [comment]
没解决~ 我的也不生效，我的archery 版本是1.8的最新版
