### ISSUE TITLE
[ 问题咨询 ]添加归档任务时候提示：审批流程不能为空，请先配置审批流程

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#917]
### 问题描述
添加归档任务时候提示：审批流程不能为空，请先配置审批流程；请问这个流程在哪里添加
用户是有归档权限的，正常SQL审核流程没有问题的
### 版本信息
 - 应用版本/分支：Release v1.7.13 
 - 部署方式：Docker
### 截图信息
报错信息：
![image](https://user-images.githubusercontent.com/71009460/95951998-e6967480-0e29-11eb-879b-bd2a81c3a668.png)
该用户权限组：
![image](https://user-images.githubusercontent.com/71009460/95952096-13e32280-0e2a-11eb-81bb-fc0c04c3e35b.png)
该用户权限组权限：
![image](https://user-images.githubusercontent.com/71009460/95952186-3bd28600-0e2a-11eb-9ed4-5e9c26496d0b.png)

**Comment by LeoQuote** [comment]
https://demo.archerydms.com/config/ 这里 , 左边的选项, 选到 "工单审核流管理"

**Comment by zhituanchen** [comment]
好的 非常感谢
