### ISSUE TITLE
切换脱敏之后，查询没办法显示

### ISSUE THREAD

**Issue by sscash** [hhyo/Archery#920]
### 问题描述
开启-DATA_MASKING、QUERY_CHECK、DISABLE_STAR、INCEPTION
切换后，尝试配置脱敏规则，没有成功，重新退回goinception。
去除上述开启，
再次进行查询时，查询无法显示数据
执行计划能够显示数据概述，SQL查询无法显示数据内容。
![图片](https://user-images.githubusercontent.com/72153261/96237853-5e9e9f00-0fd0-11eb-8645-2a4785e9ef8c.png)
![图片](https://user-images.githubusercontent.com/72153261/96237911-6b22f780-0fd0-11eb-96b2-18958c06e893.png)
其他功能正常。

### 版本信息
 - 应用版本/分支：Archery (v1.7.13)
 - 部署方式：部署在k8s上

**Comment by hhyo** [comment]
@可以在控制面板看下浏览器返回的数据，这种看起来确实像就是没有查到数据，因为列名已经返回了，说明数据库查询是正常执行的

**Comment by sscash** [comment]
![图片](https://user-images.githubusercontent.com/72153261/96392826-d4348600-11ef-11eb-8374-c4ea380ff2ea.png)
查询返回的结果

**Comment by sscash** [comment]
> 
> 
> @可以在控制面板看下浏览器返回的数据，这种看起来确实像就是没有查到数据，因为列名已经返回了，说明数据库查询是正常执行的
![图片](https://user-images.githubusercontent.com/72153261/96392892-09d96f00-11f0-11eb-81dc-8e8d29f78885.png)
返回的limit 0

**Comment by sscash** [comment]
> 
> 
> @可以在控制面板看下浏览器返回的数据，这种看起来确实像就是没有查到数据，因为列名已经返回了，说明数据库查询是正常执行的
解决了发现问题是配置项管理，页面的limit行有个 0

**Comment by hhyo** [comment]
配置管理的缓存是不是要干掉了，也没啥用，😂
