### ISSUE TITLE
[ 问题咨询 ]是否有提供Open API，供与外部应用系统集成？

### ISSUE THREAD

**Issue by kuangshengyu** [hhyo/Archery#921]
### 问题描述
是否有提供Open API，供与外部应用系统集成？
比如与ITSM集成，自动创建数据库实例，以及授权等

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by LeoQuote** [comment]
Duplicate of #354
