### ISSUE TITLE
[ 问题咨询 ] docker启动对应哪个配置文件？

### ISSUE THREAD

**Issue by ganlanshu** [hhyo/Archery#923]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
本地手动方式部署的时候正常运行，用docker部署，但是把redis配置为外部redis，django_q使用redis的时候，redis连接超时，但是进入docker，telnet可以连上配置的redis数据库，由于依赖django_q的地方很多，页面很多功能都出问题，用docker启动的时候，到底用的是哪个settings 文件呢，有没有遇到过docker 启动，但是redis配置为外部redis连接超时的情况

### 版本信息
 - 应用版本/分支：Release 1.7.3
 - 部署方式：Docker 部署

**Comment by hhyo** [comment]
入口: https://github.com/hhyo/Archery/blob/b3d39c51ba8cfae158750d23ad8007b5a64447de/src/docker/Dockerfile#L22

映射配置:https://github.com/hhyo/Archery/blob/b3d39c51ba8cfae158750d23ad8007b5a64447de/src/docker-compose/docker-compose.yml#L50

所以docker-compose启动的对应的是这个文件https://github.com/hhyo/Archery/blob/master/src/docker-compose/archery/settings.py

**Comment by ganlanshu** [comment]
问题已解决，感谢
