### ISSUE TITLE
使用中配置pgsql相关配置后连接提示报错[ 问题咨询 ]

### ISSUE THREAD

**Issue by sunsky-cn** [hhyo/Archery#925]
![image](https://user-images.githubusercontent.com/34758262/96529670-643e0280-12b8-11eb-8426-4ae296edfc36.png)
配置如上，测试连接时报错如下
![image](https://user-images.githubusercontent.com/34758262/96529790-98192800-12b8-11eb-96bd-661d86b8d70b.png)
请问是有我有什么理解错误吗

**Comment by LeoQuote** [comment]
Duplicate of #813 

你看看这个issue？

**Comment by sunsky-cn** [comment]
> Duplicate of #813
> 
> 你看看这个issue？

那表示是一个bug吗？

**Comment by hhyo** [comment]
实例配置填写一下数据库名，否则默认会使用用户名

**Comment by sunsky-cn** [comment]
> 实例配置填写一下数据库名，否则默认会使用用户名

我贴的配置里有配置数据库名啊，被我涂掉了而已

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/b3d39c51ba8cfae158750d23ad8007b5a64447de/common/check.py#L152

check只获取了连接，获取连接时没有传入db_name，应该不影响查询
