### ISSUE TITLE
[ 功能建议 ] pg数据库，用户操作界面的数据库列表

### ISSUE THREAD

**Issue by niuxz** [hhyo/Archery#926]
### 目前遇到的问题/使用障碍
sql查询处，会罗列所有实例内的数据库，包括用户没权限查询的。
### 希望如何解决/实现它
希望可以基于既有的实例数据库权限配置，仅展示有权限的。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by niuxz** [comment]
这个我改后端实现了，建议是否标准产品后续可以支持实现。

修改pgsql.py的get_all_databases中如下
        替换#db_list = [row[0] for row in result.rows if row[0] not in ['postgres', 'template0', 'template1']]
        为db_list = [row[0] for row in result.rows if row[0] in self.db_name]

**Comment by LeoQuote** [comment]
麻烦直接提个pr吧

**Comment by hhyo** [comment]
实例配置的数据库只是用来建立连接，过滤这个还是谨慎一些，后面看是否可以统一配置

目前平台查询就是只限制查询数据，不限制表结构的查看

**Comment by niuxz** [comment]
> 麻烦直接提个pr吧

后续我们又调了下之前的in判断可能不准确。改成这个了
db_list = [row[0] for row in result.rows if row[0] == self.db_name]
这样数据库只会显示该实例连接时的那个数据库。从而实现，每个用户只能看到自己有权限的库。

**Comment by hhyo** [comment]
实例配置的数据库 != 用户拥有权限的数据库

如果实例包含多个数据库，不同用户需要查不同的数据库，这就会使实例配置变得复杂
，如果需要在查询页面实现过滤，建议修改这个方法https://github.com/hhyo/Archery/blob/cda89687ce2ff62d9b9d929c287a3a4eb676c90b/sql/instance.py#L246
