### ISSUE TITLE
自动审批，开启没有效果已开启AUTO_REVIEW。

### ISSUE THREAD

**Issue by sscash** [hhyo/Archery#927]
开启自动审批
![image](https://user-images.githubusercontent.com/72153261/96541056-c6efc800-12d1-11eb-8b43-717d9ea755b7.png)
![image](https://user-images.githubusercontent.com/72153261/96541087-d5d67a80-12d1-11eb-963b-8c32881691e4.png)
![image](https://user-images.githubusercontent.com/72153261/96541114-e129a600-12d1-11eb-90d8-65c1580d9986.png)
![image](https://user-images.githubusercontent.com/72153261/96541172-028a9200-12d2-11eb-9931-1fb09250da3f.png)
![image](https://user-images.githubusercontent.com/72153261/96541202-159d6200-12d2-11eb-9d3e-78609ddea522.png)
自动审批没有生效，查看文档告知开启AUTO_REVIEW即可
![image](https://user-images.githubusercontent.com/72153261/96541399-788ef900-12d2-11eb-980b-753be405c631.png)

**Comment by hhyo** [comment]
auto_review_tag需要配置一下需要自动审批的实例标签code，code可以在管理后台https://demo.archerydms.com/admin/sql/instancetag/  获取

**Comment by niuxz** [comment]
> auto_review_tag需要配置一下需要自动审批的实例标签code，code可以在管理后台https://demo.archerydms.com/admin/sql/instancetag/ 获取
 
我这边也试过了。加了 自动审批的实例标签  ，还是会走审批。  是不是因为必须要配置审批流程，导致默认走审批

**Comment by sscash** [comment]
> auto_review_tag需要配置一下需要自动审批的实例标签code，code可以在管理后台https://demo.archerydms.com/admin/sql/instancetag/ 获取

谢谢解答，添加实例后可以实现自动审批。

**Comment by sscash** [comment]
> > auto_review_tag需要配置一下需要自动审批的实例标签code，code可以在管理后台https://demo.archerydms.com/admin/sql/instancetag/ 获取
> 
> 我这边也试过了。加了 自动审批的实例标签 ，还是会走审批。 是不是因为必须要配置审批流程，导致默认走审批

你好，我这边也是有配置审批流程，添加实例标签后可以实现，如果你还是这样可以上传下你的配置，一起看下。

**Comment by niuxz** [comment]
![微信截图_20201026141549](https://user-images.githubusercontent.com/52068200/97139960-a70b4900-1796-11eb-9f2c-1c19354d7718.png)
![微信截图_20201026141605](https://user-images.githubusercontent.com/52068200/97139963-a83c7600-1796-11eb-878a-ce1df7792abd.png)
![微信截图_20201026141509](https://user-images.githubusercontent.com/52068200/97139964-a8d50c80-1796-11eb-85e9-d670adf8a1dc.png)

我这边配置免审tag了。然后在实例上也选了免审tag了。但是还是进审核了

**Comment by dongqianzheng** [comment]
auto_review_regex 和 max_update_rows 都不能为空，都填上试下。

**Comment by niuxz** [comment]
> auto_review_regex 和 max_update_rows 都不能为空，都填上试下。

感谢答复，不过还是不行。修改配置应该不用重启吧？ 增加了配置后，还是会进审核
![Uploading image.png…]()

**Comment by niuxz** [comment]
![image](https://user-images.githubusercontent.com/52068200/97281391-6a178300-1878-11eb-84eb-6978e2c121ab.png)
这个是用户组权限，没有给用户分配权限，直接给用户分的用户组。

**Comment by niuxz** [comment]
@hhyo  麻烦得空帮看下可能的原因

**Comment by hhyo** [comment]
https://github.com/hhyo/Archery/blob/cda89687ce2ff62d9b9d929c287a3a4eb676c90b/sql/utils/sql_review.py#L12

看一下这个方法？

**Comment by niuxz** [comment]
> https://github.com/hhyo/Archery/blob/cda89687ce2ff62d9b9d929c287a3a4eb676c90b/sql/utils/sql_review.py#L12
> 
> 看一下这个方法？

感谢答复。 看了下代码，似乎有针对mysql的筛选 。  只针对mysql可以自动免审吗？ 这块有什么特别考虑吗？ 我这边用的是postgreSQL

**Comment by hhyo** [comment]
> > https://github.com/hhyo/Archery/blob/cda89687ce2ff62d9b9d929c287a3a4eb676c90b/sql/utils/sql_review.py#L12
> > 
> > 看一下这个方法？
> 
> 感谢答复。 看了下代码，似乎有针对mysql的筛选 。 只针对mysql可以自动免审吗？ 这块有什么特别考虑吗？ 我这边用的是postgreSQL

非mysql没有做审核，所以无法判断执行语句的风险，就没有放开这个功能
