### ISSUE TITLE
自主注册功能，进入页面建议增加空白权限页面。

### ISSUE THREAD

**Issue by sscash** [hhyo/Archery#928]
新注册用户登陆提示告警信息，并不友善
![image](https://user-images.githubusercontent.com/72153261/96556942-32469380-12ec-11eb-9b8c-0eaf9c8529a0.png)
![image](https://user-images.githubusercontent.com/72153261/96557016-4e4a3500-12ec-11eb-9f7f-80b3b8e9ccfd.png)
没有开启权限所以出现告警。建议优化

**Comment by hhyo** [comment]
参考配置默认权限组，给一些默认权限https://archerydms.com/home/#_15
