### ISSUE TITLE
Oracle数据库不支持sys用户创建实例

### ISSUE THREAD

**Issue by palosky** [hhyo/Archery#932]
作者您好，我想在Archery上添加一个oracle实例，用户名sys，密码123456，仅供DBA管理使用的，所以要有最大的权限,。但问题是sys这个用户是sysdba角色，直接填写sys和密码，会报错：ORA-28009：connection as SYS should be as SYSDBA or SYSOPER 。请问sysdba角色的用户 应该如何填写，才能正确添加oracle实例？

十分感谢！

**Comment by hhyo** [comment]
可参考：https://community.oracle.com/tech/apps-infra/discussion/1135635/ora-28009-connection-as-sys-should-be-as-sysdba-or-sysoper
