### ISSUE TITLE
[ 功能建议 ] 在archery中添加oracle的慢sql

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#933]
### 目前遇到的问题/使用障碍

archery没有oracle的慢sql日志

### 希望如何解决/实现它

如果可以参考 https://github.com/gumengkai/db_monitor
的方法实现，截图如下：

![image](https://user-images.githubusercontent.com/13861904/96674170-ba837200-139a-11eb-8d59-888ed1b275df.png)

**Comment by hhyo** [comment]
目前只能说欢迎pr
