### ISSUE TITLE
[ 功能建议 ] 建议加上环境管理/项目管理

### ISSUE THREAD

**Issue by zhxjdwh** [hhyo/Archery#936]
1.环境管理
   大多数公司都有多个环境，比如开发环境，uat环境，生产环境，xx环境，
   不应该 准备上uat环境，提交一个sql申请， 上生产环境 再把sql写一遍，再提交申请？
2.项目管理
   上线都是一个项目/迭代为维度，一个迭代可能几百sql上千条sql，可能经历依赖很多开发人员，可能时间周期一两个月甚至更久。
   我建议，sql审核允许按项目/迭代版本去审核，开发期间允许开发人员往这个项目里面加sql

**Comment by hhyo** [comment]
可以提供下实现思路
目前可以通过上线其他实例快速上线，因为检测必须要做，如果结合迭代版本使用钩子快速提交可能会是更友好的方案

**Comment by sona-yuan** [comment]
sql上线申请的时候加一个环境选择，dev sit prd等等，然后根据环境确定工单的流转，sql提交--开发--测试--TL--DBA，如果没有选择prd则不需要TL和DBA审核

**Comment by luofeng3465** [comment]
建议支持钩子功能~

**Comment by charnet1019** [comment]
这个功能很实用，建议加上
