### ISSUE TITLE
[ 问题咨询 ]在哪个地方可以删除历史工单或者设置工单的保留时间

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#940]
### 问题描述
您好，请问一下：
在哪个地方可以删除历史工单或者设置工单的保留时间
删除历史工单操作
设置保存工单记录的时间

### 版本信息
 - 应用版本/分支：Release v1.7.13 
 - 部署方式：Docker、手工部署
 
### 截图信息
![image](https://user-images.githubusercontent.com/71009460/97154801-518f6600-17af-11eb-9874-bd99bad64f18.png)

**Comment by hhyo** [comment]
目前不提供工单自动归档，可以自己通过平台建立一个归档任务

**Comment by zhituanchen** [comment]
hi hhyo:
   感谢回复，展示是30天的记录（没有看到数据保留策略），那一般的话是怎样清理历史的工单数据呢，直接数据库层面么，如果是的话，那么清理哪几个表呢（一般有关联关系的表），或者能否提供比较安全性的清理策略；

**Comment by hhyo** [comment]
主要是sql_workflow和sql_workflow_content

关于模型定义可以参考
https://github.com/hhyo/Archery/blob/master/sql/models.py
