### ISSUE TITLE
[ 问题咨询 ]各位大佬1.7.13版本中oracle的备份问题

### ISSUE THREAD

**Issue by wanna545** [hhyo/Archery#941]
### 问题描述
各位大佬：oracle数据库的DML工单中，无法查看sql回滚语句，备份数据库中也没有备份数据，我看功能清单里面又有oracle备份功能的哇

### 版本信息
Release v1.7.13  
Docker

**Comment by hhyo** [comment]
参考#701 同时确认下相关配置

**Comment by wanna545** [comment]
> 参考#701 同时确认下相关配置

什么配置呢？我全程按照官方文档进行docker部署的？还需要在哪儿去调整配置吗？

**Comment by LeoQuote** [comment]
archery 的代码 oracle 部分是由上面那个 pr 提供的, 我和 @hhyo 都没有 oracle 的环境, 所以我们俩也不能提供对应的帮助, 要么你看看 wiki 有没有说明要么就看看 pr 里的代码.
