### ISSUE TITLE
[ 问题咨询 ]SQLServe查询问题，可能被转换成小写

### ISSUE THREAD

**Issue by lanheader** [hhyo/Archery#943]
### 问题描述
SQLServer 查询条件里面的大写貌似被转成了小写，导致数据查询不出来

### 版本信息
  应用版本/分支：Release v1.7.9
  部署方式：Docker

![image](https://user-images.githubusercontent.com/52522047/97391645-a6032480-191a-11eb-8713-7b508cc8571e.png)
![image](https://user-images.githubusercontent.com/52522047/97391664-b3201380-191a-11eb-908d-6cbe802a8d12.png)

**Comment by LeoQuote** [comment]
看了下應該是沒有轉大小寫的, 你再確認一下?

**Comment by LeoQuote** [comment]
你加个 TOP 看看, 有默认的 top 改写, 有可能这里有些问题

**Comment by hhyo** [comment]
可以看一下查询历史，改写成什么了
