### ISSUE TITLE
[ 功能建议 ] 关于sql报错后，后续sql停止执行的可配置优化

### ISSUE THREAD

**Issue by niuxz** [hhyo/Archery#946]
### 目前遇到的问题/使用障碍
执行若干sql，一个报错，其后续sql均不在执行
### 希望如何解决/实现它
1、麻烦告知哪里这块的处理在哪里，可以自己修改
2、建议增加一个配置，就是sql报错是继续执行后续sql到完毕，还是遇错误sql就停止
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by hhyo** [comment]
处理在goinception内部，个人认为这个是合理的，有需求可以给goinception提交issue讨论一下
