### ISSUE TITLE
redis hgetall 查询前端不能正常渲染

### ISSUE THREAD

**Issue by 5sdba** [hhyo/Archery#947]
redis hgetall 查询，调试网页，发现后端有值返回，但是前端页面没办法渲染，显示

Result
--
[object Object]

我看了下代码，是sqlquery.html这个页面的320行以后的格式化有问题，可以修改一下么

**Comment by LeoQuote** [comment]
可以修改的, 欢迎提pr , 顺便给一下这个 object 的格式吧, 供后面参考

**Comment by hhyo** [comment]
#1315
