### ISSUE TITLE
自动审核只要加上注释就会自动审核通过[问题咨询]

### ISSUE THREAD

**Issue by jiachen1230** [hhyo/Archery#949]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
如题，只要在上线审核工单(update)前面加上注释信息，就会自动审核通过
![image](https://user-images.githubusercontent.com/23516898/97668516-18ac0580-1abd-11eb-885f-460d66c20af7.png)

![image](https://user-images.githubusercontent.com/23516898/97668432-e8646700-1abc-11eb-8450-f71efc97934f.png)
### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by blookerP** [comment]
我也刚遇到这个问题
不过在/sql/utils/sql_review.py内加上
from .sql_utils/ import remove_comments
并在is_auto_review()中sql_content = workflow.sqlworkflowcontent.sql_content下面
加上sql_content = remove_comments(sql_content)好像可以解决一部分问题，不过还没有测试过其他场景
