### ISSUE TITLE
[问题咨询]大佬们，编写SQL，创建视图命令，为什么会受报错：命令禁止！

### ISSUE THREAD

**Issue by L-kevin7** [hhyo/Archery#950]
### 问题描述
在SQL审核页面，编写创建视图SQL语句，点击SQL检测，检测结果中报出：命令禁止！无法创建视图xx。goInception的配置文件config.tom中已经加入enable_use_view =true，并重启docker  ，依然如此。
<img width="1207" alt="截屏2020-10-30 下午3 05 13" src="https://user-images.githubusercontent.com/46045081/97670516-59a61900-1ac1-11eb-9cab-bf8dad60e8d5.png">

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker

**Comment by hhyo** [comment]
确认下goInception版本
