### ISSUE TITLE
[ 功能建议 ] 非法日期检测

### ISSUE THREAD

**Issue by ganlanshu** [hhyo/Archery#954]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
-  sql 自动审核时，如果提交的sql语句中含有非法日期，如 2020-11-31， 2020-9-31 等目前不能检测出来，查了goinception的文档，也没有这样的审核规则，如果自己定制的话，我写下自己的思路，你觉得哪种更好呢

1. 修改goinception源码，使支持非法日期审核配置，archery 几乎不用修改
2. 不改goinception 源码，但修改archery 项目 auto_check相关的代码，除了goinception审核结果，自己再定义一些审核规则，加入审核的结果里

 

### 版本信息
 - 应用版本/分支：Release v1.7.2 
 - 部署方式：Docker、手工部署

**Comment by hhyo** [comment]
感谢建议，有成熟和高效的goInception，archery不考虑做过多的自定义审核
