### ISSUE TITLE
[ 功能建议 ] 能否兼容aurora mysql？

### ISSUE THREAD

**Issue by ghostppig** [hhyo/Archery#955]
### 目前遇到的问题/使用障碍
经过测试，执行上线工单时会报错：binlog日志未开启,无法备份! 
### 希望如何解决/实现它
期待解决此问题。
### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交

**Comment by LeoQuote** [comment]
报错说的很清楚, binlog 未开启

**Comment by ghostppig** [comment]
> 报错说的很清楚, binlog 未开启

谢谢，我再测测，本以为bihnlog是开启状态，aurora api变了archery拿不到日志
