### ISSUE TITLE
[ 问题咨询 ] 1.8更新init_sql未同步更新

### ISSUE THREAD

**Issue by idber** [hhyo/Archery#956]
### 问题描述

1.7.13-->1.8更新，表结构变更比较大，init_sql里没有更新脚本，请问可以提供下更新脚本吗？
https://github.com/hhyo/Archery/tree/master/src/init_sql
查看init_sql是未更新的

### 版本信息
 - 应用版本/分支：Release v1.8.0  
 - 部署方式：Docker

**Comment by hhyo** [comment]
项目本身没有更新，主要是依赖库的更新
按说明执行`python manage.py migrate`即可
