### ISSUE TITLE
[ 问题咨询 ] 事务的支持

### ISSUE THREAD

**Issue by ganlanshu** [hhyo/Archery#957]
### 问题描述
详细描述你的操作步骤和结果，以及你的疑问
1. 在测试一个工单多条sql执行的过程中，想到了利用事务，测试一个事务是否会完整执行或者自动回滚，发现不支持事务的关键字，begin，commit
2. 查看goinception文档，发现goinception 可以通过trans和sql的条数来配置事务，请问 archery 会支持trans 参数吗

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：手工部署

**Comment by hhyo** [comment]
暂时不考虑支持，长事务对生产环境的影响还是蛮大的，需要有靠谱的方式来规避这个风险
