### ISSUE TITLE
[ 功能建议 ]detail.html页面显示建议

### ISSUE THREAD

**Issue by wineejam** [hhyo/Archery#959]
### 目前遇到的问题/使用障碍
SQL上线工单审核后，执行工单的显示的页面中
问题1：“立即执行”为红色，给人一种危险的潜意识
问题2：“手动执行”按钮的名字容易误导

### 希望如何解决/实现它
解决1：“立即执行”按钮修改为绿色
解决2：“手动执行”按钮改名为“已手动完成”

效果如下：
![图片](https://user-images.githubusercontent.com/8789004/98430463-6988b300-20e8-11eb-9b25-b069ff8dc0ce.png)

**Comment by LeoQuote** [comment]
感谢反馈，关于1我认为是刻意的，执行sql本来就是带有一定危险性的。

关于2我感觉非常不错，看到你已经做出了效果，不妨直接提个pr

**Comment by wineejam** [comment]
#960 已提交PR
