### ISSUE TITLE
[ 问题咨询 ] 更改审批流程的问题

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#96]
### 问题描述
审批流程里面只有添加审批权限组，现在想要删除一个审批权限组或者更改一下审批顺序，应该怎么办
![image](https://user-images.githubusercontent.com/13861904/55381547-fefbb280-5555-11e9-8507-d74144d86929.png)

### 版本信息
 - 应用版本：Release v1.4.5  
 - 部署方式：Docker、

**Comment by hhyo** [comment]
变更就是重新设置流程，会按照最新选择的流程替换原有的

**Comment by czxin788** [comment]
明白了，谢谢
