### ISSUE TITLE
[ 问题咨询 ] 新用户的默认的资源组在配置项中能否指定多个

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#961]
### 问题描述
新用户的默认的资源组在配置项中能否指定多个资源组

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker

### 截图信息
![image](https://user-images.githubusercontent.com/71009460/98523690-288fca80-22b1-11eb-96ff-4351ba827d4e.png)

**Comment by LeoQuote** [comment]
目前不能, 如果做的话应该还是比较简单, 用空格或者逗号分隔就行, 最好这里能直接select 最好
