### ISSUE TITLE
[ 问题咨询 ]Archery和archer功能和设计上的区别是啥，为啥会单独弄一个分支来开发Archery呢 

### ISSUE THREAD

**Issue by zhuzhuwonder** [hhyo/Archery#965]
### 问题描述
Archery和archer功能和设计上的区别是啥，为啥会单独弄一个分支来开发Archery呢 

### 版本信息
 - 应用版本/分支：Release v1.4.5  
 - 部署方式：Docker、手工部署

**Comment by dongqianzheng** [comment]
我记得archer是携程开源的吧，但是那个早就闭源了。现在的都属于不同分支

**Comment by zhuzhuwonder** [comment]
> 我记得archer是携程开源的吧，但是那个早就闭源了。现在的都属于不同分支
archer应该没有闭源吧，这个不是吗https://github.com/jly8866/archer

**Comment by zhuzhuwonder** [comment]
archer应该没有闭源吧，这个不是吗https://github.com/jly8866/archer

**Comment by rooklyn21** [comment]
> archer应该没有闭源吧，这个不是吗https://github.com/jly8866/archer

你看看最后一次更新代码是什么时候
