### ISSUE TITLE
[ 问题咨询 ] 24h慢查询db维度统计 与  24h慢查询db/user维度统计 首页展示无数据

### ISSUE THREAD

**Issue by Gooooodman** [hhyo/Archery#966]
### 问题描述
首页 24h慢查询db维度统计 与  24h慢查询db/user维度统计 图像数据是从 mysql_slow_query_review_history 这个表获取得。
但代码中没看到往这个表插入数据。
请问这个表得数据是如何产生得呢？
(在测试得dome后台平台 Scheduled tasks 中也没找到有相关得任务计划)

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：手工部署

**Comment by hhyo** [comment]
这个是通过pt工具收集的，需要自己配置，可参考文档中关于慢日志管理的内容

**Comment by Gooooodman** [comment]
@hhyo 哦，好的，了解了。多谢。
