### ISSUE TITLE
[ bug ] 1.8 sql/db_diagnostic.py 代码出现大小写错误，导致会话管理-事务信息报错

### ISSUE THREAD

**Issue by tanglu86** [hhyo/Archery#967]
### 重现步骤
Archery 1.8，实例管理--会话管理--事务信息报错如下：
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'P.TIME' in 'where clause'")

排查发现sql/db_diagnostic.py文件275行将数据库别名大小写写错

**Comment by tanglu86** [comment]
![1](https://user-images.githubusercontent.com/38269740/99353612-d4539e80-28df-11eb-8932-919d6084fe71.png)

**Comment by hhyo** [comment]
感谢反馈，本地测试实例没有区分大小写，所以没有遇到该问题
