### ISSUE TITLE
[ bug ] SQL上线 /submitsql/ 界面中。选择备注选项代码中 备份 默认是选中状态 为何界面中没选中？

### ISSUE THREAD

**Issue by Gooooodman** [hhyo/Archery#968]
### 重现步骤

![image](https://user-images.githubusercontent.com/13062160/99468684-0dd9e780-297c-11eb-9ed8-1004b4b83bcb.png)

### 代码片段

![image](https://user-images.githubusercontent.com/13062160/99468703-21854e00-297c-11eb-908f-2653505acba3.png)

 - 应用版本/分支：Release v1.8.0 
 - 部署方式：手工部署

**Comment by hhyo** [comment]
下面对于选择框有一个重置操作

https://github.com/hhyo/Archery/blob/e4c026d2001f0d2d8796c7192b45fcc3d0fd06ab/sql/templates/sqlsubmit.html#L691-L697

**Comment by Gooooodman** [comment]
@hhyo 嗯，好得。谢谢，明白了
