### ISSUE TITLE
https协议时批量sql出现Not Allowed

### ISSUE THREAD

**Issue by yi-jun** [hhyo/Archery#969]
在生产环境正式使用的时候,  使用的是https协议.  
提交多个update的时候,出现了 Not Allowed.无法提交
后面尝试换成http就可以提交. 用的是goInception, Archery版本 docker v1.8.0

如有需要我可以提供https环境.

**Comment by LeoQuote** [comment]
有没有比较详细的截图, 后台日志?

**Comment by yi-jun** [comment]
哦买噶, 我现在切回去https试了一遍又可以了.  我也母鸡.

我说一下我的流程, 一开始在本地做的测试用, 用的http,  一切OK.
玩转一圈熟悉之后发上生产, 直接部署的Https, 就不行,还试过把本地的docker镜像发上去,
最后用http协议就可以了.

**Comment by LeoQuote** [comment]
比较建议archery app 用 http 协议, 然后前端再设置一个nginx ,这样证书管理会统一一些, 如果你在 k8s 内部署, https 证书也是在 ingress 那边做的
