### ISSUE TITLE
[ 问题咨询 ] 想不限制SQL查询结果集的行数，应该怎么设置？

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#97]
### 问题描述
如果不是超级用户，普通用户SQL查询最多只能返回1000行数据。现在我们想让普通用户不限制SQL查询返回的函数，应该怎么调整？

### 版本信息
 - 应用版本：Release v1.4.5  
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
可以在审批完成后修改该用户的权限，具体位置是 SQL 查询-查询权限申请-权限管理 ，增大限制到20000或者之类的。

但是无法取消限制，这个是安全限制，取消限制不仅对平台有害，对数据库本身也有危险。

**Comment by czxin788** [comment]
明白了，感谢

**Comment by yzypals** [comment]
这里我是改了代码  将最大限制放到10000条，原来我是想着 直接删掉 条数限制， 修改代码的时候发现有个坑  。  代码里0 来做判断条件了 而0  有事不做限制的数字。  ~！~ 后来就没动这个地方了
