### ISSUE TITLE
[ 功能建议 ]配置脱敏规则时，规则类型无法新增

### ISSUE THREAD

**Issue by tanglu86** [hhyo/Archery#972]
### 目前遇到的问题/使用障碍
配置脱敏规则的时候 ，默认创建了身份证、电话、邮箱等规则类型，但是每个规则类型只允许设置一条脱敏配置，对于身份证这种存在15位和18位区别的数据通常就要配置2条规则，但是archery没办法新增规则，“其他”规则类型也只能存在一条
### 希望如何解决/实现它
能自定义规则类型
![QQ图片20201119143922](https://user-images.githubusercontent.com/38269740/99630548-0f3b0b00-2a75-11eb-9525-af04a2e9e615.png)

**Comment by hhyo** [comment]
#884

**Comment by learn0208** [comment]
@tanglu86 我的做法是用正则匹配15位和18位的身份证类型

```
^(\d{15}|\d{18}|\d{17}[xX])$
```
