### ISSUE TITLE
[ 问题咨询 ]在archery中，删除数据库实例后，这个实例对应的工单也会被删除吗

### ISSUE THREAD

**Issue by czxin788** [hhyo/Archery#974]
### 问题描述
在archery中，我们有一个数据库实例，已经用了一年了。
今天我们把这个数据库实例在archery中删除了，最终发现这个数据库实例对应的所有工单都不见了。请问这是怎么回事，我应该怎么把这个数据库实例对应的工单找回来。
因为这些工单是需要留痕，并且有时还需用到工单里面的回滚sql。

这下我麻烦了，就因为把数据库实例删除，导致对应的工单全不见了。

### 版本信息
 - 应用版本/分支：Release v1.7.11  
 - 部署方式：Docker

**Comment by hhyo** [comment]
通过管理后台删除的吧，目前Archery的外键关联都使用的是models.CASCADE，也就是级连删除，删除界面应该有明确会删除多少关联数据的警告，恢复只能通过备份了

**Comment by czxin788** [comment]
感谢，已经通过备份恢复了。
