### ISSUE TITLE
SQL查询权限申请，审批流程内的人员不会受到消息通知，只有admin账号可以收到

### ISSUE THREAD

**Issue by allenlu13** [hhyo/Archery#975]
### 问题描述
配置完成了相应的审批流程，测试时候发现没法推送审批消息到相应用户，只有admin才有通知，还请您看下具体原因，流程已经配置过了，相应的权限组也给了审批的权限

### 版本信息
 - 应用版本/分支：1.17.2
 - 部署方式：Docker

![image](https://user-images.githubusercontent.com/74892918/99933090-f85a2880-2d94-11eb-8bba-dd9533aa5290.png)
![image](https://user-images.githubusercontent.com/74892918/99933115-0c058f00-2d95-11eb-85e4-65ee8eb8a81e.png)
![image](https://user-images.githubusercontent.com/74892918/99933145-22abe600-2d95-11eb-8d6d-e860ce56805c.png)

**Comment by hhyo** [comment]
https://archerydms.com/modules/notify/#_4

对应的通知条件都确认一下

**Comment by allenlu13** [comment]
已经按照您提供的确认了，通知条件都已经检查了，权限组里面都添加了，我没有使用钉钉邮件之类，就是系统默认通知所在审批流的对应用户，还是没有显示审批通知，就算给某个用户所在组全部权限，还是不会有通知，只有admin才有呢

**Comment by hhyo** [comment]
确认下资源组关联情况

**Comment by allenlu13** [comment]
资源组里面也都是有相应的用户和库的

**Comment by allenlu13** [comment]
您看什么时间有空，远程或者其它方式帮忙调试下？2674396134@qq.com这是我邮箱，谢谢啦

**Comment by hhyo** [comment]
这个问题搜索一下issue应该有很多的同类反馈

麻烦提供以下信息
- 审批流程配置截图
- 工单详情截图，确保可以看到资源组
- 审批人关联的权限组和资源组截图

同时可以设置配置文件的日志等级，调整为debug可以输出消息日志
