### ISSUE TITLE
最新版 修改了sql/notify.py和common/utils/sendmsg.py，为什么没有生效啊？

### ISSUE THREAD

**Issue by runblood** [hhyo/Archery#976]
最新版 修改了sql/notify.py和common/utils/sendmsg.py，为什么没有生效啊？
感觉这2个文件都没有调用，是不是哪里开关限制了？？？

**Comment by hhyo** [comment]
这个确实没有办法回答，可以重新描述下遇到的问题

**Comment by runblood** [comment]
> 这个确实没有办法回答，可以重新描述下遇到的问题

我想修改发送通知  dingding的模版（markdown的方式），需要修改那些地方？

现在修改了sql/notify.py和common/utils/sendmsg.py两个文件，感觉没生效。

**Comment by runblood** [comment]
已经解决！
