### ISSUE TITLE
[ 问题咨询 ]1.7.7archery存在sql注入风险，已被安全检测，可否消除这个隐患

### ISSUE THREAD

**Issue by mingjia1** [hhyo/Archery#979]
### 问题描述
ip:port/instance/instance_resource/?db_name=rural_house_census_pro&instance_name=库名&resource_type=column&schema_name=&tb_name=表明
上述链接被安全检测出安全漏洞，这个问题能否解决
### 版本信息
 - 应用版本/分支：Release v1.7.7
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
能不能详细提供一下 sql 注入的方式, 或者安全检测工具以及详细的报告?

**Comment by hhyo** [comment]
使用sql拼接并且接受传参的方式都会存在这个隐患，可以集中处理一下

**Comment by LeoQuote** [comment]
一般是咋处理? 接个第三方的库吗?

**Comment by mingjia1** [comment]
我有报告怎么提交给你

**Comment by mingjia1** [comment]
[系统SQL注入介绍.docx](https://github.com/hhyo/Archery/files/5634010/SQL.docx)
