### ISSUE TITLE
[ bug ] 在大量SQL（1000+ 甚至5000+）多字段执行插入时卡死问题

### ISSUE THREAD

**Issue by niuxz** [hhyo/Archery#980]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

数据上线操作，一次提交超过1000个以上的SQL时，SQL的检查 和提交过程非常慢，时间长了还会超时报错。刷新页面后数据量小的会出现在待执行列表，数据量大了，在执行列表都看不到提交的单子。

此时关注系统资源消耗，发现CPU使用100% ， 系统内存本身也的确不是很高，大概8G 。 不知道在大量SQL 检查、提交 以及执行时，会明显消耗哪些资源？ 或者产品本身有什么参数可以调整吗？  可以去优化的？

### 期待结果和实际结果
期待结果：

调整参数解决、调整系统配置解决或者产品优化

实际结果:

### 错误日志
![image](https://user-images.githubusercontent.com/52068200/101166051-9c37b400-3672-11eb-9d15-e454b2a10ee8.png)

### 版本信息
应用版本/分支：1.6.2

部署方式：手工部署

**Comment by hhyo** [comment]
升级新版即可，检测和提交慢的问题都有解决
