### ISSUE TITLE
[ bug ]postgresql查询结果有json字符串的前端显示错误

### ISSUE THREAD

**Issue by moutianmouke** [hhyo/Archery#982]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤

postgresql某表某字段为json字段，查询pg后端返回了正确的json数据结果，但前端展示异常

### 期待结果和实际结果
期待结果：
显示正确后端返回的json串
实际结果:
![图片](https://user-images.githubusercontent.com/14121067/101238113-f25f3280-3718-11eb-9000-fc45634bb61a.png)

json串结果集后端返回正常，但前端显示均为  [object Object]

部署方式：手工部署
应用版本/分支：Release v1.8.0

**Comment by liujing1087** [comment]
pgsql json字段显示为[object Object]， 版本v1.8.5

**Comment by dmanbu** [comment]
pgsql json字段显示为[object Object]， 版本v1.11.3
