### ISSUE TITLE
[ 问题咨询 ]

### ISSUE THREAD

**Issue by wbcmax** [hhyo/Archery#983]
### 问题描述
请问archery是否支持同时查询多条SQL语句，获取多条结果？

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by hhyo** [comment]
执行结果可以有多个tab，选中不同的语句分别执行即可

**Comment by wbcmax** [comment]
明白了，非常感谢 @hhyo
