### ISSUE TITLE
[ 问题咨询 ] 请问archery本地开发环境你们是怎么部署的啊？我想用pycharm来开发

### ISSUE THREAD

**Issue by hailianghe** [hhyo/Archery#984]
### 问题描述
现在运行是用的容器，我们要改一些东西，加一些功能，发现文件都是在容器里面，本地开发不知道怎么来做，故想问下你们是怎么做的？

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker

**Comment by hhyo** [comment]
部署方式和开发环境搭建两者不冲突，可以参考手动部署步骤搭建本地测试环境

**Comment by hailianghe** [comment]
我本地是windows系统，开发环境是要安装一个虚拟机，虚拟机里面安装centos7, centos7里面安装pycharm吗？

**Comment by hailianghe** [comment]
已经解决了， windows的ldap安装需要安装对应版本的ldap，直接用手动启动python
https://archerydms.com/installation/manual/

**Comment by Shlpeng** [comment]
> 部署方式和开发环境搭建两者不冲突，可以参考手动部署步骤搭建本地测试环境

macbook本地pycharm 调试环境的搭建

**Comment by Shlpeng** [comment]
> macbook本地pycharm 调试环境的搭建

有没有直接的搭建手册

**Comment by Shlpeng** [comment]
macbook本地pycharm 调试环境的搭建，有没有直接的搭建手册
