### ISSUE TITLE
[ 问题咨询 ] TiDB 好像不支持备份和脱敏

### ISSUE THREAD

**Issue by T-baby** [hhyo/Archery#985]
如题，我们使用的是 TiDB，但是使用 Archery 做 SQL 查询时配置的脱敏规则不生效，还有就是执行上线 SQL 时不支持备份。

**Comment by hhyo** [comment]
对，tidb只支持审核和执行

**Comment by lsp201811** [comment]
是哪一个版本支持tidb

**Comment by h77626592** [comment]
tidb 执行时报错，怎么解决
![图片](https://github.com/user-attachments/assets/df36741f-7f18-4dc0-9e55-29cf68bcc8fd)
