### ISSUE TITLE
[ 问题咨询 ]配置飞书webbook执行提交sql后没有发送信息

### ISSUE THREAD

**Issue by charnet1019** [hhyo/Archery#986]
### 问题描述
配置飞书webbook执行提交sql后没有发送信息，在sql/notify.py中增加日志确认没有进入feishu_webhook判断逻辑

### 版本信息
 - 应用版本/分支：Release v1.7.13
 - 部署方式：Docker

**Comment by LeoQuote** [comment]
你看看更新后能不能修复呢?
