### ISSUE TITLE
[ bug ]Postgresql查询有大写的表的表结构查询异常

### ISSUE THREAD

**Issue by moutianmouke** [hhyo/Archery#989]
在提交 issue 前，请查阅以下资源，请先进行搜索来保证没有类似的 issue。
[文档](https://github.com/hhyo/archery/wiki) | [FAQ](https://github.com/hhyo/archery/wiki/FAQ) 

### 重现步骤
1、postgresql 存在有大写的表，Archery无法查询其对应表结构，提示表不存在，但是表下拉框可以看到表存在

### 期待结果和实际结果
期待结果：
可以显示有大写的表的表结构
实际结果:

![图片](https://user-images.githubusercontent.com/14121067/101894311-f8558780-3be0-11eb-98dd-8d9d62f8bab5.png)

 
### 版本信息
应用版本/分支：
最新版本 1.8.0版本
部署方式：Docker、手工部署

**Comment by moutianmouke** [comment]
可以考虑替换掉 查询pgsql的表结构的sql代码。
sql/engines/pgsql.py上

        select
        col.column_name,
        col.data_type,
        col.character_maximum_length,
        col.numeric_precision,
        col.numeric_scale,
        col.is_nullable,
        col.column_default,
        des.description
        from
        information_schema.columns col left join pg_description des on
        col.table_name::regclass = des.objoid
        and col.ordinal_position = des.objsubid
				        where table_name = '{tb_name}'
        order by ordinal_position;
替换为
        sql = f"""select
        a.attnum, 
        a.attname AS column_name, 
        t.typname AS data_type,
        a.attlen AS character_maximum_length,
        a.atttypmod AS lengthvar, 
        a.attnotnull AS notnull, 
        b.description AS comment
        FROM 
        pg_class c, pg_attribute a
        LEFT JOIN pg_description b
        ON a.attrelid = b.objoid
        AND a.attnum = b.objsubid, pg_type t
        WHERE c.relname = '{tb_name}'
        AND a.attnum > 0
        AND a.attrelid = c.oid
        AND a.atttypid = t.oid
        ORDER BY a.attnum;"""

**Comment by hhyo** [comment]
#698
感谢反馈，可以提交一个pr
