### ISSUE TITLE
[ 问题咨询 ]执行工单时状态一直显示执行中

### ISSUE THREAD

**Issue by zengyananaaa** [hhyo/Archery#99]
执行工单时状态一直显示执行中，但是在库里show processlist并没有这个进程，这个情况是怎么回事呢？应该怎么解决呢？
如果用管理员账号在后台手动把工单的状态改成“执行有异常”或“人工终止流程”的话，会结束这个工单吗？

**Comment by LeoQuote** [comment]
请查看文档 https://github.com/hhyo/archery/wiki/FAQ#%E5%B7%A5%E5%8D%95%E7%8A%B6%E6%80%81%E4%B8%80%E7%9B%B4%E6%98%AF%E6%89%A7%E8%A1%8C%E4%B8%AD

另外，我们的模版不是让你把内容删掉然后开始自我发挥的。

启动方式和版本都没有说， 我们很难帮你解决问题
