### ISSUE TITLE
[ 功能建议 ] 建议添加归档工单功能

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#990]
### 目前遇到的问题/使用障碍
随着工单量的增长，需要对历史的工单进行删除操作，这个相对还是比较重要的

### 希望如何解决/实现它
可以使用时间区间删除不需要的工单内容及备份的内容，是否有自动清理默认时间

### 其他信息
如果有其他类似的产品功能或者图片信息，可在此提交
yearning工具存在此功能，请查看截图信息
![image](https://user-images.githubusercontent.com/71009460/102062823-2f6da800-3e30-11eb-93f7-25ac5baa0923.png)

**Comment by hhyo** [comment]
#940 
建议使用平台的归档功能，归档策略可以自己配置，具体需要归档哪些表，可以查看https://github.com/hhyo/Archery/blob/master/sql/models.py
