### ISSUE TITLE
gateway timeout 504[ 问题咨询 ]

### ISSUE THREAD

**Issue by langhuadb** [hhyo/Archery#993]
### 问题描述
查询数据库数据超过60s后就返回 gateway timeout  504 ,请问这个怎么解决

### 版本信息
 - 应用版本/分支：Release v1.8.0  
 - 部署方式：手工部署

**Comment by LeoQuote** [comment]
504 可以修改 nginx 的配置, 增大一些 nginx 的timeout

**Comment by langhuadb** [comment]
> 504 可以修改 nginx 的配置, 增大一些 nginx 的timeout

嗯谢谢，调整了，但是我查了200w条数据 服务就查挂了，这个怎么处理呢

**Comment by LeoQuote** [comment]
200W 的数据, 一般不建议用这个平台, 如果真就要用, 就加内存

**Comment by langhuadb** [comment]
> 200W 的数据, 一般不建议用这个平台, 如果真就要用, 就加内存

感谢您的回复，加了内存之后突破了200w的瓶颈，但是最大就能查到400w的量级，现在cpu内存都富裕，如何能提高到更高的一个性能呢

**Comment by dongqianzheng** [comment]
配置项管理里面有一个 MAX_EXECUTION_TIME 参数
启动的配置文件里面也有一个timeout参数，你都调下试下。

**Comment by langhuadb** [comment]
> 配置项管理里面有一个 MAX_EXECUTION_TIME 参数
> 启动的配置文件里面也有一个timeout参数，你都调下试下。

感谢您的回复，调整了还是不行，看日志是程序挂掉了
