### ISSUE TITLE
[ 问题咨询 ]隧道连接实例的代码检测和上线出现报错

### ISSUE THREAD

**Issue by soy-sauce-rice** [hhyo/Archery#994]
### 问题描述
使用k8s修改部署了archery服务。
改造内容如下：

1. 将mysql和redis建立在外部启动，并进行了初始化。
2. 修改/opt/archery/src/docker/startup.sh文件，启动命令改成`gunicorn -w 4 -k sync -b 127.0.0.1:8888 --timeout 600 archery.wsgi:application`，在`source /opt/venv4archery/bin/activate`下`添加python3 manage.py makemigrations sql`
3. 通过configmap来映射/etc/inc.cnf，/etc/config.toml，/opt/archery/archery/settings.py
4. 将pem文件放到docker文件并授权600权限。
5. 利用yaml启动archery，inception，goinception3个服务。
在不使用隧道连接的情况下运行正常，但在添加了使用隧道的mysql实例并测试时，会出现超时情况。通过`kubectl exec`进入内部后能够快速的连接隧道主机并连接mysql。

通过ssh可以连接
![image](https://user-images.githubusercontent.com/27428177/102698221-ceeaca80-4276-11eb-976b-6b6f2c80b0b7.png)
隧道设置
![image](https://user-images.githubusercontent.com/27428177/102698232-e45ff480-4276-11eb-9077-c2920302cc0c.png)
修改后的startup.sh文件
![image](https://user-images.githubusercontent.com/27428177/102698344-97305280-4277-11eb-9ecd-d4ce727ddec6.png)

### 版本信息
 - 应用版本/分支：Release v1.8.0
 - 部署方式：Docker

**Comment by soy-sauce-rice** [comment]
只会测试连接时会出现这个问题，实际使用还是没有问题的。那可能是检测的代码对我的数据库有些不适用吧。

**Comment by hhyo** [comment]
检测脚本也是获取连接和数据库，这个和查询或者上线获取得信息是一致的

**Comment by soy-sauce-rice** [comment]
> 检测脚本也是获取连接和数据库，这个和查询或者上线获取得信息是一致的

使用了一天下来，查询的使用是很正常的。就是测试连接的时候，通过浏览器的控制台看，check/instance/请求一定会peding一会，最后报504错误。还有就是上线的时候，点击代码检测，sql语句是`inception_magic_start`，审核信息是`con:27 dial tcp 127.0.0.1:41043: connect: connection refused.`，也是只在配置了隧道的里面显示，这个有什么解决方案？

**Comment by soy-sauce-rice** [comment]
上线和查询的功能在没有隧道的实例里是没有问题的。

**Comment by soy-sauce-rice** [comment]
在本地利用https://archerydms.com/home/ 快速开启里的步骤搭建了一个平台，5个docker都跑在本地了。配置了隧道连接，结果也是这样的。

<img width="1163" alt="CleanShot 2020-12-21 at 00 22 37@2x" src="https://user-images.githubusercontent.com/27428177/102718350-a5877880-4322-11eb-87b3-c6b0472b0f04.png">

**Comment by hhyo** [comment]
参考一下#951

**Comment by soy-sauce-rice** [comment]
在k8s里把所有容器放到一个deployment里，解决了sql检测里的报错。
