### ISSUE TITLE
[ 问题咨询 ]导出excel文件出现数字出现科学计数。

### ISSUE THREAD

**Issue by chenweihua** [hhyo/Archery#997]
### 问题描述
点查询后，结果导出的时候数字超过12位后数字出现科学计数法，并且数据还进行四舍五入了。

### 版本信息
 - 应用版本/分支：Release v1.7.10  
 - 部署方式：Docker

 
能否修复这个BUG

**Comment by chenweihua** [comment]
例如
![image](https://user-images.githubusercontent.com/4547754/103121251-5771cc80-46b6-11eb-86ca-b994bc509410.png)
导出来后就成
![image](https://user-images.githubusercontent.com/4547754/103121272-6eb0ba00-46b6-11eb-96ed-f0f14293d0c0.png)

**Comment by LeoQuote** [comment]
这个挺难搞的, 我建议你导出 csv 然后再做处理, excel 这个看我们用的前端组件支持不支持
