### ISSUE TITLE
[ 问题咨询 ]数据库端口不是默认3306时，大表操作调用PT的osc工具时报错

### ISSUE THREAD

**Issue by zhituanchen** [hhyo/Archery#999]
### 问题描述
数据库端口不是默认3306时，大表操作调用PT的osc工具时报错，使用端口3306则正常，麻烦确认是否调用PT工具强制指定了3306端口:
报错信息：
Execute: exit status 18.
Cannot connect to MySQL: DBI connect('archery;host=10.0.0.21;charset=utf8;mysql_read_default_group=client','readwrite',...) failed: Can't connect to MySQL server on '10.0.0.21' (115) at /usr/local/bin/pt-online-schema-change line 2345.

### 版本信息
 - 应用版本/分支：Releasev1.7.13  
 - 部署方式：Docker

### 截图信息
3307端口异常：
![image](https://user-images.githubusercontent.com/71009460/103130618-72edcf00-46d8-11eb-9c4f-c5ab4ffbc8e1.png)
3306端口正常：
![image](https://user-images.githubusercontent.com/71009460/103130704-c233ff80-46d8-11eb-92eb-2409a537d558.png)

工单信息：
![image](https://user-images.githubusercontent.com/71009460/103130732-e099fb00-46d8-11eb-977b-840b7f90497e.png)

**Comment by hhyo** [comment]
pt默认使用的process查找的从库信息，可以尝试调整下recursion_method参数
